"""Repair only the table aperture, keeping all existing fittings and avatar-free board.
Run with Blender --background --python this_file -- <source asset directory>.
The input must be the pre-repair board GLBs (240d0a5); writes current workspace.
"""
import bpy,bmesh,math,json,sys
from pathlib import Path
from mathutils import Vector
ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/'client/public/models/reading-board/v1'
SOURCE=Path(sys.argv[sys.argv.index('--')+1])
def cubic(a,b,c,d,n=64):
 return [tuple((1-t)**3*a[k]+3*(1-t)**2*t*b[k]+3*(1-t)*t*t*c[k]+t**3*d[k] for k in range(2)) for t in [i/n for i in range(n+1)]]
# Same two sweeping ribs as the silver rail. A small inset leaves the silver's
# inner bevel visible; the old, independently drawn diagonal oval is removed.
left=cubic((.648,.399),(.655,.272),(.741,.148),(.731,.052))
right=cubic((.648,.399),(.760,.356),(.794,.211),(.733,.054))
hole=[(.71+(x-.71)*.97,.225+(y-.225)*.965) for x,y in left+list(reversed(right))]
# Store sampled coordinates used by BOTH the cutter and runtime projection.
(ROOT/'client/src/ui/riftOutline.ts').write_text('/** Generated by scripts/blender/align_rift_apertures.py. Meter-space cutter. */\nexport const RIFT_OUTLINE:number[][]='+json.dumps([[round(x,8),round(y,8)] for x,y in hole],separators=(',',':'))+';\n')
nodes=[(.80,0),(.79,.26),(.762,.367),(.718,.415),(.62,.438),(.17,.438),(.112,.442),(.066,.463),(0,.47),(-.066,.463),(-.112,.442),(-.17,.438),(-.59,.438),(-.706,.421),(-.77,.365),(-.797,.20),(-.80,0),(-.797,-.20),(-.77,-.365),(-.706,-.421),(-.59,-.438),(-.17,-.438),(-.112,-.442),(-.066,-.463),(0,-.47),(.066,-.463),(.112,-.442),(.17,-.438),(.62,-.438),(.718,-.415),(.762,-.367),(.79,-.26)]
outline=[]
for i in range(len(nodes)):
 a,b,c,d=[Vector(nodes[j%len(nodes)]) for j in (i-1,i,i+1,i+2)]
 for j in range(6):
  t=j/6;outline.append(tuple(.5*((2*b)+(-a+c)*t+(2*a-5*b+4*c-d)*t*t+(-a+3*b-3*c+d)*t*t*t)))
def bounds(o):
 vs=[o.matrix_world@v.co for v in o.data.vertices];return [min(v[i] for v in vs) for i in range(3)],[max(v[i] for v in vs) for i in range(3)]
def solid(name,pts,lo,hi,mat=None):
 n=len(pts);vs=[(x,y,z) for z in [lo,hi] for x,y in pts];fs=[tuple(reversed(range(n))),tuple(range(n,2*n))]+[(i,(i+1)%n,(i+1)%n+n,i+n) for i in range(n)]
 me=bpy.data.meshes.new(name);me.from_pydata(vs,[],fs);me.update();bm=bmesh.new();bm.from_mesh(me);bmesh.ops.recalc_face_normals(bm,faces=bm.faces);bm.to_mesh(me);bm.free()
 o=bpy.data.objects.new(name,me);bpy.context.collection.objects.link(o)
 if mat:o.data.materials.append(mat)
 uv=me.uv_layers.new(name='UVMap')
 for p in me.polygons:
  for li in p.loop_indices:
   co=me.vertices[me.loops[li].vertex_index].co;uv.data[li].uv=(co.x/.32,co.y/.32) if abs(p.normal.z)>.5 else (co.x/.32,co.z/.12)
 return o
def apply(o,mod):bpy.context.view_layer.objects.active=o;bpy.ops.object.modifier_apply(modifier=mod.name)
for name in ['board.glb','board-low.glb']:
 bpy.ops.wm.read_factory_settings(use_empty=True);bpy.ops.import_scene.gltf(filepath=str(SOURCE/name))
 materials={m.name.split('.')[0]:m for m in bpy.data.materials};wood=materials['01_InkWood'];ink=materials['06_RecessInk']
 # Undo export seam duplication only for the carcass, then separate its original components.
 for o in list(bpy.context.scene.objects):
  if o.type!='MESH':continue
  bpy.ops.object.select_all(action='DESELECT');o.select_set(True);bpy.context.view_layer.objects.active=o
  if '01_InkWood' in o.name:
   bm=bmesh.new();bm.from_mesh(o.data);bmesh.ops.remove_doubles(bm,verts=list(bm.verts),dist=1e-7);bm.to_mesh(o.data);bm.free()
  bpy.ops.object.mode_set(mode='EDIT');bpy.ops.mesh.select_all(action='SELECT');bpy.ops.mesh.separate(type='LOOSE');bpy.ops.object.mode_set(mode='OBJECT')
 removed=[]
 for o in list(bpy.context.scene.objects):
  if o.type!='MESH':continue
  lo,hi=bounds(o);w=hi[0]-lo[0];d=hi[1]-lo[1]
  body='01_InkWood' in o.name and w>1.5 and lo[2]<-.039
  bottom='06_RecessInk' in o.name and w>1.5 and hi[2]<-.034
  shoulder='01_InkWood' in o.name and lo[0]>.65 and .23<d<.29 and -.006<lo[2]<-.004 and hi[2]<.010
  trim='05_WarmSilver' in o.name and lo[0]>.66 and .24<d<.27 and lo[2]>.008 and hi[2]<.014
  if body or bottom or shoulder or trim:removed.append(o.name);bpy.data.objects.remove(o,do_unlink=True)
 assert len(removed)>=6,removed
 body=solid('Aligned archive carcass',outline,-.040,-.001,wood)
 bottom=solid('Aligned archive lower plinth',[(x*.994,y*.989) for x,y in outline],-.041,-.035,ink)
 cutters=[solid('Rift cut',[(x,y*s) for x,y in hole],-.08,.09) for s in [-1,1]]
 cutters.append(solid('Timer cut',[(.70+.0475*math.cos(i*2*math.pi/96),.0475*math.sin(i*2*math.pi/96)) for i in range(96)],-.08,.09))
 for o in [body,bottom]:
  for c in cutters:
   mod=o.modifiers.new('Through cut','BOOLEAN');mod.operation='DIFFERENCE';mod.solver='EXACT';mod.object=c;apply(o,mod)
  mod=o.modifiers.new('Cut edge bevel','BEVEL');mod.width=.0008;mod.segments=2;apply(o,mod)
  o.data.set_sharp_from_angle(angle=math.radians(30))
 for c in cutters:bpy.data.objects.remove(c,do_unlink=True)
 # Restore the five-material batching; preserve every existing empty/anchor.
 for mat in list(bpy.data.materials):
  objects=[o for o in bpy.context.scene.objects if o.type=='MESH' and o.data.materials and o.data.materials[0]==mat]
  if not objects:continue
  bpy.ops.object.select_all(action='DESELECT')
  for o in objects:o.select_set(True)
  bpy.context.view_layer.objects.active=objects[0];bpy.ops.object.join();objects[0].name='aligned_'+mat.name
 bpy.ops.export_scene.gltf(filepath=str(OUT/name),export_format='GLB',export_yup=True,export_apply=True,export_image_format='AUTO',export_extras=True)
 print('REPAIRED',name,'removed',removed)
