import '../../styles/tokens.css';import '../../styles/base.css';import '../../styles/card.css';import '../../styles/game-overlays.css';import '../../styles/game.css';import '../../styles/screens.css';import '../../styles/reading-board.css';import '../../styles/presentation.css';import '../../styles/duel-opening.css';
import './style.css';
import {GameView,setMyAvatar,setOppAvatar} from '../../ui/boardView';
import {createGame} from '../../shared/engine';
import {FRAME_BACK} from '../../shared/cards';
import {passiveIcon} from '../../ui/passiveIcon';
import {cardEl} from '../../ui/cardView';
import {captureCardSurface} from '../../ui/cardSurface';
import {waitForDuel} from '../../ui/duelReadiness';
import {startBoardLayout} from '../../ui/layout';
import {setLang} from '../../i18n';
import {cards,families,cues,variants,planFor,type Plan,type Options} from './catalog';
import {Renderer,prepareSurface,type Point,type Anchors} from './renderer';
import type {CardInst,FieldMon,Side} from '../../shared/types';
import {winModal,closeOverlay} from '../../ui/modal';
import {turnBanner,setFxSkip,animateDraw} from '../../ui/anim';
import {mountDuelOutcome} from '../../ui/duelOutcome';
import {playDuelOpening} from '../../ui/duelOpeningDirector';
import {createAttackAim} from '../../ui/attackAim';

const params=new URLSearchParams(location.search);
setLang('ja');
if(!params.has('stage')){
 document.body.className='c-shell';
 document.getElementById('app')!.innerHTML=`<aside class="c-controls"><header><span>LORE / EFFECT ATELIER</span><h1>C — 材質と戦術</h1><p>6系統 · 48場面 · 2案<br>実GameView / ローカル比較試作</p></header><label>系統・場面<select id="scene"></select></label><label>カード<select id="card"></select></label><div class="c-variants"><button id="v0">①</button><button id="v1">②</button></div><p id="intent"></p><div class="c-row"><label>陣営<select id="side"><option value="0">自分</option><option value="1">相手</option><option value="both">両陣営同時</option></select></label><label>速度<select id="speed"><option value="1">1 ×</option><option value="0.5">0.5 ×</option><option value="0.25">0.25 ×</option></select></label></div><div class="c-row"><button id="play">▶ 再生</button><button id="pause">停止</button><button id="reset">リセット</button></div><input id="seek" aria-label="タイムライン" type="range" min="0" max="3000" value="0" step="1"><output id="clock">0.00s</output><div class="c-checks"><label><input id="loop" type="checkbox" checked>ループ</label><label><input id="outcome" type="checkbox" checked>判定成功</label><label><input id="boost" type="checkbox">強化／追加条件</label><label><input id="dark" type="checkbox">暗背景</label><label><input id="reduced" type="checkbox">動き低減</label></div><label>対象／職業<select id="choice"><option value="monster">モンスター</option><option value="player">プレイヤー</option><option value="CHOSEN_KNIGHT">剣士</option><option value="CHOSEN_MAGE">魔法使い</option><option value="CHOSEN_ARCHER">弓手</option><option value="CHOSEN_ROGUE">盗賊</option></select></label><details open><summary>現在の効果と進行</summary><p id="rule"></p><ol id="events"></ol></details><details><summary>既存演出への接続確認</summary><div id="existing"></div></details><footer>状態・抽選結果は比較用フィクスチャ。<br>本番ルール処理と独立／ユーザー未承認</footer></aside><main class="c-board"><iframe title="LORE 実盤面" src="/series-vfx-c.html?stage=1"></iframe><div class="c-caption"><b id="caption">準備中</b><span id="phase"></span></div></main>`;
 const el=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
 const scene=el<HTMLSelectElement>('scene'),card=el<HTMLSelectElement>('card'),frame=document.querySelector('iframe')!;
 scene.innerHTML=`<optgroup label="系統ごとの比較">${families.map(f=>`<option value="${f.id}">${f.id} ${f.name}</option>`).join('')}</optgroup><optgroup label="効果・状態">${cues.filter(c=>c.scope==='two-variant-preview').map(c=>`<option value="${c.id}">${c.id} ${c.name}</option>`).join('')}</optgroup>`;
 let variant=0,api:any;
 function fill(){const row=[...families,...cues].find(r=>r.id===scene.value)!;const ids=row.cardIds.length?row.cardIds:['GOLEM2','INFKNIGHT','CASTLE'];card.innerHTML=ids.filter(id=>cards[id]).map(id=>`<option value="${id}">${cards[id].nameJa||id}</option>`).join('');}
 function opts():Options{return{outcome:el<HTMLInputElement>('outcome').checked,boost:el<HTMLInputElement>('boost').checked,choice:el<HTMLSelectElement>('choice').value}}
 async function load(){if(!api)return;const p:Plan=await api.load(scene.value,card.value,variant,el<HTMLSelectElement>('side').value,opts());el<HTMLInputElement>('seek').max=String(p.duration);const names=variants[p.family]||variants.S08;el('v0').textContent='① '+names[0];el('v1').textContent='② '+names[1];el('v0').classList.toggle('active',variant===0);el('v1').classList.toggle('active',variant===1);el('intent').textContent=variant===0?'① 刻印を起点に太い材質が連続して流れ、接触で局所的に裂けて収束。':'② カード表面を薄い層に分け、時間差で折り開き、対象へ組み上げる。';el('rule').textContent=p.note;el('caption').textContent=`${p.id} / ${p.title} — ${variant+1} ${names[variant]}`;el('events').innerHTML=p.events.filter(e=>e.kind!=='surface').map(e=>`<li>${(e.at/1000).toFixed(2)}s ${e.label}</li>`).join('');}
 fill();scene.onchange=()=>{fill();void load()};card.onchange=()=>void load();for(const i of [0,1])el('v'+i).onclick=()=>{variant=i;void load()};['side','outcome','boost','choice'].forEach(id=>el(id).onchange=()=>void load());
 el('play').onclick=()=>api?.play();el('pause').onclick=()=>api?.pause();el('reset').onclick=()=>api?.reset();el<HTMLInputElement>('seek').oninput=e=>api?.seek(+(e.target as HTMLInputElement).value);el('speed').onchange=()=>api?.speed(+el<HTMLSelectElement>('speed').value);el('loop').onchange=()=>api?.loop(el<HTMLInputElement>('loop').checked);el('dark').onchange=()=>api?.dark(el<HTMLInputElement>('dark').checked);el('reduced').onchange=()=>api?.reduced(el<HTMLInputElement>('reduced').checked);
 const existing=[['A177','勝利'],['A177-loss','敗北'],['A177-draw','引き分け'],['A182','対戦開始'],['A183','ターン交代'],['A184','照準'],['A185','手札操作'],['A186','中断・解放']];
 el('existing').innerHTML=existing.map(([id,name])=>`<button data-existing="${id}">${id} ${name}</button>`).join('');el('existing').querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.onclick=()=>api?.existing(b.dataset.existing));
 frame.onload=async()=>{api=(frame.contentWindow as any).seriesC;await api.ready;await load();(window as any).seriesC={load:async(id:string,cardId:string,v=0,side='0',options:Partial<Options>={})=>{scene.value=id;fill();card.value=cardId;variant=v;el<HTMLSelectElement>('side').value=side;for(const k of ['outcome','boost'] as const)if(options[k]!==undefined)el<HTMLInputElement>(k).checked=options[k]!;if(options.choice)el<HTMLSelectElement>('choice').value=options.choice;await load()},api,catalog:{families,cues},snapshot:()=>api.snapshot()};};
 window.addEventListener('message',e=>{if(e.source!==frame.contentWindow||e.data?.type!=='series-c-time')return;el<HTMLInputElement>('seek').value=String(e.data.ms);el('clock').textContent=(e.data.ms/1000).toFixed(2)+'s';el('phase').textContent=e.data.phase;});
}else{
 document.body.className='c-stage';localStorage.setItem('lore_help_callout_seen',new Date().toISOString().slice(0,10));setMyAvatar('SEEKER_BLUE');setOppAvatar('SEEKER_RED');
 const g=createGame({mode:'bot',seed:734,starting:0,p0:{id:'series-c-0',name:'シーカー'},p1:{id:'series-c-1',name:'シーカー'}}).state;g.turn=4;g.pending=null;g.opening=undefined;
 let plan:Plan=planFor('S04','FIRE_BALL',{boost:false,outcome:true,choice:'monster'}),side:Side=0,both=false,ms=0,speed=1,loop=true,playing=false,raf=0,last=0,epoch=0;
 const inst=(id:string,uid:string):CardInst=>({...cards[id],uid});
 const mon=(id:string,uid:string):FieldMon=>({...inst(id,uid),exhausted:false,summonedTurn:0,tempAtk:0,atkMod:0,defMod:0,dmg:0,guts:cards[id]?.passive?.includes('guts')?1:0});
 const noop=()=>{};
 const view=new GameView(document.getElementById('app')!,0,{onPlay:noop,onBlockedPlay:noop,onAttack:noop,onBlockedAttack:noop,onReorder:(from,to)=>{const f=g.players[0].field;f.splice(to,0,f.splice(from,1)[0]);view.render(g)},onChooseTarget:noop,onBuyMarket:noop,onBuySupply:noop,onRefresh:noop,onEndTurn:noop,onSurrender:noop});// Fixture replacement reuses UIDs; native statRise would read card changes as buffs outside this clock.
 (view as unknown as {statRise:{dispose():void}}).statRise.dispose();
 const stopLayout=startBoardLayout(),renderer=new Renderer();
 let currentOptions:Options={boost:false,outcome:true,choice:'monster'};let cleanExisting:(()=>void)|undefined;let baseline=new Map<HTMLElement,string>();
 function fixture(){for(const [i,p] of g.players.entries()){const selected=cards[plan.card];p.openingDrawReady=false;p.mana=8;p.maxMana=12;p.hp=32;p.quests=[];p.enchants=[];p.traps=[];p.discard=[inst('SOLDIER2',`shelf-${i}`)];p.removed=Array.from({length:6},(_,n)=>inst('STARTER_TRASH',`rift-${i}-${n}`));p.field=[selected?.t==='mon'?plan.card:'GOLEM2','INFKNIGHT','CASTLE'].map((id,n)=>mon(id,`field-${i}-${n}`));for(const e of plan.events.filter(e=>e.kind==='summon')){const n=Number(e.to.replace('ally',''));if(e.to.startsWith('ally')&&cards[e.shape||'']?.t==='mon')p.field[n]=mon(e.shape!,`field-${i}-${n}`);}p.field[2].gcount=2;if(plan.id==='A033')p.field[0].def=15;if(['EXPANSION','LAND_GRANT'].includes(plan.card)||(plan.card==='INTERCEPT'&&currentOptions.boost))p.field[0]=mon('CASTLE',`field-${i}-0`);if(plan.card==='STABLE')p.field[0]=mon('INFKNIGHT',`field-${i}-0`);if(plan.card==='MERC_ART')p.field[0]=mon('MERC_LEADER',`field-${i}-0`);if(plan.id==='A101')p.field=[plan.card,'CHOSEN_MAGE','CHOSEN_ARCHER'].map((id,n)=>mon(id,`field-${i}-${n}`));if(plan.id==='A122'||plan.card==='MIND_BURST')p.field=['GOLEM1','GOLEM2','NWL3'].map((id,n)=>({...mon(id,`field-${i}-${n}`),guts:0}));p.hand=[inst(plan.card,`source-${i}`),inst('STARTER_CHEST',`hand-${i}`),inst('STARTER_TRASH',`cull-${i}`)];}if(plan.card==='AHEUK'&&currentOptions.boost)g.players[side].field=[];if(plan.family==='S22'&&currentOptions.boost)g.players[side].field.push(mon('CASINO',`casino-${side}`));g.cur=side;view.render(g);view.setHandOpen(true);for(const key of ['source','hand']){const back=document.querySelector<HTMLElement>(`#oppHand [data-uid="${key}-1"]`);if(back){const face=cardEl(inst(key==='source'?plan.card:'STARTER_CHEST',`${key}-1`));face.style.cssText=back.style.cssText;face.style.setProperty('--cw','72.576px');face.style.setProperty('--ch','113.4px');back.replaceWith(face);}}document.querySelector('.help-callout')?.remove();baseline.clear();}
 function point(selector:string):Point{const e=document.querySelector<HTMLElement>(selector),r=e?.getBoundingClientRect();return{x:r?r.left+r.width/2:innerWidth/2,y:r?r.top+r.height/2:innerHeight/2,w:r?.width||50,h:r?.height||65,el:e||undefined}}
 function anchors(s=side):Anchors{const o=1-s,field=(p:number,n:number)=>point(`[data-uid="field-${p}-${n}"]`),portrait=(p:number)=>point(`#portrait${p?'Opp':'Me'} .pt-ring`);return{source:point(`[data-uid="source-${s}"]`),ally0:field(s,0),ally1:field(s,1),ally2:field(s,2),ally3:field(s,3),ally4:field(s,4),enemy0:field(o,0),enemy1:field(o,1),enemy2:field(o,2),me:portrait(s),opponent:portrait(o),mana:point(`#portrait${s?'Opp':'Me'} .pt-mana`),enemyMana:point(`#portrait${o?'Opp':'Me'} .pt-mana`),rift:point(`#rift-${s?'opp':'me'}`),shelf:point(`#${s?'opp':'me'}Row .pile--shelf`),hand:point(`[data-uid="hand-${s}"]`)};}
 const faceCache=new Map<string,Promise<HTMLCanvasElement>>();
 async function texture(seq=epoch){renderer.faces.clear();await document.fonts.ready;const list=[...document.querySelectorAll<HTMLElement>('.card[data-uid]')].filter(e=>/^(field|source|hand)-/.test(e.dataset.uid||''));await Promise.all(list.map(async e=>{await Promise.all([...e.querySelectorAll('img')].map(i=>i.decode().catch(()=>{})));const r=e.getBoundingClientRect(),key=(e.dataset.cardId||'')+':'+Math.round(r.height/r.width*100)+':'+[...e.querySelectorAll('.seal-value')].map(n=>n.textContent).join(',');let task=faceCache.get(key);if(!task){task=(async()=>{const s=await captureCardSurface(e,FRAME_BACK,true,false),src=s.face||s.back,face=document.createElement('canvas');const crop=src.width/1.24,pad=crop*.12;face.width=384;face.height=Math.round(384*r.height/r.width);face.getContext('2d')!.drawImage(src,pad,pad,crop,src.height-pad*2,0,0,face.width,face.height);return face})();faceCache.set(key,task);if(faceCache.size>48)faceCache.delete(faceCache.keys().next().value!);}const face=await task;prepareSurface(face);if(seq===epoch)renderer.faces.set(e.dataset.uid!,face);}));if(seq===epoch)renderer.faces.set('source',renderer.faces.get(`source-${side}`)!);}
 function restoreText(){document.querySelectorAll('[data-c-generated]').forEach(e=>e.remove());baseline.forEach((text,e)=>{e.textContent=text});}
 function setText(e:HTMLElement|null|undefined,text:string){if(!e)return;if(!baseline.has(e))baseline.set(e,e.textContent||'');e.textContent=text;}
 function feedback(a:Anchors){restoreText();const accum=new Map<HTMLElement,number>();for(const e of plan.events){if(ms<e.at+e.duration*.78)continue;const target=a[e.to].el;if(!target)continue;let seal:HTMLElement|null=null;let amount=0;if(e.kind==='hit'&&!plan.events.some(s=>s.kind==='shield'&&s.to===e.to&&s.shape!=='guts'&&s.at<=e.at+200&&s.at+s.duration>=e.at)){seal=target.querySelector<HTMLElement>('.ad-def .seal-value')||target.closest('.portrait')?.querySelector<HTMLElement>('.pt-hp b')||null;amount=-(e.amount||0)}if(e.kind==='buff'){seal=e.shape==='mana'||e.shape==='spend'||e.shape==='refill'||e.shape==='setmana'?target.querySelector<HTMLElement>(e.shape==='mana'||e.shape==='setmana'?'.pt-mana-max':'.mana-readout b'):target.querySelector<HTMLElement>(e.shape==='hp'||e.shape==='sethp'?'.ad-def .seal-value':'.ad-atk .seal-value');amount=e.amount||0;if(e.shape?.startsWith('set')&&seal)amount-=parseInt((baseline.get(seal)||seal.textContent||'0').replace('/',''),10);}if(seal){if(!baseline.has(seal))baseline.set(seal,seal.textContent||'');accum.set(seal,(accum.get(seal)||0)+amount)}if(e.kind==='swap'){const atk=target.querySelector<HTMLElement>('.ad-atk .seal-value'),hp=target.querySelector<HTMLElement>('.ad-def .seal-value');if(atk&&hp){const at=baseline.get(atk)||atk.textContent||'',ht=baseline.get(hp)||hp.textContent||'';if(!baseline.has(atk))baseline.set(atk,at);if(!baseline.has(hp))baseline.set(hp,ht);const guts=new Map<HTMLElement,number>();for(const e of plan.events){if(ms<e.at+e.duration*.8)continue;const anchor=e.kind==='charge'&&(e.count||0)<0?e.from:e.to;const n=a[anchor]?.el;if(!n||!n.dataset.uid?.startsWith('field'))continue;if((e.kind==='charge'&&plan.family==='S08')||(e.kind==='shield'&&e.shape==='guts')){const badge=n.querySelector<HTMLElement>('[data-psv="guts"] b'),initial=badge?parseInt(baseline.get(badge)||badge.textContent||'0',10):0;const value=guts.get(n)??initial;guts.set(n,e.kind==='shield'?Math.max(0,value-1):e.shape==='setguts'?Math.abs(e.count||1):Math.max(0,value+(e.count||1)));}}for(const [n,count] of guts){let badge=n.querySelector<HTMLElement>('[data-psv="guts"] b');if(!badge&&count>0){const band=n.querySelector('.card-status');if(!n.querySelector('[data-psv="guts"]')){const wrap=document.createElement('span');wrap.dataset.cGenerated='true';wrap.innerHTML=passiveIcon('guts',{count,granted:true});band?.append(wrap);}else{badge=document.createElement('b');badge.dataset.cGenerated='true';badge.textContent=String(count);n.querySelector('[data-psv="guts"]')!.append(badge);}}else if(badge)setText(badge,String(count));}const active=plan.events.filter(x=>x.kind==='swap'&&x.to===e.to&&ms>=x.at+x.duration*.78).length%2;setText(atk,active?ht:at);setText(hp,active?at:ht);}}if(e.kind==='shield'&&e.shape==='guts')setText(target.querySelector<HTMLElement>('.ad-def .seal-value'),'1');}accum.forEach((n,e)=>setText(e,(baseline.get(e)!.startsWith('/')?'/':'')+String(Math.max(0,parseInt(baseline.get(e)!.replace('/',''),10)+n))));}
 function paint(){renderer.clear();const a=anchors();renderer.draw(plan,ms,a);if(both){const save=renderer.clear.bind(renderer);renderer.clear=()=>{};renderer.draw(plan,ms,anchors(1));renderer.clear=save;}feedback(a);for(const e of plan.events){if(e.kind==='summon'&&e.shape===plan.card&&cards[plan.card]?.t==='mon'&&e.from==='source'&&ms>=e.at&&a.source.el){a.source.el.style.visibility='hidden';a.source.el.dataset.cMotion='1';}if(e.kind==='summon'&&ms<e.at){const n=a[e.to].el;if(n){n.style.visibility='hidden';n.dataset.cMotion='1';}}if(e.kind==='break'&&ms>=e.at+e.duration){const n=a[e.from].el;if(n){n.style.visibility='hidden';n.dataset.cMotion='1';}}if(e.kind==='shield'&&e.shape==='guts'&&ms>=e.at+e.duration*.5){setText(a[e.to].el?.querySelector<HTMLElement>('.ad-def .seal-value'),'1');setText(a[e.to].el?.querySelector<HTMLElement>('[data-psv="guts"] b'),'0');}if(e.kind==='charge'&&ms>=e.at+e.duration*.8){const b=a[e.to].el?.querySelector<HTMLElement>('[data-psv="guts"] b');if(b)setText(b,String(Math.max(0,1+(e.count||1))));}}const guts=new Map<HTMLElement,number>();for(const e of plan.events){if(ms<e.at+e.duration*.8)continue;const anchor=e.kind==='charge'&&(e.count||0)<0?e.from:e.to;const n=a[anchor]?.el;if(!n||!n.dataset.uid?.startsWith('field'))continue;if((e.kind==='charge'&&plan.family==='S08')||(e.kind==='shield'&&e.shape==='guts')){const badge=n.querySelector<HTMLElement>('[data-psv="guts"] b'),initial=badge?parseInt(baseline.get(badge)||badge.textContent||'0',10):0;const value=guts.get(n)??initial;guts.set(n,e.kind==='shield'?Math.max(0,value-1):e.shape==='setguts'?Math.abs(e.count||1):Math.max(0,value+(e.count||1)));}}for(const [n,count] of guts){let badge=n.querySelector<HTMLElement>('[data-psv="guts"] b');if(!badge&&count>0){const band=n.querySelector('.card-status');if(!n.querySelector('[data-psv="guts"]')){const wrap=document.createElement('span');wrap.dataset.cGenerated='true';wrap.innerHTML=passiveIcon('guts',{count,granted:true});band?.append(wrap);}else{badge=document.createElement('b');badge.dataset.cGenerated='true';badge.textContent=String(count);n.querySelector('[data-psv="guts"]')!.append(badge);}}else if(badge)setText(badge,String(count));}const active=plan.events.filter(e=>ms>=e.at&&ms<e.at+e.duration).map(e=>e.label);parent.postMessage({type:'series-c-time',ms,phase:active.at(-1)||'余韻・完了'},location.origin);}
 function tick(now:number){if(!playing)return;const dt=last?Math.min(80,now-last):0;last=now;ms+=dt*speed;if(ms>plan.duration){if(loop)ms=0;else{ms=plan.duration;playing=false;if(plan.id==='A174'||plan.card==='CHOSEN_AREA')cleanExisting=mountDuelOutcome(anchors().opponent.el||null,side===0,'選ばれし領域');}}paint();if(playing)raf=requestAnimationFrame(tick)}
 function pause(){playing=false;cancelAnimationFrame(raf);last=0}
 function play(){pause();if(ms>=plan.duration)ms=0;playing=true;raf=requestAnimationFrame(tick)}
 function reset(){pause();ms=0;cleanExisting?.();cleanExisting=undefined;renderer.clear();restoreText();paint()}
 const ready=(async()=>{fixture();await waitForDuel(document.getElementById('app')!);await texture();paint()})();
 async function load(id:string,card:string,v=0,s='0',options:Options={boost:false,outcome:true,choice:'monster'}){pause();cleanExisting?.();cleanExisting=undefined;const seq=++epoch;renderer.clear();restoreText();currentOptions=options;plan=planFor(id,card,options);side=s==='1'?1:0;both=s==='both';renderer.variant=v;ms=0;fixture();await new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r())));await texture();if(seq!==epoch)return plan;paint();return plan;}
 async function existing(id:string){reset();setFxSkip(false);if(id==='A177'||id==='A177-loss')cleanExisting=mountDuelOutcome(document.querySelector(id==='A177'?'#portraitOpp':'#portraitMe'),id==='A177',null);if(id==='A177-draw'){winModal(null,'既存の引き分け結果UI',reset,reset);cleanExisting=closeOverlay;}if(id==='A182'){const abort=new AbortController();cleanExisting=()=>abort.abort();await playDuelOpening({root:document.getElementById('app')!,me:{name:'シーカー',avatar:'SEEKER_BLUE'},opp:{name:'相手',avatar:'SEEKER_RED'},firstIsMe:true,signal:abort.signal,onDeal:async signal=>{await Promise.all([animateDraw(document.getElementById('hand'),3,'me',{signal}),animateDraw(document.getElementById('oppHand'),3,'opp',{signal})]);}});}if(id==='A183')await turnBanner(true,5);if(id==='A184'){const aim=createAttackAim(()=>{const a=anchors();return{x:a.ally0.x,y:a.ally0.y,tx:a.enemy0.x,ty:a.enemy0.y,valid:true,blocked:false}});cleanExisting=()=>aim.remove();}if(id==='A185')view.setHandOpen(true);if(id==='A186'){setFxSkip(true);setFxSkip(false);renderer.clear();}}
 (window as any).seriesC={ready,load,play,pause,reset,dispose,seek:(n:number)=>{pause();ms=n;paint()},speed:(n:number)=>speed=n,loop:(v:boolean)=>loop=v,dark:(v:boolean)=>document.body.classList.toggle('c-dark',v),reduced:(v:boolean)=>{renderer.reduced=v;paint()},existing,snapshot:()=>({plan,ms,playing,side,both,metrics:renderer.metrics,anchors:Object.fromEntries(Object.entries(anchors()).map(([k,p])=>[k,{x:p.x,y:p.y,w:p.w,h:p.h,uid:p.el?.dataset.uid}])),resources:{canvas:document.querySelectorAll('.c-vfx').length,textures:renderer.faces.size,moving:document.querySelectorAll('[data-c-motion]').length}}),cardData:cards};
 const media=matchMedia('(prefers-reduced-motion: reduce)');renderer.reduced=media.matches;const onMedia=()=>{renderer.reduced=media.matches;paint()},onResize=()=>{renderer.resize();paint()};media.addEventListener('change',onMedia);window.addEventListener('resize',onResize);let disposed=false;function dispose(){if(disposed)return;disposed=true;epoch++;pause();cleanExisting?.();restoreText();renderer.dispose();faceCache.clear();stopLayout();view.destroy();media.removeEventListener('change',onMedia);window.removeEventListener('resize',onResize);window.removeEventListener('pagehide',dispose)}window.addEventListener('pagehide',dispose,{once:true});
}
