import type {Anchor,Cue,Plan} from './catalog';
export interface Point{x:number;y:number;w:number;h:number;el?:HTMLElement}
export type Anchors=Record<Anchor,Point>;
const clamp=(n:number)=>Math.max(0,Math.min(1,n));
const smooth=(n:number)=>{const p=clamp(n);return p*p*(3-2*p)};
const lerp=(a:number,b:number,p:number)=>a+(b-a)*p;
const hash=(n:number)=>{const x=Math.sin(n*78.233)*43758.5453;return x-Math.floor(x)};
type C=CanvasRenderingContext2D;
const palettes:Record<string,string[]>={S04:['#431b24','#c84029','#ff9e41','#fff2c3'],S06:['#102c48','#277bba','#70dedf','#effffd'],S08:['#202b36','#557680','#aad6c2','#efffe5'],S12:['#231e48','#6553b0','#d0a3ed','#fff5d9'],S21:['#283848','#a08450','#e3c99b','#fff5dd'],S22:['#321e28','#915044','#cf9f69','#fff0cf']};
function poly(c:C,p:number[][],fill:string,stroke?:string,line=1){c.beginPath();p.forEach(([x,y],i)=>i?c.lineTo(x,y):c.moveTo(x,y));c.closePath();c.fillStyle=fill;c.fill();if(stroke){c.strokeStyle=stroke;c.lineWidth=line;c.stroke()}}
function ribbon(c:C,points:number[][],width:number,fill:string){const a:number[][]=[],b:number[][]=[];for(let i=0;i<points.length;i++){const prev=points[Math.max(0,i-1)],next=points[Math.min(points.length-1,i+1)],dx=next[0]-prev[0],dy=next[1]-prev[1],d=Math.hypot(dx,dy)||1,w=width*Math.sin(Math.PI*i/(points.length-1))**.7;a.push([points[i][0]-dy/d*w,points[i][1]+dx/d*w]);b.unshift([points[i][0]+dy/d*w,points[i][1]-dx/d*w]);}poly(c,[...a,...b],fill)}
function glow(c:C,x:number,y:number,r:number,color:string,a=.3){if(r<=0)return;c.save();c.globalAlpha*=a;const g=c.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,color+'aa');g.addColorStop(1,color+'00');c.fillStyle=g;c.fillRect(x-r,y-r,r*2,r*2);c.restore()}
function glyph(c:C,shape:string,x:number,y:number,r:number,color:string){c.save();c.translate(x,y);c.strokeStyle=color;c.fillStyle=color;c.lineWidth=Math.max(1,r*.065);c.lineCap='round';c.lineJoin='round';c.beginPath();
 if(/KNIGHT|swords|blade/.test(shape)){c.moveTo(0,r);c.lineTo(0,-r);c.lineTo(-r*.2,-r*.65);c.moveTo(0,-r);c.lineTo(r*.2,-r*.65);c.moveTo(-r*.55,r*.3);c.lineTo(r*.55,r*.3);}
 else if(/MAGE|sigil|crown/.test(shape)){c.moveTo(0,r);c.lineTo(0,-r*.5);c.moveTo(0,-r);c.lineTo(r*.45,-r*.5);c.lineTo(0,0);c.lineTo(-r*.45,-r*.5);c.closePath();if(shape==='crown'){c.moveTo(-r,r*.1);c.lineTo(-r*.7,r*.65);c.lineTo(r*.7,r*.65);c.lineTo(r,r*.1)}}
 else if(/ARCHER|arrow/.test(shape)){c.moveTo(-r*.3,-r);c.quadraticCurveTo(r,r*.1,-r*.3,r);c.lineTo(-r*.3,-r);c.moveTo(-r,0);c.lineTo(r,0);c.lineTo(r*.65,-r*.25);}
 else if(/ROGUE/.test(shape)){c.moveTo(-r*.6,r);c.lineTo(r*.35,-r);c.lineTo(r*.6,-r*.2);c.lineTo(-r*.3,r*.65);}
 else if(shape==='hourglass'){c.moveTo(-r*.6,-r);c.lineTo(r*.6,-r);c.lineTo(-r*.6,r);c.lineTo(r*.6,r);c.closePath()}
 else if(shape==='target'){for(let i=0;i<4;i++){c.moveTo(-r,-r*.5);c.lineTo(-r,-r);c.lineTo(-r*.5,-r);c.rotate(Math.PI/2)}}
 else{c.moveTo(0,-r);c.lineTo(r*.7,-r*.45);c.lineTo(r*.5,r*.5);c.lineTo(0,r);c.lineTo(-r*.5,r*.5);c.lineTo(-r*.7,-r*.45);c.closePath();c.moveTo(0,-r*.55);c.lineTo(0,r*.4);c.moveTo(-r*.3,-r*.1);c.lineTo(r*.3,-r*.1)}
 c.stroke();c.restore();}
const edgeCache=new WeakMap<HTMLCanvasElement,HTMLCanvasElement>();
function edges(face:HTMLCanvasElement){let edge=edgeCache.get(face);if(edge)return edge;edge=document.createElement('canvas');edge.width=face.width;edge.height=face.height;const c=edge.getContext('2d')!;c.drawImage(face,0,0);const img=c.getImageData(0,0,edge.width,edge.height),src=new Uint8ClampedArray(img.data),w=edge.width;for(let y=1;y<edge.height-1;y++)for(let x=1;x<w-1;x++){const i=(y*w+x)*4;const lum=(j:number)=>(src[j]+src[j+1]+src[j+2])/3;const diff=Math.abs(lum(i+4)-lum(i-4))+Math.abs(lum(i+w*4)-lum(i-w*4));img.data[i]=235;img.data[i+1]=249;img.data[i+2]=255;img.data[i+3]=Math.min(160,diff*1.6)*src[i+3]/255;}c.putImageData(img,0,0);edgeCache.set(face,edge);return edge;}
export function prepareSurface(face:HTMLCanvasElement){edges(face)}
export class Renderer{
 canvas=document.createElement('canvas');ctx:C; variant=0;reduced=false;faces=new Map<string,HTMLCanvasElement>();anchors!:Anchors;metrics={frames:0,totalMs:0,maxMs:0};
 constructor(){this.canvas.className='c-vfx';this.canvas.style.cssText='position:fixed;inset:0;pointer-events:none;z-index:90';document.body.append(this.canvas);this.ctx=this.canvas.getContext('2d')!;this.resize();}
 resize(){const d=Math.min(devicePixelRatio,2);this.canvas.width=innerWidth*d;this.canvas.height=innerHeight*d;this.canvas.style.width=innerWidth+'px';this.canvas.style.height=innerHeight+'px';this.ctx.setTransform(d,0,0,d,0,0)}
 clear(){this.ctx.clearRect(0,0,innerWidth,innerHeight);document.querySelectorAll<HTMLElement>('[data-c-motion]').forEach(e=>{e.style.translate='';e.style.rotate='';e.style.visibility='';delete e.dataset.cMotion;})}
 face(point:Point,_p:number[],alpha=1,offset=0){const c=this.ctx,face=this.faces.get(point.el?.dataset.uid||'')||this.faces.get('source');if(!face)return;c.save();c.globalAlpha*=alpha;c.drawImage(face,point.x-point.w/2,point.y-point.h/2+offset,point.w,point.h);c.restore()}
 surface(pt:Point,p:number,pal:string[],seg=false){const c=this.ctx,w=pt.w,h=pt.h,life=Math.sin(Math.PI*clamp(p));c.save();c.translate(pt.x,pt.y);c.beginPath();c.roundRect(-w*.5,-h*.5,w,h,w*.05);c.clip();
  c.globalAlpha=.22*life;c.fillStyle=pal[0];c.fillRect(-w/2,-h/2,w,h);c.globalAlpha=.6*life;
  for(let i=0;i<8;i++){const x=(hash(i+3)-.5)*w,y=(hash(i+33)-.5)*h;c.beginPath();c.moveTo(x,y);for(let j=1;j<6;j++){const yy=y+(j-2)*h*.13;c.lineTo(x+Math.sin(j*1.7+i)*w*.12,yy)}c.strokeStyle=i%3?pal[2]:pal[3];c.lineWidth=i%3?.65:1.1;c.setLineDash(seg?[w*.045,w*.018]:[]);c.lineDashOffset=-p*30;c.stroke();}
  const face=pt.el?.dataset.uid?this.faces.get(pt.el.dataset.uid):undefined;if(face){c.save();c.globalAlpha=life*.65;c.globalCompositeOperation='screen';c.drawImage(edges(face),-w/2,-h/2,w,h);c.restore();}const sweep=-h*.6+h*1.2*smooth(p);const g=c.createLinearGradient(0,sweep-h*.14,0,sweep+h*.14);g.addColorStop(0,pal[2]+'00');g.addColorStop(.5,pal[3]+'bb');g.addColorStop(1,pal[2]+'00');c.fillStyle=g;c.fillRect(-w/2,-h/2,w,h);
  c.setLineDash([]);c.lineWidth=1.4;c.strokeStyle=pal[3];c.strokeRect(-w*.46,-h*.46,w*.92,h*.92);c.restore();glow(c,pt.x,pt.y,w*.9,pal[2],life*.12);
 }
 material(pt:Point,p:number,pal:string[],shape:string,assemble=true){const c=this.ctx,w=pt.w,h=pt.h,seg=this.variant===1;const q=assemble?1-smooth(p):smooth(p);const face=this.faces.get(pt.el?.dataset.uid||'')||this.faces.get('source');
  c.save();c.translate(pt.x,pt.y);c.scale(1,1);const shadow=(1-q)*.24;c.fillStyle=`rgba(15,20,30,${shadow})`;c.beginPath();c.ellipse(0,h*.53,w*.58,h*.09,0,0,Math.PI*2);c.fill();
  const cloth=/SOLDIER|KNIGHT|GUNNER|CAVALRY|M11|GM[56]|HORDE|ELITE|LEVY|VITAL4|CASTLE/.test(shape),stone=/GOLEM|NGA3|NWL3|MANA_GIANT|M10|CASTLE/.test(shape),contract=/MERC/.test(shape);const rows=seg?(cloth?4:5):(stone?4:9),cols=seg?(cloth?1:3):(stone?3:1);
  for(let row=0;row<rows;row++)for(let col=0;col<cols;col++){
   const idx=row*cols+col;const local=seg?clamp((p-idx/(rows*cols)*.18)/.82):p;const q=assemble?1-smooth(local):smooth(local);const sw=w/cols,sh=h/rows,x=-w/2+col*sw,y=-h/2+row*sh,sign=(idx%2?1:-1);c.save();
   const bend=q*(seg?(cloth?Math.sin(row*1.4)*w*.35:sign*w*.65):stone?sign*w*.35:Math.sin(row*.65)*w*.4),rise=q*(seg?-(rows-row)*h*.17:stone?(rows-row)*h*.22:-(rows-row)*h*.11);c.translate(bend,rise);c.rotate(q*sign*(seg?(cloth?.16:.38):stone?.1:.06));if(contract)c.scale(1,1+q*.6);
   c.beginPath();c.moveTo(x,y);c.lineTo(x+sw*.38,y+q*sh*.13);c.lineTo(x+sw*.62,y-q*sh*.05);c.lineTo(x+sw,y+q*sh*.3);c.lineTo(x+sw-q*sw*.12,y+sh);c.lineTo(x+sw*.45,y+sh-q*sh*.08);c.lineTo(x,y+sh-q*sh*.1);c.closePath();c.clip();
   c.globalAlpha=1-q*.25;if(face)c.drawImage(face,-w/2,-h/2,w,h);c.globalAlpha=q*.7;c.fillStyle=pal[idx%2];c.fillRect(x,y,sw,sh);if(face){c.globalAlpha=.55*Math.sin(p*Math.PI);c.globalCompositeOperation='screen';c.drawImage(edges(face),-w/2,-h/2,w,h);c.globalCompositeOperation='source-over';}c.globalAlpha=1;c.strokeStyle=pal[2];c.lineWidth=1.5;c.strokeRect(x,y,sw,sh);c.strokeStyle=pal[3];c.lineWidth=.6;c.beginPath();c.moveTo(x+sw*.15,y+sh*.5);c.lineTo(x+sw*.5,y+sh*.15);c.lineTo(x+sw*.85,y+sh*.5);c.stroke();c.restore();
  }
  c.restore();if(p>.72&&/CHOSEN|CASTLE|MERC/.test(shape))glyph(c,shape,pt.x,pt.y,pt.w*.25*Math.sin((p-.72)/.28*Math.PI),pal[3]);
 }
 flight(a:Point,b:Point,p:number,pal:string[],shape='blade',power=1){const c=this.ctx,seg=this.variant===1,w=Math.max(5,a.w*.11)*power,meteor=shape==='meteor';let u=smooth(seg?clamp((p-.12)/.88):p),x=lerp(a.x,b.x,u),y=lerp(a.y,b.y,u)-Math.sin(Math.PI*u)*(seg?55:25);if(meteor)y-=Math.sin(Math.PI*u)*a.h*1.7;
  const dx=b.x-a.x,dy=b.y-a.y,angle=Math.atan2(dy,dx);const pts:number[][]=[];for(let i=0;i<22;i++){const t=clamp(u-(1-i/21)*.38),px=lerp(a.x,b.x,t),py=lerp(a.y,b.y,t)-Math.sin(Math.PI*t)*(meteor?a.h*1.7:seg?55:25);const wave=Math.sin(t*Math.PI)*Math.sin(t*12+p*5)*w*.55;pts.push([px+Math.cos(angle+Math.PI/2)*wave,py+Math.sin(angle+Math.PI/2)*wave]);}
  if(!seg){ribbon(c,pts,w*.9,pal[0]);ribbon(c,pts,w*.55,pal[1]);ribbon(c,pts.map(([xx,yy],i)=>[xx,yy+Math.sin(i*.6+p*12)*w*.16]),w*.2,pal[2]);ribbon(c,pts,w*.045,pal[3]);for(let strand=0;strand<3;strand++){const trace=pts.map(([xx,yy],i)=>[xx+Math.sin(i*.62+strand*2+p*10)*w*.24,yy+Math.cos(i*.5+strand)*w*.15]);ribbon(c,trace,w*.045,pal[strand+1]);}}
  else{for(let i=2;i<18;i+=2){const [xx,yy]=pts[i],z=w*(i/22);c.save();c.translate(xx,yy);c.rotate(angle+Math.sin(i)*.3);poly(c,[[-z*1.5,0],[0,-z*.45],[z,0],[0,z*.55]],pal[i%3],pal[3],.65);c.restore();}}
  c.save();c.translate(x,y);c.rotate(angle);if(/fireball|flame|meteor/.test(shape)){for(let k=0;k<3;k++){const z=w*(1-k*.27);c.beginPath();c.moveTo(z*1.3,0);c.bezierCurveTo(z*.8,-z*1.15,-z*.3,-z*.95,-z*1.7,-z*.55);c.quadraticCurveTo(-z*.55,-z*.2,-z*2.5,-z*.85);c.quadraticCurveTo(-z*1.2,z*.1,-z*2,z*.62);c.quadraticCurveTo(-z*.65,z*.35,-z*1.3,z*.85);c.bezierCurveTo(-z*.3,z*.7,z*.8,z*.9,z*1.3,0);c.fillStyle=pal[k];c.fill();if(k===0){c.strokeStyle=pal[2];c.lineWidth=.8;c.stroke();}}const face=this.faces.get(a.el?.dataset.uid||'')||this.faces.get('source');if(face){c.save();c.beginPath();c.ellipse(0,0,w*.8,w*.55,0,0,Math.PI*2);c.clip();c.globalAlpha=.22;c.globalCompositeOperation='screen';c.drawImage(face,-w,-w,w*2,w*2);c.restore();}}else poly(c,[[w*1.5,0],[-w*.4,-w*.55],[-w*1.1,0],[-w*.4,w*.55]],pal[1],pal[3],1.2);c.restore();glow(c,x,y,w*2,pal[2],.2);
 }
 impact(pt:Point,p:number,pal:string[],size=1){const c=this.ctx,r=pt.w*.48*size,expand=smooth(p*3),collapse=1-smooth((p-.35)/.65);c.save();c.translate(pt.x,pt.y);for(let k=0;k<3;k++){const s=r*(1-k*.25)*expand*collapse;const points:number[][]=[];for(let i=0;i<18;i++){const angle=i/18*Math.PI*2,z=s*(i%2?.4:1)*(1+hash(i)*.35);points.push([Math.cos(angle)*z,Math.sin(angle)*z*.72]);}poly(c,points,pal[k],k===0?pal[2]:undefined,.6)}for(let i=0;i<7;i++){const a=i*2.4,d=r*(.45+p)*1.2,z=r*.09*collapse;poly(c,[[Math.cos(a)*d,Math.sin(a)*d],[Math.cos(a)*d+z,Math.sin(a)*d-z],[Math.cos(a)*d+z*.5,Math.sin(a)*d+z]],pal[2])}c.restore();}
 draw(plan:Plan,ms:number,anchors:Anchors){const start=performance.now();this.anchors=anchors;this.clear();const pal=palettes[plan.family]||palettes.S08;
  for(const e of plan.events){const p=(ms-e.at)/e.duration;if(p<0||p>1)continue;const a=anchors[e.from],b=anchors[e.to];if(!a||!b)continue;this.effect(e,a,b,p,pal);}
  this.metrics.frames++;const dt=performance.now()-start;this.metrics.totalMs+=dt;this.metrics.maxMs=Math.max(dt,this.metrics.maxMs);
 }
 effect(e:Cue,a:Point,b:Point,p:number,pal:string[]){const c=this.ctx,life=Math.sin(Math.PI*p),seg=this.variant===1;
  if(this.reduced){c.save();c.globalAlpha=.5*life;glyph(c,e.shape||e.kind,b.x,b.y,b.w*.23,pal[1]);c.restore();return;}
  switch(e.kind){
  case 'surface':this.surface(a,p,pal,seg);break;
  case 'summon':{if(b.el){b.el.style.visibility='hidden';b.el.dataset.cMotion='1';}const q=smooth(p/.78);const pos={...b,x:lerp(a.x,b.x,q),y:lerp(a.y,b.y,q)-Math.sin(Math.PI*q)*a.h*.45,w:lerp(a.w,b.w,q),h:lerp(a.h,b.h,q)};this.material(pos,p,pal,e.shape||'',true);if(p>.7)this.impact({...b,y:b.y+b.h*.45},(p-.7)/.3,pal,.65);break;}
  case 'break':if(a.el){a.el.style.visibility='hidden';a.el.dataset.cMotion='1';}if(p<.7)this.material({...a,x:lerp(a.x,b.x,smooth(p)*.2),y:a.y-p*a.h*.2,w:a.w*(1-smooth(p)*.7),h:a.h*(1-smooth(p)*.7)},p/.7,pal,'',false);else this.flight({...a,w:a.w*.4},b,(p-.7)/.3,pal,'sigil',.5);break;
  case 'move':this.flight(a,b,p,pal,e.shape);if(p<.4)this.surface(a,p/.4,pal,seg);if(p>.8)this.surface(b,(p-.8)/.2,pal,seg);break;
  case 'shot':if((e.shape==='blade'||e.shape==='counter')&&a.el?.dataset.uid?.startsWith('field')){const approach=p<.64?smooth(p/.64):1-smooth((p-.64)/.36);a.el.dataset.cMotion='1';a.el.style.translate=`${(b.x-a.x)*approach*.72}px ${(b.y-a.y)*approach*.72}px`;a.el.style.rotate=`${Math.sin(p*Math.PI)*(seg?-7:5)}deg`;if(p>.45)this.flight({...a,x:lerp(a.x,b.x,.7),y:lerp(a.y,b.y,.7)},b,(p-.45)/.55,pal,e.shape,.7);}else this.flight(a,b,p,pal,e.shape,e.shape==='fireball'?1.35:e.shape==='cannon'?1.25:1);if(p<.32)this.surface(a,p/.32,pal,seg);break;
  case 'hit':this.impact(b,p,pal);if(b.el){b.el.dataset.cMotion='1';b.el.style.translate=`${Math.sin(p*30)*(1-p)*4}px ${Math.sin(p*24)*(1-p)*2}px`;}break;
  case 'zone':{const z={...b,h:b.h*.6,y:b.y+b.h*.2};this.surface(b,p,pal,seg);if(e.shape==='flame'){for(let i=0;i<4;i++)this.flight({...z,x:z.x+(i-1.5)*z.w*.2,y:z.y+z.h*.45},{...z,x:z.x+(i-1.5)*z.w*.3,y:z.y-z.h*.8},(p+i*.13)%1,pal,'flame',.7);}else{for(let i=0;i<5;i++){const x=b.x+(i-2)*b.w*.22,y=b.y+b.h*.45,q=life;poly(c,[[x-8,y],[x-4,y-q*b.h*.4],[x+5,y-q*b.h*.55],[x+9,y]],pal[i%2],pal[2],1)}}break;}
  case 'charge':{const n=Math.min(5,Math.abs(e.count||1));for(let i=0;i<n;i++){const q=clamp((p-i*.07)/.7);if(q<1)this.flight({...a,x:a.x+(i-(n-1)/2)*a.w*.15},b,q,pal,'sigil',.5);else glyph(c,'guts',b.x+(i-(n-1)/2)*b.w*.17,b.y+b.h*.35,b.w*.09*(1-smooth((p-.85)/.15)),pal[2]);}this.surface(b,p,pal,seg);break;}
  case 'shield':{const r=b.w*.58*life;const evade=e.shape==='evade';if(evade&&b.el){b.el.dataset.cMotion='1';b.el.style.translate=`${Math.sin(p*Math.PI)*b.w*.7}px 0px`;}c.save();c.translate(b.x,b.y);if(seg){for(let i=0;i<3;i++)poly(c,[[-r+i*r*.65,-r*.65],[-r+i*r*.65+r*.7,-r*.65],[-r+i*r*.65+r*.6,r*.55],[-r+i*r*.65+r*.25,r]],pal[i%2]+'cc',pal[2],1.3);}else poly(c,[[-r,-r*.65],[0,-r],[r,-r*.65],[r*.85,r*.45],[0,r],[-r*.85,r*.45]],pal[0]+'cc',pal[2],2);glyph(c,e.shape||'shield',0,0,r*.45,pal[3]);c.restore();break;}
  case 'buff':{if(['mana','setmana','spend','refill'].includes(e.shape||'')){const target={...b,x:b.x+b.w*.27,w:Math.max(12,Math.min(28,b.h*.48)),h:b.h*.7},positive=e.shape!=='setmana'&&(e.amount||0)>0;const q=clamp(p/.7);if(q<1)this.flight(positive?a:target,positive?target:a,q,pal,'sigil',.55);if(p>.5){const r=target.w*.52*(positive?smooth((p-.5)/.2):1-smooth((p-.5)/.5));c.save();c.translate(target.x,target.y);poly(c,[[0,-r*1.6],[r,-r*.35],[r*.7,r],[0,r*1.6],[-r*.7,r],[-r,-r*.35]],pal[0],pal[2],1);poly(c,[[0,-r*1.6],[r,-r*.35],[0,r*.1]],pal[2],pal[3],.8);poly(c,[[r,-r*.35],[r*.7,r],[0,r*1.6],[0,r*.1]],pal[1],pal[2],.7);poly(c,[[-r,-r*.35],[0,r*.1],[0,r*1.6],[-r*.7,r]],pal[1],pal[2],.7);c.restore();}break;}const col=(e.shape==='hp'||e.shape==='sethp')?['#572132','#a94157','#f17d93','#ffeaec']:['#143455','#226aac','#6bbcee','#e8faff'];const r=b.w*.22*life,dy=(e.amount||1)>0?-1:1;const x=b.x-b.w*.3,y=b.y+dy*(b.h*.2+p*b.h*.25);c.save();c.translate(x,y);c.scale(1,dy);poly(c,[[0,r],[-r,-r*.1],[-r*.4,-r*.1],[-r*.4,-r],[r*.4,-r],[r*.4,-r*.1],[r,-r*.1]],col[1],col[3],1);c.restore();this.surface(b,p,col,seg);break;}
  case 'swap':{for(let i=0;i<2;i++){const x=b.x+(i?1:-1)*b.w*.35,y=b.y+b.h*.4;this.flight({...b,x,y,w:b.w*.35},{...b,x:b.x-(i?1:-1)*b.w*.35,y:y-b.h*.2},p,i?[pal[0],'#ad3857','#f396ab',pal[3]]:[pal[0],'#2775bd','#a4d6fc',pal[3]],'sigil',.8)}break;}
  case 'dice':{const n=e.count||1,r=Math.min(15,b.w*.16);for(let i=0;i<n;i++){const cols=Math.min(5,n),x=b.x+(i%cols-(cols-1)/2)*r*2.3,y=b.y-b.h*.35-Math.floor(i/cols)*r*2.3;c.save();c.translate(x,y);c.rotate(p<.6?(1-smooth(p/.6))*Math.PI*3:0);poly(c,[[-r,-r],[r,-r],[r,r],[-r,r]],pal[0],pal[2],1.5);const value=p<.6?1+Math.floor(p*20+i)%6:((e.amount||4)-1+i)%6+1;for(let j=0;j<value;j++){c.beginPath();c.arc((j%2-.5)*r*.75,(Math.floor(j/2)-1)*r*.6,Math.max(1,r*.14),0,Math.PI*2);c.fillStyle=pal[3];c.fill()}c.restore();}break;}
  case 'mark':this.surface(b,p,pal,seg);glyph(c,e.shape||'shield',b.x,b.y,b.w*.32*life,pal[2]);break;
  }
 }
 dispose(){this.clear();this.faces.clear();this.canvas.remove()}
}
