import './style.css';import {scenes,cardsFor,families,familyFor,DURATION,plan} from './choreography';import {DB} from '../../shared/cards';
const root=document.querySelector<HTMLElement>('#lab')!;
root.innerHTML=`<aside><div class="eyebrow">LORE / A · MATERIAL STUDIES</div><h1>記録の変容</h1><p class="intro">影・呪い・血・知識の9系統。<br>同じ実盤面で、ふたつの物質と時間を比較。</p><label>系統 / 効果場面<select id="scene"></select></label><label>カード<select id="card"></select></label><div class="variant-row"><button id="v0" class="selected">① 刻む</button><button id="v1">② 織る</button></div><h2 id="title"></h2><p id="intent"></p><label>陣営<select id="side"><option value="0">自分</option><option value="1">相手（公開済みカード）</option></select></label><label>場面の分岐<select id="branch"><option value="success">基本 / 成立</option><option value="alternate">別条件 / 不成立 / 複数</option></select></label><details><summary>現行カードの効果 / 接続</summary><p id="effect"></p><p id="stages"></p></details><p class="disclaimer">ローカル制作プレビュー・ユーザー未承認<br>GameView＋現行カード描画。状態と効果イベントは固定の検証用。通常対戦は変更しません。</p></aside><section class="workspace"><header><span id="scene-name"></span><span class="badge">v54 · 実盤面</span></header><div id="stage"><iframe title="LORE 実盤面" src="/src/dev/series-vfx-a/board.html"></iframe></div><footer><div id="phase">描画を準備しています…</div><input id="seek" aria-label="シーク" type="range" min="0" max="3900" value="0"><div class="controls"><button id="play">再生</button><button id="reset">リセット</button><select id="speed" aria-label="速度"><option value="1">1×</option><option value=".5">0.5×</option><option value=".25">0.25×</option></select><label><input type="checkbox" id="loop" checked>ループ</label><label><input type="checkbox" id="dark">暗背景</label><label><input type="checkbox" id="reduced">動きを減らす</label><button id="sequence">全場面を連続</button><button id="both">同時発動</button><span id="clock">0.00 / 3.90</span></div></footer></section>`;
const el=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;const select=el<HTMLSelectElement>('scene'),card=el<HTMLSelectElement>('card');
for(const s of scenes){const o=document.createElement('option');o.value=s.id;o.textContent=`${s.id} · ${s.name}`;select.append(o);}
const iframe=root.querySelector('iframe')!;const board=()=> (iframe.contentWindow as any)?.seriesABoard;
let selected=scenes[0],variant=0,time=0,playing=false,speed=1,last=0,raf=0,loaded=false,sequence=false,simultaneous=false,loading=0;
function refreshCard(){card.replaceChildren();for(const id of cardsFor(selected)){const o=document.createElement('option');o.value=id;o.textContent=`${DB[id]?.nameJa||id} · ${id}`;card.append(o);}}
function updateLabels(){const f=families[familyFor(selected,card.value)];el('title').textContent=(variant===0?'① '+f.name:'② '+f.other);el('intent').textContent=f.intent[variant];el('effect').textContent=DB[card.value]?.textJa||DB[card.value]?.text||'';el('stages').textContent=selected.stages||selected.animation||'';el('scene-name').textContent=selected.id+' / '+selected.name;el('v0').classList.toggle('selected',variant===0);el('v1').classList.toggle('selected',variant===1);}
async function load(){const token=++loading;playing=false;loaded=false;time=0;updateLabels();el('phase').textContent='カード表面を読み込み中…';await board()?.load(selected.id,card.value,variant,+el<HTMLSelectElement>('side').value,el<HTMLSelectElement>('branch').value);if(token!==loading)return;loaded=true;seek(0);el('play').textContent='再生';}
function seek(ms:number){time=Math.max(0,Math.min(DURATION,ms));if(!loaded)return;board().seek(time);if(simultaneous){const api=board();const first=api.info();/* additional time window is rendered by the board API when enabled */if(api.simultaneous)api.simultaneous(time);void first;}el<HTMLInputElement>('seek').value=String(time);el('clock').textContent=(time/1000).toFixed(2)+' / 3.90';const active=plan(selected,card.value,el<HTMLSelectElement>('branch').value).filter(b=>time>=b.at&&time<b.at+b.duration);el('phase').textContent=active.map(b=>b.label).join(' → ')||(time===DURATION?'完了 · リセットで初期状態へ':time>Math.max(...plan(selected,card.value,el<HTMLSelectElement>('branch').value).map(b=>b.at+b.duration))?'作用完了 / 余韻':'予兆 / 次の段階を待つ');}
function tick(now:number){if(playing&&loaded){time+=(now-last)*speed;if(time>=DURATION){if(sequence){playing=false;const i=(scenes.indexOf(selected)+1)%scenes.length;selected=scenes[i];select.value=selected.id;refreshCard();void load().then(()=>play());}else if(el<HTMLInputElement>('loop').checked)time%=DURATION;else{time=DURATION;playing=false;el('play').textContent='再生';}}seek(time);}last=now;raf=requestAnimationFrame(tick);}
function play(){if(!loaded)return;if(time>=DURATION)time=0;playing=true;last=performance.now();el('play').textContent='停止';}
refreshCard();updateLabels();select.onchange=()=>{selected=scenes.find(s=>s.id===select.value)!;refreshCard();void load();};card.onchange=()=>void load();for(const v of [0,1])el('v'+v).onclick=()=>{variant=v;void load();};for(const id of ['side','branch'])el<HTMLSelectElement>(id).onchange=()=>void load();
el('play').onclick=()=>{if(playing){playing=false;el('play').textContent='再生';}else play();};el('reset').onclick=()=>{playing=false;sequence=false;seek(0);el('play').textContent='再生';};el<HTMLInputElement>('seek').oninput=e=>{playing=false;seek(+(e.target as HTMLInputElement).value);el('play').textContent='再生';};el<HTMLSelectElement>('speed').onchange=e=>speed=+(e.target as HTMLSelectElement).value;el<HTMLInputElement>('dark').onchange=e=>board().setDark((e.target as HTMLInputElement).checked);el<HTMLInputElement>('reduced').onchange=e=>{board().setReduced((e.target as HTMLInputElement).checked);};el('sequence').onclick=()=>{sequence=!sequence;el('sequence').textContent=sequence?'連続再生を終了':'全場面を連続';play();};el('both').onclick=()=>{simultaneous=!simultaneous;board().setSimultaneous?.(simultaneous);el('both').classList.toggle('selected',simultaneous);play();};
iframe.onload=()=>{const wait=setInterval(()=>{if(board()?.ready){clearInterval(wait);void load();}},100);};
if(matchMedia('(prefers-reduced-motion:reduce)').matches){el<HTMLInputElement>('reduced').checked=true;el<HTMLInputElement>('loop').checked=false;}
document.addEventListener('visibilitychange',()=>{if(document.hidden){playing=false;board()?.seek(0);el('play').textContent='再生';}});raf=requestAnimationFrame(tick);window.addEventListener('pagehide',()=>{cancelAnimationFrame(raf);board()?.dispose();},{once:true});
(window as any).seriesALab={get ready(){return loaded},get playing(){return playing},get time(){return time},get scenes(){return scenes},async choose(id:string,c?:string,v=0,side=0,branch='success'){selected=scenes.find(s=>s.id===id)!;select.value=id;refreshCard();if(c)card.value=c;variant=v;el<HTMLSelectElement>('side').value=String(side);el<HTMLSelectElement>('branch').value=branch;await load();},seek,play,pause(){playing=false;el('play').textContent='再生'},board, setSpeed(n:number){speed=n},setLoop(v:boolean){el<HTMLInputElement>('loop').checked=v}};
