import '../../styles/tokens.css';import '../../styles/base.css';import '../../styles/card.css';import '../../styles/game-overlays.css';import '../../styles/game.css';import '../../styles/screens.css';import '../../styles/reading-board.css';import '../../styles/presentation.css';
import {GameView,setMyAvatar,setOppAvatar} from '../../ui/boardView';import {createGame} from '../../shared/engine';import {DB,STARTERS,FRAME_BACK} from '../../shared/cards';import {startBoardLayout} from '../../ui/layout';import {cardEl} from '../../ui/cardView';import {captureCardSurface} from '../../ui/cardSurface';import {setLang} from '../../i18n';import {projectBoardDOM} from '../../ui/boardProjection';
import {scenes,cardsFor,familyFor,plan,DURATION,type Anchor,type Beat} from './choreography';import {Renderer,type Point} from './render';
setLang('ja');setMyAvatar('SEEKER_BLUE');setOppAvatar('SEEKER_RED');
const noop=()=>{};const view=new GameView(document.querySelector('#app')!,0,{onPlay:noop,onBlockedPlay:noop,onAttack:noop,onBlockedAttack:noop,onReorder:noop,onChooseTarget:noop,onBuyMarket:noop,onBuySupply:noop,onRefresh:noop,onEndTurn:noop,onSurrender:noop});
const css=document.createElement('style');css.textContent=`.topbar,.help-fab,.mute-fab,.help-callout{display:none!important}body{overflow:hidden}body.a-dark #app{filter:brightness(.66) saturate(.7)}.a-reveal{position:fixed!important;z-index:40;pointer-events:none;transform:none!important;transition:none!important}.a-semantic{position:fixed;z-index:85;pointer-events:none;padding:4px 7px;border:1px solid #a99570;background:#171724ee;color:#f3e8d8;border-radius:4px;font:11px system-ui;max-width:180px;text-align:center}.a-result{outline:1px solid #b49c70;outline-offset:2px}`;document.head.append(css);
const stop=startBoardLayout();const renderer=new Renderer();const faces=new Map<string,HTMLCanvasElement>();const surfaces=new Map<string,HTMLCanvasElement>();
let scene=scenes[0],cardId=cardsFor(scene)[0],variant=0,side=0,branch='success',time=0,beats:Beat[]=[],source:HTMLElement|null=null,ready=false,generation=0,disposed=false;let reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
let simultaneous=false;let resultNodes:HTMLElement[]=[];let sourceFace:HTMLCanvasElement;let resultCards:HTMLElement[]=[];let fixtureCards:HTMLElement[]=[];let support1='VAMP1',support2='TDE1',enemyId='ASSASSIN1',triggerId='RUNE3';
const card=(id:string,uid:string)=>({...DB[id]||STARTERS[id]||DB.M4,uid});
const mon=(id:string,uid:string)=>({...card(id,uid),atk:DB[id]?.atk??3,def:DB[id]?.def??4,exhausted:false,summonedTurn:0,tempAtk:0,atkMod:0,defMod:0,dmg:0});
function clearExtra(){source?.remove();source=null;for(const n of fixtureCards)n.remove();fixtureCards=[];for(const el of [...resultNodes,...resultCards])el.remove();resultNodes=[];resultCards=[];document.querySelectorAll<HTMLElement>('[data-a-hidden]').forEach(n=>{n.style.visibility='';delete n.dataset.aHidden;});}
async function surface(id:string){if(surfaces.has(id))return surfaces.get(id)!;const c=cardEl(card(id,'capture'),{compactField:DB[id]?.t==='mon'});c.style.cssText='position:fixed;left:-3000px;top:0;width:160px;height:250px;--cw:160px;--ch:250px;transform:none;pointer-events:none';document.body.append(c);try{await document.fonts.ready;await Promise.all([...c.querySelectorAll('img')].map(i=>i.decode().catch(()=>{})));const raw=await captureCardSurface(c,FRAME_BACK,true,false);const out=document.createElement('canvas');out.width=384;out.height=Math.round(384*raw.face!.height/raw.face!.width);out.getContext('2d')!.drawImage(raw.face!,0,0,out.width,out.height);surfaces.set(id,out);if(surfaces.size>30){const oldest=surfaces.keys().next().value!;surfaces.delete(oldest);}return out;}finally{c.remove();}}
function rect(selector:string,fallback:Point):Point{const el=document.querySelector<HTMLElement>(selector);if(!el)return fallback;const r=el.getBoundingClientRect();if(!r.width)return fallback;return{x:r.x+r.width/2,y:r.y+r.height/2,w:r.width,h:r.height};}
function anchors():Record<Anchor,Point>{const mine=side===0?'me':'opp',enemy=side===0?'opp':'me',p=side===0?'Me':'Opp',o=side===0?'Opp':'Me',prefix=side===0?'my':'opp',other=side===0?'opp':'my';const fallback={x:innerWidth*.5,y:innerHeight*.65,w:innerWidth*.065,h:innerWidth*.10};
 const src=rect(`[data-uid="a-source-${side}"]`,fallback),ally=rect(`[data-uid="a-ally-${side}"]`,{...src,x:src.x-src.w*1.4}),ally2=rect(`[data-uid="a-ally2-${side}"]`,{...src,x:src.x+src.w*1.4});
 const point=(selector:string,fb=src,cardSize=false)=>{const a=rect(selector,fb);return cardSize?{...a,w:src.w,h:src.h}:a;};
 return{source:src,ally,ally2,enemy:point(`[data-uid="a-source-${1-side}"]`),hp:point(`#portrait${p} .pt-vitals`,src,true),enemyHp:point(`#portrait${o} .pt-vitals`,src,true),mana:point(`#portrait${p} .pt-mana`,src,true),enemyMana:point(`#portrait${o} .pt-mana`,src,true),shelf:point(`#pile-${prefix}Disc`,src,true),enemyShelf:point(`#pile-${other}Disc`,src,true),rift:point(`#rift-${mine}`,src,true),enemyRift:point(`#rift-${enemy}`,src,true),deck:point(`#pile-${prefix}Deck`,src,true),enemyDeck:point(`#pile-${other}Deck`,src,true),hand:point(side===0?'#hand':'#oppHand',src,true),spell:point(`#${mine}Row .buff-icon`,src,true),quest:point(`#${mine}Row .buff-icon--quest`,src,true)};
}
async function loadNow(id=scene.id,selected?:string,nextVariant=variant,nextSide=side,nextBranch=branch){const token=++generation;ready=false;renderer.clear();clearExtra();scene=scenes.find(s=>s.id===id)||scenes[0];cardId=selected||cardsFor(scene)[0];variant=nextVariant;side=nextSide;branch=nextBranch;beats=plan(scene,cardId,branch);support1=scene.id==='A180'?'CASTLE':scene.id==='A164'?'TSO1':scene.id==='S20'||['A055','A167','A168','A169'].includes(scene.id)?'TDE2':'VAMP1';support2=scene.id==='A164'?'TSO2':scene.id==='S20'||['A055','A167','A168','A169'].includes(scene.id)?'TDE3':'TDE1';triggerId=DB[cardId]?.evolveTo?'BLOOD1':scene.id==='A095'?'BLACK_CURSE':scene.id==='A136'||cardId==='RUNE3'?'S10':DB[cardId]?.ench?cardId:'RUNE3';enemyId=scene.id==='A015'?'E3':scene.id==='A084'?'S10':scene.id==='S28'&&cardId==='RUNE1'?'M12':'ASSASSIN1';
 const g=createGame({mode:'bot',seed:71,starting:0,p0:{id:'a-me',name:'YOU'},p1:{id:'a-opp',name:'OPPONENT'}}).state;g.turn=3;g.pending=null;g.opening=undefined;
 for(const [i,p] of g.players.entries()){p.openingDrawReady=false;p.mana=8;p.maxMana=12;p.hp=32;p.traps=[];p.hand=[card('S10',`a-hand-${i}-0`),card('BLOOD1',`a-hand-${i}-1`),card('S6',`a-hand-${i}-2`)];p.discard=[card('CURSE',`a-discard-${i}`),card('M4',`a-discard-${i}-2`)];p.enchants=[{card:card(triggerId,`a-ench-${i}`),turns:3}];p.quests=[{card:card(DB[cardId]?.t==='quest'?cardId:'Q_CASTLE',`a-quest-${i}`),progress:4,startedTurn:1}];p.field=[mon(i===side?(DB[cardId]?.t==='mon'?cardId:'ASSASSIN1'):(DB[enemyId]?.t==='mon'?enemyId:'ASSASSIN1'),`a-source-${i}`),mon(support1,`a-ally-${i}`),mon(support2,`a-ally2-${i}`)];}
 view.render(g);view.setHandOpen(false);await new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r())));projectBoardDOM(view.root);
 const a=anchors();if(DB[cardId]?.t!=='mon'){
 // Public cast fixture: actual cardEl is placed at a measured GameView card slot.
  const slot=document.querySelector<HTMLElement>(`[data-uid="a-source-${side}"]`)!;slot.style.visibility='hidden';slot.dataset.aHidden='true';slot.dataset.uid=`a-under-source-${side}`;
  source=cardEl(card(cardId,`a-source-${side}`));source.classList.add('a-reveal');source.style.cssText=`left:${a.source.x-a.source.w/2}px;top:${a.source.y-a.source.h/2}px;width:${a.source.w}px;height:${a.source.h}px;--cw:${a.source.w}px;--ch:${a.source.h}px`;document.body.append(source);
 }
 if(DB[enemyId]?.t!=='mon'){const target=document.querySelector<HTMLElement>(`[data-uid="a-source-${1-side}"]`)!;const r=target.getBoundingClientRect();target.style.visibility='hidden';target.dataset.aHidden='true';target.dataset.uid=`a-under-enemy-${1-side}`;const face=cardEl(card(enemyId,`a-source-${1-side}`));face.classList.add('a-reveal');face.style.cssText=`left:${r.x}px;top:${r.y}px;width:${r.width}px;height:${r.height}px;--cw:${r.width}px;--ch:${r.height}px`;fixtureCards.push(face);document.body.append(face);}
 sourceFace=await surface(cardId);faces.clear();faces.set('@source',sourceFace);faces.set('@ally',await surface(support1));faces.set('@ally2',await surface(support2));faces.set('@enemy',await surface(enemyId));faces.set('@shelf',await surface('M4'));faces.set('@enemyShelf',await surface('CURSE'));faces.set('@spell',await surface(triggerId));faces.set('@quest',await surface(DB[cardId]?.t==='quest'?cardId:'Q_CASTLE'));for(const id of [...new Set(beats.map(b=>b.card).filter(Boolean))] as string[])faces.set(id,await surface(id));if(token!==generation||disposed)return;ready=true;seek(0);return info();
}
let loadQueue:Promise<unknown>=Promise.resolve();
function load(id=scene.id,selected?:string,nextVariant=variant,nextSide=side,nextBranch=branch){const args=[id,selected,nextVariant,nextSide,nextBranch] as const;loadQueue=loadQueue.catch(()=>undefined).then(()=>disposed?undefined:loadNow(...args));return loadQueue;}
function anchorNode(key:Anchor):HTMLElement|null {const mine=side===0?'me':'opp';const selectors:Partial<Record<Anchor,string>>={source:`[data-uid="a-source-${side}"]`,ally:`[data-uid="a-ally-${side}"]`,ally2:`[data-uid="a-ally2-${side}"]`,enemy:`[data-uid="a-source-${1-side}"]`,spell:`#${mine}Row .buff-icon--spell`,quest:`#${mine}Row .buff-icon--quest`};return selectors[key]?document.querySelector(selectors[key]!):null;}
function seek(ms:number){time=Math.max(0,Math.min(DURATION,ms));renderer.clear();for(const el of [...resultNodes,...resultCards])el.remove();resultNodes=[];resultCards=[];if(!ready)return;const a=anchors(),f=familyFor(scene,cardId);
 const original=anchorNode('source');
 for(const key of ['source','ally','ally2','enemy','spell','quest'] as Anchor[]){const n=anchorNode(key);if(n)n.style.opacity='1';}
 // Summons use a reserved real field slot; the source never disappears for an additional summon.
 for(const b of beats)if(b.kind==='summon'&&b.to!=='source'&&time<DURATION){const n=anchorNode(b.to);if(n)n.style.opacity='0';}
 const q=anchorNode('quest')?.querySelector('.quest-progress');if(q)q.textContent='4/'+(DB[cardId]?.quest?.target||9);
 for(const b of beats){const active=time>=b.at&&time<=b.at+b.duration;
 if(active&&b.from==='source'&&['awaken','summon','shatter'].includes(b.kind)&&(b.kind!=='summon'||b.to==='source')&&!reduced&&original)original.style.opacity='0';
 if(b.kind==='shatter'&&time>=b.at&&time<DURATION){const n=anchorNode(b.from);if(n)n.style.opacity='0';}
 if(time>=b.at+b.duration&&time<DURATION){
   if(b.to==='quest'&&q){if(b.kind==='reset')q.textContent='0/'+(DB[cardId]?.quest?.target||9);else if(b.kind==='progress')q.textContent='5/'+(DB[cardId]?.quest?.target||9);else if(b.kind==='complete')q.textContent=(DB[cardId]?.quest?.target||9)+'/'+(DB[cardId]?.quest?.target||9);}
   if(b.kind==='transfer'&&b.from==='source'&&b.to==='shelf'&&['A002','A092'].includes(scene.id)&&original)original.style.opacity='0';
 }
 renderer.render(b,time,a,faces,sourceFace,f,variant,reduced);
 if(simultaneous){const mirrored={...a,source:a.ally,ally:a.ally2};renderer.render(b,time-180,mirrored,faces,sourceFace,f,variant,reduced);}
 if(time>=b.at+b.duration&&time<DURATION&&['seal','inscribe','progress','reset','deny','complete'].includes(b.kind)){
  const node=document.createElement('span');node.className='a-semantic';node.textContent=b.label;node.style.left=Math.max(3,Math.min(innerWidth-130,a[b.to].x-55))+'px';node.style.top=Math.min(innerHeight-26,a[b.to].y+a[b.to].h*.4)+'px';resultNodes.push(node);document.body.append(node);
 }
 if(time>=b.at+b.duration&&time<DURATION&&b.kind==='summon'&&b.to!=='source'){
  const inst=card(b.card||DB[cardId]?.evolveTo||'VAMP1','a-result');if(scene.id==='A009')inst.passive=[...(inst.passive||[]),'void'];const node=cardEl(inst);node.classList.add('a-reveal','a-result');const p=a[b.to];node.style.cssText=`left:${p.x-p.w/2}px;top:${p.y-p.h/2}px;width:${p.w}px;height:${p.h}px;--cw:${p.w}px;--ch:${p.h}px`;resultCards.push(node);document.body.append(node);
 }
 }
 renderer.canvas.dataset.time=String(Math.round(time));
}
function info(){return{ready,id:scene.id,cardId,variant,side,branch,time,beats,renderer:renderer.material?'webgl':'reduced-fallback',resourceCount:surfaces.size,sourcePresent:!!document.querySelector(`[data-uid="a-source-${side}"]`),viewport:[innerWidth,innerHeight]};}
const api={load,seek,info,anchors,setSimultaneous(v:boolean){simultaneous=v;seek(time)},get ready(){return ready},setReduced(value:boolean){reduced=value;seek(time)},setDark(value:boolean){document.body.classList.toggle('a-dark',value)},dispose(){if(disposed)return;disposed=true;++generation;clearExtra();renderer.dispose();surfaces.clear();faces.clear();stop();view.destroy();},canvas:renderer.canvas};
(window as any).seriesABoard=api;window.addEventListener('resize',()=>{if(ready){const previous=time;void load(scene.id,cardId,variant,side,branch).then(()=>seek(previous));}});window.addEventListener('pagehide',()=>api.dispose(),{once:true});void load();
