import './style.css';
import {ChosenRenderer} from '../../ui/chosenVictory/renderer';
import {CHOSEN_FLASH_MS} from '../../ui/chosenVictory/timing';
import manifest from './assets/manifest.json';
const urls=[new URL('./assets/01.mp3',import.meta.url),new URL('./assets/02.mp3',import.meta.url),new URL('./assets/03.mp3',import.meta.url),new URL('./assets/04.mp3',import.meta.url),new URL('./assets/05.mp3',import.meta.url),new URL('./assets/06.mp3',import.meta.url),new URL('./assets/07.mp3',import.meta.url)];
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T,cv=$<HTMLCanvasElement>('scene'),c=cv.getContext('2d')!,frame=$<HTMLIFrameElement>('board');
let ctx:AudioContext|undefined,master:GainNode|undefined,renderer:ChosenRenderer,buffers:AudioBuffer[]=[],encoded:ArrayBuffer[]=[],selected=0,raf=0,token=0,playing=false,ready=false,sequence=false,voice:AudioBufferSourceNode|undefined,level:GainNode|undefined,time=3750;
const events:{variant:number;scheduled:number;visualTime:number;mode:string}[]=[];
function board(){return (frame.contentWindow as any)?.chosenSoundBoard;}
function draw(ms:number){time=ms;const r=$('stage').getBoundingClientRect(),d=Math.min(devicePixelRatio,1.5);if(cv.width!==Math.round(r.width*d)||cv.height!==Math.round(r.height*d)){cv.width=Math.round(r.width*d);cv.height=Math.round(r.height*d);c.setTransform(d,0,0,d,0,0);}renderer?.draw(c,r.width,r.height,0,ms,{board:true,dark:true,source:board()?.anchor('me')??undefined,rift:board()?.rift('me')??undefined});}
function stop(){token++;playing=false;sequence=false;cancelAnimationFrame(raf);if(voice&&ctx){level?.gain.setTargetAtTime(0,ctx.currentTime,.005);try{voice.stop(ctx.currentTime+.03)}catch{}}voice=undefined;draw(3750);$('phase').textContent='停止';$('replay').textContent='もう一度再生';$('sequence').textContent='7案を順番に';}
async function audio(){if(!ctx){ctx=new AudioContext();master=ctx.createGain();master.gain.value=(Number($<HTMLInputElement>('volume').value)/100)**2;master.connect(ctx.destination);}await ctx.resume();if(!buffers.length)buffers=await Promise.all(encoded.map(a=>ctx!.decodeAudioData(a.slice(0))));}
function selection(i:number){selected=i;const row=manifest[i];$('title').textContent=row.number+' '+row.title;$('desc').textContent=row.description;document.querySelectorAll('.choice').forEach((el,j)=>el.setAttribute('aria-pressed',String(i===j)));}
async function play(i=selected,mode=$<HTMLSelectElement>('mode').value,chain=false){if(!ready)return;stop();selection(i);const own=token;sequence=chain;await audio();if(own!==token||document.hidden)return;const start=mode==='full'?0:mode==='sound'?CHOSEN_FLASH_MS:1900,end=mode==='full'?7400:mode==='sound'?CHOSEN_FLASH_MS+manifest[i].seconds*1000+500:5100;
 const ac=ctx!,base=ac.currentTime+.055,when=base+(CHOSEN_FLASH_MS-start)/1000;const s=ac.createBufferSource(),g=ac.createGain();s.buffer=buffers[i];s.connect(g).connect(master!);voice=s;level=g;s.onended=()=>{s.disconnect();g.disconnect();if(voice===s)voice=undefined;};s.start(when);events.push({variant:i+1,scheduled:when,visualTime:CHOSEN_FLASH_MS,mode});playing=true;$('replay').textContent='再生し直す';$('status').textContent=`${manifest[i].number} ${manifest[i].character} · ${manifest[i].seconds.toFixed(2)}秒`;if(chain)$('sequence').textContent='順番に再生中';
 const tick=()=>{if(own!==token)return;const ms=Math.max(start,start+(ac.currentTime-base)*1000);if(mode!=='sound')draw(ms);else draw(3750);$('phase').textContent=mode==='sound'?'効果音のみ':ms<CHOSEN_FLASH_MS?'冠の形成':'完成の光 ＋ 効果音';if(ms<end){raf=requestAnimationFrame(tick);}else{playing=false;$('replay').textContent='もう一度再生';if(sequence&&i<6)void play(i+1,mode,true);else{sequence=false;$('sequence').textContent='7案を順番に';draw(3750);$('phase').textContent='再生完了';}}};raf=requestAnimationFrame(tick);
}
manifest.forEach((row,i)=>{const b=document.createElement('button');b.className='choice';b.disabled=true;b.setAttribute('aria-pressed',String(i===0));b.innerHTML=`<small>${row.number}</small><b>${row.title}</b><span>${row.character}</span>`;b.onclick=()=>void play(i);$('choices').append(b);});
$('replay').onclick=()=>void play();$('stop').onclick=stop;$('sequence').onclick=()=>sequence?stop():void play(0,$<HTMLSelectElement>('mode').value,true);$('mode').onchange=stop;$('volume').oninput=()=>{if(ctx&&master)master.gain.setTargetAtTime((Number($<HTMLInputElement>('volume').value)/100)**2,ctx.currentTime,.015);};
document.addEventListener('keydown',e=>{if((e.target as HTMLElement).matches('input,select'))return;if(/^[1-7]$/.test(e.key))void play(Number(e.key)-1);if(e.key==='Escape')stop();});document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});window.addEventListener('pagehide',()=>{stop();renderer?.destroy();void ctx?.close();},{once:true});new ResizeObserver(()=>{if(!playing)draw(time)}).observe($('stage'));
try{const im=new Image();im.src='/vfx/chosen-victory/crown.png';await im.decode();renderer=new ChosenRenderer([im]);encoded=await Promise.all(urls.map(async url=>{const r=await fetch(url);if(!r.ok)throw Error('Audio unavailable');return r.arrayBuffer()}));await new Promise<void>((resolve,reject)=>{const until=performance.now()+15000;const check=()=>{if(board()?.ready)resolve();else if(performance.now()>until)reject(Error('Board not ready'));else requestAnimationFrame(check)};check()});ready=true;selection(0);draw(3750);document.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.disabled=false);$('replay').textContent='実盤面で再生';$('status').textContent='番号を押して比較できます。音量は7案で揃えています。';$('phase').textContent='01 虚空の戴冠';}catch(e){$('status').textContent='読み込みに失敗しました。ページを再読み込みしてください。';console.error(e);}
(window as any).chosenSoundSeven={get ready(){return ready},play,stop,get selected(){return selected},get playing(){return playing},get events(){return events},get time(){return time}};
