import '../../styles/tokens.css';import '../../styles/base.css';import '../../styles/card.css';import '../../styles/game-overlays.css';import '../../styles/game.css';import '../../styles/screens.css';import '../../styles/reading-board.css';import '../../styles/presentation.css';
import {GameView,setMyAvatar,setOppAvatar} from '../../ui/boardView';import {startBoardLayout} from '../../ui/layout';import {waitForDuel} from '../../ui/duelReadiness';import {clearMonsterStates} from '../../ui/monster/runtime';import {createGame} from '../../shared/engine';import {DB} from '../../shared/cards';import {setLang} from '../../i18n';
import {studies} from './catalog';import {Renderer,loadAssets} from './renderer';
setLang('ja');setMyAvatar('SEEKER_BLUE');setOppAvatar('SEEKER_RED');
const css=document.createElement('style');css.textContent='body{margin:0;overflow:hidden;background:#f2eee8}.topbar,.help-callout,.help-fab,.mute-fab{display:none!important}.sb-anchor{position:absolute;left:77%;top:61%;width:32%;height:34%;pointer-events:none}';document.head.append(css);
const root=document.getElementById('app')!,noop=()=>{};
const view=new GameView(root,0,{onPlay:noop,onBlockedPlay:noop,onAttack:noop,onBlockedAttack:noop,onReorder:noop,onChooseTarget:noop,onBuyMarket:noop,onBuySupply:noop,onRefresh:noop,onEndTurn:noop,onSurrender:noop});
const g=createGame({mode:'bot',seed:73,starting:0,p0:{id:'preview-me',name:'YOU'},p1:{id:'preview-opp',name:'OPPONENT'}}).state;
g.turn=3;g.phase='main';g.pending=null;for(const [i,p] of g.players.entries()){p.openingDrawReady=false;p.hp=30;p.shield=8;p.dew=0;p.brand=0;p.mana=8;p.maxMana=8;p.enchants=[];p.quests=[];p.traps=[];p.field=['M4','ELF','TDE2'].map((id,j)=>({...DB[id],uid:`sb-${i}-${j}`,exhausted:false,summonedTurn:0,dmg:0,tempAtk:0,atkMod:0,defMod:0}));p.hand=[{...DB.DEFENSIVE_STANCE,uid:`sb-hand-${i}`}];}
view.render(g);view.setHandOpen(false);clearMonsterStates(root);
const canvas=document.createElement('canvas');canvas.style.cssText='position:fixed;inset:0;width:100%;height:100%;pointer-events:none;z-index:180';document.body.append(canvas);
const anchors=[...root.querySelectorAll<HTMLElement>('.portrait')].map(p=>{const a=document.createElement('span');a.className='sb-anchor';p.append(a);return a;});
let renderer:Renderer,ready=false,disposed=false,active=false,id='SF1',ms=0,side=0,multi=false,reduced=false,dark=false;
const shields=[...root.querySelectorAll<HTMLElement>('.pt-shield')];
function restore(){shields.forEach(e=>e.style.visibility='');canvas.getContext('2d')!.clearRect(0,0,canvas.width,canvas.height);}
function draw(){restore();if(!ready||!active||disposed||document.hidden)return;const dpr=Math.min(2,devicePixelRatio||1);if(canvas.width!==Math.round(innerWidth*dpr)||canvas.height!==Math.round(innerHeight*dpr)){canvas.width=Math.round(innerWidth*dpr);canvas.height=Math.round(innerHeight*dpr);}const c=canvas.getContext('2d')!;c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,innerWidth,innerHeight);root.style.filter=dark?'brightness(.62)':'';const s=studies.find(x=>x.id===id)!;
 for(const index of multi?[0,1]:[side]){const portrait=document.getElementById(index?'portraitOpp':'portraitMe')!;const anchor=s.family==='shield'?portrait.querySelector<HTMLElement>('.pt-shield')!:portrait.querySelector<HTMLElement>('.sb-anchor')!;const r=s.family==='shield'?anchor.getBoundingClientRect():portrait.querySelector('.pt-ring')!.getBoundingClientRect();if(s.family==='shield')anchor.style.visibility='hidden';const size=s.family==='shield'?Math.max(r.width,r.height):r.width*.32,x=s.family==='shield'?r.x+r.width/2:r.x+r.width*.93,y=s.family==='shield'?r.y+r.height/2:r.y+r.height*.78;renderer.effect(c,s,ms,x,y,size,reduced);renderer.count(c,s,ms,x,y,size);const source=document.querySelector<HTMLElement>(`[data-uid="sb-${index}-1"]`);if(source&&!reduced){const a=source.getBoundingClientRect();renderer.transfer(c,s,ms,{x:a.x+a.width/2,y:a.y+a.height/2},{x,y},size/139);}}
}
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent)return;if(e.data?.kind==='shield-brand-dispose'){dispose();return;}if(e.data?.kind!=='shield-brand-control'||disposed)return;const d=e.data;if(studies.some(x=>x.id===d.id))id=d.id;ms=Math.max(0,Math.min(studies.find(x=>x.id===id)!.duration,Number(d.ms)||0));side=d.side===1?1:0;multi=!!d.multi;reduced=!!d.reduced;dark=!!d.dark;active=!!d.active;draw();});
window.addEventListener('resize',()=>requestAnimationFrame(draw));document.addEventListener('visibilitychange',draw);
const stop=startBoardLayout();function dispose(){if(disposed)return;disposed=true;restore();renderer?.dispose();canvas.remove();anchors.forEach(a=>a.remove());stop();view.destroy();}window.addEventListener('pagehide',dispose,{once:true});
(window as any).shieldBrandBoard={get state(){return{ready,disposed,active,id,ms,side,multi,hidden:shields.filter(x=>x.style.visibility==='hidden').length,canvases:document.querySelectorAll('body>canvas').length}},restore};
void(async()=>{renderer=new Renderer(await loadAssets());await waitForDuel(root);ready=true;parent.postMessage({kind:'shield-brand-ready'},location.origin);draw();})().catch(e=>parent.postMessage({kind:'shield-brand-error',error:String(e)},location.origin));
