import {currentId,ids,cardInfo} from './catalog';
import './style.css';import {patterns,DURATION} from './rig';
const q=new URLSearchParams(location.search);let variant=Math.max(1,Math.min(3,Number(q.get('variant')||1)));const app=document.getElementById('app')!;
app.innerHTML=`<header><small>LORE / MIMIC FAMILY · 5種 × 3案</small><h1>${cardInfo(currentId).name} / 3つの召喚演出</h1><p>コスト${cardInfo(currentId).cost} · ${cardInfo(currentId).text}</p></header><div class="family-nav">${ids.map(id=>`<a class="${id===currentId?'selected':''}" href="?card=${id}&mode=compare"><img src="/art/cards/${id}.webp"><span>${cardInfo(id).name}<small>コスト${cardInfo(id).cost} / 3案</small></span></a>`).join('')}</div><nav aria-label="3つの演出案">${patterns.map((p,i)=>`<button data-variant="${i+1}"><span>0${i+1}</span><strong>${p.name}</strong><small>${p.description}</small></button>`).join('')}</nav><section class="work"><div class="controls"><button id="play" disabled>再生</button><button id="pause">停止</button><button id="reset">最初へ</button><select id="mode" aria-label="表示"><option value="summon">召喚時の提示 → 着地</option><option value="board">実盤面の位置で確認</option><option value="compare">新3案を並べて比較</option><option value="reference">確定マスターと比較</option></select><select id="side" aria-label="陣営"><option value="0">自分側</option><option value="1">相手側</option></select><select id="speed" aria-label="再生速度"><option value="1">1倍</option><option value="0.5">0.5倍</option><option value="0.25">0.25倍</option></select><label><input id="loop" type="checkbox">反復</label><label><input id="reduced" type="checkbox">動きを減らす</label><label><input id="dark" type="checkbox">暗い盤面</label></div><div class="screen"><iframe title="ミミックの実盤面プレビュー"></iframe><div id="loading">カードを準備しています…</div></div><div class="timeline"><span id="phase">準備中</span><input id="seek" aria-label="時刻" type="range" min="0" max="${DURATION}" value="0"><output id="clock">0.00 s</output></div></section><footer>全5種類・15案をこのページで切替。通常ミミック・マスターは確定済み。追加案は確認用・未デプロイ。 <a href="/master-mimic.html?mode=compare">確定版を見る</a></footer>`;
const el=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id)as T;const frame=document.querySelector('iframe')!;
const send=(command:string,extra:Record<string,unknown>={})=>frame.contentWindow?.postMessage({kind:'mimic-control',command,...extra},location.origin);
function options(){send('options',{speed:+el<HTMLSelectElement>('speed').value,loop:el<HTMLInputElement>('loop').checked,reduced:el<HTMLInputElement>('reduced').checked});send('background',{dark:el<HTMLInputElement>('dark').checked});}
function load(){el<HTMLButtonElement>('play').disabled=true;el('loading').hidden=false;el('loading').textContent='カードを準備しています…';const url=new URL(location.href);url.searchParams.set('variant',String(variant));url.searchParams.set('mode',el<HTMLSelectElement>('mode').value);url.searchParams.set('side',el<HTMLSelectElement>('side').value);history.replaceState(null,'',url);url.searchParams.set('stage','1');frame.src=url.href;document.querySelectorAll<HTMLButtonElement>('[data-variant]').forEach(b=>{b.classList.toggle('active',Number(b.dataset.variant)===variant);b.setAttribute('aria-pressed',String(Number(b.dataset.variant)===variant));});el<HTMLInputElement>('seek').value='0';}
for(const b of document.querySelectorAll<HTMLButtonElement>('[data-variant]'))b.onclick=()=>{variant=+b.dataset.variant!;if(el<HTMLSelectElement>('mode').value==='compare')el<HTMLSelectElement>('mode').value='summon';load();};
for(const id of ['mode','side'])el(id).onchange=load;for(const id of ['speed','loop','reduced','dark'])el(id).onchange=options;
for(const id of ['play','pause','reset'])el(id).onclick=()=>send(id);el<HTMLInputElement>('seek').oninput=()=>send('seek',{time:+el<HTMLInputElement>('seek').value});
let loaded=false;frame.addEventListener('load',()=>{loaded=false;});window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==frame.contentWindow||e.data?.kind!=='mimic-four')return;const d=e.data;if(d.error){el('loading').textContent=d.error;return;}if(d.ready){el('loading').hidden=true;el<HTMLButtonElement>('play').disabled=false;if(!loaded){loaded=true;options();}}el<HTMLInputElement>('seek').value=String(d.time);el('clock').textContent=(d.time/1000).toFixed(2)+' s';el('phase').textContent=d.time<470?'提示':d.time<DURATION*.27?'予兆':d.time<DURATION*.4?'変化':d.time<DURATION*.6?'見せ場':d.time<DURATION*.79?'収束':d.time<DURATION*.97?'カードへ戻る':'完了';});
if(['board','compare','reference'].includes(q.get('mode')||''))el<HTMLSelectElement>('mode').value=q.get('mode')!;el<HTMLSelectElement>('side').value=q.get('side')==='1'?'1':'0';load();
