import '../../../styles/tokens.css';import '../../../styles/base.css';import '../../../styles/card.css';import '../../../styles/game-overlays.css';import '../../../styles/game.css';import '../../../styles/screens.css';import '../../../styles/reading-board.css';import '../../../styles/presentation.css';
import {GameView,setMyAvatar,setOppAvatar} from '../../../ui/boardView';import {cardEl,backEl} from '../../../ui/cardView';import {startBoardLayout} from '../../../ui/layout';import {waitForDuel} from '../../../ui/duelReadiness';import {fieldPlacement,setFxSkip,attackStrike} from '../../../ui/anim';import {setLang} from '../../../i18n';
import {clearMonsterStates} from '../../../ui/monster/runtime';
import {makeFixture,type Fixture} from './fixture';import {available,type Config} from './catalog';import {paint,Surface,ease} from './material';import {nativeExit,exileCard,freezeMaterial} from './endpoints';
setLang('ja');setMyAvatar('SEEKER_BLUE');setOppAvatar('SEEKER_RED');const css=document.createElement('style');css.textContent='body{overflow:hidden}.topbar,.help-callout,.help-fab,.mute-fab{display:none!important}[data-a3-float],[data-a3-generated]{transition:none!important;animation:none!important}';document.head.append(css);
const noop=()=>{};const view=new GameView(document.querySelector('#app')!,0,{onPlay:noop,onBlockedPlay:noop,onAttack:noop,onBlockedAttack:noop,onReorder:noop,onChooseTarget:noop,onBuyMarket:noop,onBuySupply:noop,onRefresh:noop,onEndTurn:noop,onSurrender:noop});const stop=startBoardLayout();
let cfg:Config={item:'S05',card:'BLACK_CURSE',variant:1,side:0,outcome:'hit',reduced:false},fixture:Fixture;let ready=false,playing=false,time=0,raf=0,epoch=0,last=0,error='',native:Promise<void>|null=null,finalized=false,duration=3300,nativeDone=false;
let floating:HTMLElement|null=null,surface:Surface|null=null,sourceSurface:Surface|null=null,art:HTMLImageElement|null=null,origin:DOMRect;const texture=document.createElement('canvas');const hidden=new Map<HTMLElement,string>();const generated:{node:HTMLElement;side:0|1;uid:string;dest:'shelf'|'field'|'hand'}[]=[];let targetLayers:{node:HTMLElement;surface:Surface;art:HTMLImageElement;id:string}[]=[];const endpointTrace:{step:string;ms:number}[]=[];
const byUid=(uid:string)=>view.root.querySelector<HTMLElement>(`[data-uid="${CSS.escape(uid)}"]`);
const post=()=>parent.postMessage({kind:'a3-status',ready,playing,time,duration,error,native:!!native,phase:time<600?'提示':time<1550?'素材の展開':time<2450?'効果の確定':time<3300?'到着・収束':'完了',events:fixture?.events,seed:fixture?.seed},location.origin);
function conceal(n:HTMLElement|null){if(n&&!hidden.has(n)){hidden.set(n,n.style.visibility);n.style.visibility='hidden';}}
function restore(){for(const[n,v]of hidden)n.style.visibility=v;hidden.clear();}
function cleanup(){sourceSurface?.dispose();sourceSurface=null;for(const t of targetLayers)t.surface.dispose();targetLayers=[];restore();surface?.dispose();surface=null;floating?.remove();floating=null;for(const a of generated)a.node.remove();generated.length=0;}
function render(final=false){restore();view.render(final?fixture.after:fixture.before);clearMonsterStates(view.root);view.setHandOpen(false);finalized=final;}
function rebindMaterials(){sourceSurface?.dispose();sourceSurface=null;const source=byUid(fixture.source.uid);if(fixture.zone==='field'&&source?.querySelector('.card-art img'))sourceSurface=new Surface(source);for(const t of targetLayers){t.surface.dispose();const node=byUid(t.node.dataset.uid||'');if(node?.querySelector('.card-art img')){t.node=node;t.surface=new Surface(node);}}}
function intermediate(){const g=structuredClone(fixture.before);for(const side of [0,1]as const){for(const c of fixture.after.players[side].field)if(!g.players[side].field.some(x=>x.uid===c.uid))g.players[side].field.push(c);for(const e of fixture.after.players[side].enchants)if(!g.players[side].enchants.some(x=>x.card.uid===e.card.uid))g.players[side].enchants.push(e);for(const c of fixture.after.players[side].hand)if(!g.players[side].hand.some(x=>x.uid===c.uid))g.players[side].hand.push(c);}restore();view.render(g);clearMonsterStates(view.root);view.setHandOpen(false);for(const e of fixture.events)if(e.type==='summon')conceal(byUid(e.uid));for(const side of [0,1]as const)for(const e of fixture.after.players[side].enchants)if(!fixture.before.players[side].enchants.some(x=>x.card.uid===e.card.uid))conceal(byUid(e.card.uid));for(const side of [0,1]as const)for(const c of fixture.after.players[side].hand)if(!fixture.before.players[side].hand.some(x=>x.uid===c.uid))conceal(byUid(c.uid));rebindMaterials();}
async function setup(next:Partial<Config>={}){
 const token=++epoch;playing=false;ready=false;error='';cancelAnimationFrame(raf);if(native){setFxSkip(true);await native.catch(()=>{});native=null;setFxSkip(false);}cleanup();cfg={...cfg,...next};time=0;duration=3300;nativeDone=false;endpointTrace.length=0;if(!available(cfg.item,cfg.card))throw Error('未制作の項目は再生できません');fixture=makeFixture(cfg);if(!fixture.accepted||fixture.after.pending)throw Error('このfixtureはまだ結果まで接続できていません');render();await waitForDuel(view.root);await new Promise<void>(r=>requestAnimationFrame(()=>r()));
 if(token!==epoch)return;origin=(fixture.zone==='market'?document.querySelector('#market [data-market-idx="0"]'):byUid(fixture.source.uid))?.getBoundingClientRect()||new DOMRect(innerWidth*.46,innerHeight*.78,90,126);intermediate();
 floating=cardEl(fixture.source,{size:'hand',fullArt:true});floating.dataset.a3Float='1';floating.style.cssText='position:fixed;left:0;top:0;width:180px;height:280px;--cw:180px;--ch:280px;transform-origin:0 0;pointer-events:none;z-index:180;visibility:hidden';document.body.append(floating);surface=new Surface(floating);art=new Image();art.src=`/art/cards/${cfg.card}.webp`;
 for(const side of [0,1]as const){const old=new Set(fixture.before.players[side].discard.map(c=>c.uid));for(const c of fixture.after.players[side].discard.filter(c=>!old.has(c.uid)&&c.uid!==fixture.source.uid&&!fixture.before.players[side].field.some(x=>x.uid===c.uid)&&!fixture.before.players[side].enchants.some(x=>x.card.uid===c.uid))){const node=cardEl(c,{size:'hand',fullArt:true});node.dataset.a3Generated='1';node.style.cssText='position:fixed;left:0;top:0;width:120px;height:184px;--cw:120px;--ch:184px;transform-origin:0 0;pointer-events:none;z-index:179;visibility:hidden';document.body.append(node);generated.push({node,side,uid:c.uid,dest:'shelf'});}}
 for(const side of [0,1]as const)for(const c of fixture.after.players[side].field){if(c.uid===fixture.source.uid||fixture.before.players[side].field.some(x=>x.uid===c.uid))continue;const node=cardEl(c,{field:true,fullArt:true});node.dataset.a3Generated='1';node.style.cssText='position:fixed;left:0;top:0;width:120px;height:184px;--cw:120px;--ch:184px;transform-origin:0 0;pointer-events:none;z-index:181;visibility:hidden';document.body.append(node);generated.push({node,side,uid:c.uid,dest:'field'});}
 for(const side of [0,1]as const)for(const c of fixture.after.players[side].hand){if(fixture.before.players[side].hand.some(x=>x.uid===c.uid))continue;const node=side===0?cardEl(c,{size:'hand',fullArt:true}):backEl(120,184);node.dataset.a3Generated='1';node.style.cssText='position:fixed;left:0;top:0;width:120px;height:184px;--cw:120px;--ch:184px;transform-origin:0 0;pointer-events:none;z-index:181;visibility:hidden';document.body.append(node);generated.push({node,side,uid:c.uid,dest:'hand'});}
 for(const e of fixture.events)if(e.type==='destroy'){const node=byUid(e.uid),c=fixture.before.players[e.player].field.find(c=>c.uid===e.uid);if(node&&c){const image=new Image();image.src=`/art/cards/${c.id}.webp`;await image.decode();targetLayers.push({node,surface:new Surface(node),art:image,id:c.id});}}
 await Promise.all([art.decode(),...Array.from(floating.querySelectorAll('img')).map(i=>i.decode()),...generated.flatMap(a=>Array.from(a.node.querySelectorAll('img')).map(i=>i.decode()))]);await new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r())));if(token!==epoch)return;if(fixture.zone==='field'){sourceSurface?.dispose();const n=byUid(fixture.source.uid);if(n?.querySelector('.card-art img'))sourceSurface=new Surface(n);}ready=true;draw();post();
}
function safePlacement(node:HTMLElement,w:number,h:number){const m=fieldPlacement(node,w,h);if(Array.from(m.toFloat64Array()).every(Number.isFinite))return m;const r=node.getBoundingClientRect();return new DOMMatrix().translate(r.x,r.y).scale(Math.max(.01,r.width/w),Math.max(.01,r.height/h));}
function mix(a:DOMMatrix,b:DOMMatrix,q:number){const aa=a.toFloat64Array(),bb=b.toFloat64Array();return new DOMMatrix(Array.from(aa,(n,i)=>n+(bb[i]-n)*q));}
function destNode(){const uid=fixture.source.uid;const persisted=fixture.after.players[cfg.side].field.some(c=>c.uid===uid)||fixture.after.players[cfg.side].enchants.some(e=>e.card.uid===uid);return persisted?byUid(uid):document.querySelector<HTMLElement>(`#pile-${cfg.side===0?'my':'opp'}Disc .pile-print .card`);}
function draw(){if(!ready||!floating||!surface||!art)return;if(time>=duration&&!native){if(!finalized)render(true);floating.style.visibility='hidden';for(const a of generated)a.node.style.visibility='hidden';post();return;}if(finalized){finalized=false;intermediate();}
 const w=floating.offsetWidth,h=floating.offsetHeight,scale=Math.min(1.22,innerWidth*.46/w,innerHeight*.63/h);const middle=new DOMMatrix().translate((innerWidth-w*scale)/2,(innerHeight-h*scale)/2).scale(scale);const from=new DOMMatrix().translate(origin.x,origin.y).scale(origin.width/w,origin.height/h);const target=destNode();const stay=fixture.zone==='field';const exiles=fixture.after.players[cfg.side].removed?.some(c=>c.uid===fixture.source.uid||(fixture.source.quick&&c.id===cfg.card));const to=stay?new DOMMatrix().translate(origin.x,origin.y).scale(origin.width/w,origin.height/h):!exiles&&target?safePlacement(target,w,h):middle;
 const blocked=fixture.events.every(e=>!['playSpell','summon','buy'].includes(e.type))&&['A022','A163','A161'].includes(cfg.item);let matrix=time<600?mix(from,middle,ease(0,600,time)):mix(middle,to,ease(2560,3300,time));if(cfg.reduced)matrix=from;if(blocked){const a=Math.sin(Math.min(1,time/600)*Math.PI)*Math.exp(-time/250);matrix=new DOMMatrix().translate(cfg.variant===1?Math.sin(time/35)*8*a:0,0).multiply(from);if(cfg.variant===2)matrix=matrix.rotate(0,0,3*a);}floating.style.transform=matrix.toString();floating.style.visibility=time>0&&time<3300?'visible':'hidden';if(time>0&&fixture.zone!=='field')for(const n of view.root.querySelectorAll<HTMLElement>(`[data-uid="${CSS.escape(fixture.source.uid)}"]`))conceal(n);
 paint(texture,art,cfg.card,cfg.variant,blocked?0:time,cfg.reduced,cfg.item);surface.draw(texture);if(sourceSurface){sourceSurface.draw(texture);floating.style.visibility='hidden';}
 for(const a of targetLayers){paint(texture,a.art,a.id,cfg.variant,Math.min(1550,Math.max(0,time-700)),cfg.reduced,cfg.item);a.surface.draw(texture);}
 for(const[aIndex,a]of generated.entries()){const deferred=deferredArrivals(),clock=deferred?time-3300:time,at=(deferred?0:1750)+aIndex*70,end=(deferred?900:2920)+aIndex*35,q=cfg.reduced?(clock>=at?1:0):ease(at,end,clock),n=a.dest==='field'||a.dest==='hand'?byUid(a.uid)||document.querySelector<HTMLElement>('#oppHand .card'):document.querySelector<HTMLElement>(`#pile-${a.side===0?'my':'opp'}Disc .pile-print .card`);a.node.style.visibility=(!deferred||nativeDone)&&clock>=at&&time<duration?'visible':'hidden';if(n){const deck=document.querySelector<HTMLElement>(`#pile-${a.side===0?'my':'opp'}Deck`);const dr=deck?.getBoundingClientRect();const start=a.dest==='hand'&&dr?new DOMMatrix().translate(dr.x,dr.y).scale(.4):new DOMMatrix().translate(innerWidth*.5+Math.sin(aIndex*2)*12,innerHeight*.52).scale(.28);const arrival=safePlacement(n,a.node.offsetWidth,a.node.offsetHeight);const base=mix(start,arrival,q);a.node.style.transform=new DOMMatrix().translate(0,cfg.reduced?0:-Math.sin(q*Math.PI)*(cfg.variant===1?38:62)).multiply(base).toString();}}
 post();}
function needRift(){return fixture.after.players[cfg.side].removed?.some(c=>c.uid===fixture.source.uid||(fixture.source.quick&&c.id===cfg.card));}
function deferredArrivals(){return generated.length>0&&fixture.events.some(e=>e.type==='attack'||e.type==='destroy');}
function hasEndpoints(){return fixture.before.players.some((p,i)=>[...p.enchants.map(e=>e.card),...(p.quests||[]).map(q=>q.card)].some(c=>c.uid!==fixture.source.uid&&!fixture.after.players[i].enchants.some(e=>e.card.uid===c.uid)&&!fixture.after.players[i].quests?.some(q=>q.card.uid===c.uid)))||needRift()||fixture.events.some(e=>e.type==='destroy'||e.type==='attack')||fixture.after.players.some((p,i)=>p.removed?.some(c=>!fixture.before.players[i].removed?.some(x=>x.uid===c.uid)));}
async function runEndpoints(){
 for(const side of [0,1]as const)for(const c of [...fixture.before.players[side].enchants.map(e=>e.card),...(fixture.before.players[side].quests||[]).map(q=>q.card)]){const after=fixture.after.players[side];if(c.uid===fixture.source.uid||after.enchants.some(e=>e.card.uid===c.uid)||after.quests?.some(q=>q.card.uid===c.uid)||after.removed?.some(x=>x.uid===c.uid))continue;const node=byUid(c.uid);if(node){endpointTrace.push({step:'tile exit start '+c.uid,ms:performance.now()});await nativeExit(node,side,'destroy',c.uid);endpointTrace.push({step:'tile exit complete '+c.uid,ms:performance.now()});}}
 for(const e of fixture.events){if(e.type!=='attack')continue;const n=byUid(e.uid);if(!n)continue;const restore=await freezeMaterial(n);endpointTrace.push({step:'attack start '+e.uid,ms:performance.now()});try{await attackStrike(e.uid,e.targetUid,e.player===0?'opp':'me');}finally{restore();}endpointTrace.push({step:'attack complete '+e.uid,ms:performance.now()});}
 for(const e of fixture.events){if(e.type!=='destroy')continue;const node=byUid(e.uid);if(!node)continue;const voided=fixture.after.players[e.player].removed?.some(c=>c.uid===e.uid)||false;endpointTrace.push({step:'destroy start '+e.uid,ms:performance.now()});await nativeExit(node,e.player,'destroy',e.uid,voided);endpointTrace.push({step:'destroy complete '+e.uid,ms:performance.now()});}
 for(const side of [0,1]as const)for(const c of fixture.after.players[side].removed||[]){if(fixture.before.players[side].removed?.some(x=>x.uid===c.uid)||fixture.events.some(e=>e.type==='destroy'&&e.uid===c.uid))continue;
 const source=c.uid===fixture.source.uid||(fixture.source.quick&&c.id===cfg.card);endpointTrace.push({step:'rift start '+c.id,ms:performance.now()});if(source)await nativeExit(floating!,side,'rift');else await exileCard(c,side===0?'me':'opp',byUid(c.uid));endpointTrace.push({step:'rift complete '+c.id,ms:performance.now()});}
}
async function exit(){const token=epoch;playing=false;time=2790;draw();if(cfg.reduced)setFxSkip(true);native=runEndpoints();post();try{await native;if(token!==epoch)return;nativeDone=true;}catch(e){error=String(e);}finally{native=null;if(cfg.reduced)setFxSkip(false);if(token===epoch){time=3300;if(nativeDone&&deferredArrivals()){duration=4500+generated.length*70;endpointTrace.push({step:'followup start after native completion',ms:performance.now()});playing=true;last=performance.now();raf=requestAnimationFrame(tick);}draw();post();}}}

function tick(now:number){if(!playing)return;time+=Math.min(80,now-last);last=now;if(['A022','A163','A161'].includes(cfg.item)&&fixture.events.every(e=>!['playSpell','summon','buy'].includes(e.type))&&time>=600){time=3300;playing=false;draw();return;}if(!nativeDone&&hasEndpoints()&&time>=2790){void exit();return;}if(time>=duration){time=duration;playing=false;}draw();if(playing)raf=requestAnimationFrame(tick);}
async function play(){if(!ready||native||playing)return;if(time>=duration)await setup();playing=true;last=performance.now();raf=requestAnimationFrame(tick);}
function seek(ms:number){if(!ready||native)return;playing=false;cancelAnimationFrame(raf);time=Math.max(0,Math.min(duration,ms));if(time<2790)nativeDone=false;draw();}
function dispose(){++epoch;playing=false;cancelAnimationFrame(raf);setFxSkip(true);cleanup();stop();view.destroy();}
window.addEventListener('pagehide',dispose,{once:true});document.addEventListener('visibilitychange',()=>{if(document.hidden){playing=false;cancelAnimationFrame(raf);}});
(window as any).aR3={setup,play,seek,pause:async()=>{if(native){await setup(cfg);return;}playing=false;cancelAnimationFrame(raf);},get state(){return{ready,playing,time,duration,nativeDone,cfg,error,native:!!native,generated:generated.length,finalized};},get fixture(){return fixture;},get endpointTrace(){return endpointTrace;},dispose};
parent.postMessage({kind:'a3-boot'},location.origin);
