import '../../styles/tokens.css';import '../../styles/base.css';import '../../styles/card.css';import '../../styles/game-overlays.css';import '../../styles/game.css';import '../../styles/screens.css';import '../../styles/reading-board.css';import '../../styles/presentation.css';
import {BaseController} from '../../game/controller';import {createGame,reduce} from '../../shared/engine';import {DB} from '../../shared/cards';import type {Action,Side,FieldMon} from '../../shared/types';import {startBoardLayout} from '../../ui/layout';import {waitForDuel} from '../../ui/duelReadiness';import {setLang} from '../../i18n';import {setFxSkip} from '../../ui/anim';import {setMyAvatar,setOppAvatar} from '../../ui/boardView';
setLang('ja');setMyAvatar('SEEKER_BLUE');setOppAvatar('SEEKER_RED');const css=document.createElement('style');css.textContent='body{margin:0;overflow:hidden}.topbar,.help-fab,.mute-fab{display:none!important}';document.head.append(css);
const mon=(id:string,uid:string):FieldMon=>({...DB[id],uid,dmg:0,token:true,exhausted:false,summonedTurn:0,tempAtk:0,atkMod:0,defMod:0}) as FieldMon;
class Harness extends BaseController{
 protected submit(_action:Action){}
 async reset(side:Side){setFxSkip(false);const g=createGame({mode:'bot',seed:71,starting:(1-side) as Side,p0:{id:'obsidian-me',name:'YOU'},p1:{id:'obsidian-opp',name:'OPPONENT'}}).state;g.turn=4;g.cur=(1-side) as Side;g.pending=null;g.opening=undefined;g.phase='main';for(const [i,p]of g.players.entries()){p.openingDrawReady=false;p.mana=12;p.maxMana=12;p.hp=30;p.field=['M4','ELF','TDE2'].map((id,j)=>mon(id,`obsidian-${i}-${j}`));p.enchants=[];p.quests=[];p.traps=[];p.hand=[];p.discard=[];p.removed=[];}this.state=g;this.view.render(g);this.view.setHandOpen(false);await waitForDuel(document.querySelector('#app')!);}
 async play(side:Side){await this.reset(side);this.state.pending={kind:'oppMon',hint:'',hintJa:'',reason:'destroyMon',allowCancel:false,data:{val:1}};const result=reduce(this.state,{type:'pick',uid:`obsidian-${side}-1`});this.applyResult(result);await (this as unknown as {queue:Promise<void>}).queue;return {events:result.events.filter(e=>e.type==='destroy'),field:this.state.players[side].field.map(c=>c.uid),removed:this.state.players[side].removed?.map(c=>c.uid),hp:this.state.players[side].hp};}
}
const controller=new Harness(document.querySelector('#app')!,0,{onHome(){},onRematch(){}});const stop=startBoardLayout();
(window as any).obsidianQA={controller,ready:false,play:(side:Side)=>controller.play(side),reset:(side:Side)=>controller.reset(side),skip:()=>setFxSkip(true),dispose:()=>{controller.destroy();stop();}};
const bar=document.createElement('div');bar.style.cssText='position:fixed;bottom:12px;left:12px;z-index:200;background:#14231f;padding:12px;display:flex;gap:12px';bar.innerHTML='<button id="self">自分側・虚無破壊</button><button id="opp">相手側・虚無破壊</button><button id="skip">スキップ</button>';document.body.append(bar);bar.querySelector<HTMLButtonElement>('#self')!.onclick=()=>void controller.play(0);bar.querySelector<HTMLButtonElement>('#opp')!.onclick=()=>void controller.play(1);bar.querySelector<HTMLButtonElement>('#skip')!.onclick=()=>setFxSkip(true);
await controller.reset(0);(window as any).obsidianQA.ready=true;window.addEventListener('pagehide',()=>{controller.destroy();stop();},{once:true});
