import '../../styles/tokens.css';import '../../styles/base.css';import '../../styles/card.css';import '../../styles/game-overlays.css';import '../../styles/game.css';import '../../styles/screens.css';import '../../styles/reading-board.css';import '../../styles/presentation.css';
import {GameView,setMyAvatar,setOppAvatar} from '../../ui/boardView';import {startBoardLayout} from '../../ui/layout';import {waitForDuel} from '../../ui/duelReadiness';import {projectedPlacement} from '../../ui/boardProjection';import {clearMonsterStates} from '../../ui/monster/runtime';import {createGame} from '../../shared/engine';import {DB} from '../../shared/cards';import {setLang} from '../../i18n';import {surface} from './surface';import {Renderer} from './renderer';import {DURATION} from './catalog';
setLang('ja');setMyAvatar('SEEKER_BLUE');setOppAvatar('SEEKER_RED');document.body.style.cssText='margin:0;overflow:hidden;background:#f2eee8';const css=document.createElement('style');css.textContent='.topbar,.help-callout,.help-fab,.mute-fab{display:none!important}';document.head.append(css);
const root=document.getElementById('app')!,noop=()=>{};const view=new GameView(root,0,{onPlay:()=>play(),onBlockedPlay:()=>play(),onAttack:noop,onBlockedAttack:noop,onReorder:noop,onChooseTarget:noop,onBuyMarket:noop,onBuySupply:noop,onRefresh:noop,onEndTurn:noop,onSurrender:noop});const renderer=new Renderer(),faces=new Map<string,HTMLCanvasElement>();
let side=0,variant=0,card='GAMBLER',multi=false,reduced=matchMedia('(prefers-reduced-motion:reduce)').matches,dark=false,ready=false,disposed=false,raf=0,clock=0,last=0,speed=1,running=false;let targets:HTMLElement[]=[],hands:HTMLElement[]=[];const rigs:Array<{el:HTMLElement;canvas:HTMLCanvasElement}>=[];let starts:DOMMatrix[]=[],ends:DOMMatrix[]=[];
for(let i=0;i<3;i++){const el=document.createElement('div');el.style.cssText='position:fixed;left:0;top:0;width:180px;height:270px;transform-origin:0 0;pointer-events:none;z-index:190;visibility:hidden';const canvas=document.createElement('canvas');canvas.style.cssText='position:absolute;left:-180px;top:-69.23px;width:540px;height:408.46px';el.append(canvas);document.body.append(el);rigs.push({el,canvas})}
const mon=(id:string,uid:string)=>({...DB[id],uid,exhausted:false,summonedTurn:0,dmg:0,tempAtk:0,atkMod:0,defMod:0});
function restore(){targets.forEach(n=>n.style.visibility='');hands.forEach(n=>n.style.visibility='');rigs.forEach(r=>r.el.style.visibility='hidden')}
function cancel(){running=false;cancelAnimationFrame(raf);restore();targets.forEach(n=>n.style.visibility='hidden');clock=0}
function setup(){cancel();const g=createGame({mode:'bot',seed:83,starting:0,p0:{id:'study-self',name:'YOU'},p1:{id:'study-opp',name:'OPPONENT'}}).state;g.turn=3;g.phase='main';g.pending=null;for(const [i,p]of g.players.entries()){p.openingDrawReady=false;p.mana=20;p.maxMana=20;p.hp=40;p.enchants=[];p.quests=[];p.traps=[];p.field=['M4',card,card,card,'TDE2'].map((id,j)=>mon(id,`gam-${i}-${j}`));p.hand=Array.from({length:3},(_,j)=>({...DB[card],uid:`gam-hand-${i}-${j}`}))}view.render(g);view.setHandOpen(true);clearMonsterStates(root);targets=Array.from(root.querySelectorAll<HTMLElement>(`.zone-mon [data-uid^="gam-${side}-"]`)).filter(n=>['1','2','3'].includes(n.dataset.uid!.slice(-1)));hands=Array.from(root.querySelectorAll<HTMLElement>(side?'#oppHand .card--back':'#hand .card'));if(!multi)hands=hands.slice(0,1);if(!multi)targets=targets.slice(1,2);targets.forEach(n=>n.style.visibility='hidden');root.style.filter=dark?'brightness(.62)':''}
function prepare(){starts=[];ends=[];for(const [i,n]of targets.entries()){const h=hands[Math.min(i,hands.length-1)];const r=h?.getBoundingClientRect();starts.push(r?new DOMMatrix().translate(r.left,r.top).scale(r.width/180,r.height/270):projectedPlacement(n,180,270).translate(0,300));ends.push(projectedPlacement(n,180,270))}}
function sample(ms:number){if(!ready||disposed)return;clock=ms;const flight=1;const effect=reduced?DURATION:ms;targets.forEach(n=>n.style.visibility='hidden');hands.forEach(n=>n.style.visibility='hidden');for(const [i,n]of targets.entries()){const rig=rigs[i];if(ms>=DURATION){rig.el.style.visibility='hidden';n.style.visibility='';continue}rig.el.style.visibility='visible';const aa=starts[i].toFloat64Array(),bb=ends[i].toFloat64Array();rig.el.style.transform=new DOMMatrix(Array.from(aa,(v,j)=>v+(bb[j]-v)*flight)).toString();renderer.draw(rig.canvas,faces.get(card)!,variant,effect,card==='LEGEND_GAMBLER',reduced,true,dark)} }
function tick(now:number){if(!running)return;clock+=Math.max(0,Math.min(80,now-last))*speed;last=now;sample(clock);if(clock<DURATION)raf=requestAnimationFrame(tick);else running=false}
function play(){if(!ready)return;setup();prepare();clock=0;if(reduced){sample(DURATION);return}running=true;last=performance.now();raf=requestAnimationFrame(tick)}
root.addEventListener('click',e=>{if((e.target as HTMLElement).closest('#hand .card,#oppHand .card--back')){e.preventDefault();e.stopImmediatePropagation();play()}},true);
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent||e.data?.kind!=='gambler-control')return;const d=e.data;const next=['GAMBLER','LEGEND_GAMBLER'].includes(d.card)?d.card:card;const changed=next!==card||side!==Number(d.side)||multi!==!!d.multi;card=next;side=d.side===1?1:0;multi=!!d.multi;variant=Math.max(0,Math.min(4,Number(d.variant)||0));reduced=!!d.reduced;dark=!!d.dark;if(d.speed)speed=Number(d.speed);if(changed||d.action==='cancel'){setup()}root.style.filter=dark?'brightness(.62)':'';if(d.action==='play')play();if(d.action==='seek'){cancel();prepare();sample(Math.max(0,Math.min(DURATION,d.ms||0)))}});
window.addEventListener('resize',()=>{cancel();if(ready)setup()});document.addEventListener('visibilitychange',()=>{if(document.hidden)cancel()});window.addEventListener('pagehide',()=>{disposed=true;cancel();renderer.dispose();rigs.forEach(r=>r.el.remove());stop();view.destroy()},{once:true});
setup();const stop=startBoardLayout();(window as any).gamblerBoard={get state(){return{ready,side,variant,card,multi,reduced,running,clock,targets:targets.length,visibleRigs:rigs.filter(r=>r.el.style.visibility==='visible').length,hiddenTargets:targets.filter(n=>n.style.visibility==='hidden').length}},play,cancel,seek(ms:number){cancel();prepare();sample(ms)}};
void(async()=>{await waitForDuel(root);for(const id of ['GAMBLER','LEGEND_GAMBLER'])faces.set(id,await surface(id));ready=true;setup();parent.postMessage({kind:'gambler-ready'},location.origin)})().catch(e=>console.error(e));
