import '../../styles/tokens.css';import '../../styles/base.css';import '../../styles/card.css';import '../../styles/game-overlays.css';import '../../styles/game.css';import '../../styles/screens.css';import '../../styles/reading-board.css';import '../../styles/presentation.css';
import './style.css';
import {setLang} from '../../i18n';import {entries,entry} from './catalog';import {Stage} from './stage';
setLang('ja');const q=new URLSearchParams(location.search),root=document.getElementById('app')!;
if(q.has('stage')){
 const board=q.get('view')==='board';document.body.className=board?'element-board':'element-studio';
 const stage=new Stage(root,board);(window as any).elementStage=stage;
 stage.onTick=()=>parent.postMessage({type:'element-tick',status:stage.status()},location.origin);
 void stage.load(q.get('effect')??'cannon').then(()=>parent.postMessage({type:'element-ready'},location.origin));
 window.addEventListener('resize',()=>stage.seek(stage.time));window.addEventListener('pagehide',()=>stage.dispose(),{once:true});document.addEventListener('visibilitychange',()=>{if(document.hidden)stage.stop()});
}else{
 document.body.className='element-shell';let selected=entry(q.get('effect')??'cannon'),api:Stage|undefined,view=q.get('view')??'studio';
 root.innerHTML=`<header class="element-header"><a class="wordmark" href="/elemental-seven.html">LORE<span>ANIMATION ATELIER</span></a><div class="edition">ELEMENTAL STUDIES <b>07</b></div><span class="preview-badge">制作プレビュー</span></header><div class="element-layout"><aside class="element-list"><p>THE COLLECTION</p>${entries.map((e,i)=>`<button data-effect="${e.kind}" class="effect-option"><span class="effect-num">0${i+1}</span><span><b>${e.name}</b><small>${e.en}</small></span><i>↗</i></button>`).join('')}<div class="collection-note">炎・雷・鋼の質感と、<br>カードから着弾までの連続性。</div></aside><main class="element-main"><div class="element-heading"><div><div id="effect-en"></div><h1 id="effect-name"></h1><p id="effect-concept"></p></div><div class="view-switch"><button id="studio">拡大</button><button id="board">実盤面</button></div></div><select id="mobile-effect" aria-label="演出を選択">${entries.map(e=>`<option value="${e.kind}">${e.name}</option>`).join('')}</select><div class="element-viewport"><iframe title="7種類のカード演出" allow="autoplay"></iframe><span id="loading">盤面とカードを準備しています…</span><span id="phase">READY</span></div><div class="element-transport"><button id="play" class="primary">▶ 再生</button><button id="reset">↺ 最初へ</button><input id="seek" type="range" min="0" max="3300" value="0" aria-label="再生位置"><output id="time">0.00 / 3.30</output></div><div class="element-options"><label>速度<select id="speed"><option value="1">1×</option><option value="0.5">0.5×</option><option value="0.25">0.25×</option></select></label><label>陣営<select id="side"><option value="0">自分側</option><option value="1">相手側</option></select></label><label><input id="loop" type="checkbox">ループ</label><label><input id="light" type="checkbox">白背景</label><label><input id="reduced" type="checkbox">動き低減</label><label id="heavy-label"><input id="heavy" type="checkbox">大砲兵</label><label id="friendly-label"><input id="friendly" type="checkbox">味方に攻撃</label><label id="enhanced-label"><input id="enhanced" type="checkbox">9ダメージ</label><label id="player-label"><input id="player" type="checkbox">相手プレイヤーへ</label></div><footer><span id="effect-detail"></span><span>固定局面での演出確認 · 実対戦への接続前</span></footer></main></div>`;
 const get=(id:string)=>document.getElementById(id)!;const input=(id:string)=>get(id) as HTMLInputElement;const frame=root.querySelector('iframe')!;
 function describe(){get('effect-name').textContent=selected.name;get('effect-en').textContent=selected.en;get('effect-concept').textContent=selected.concept;root.querySelectorAll<HTMLElement>('[data-effect]').forEach(el=>el.classList.toggle('active',el.dataset.effect===selected.kind));(get('mobile-effect')as HTMLSelectElement).value=selected.kind;input('seek').max=String(selected.duration);get('heavy-label').hidden=selected.kind!=='cannon';get('friendly-label').hidden=selected.kind!=='berserk';get('enhanced-label').hidden=selected.kind!=='zone';get('player-label').hidden=!['cannon','ball'].includes(selected.kind);get('effect-detail').textContent=selected.kind==='lightning'?'旧仕様の演出 · 12ダメージ × 3回 · 味方を含む':selected.kind==='zone'?'敵モンスターと相手プレイヤーへ同時着弾':`${selected.damage}ダメージ × ${selected.hits}回`;get('studio').classList.toggle('selected',view==='studio');get('board').classList.toggle('selected',view==='board')}
 function sync(){if(!api)return;input('seek').value=String(api.time);get('time').textContent=`${(api.time/1000).toFixed(2)} / ${(selected.duration/1000).toFixed(2)}`;get('play').textContent=api.playing?'Ⅱ 一時停止':'▶ 再生';const t=api.time,last=api.hits.at(-1)?.at??1500;get('phase').textContent=t===0?'READY':t<850?'CHARGE / 蓄熱・予兆':t<last?'FLIGHT / 移動・接触':t<selected.duration-450?'AFTERGLOW / 余韻':'COMPLETE';if(!api.fx.fire.available)get('phase').textContent+=' · 簡易描画'}
 async function apply(){if(!api)return;get('loading').hidden=false;api.heavy=input('heavy').checked;api.friendly=input('friendly').checked;api.enhanced=input('enhanced').checked;api.player=input('player').checked;api.reduced=input('reduced').checked;api.loop=input('loop').checked;api.speed=+(get('speed')as HTMLSelectElement).value;await api.load(selected.kind,+(get('side')as HTMLSelectElement).value);get('loading').hidden=true;sync()}
 function navigate(){api?.dispose();api=undefined;get('loading').hidden=false;frame.src=`/elemental-seven.html?stage=1&view=${view}&effect=${selected.kind}`;history.replaceState({},'',`/elemental-seven.html?effect=${selected.kind}&view=${view}`);describe()}
 function choose(id:string){selected=entry(id);describe();history.replaceState({},'',`/elemental-seven.html?effect=${selected.kind}&view=${view}`);void apply()}
 root.querySelectorAll<HTMLButtonElement>('[data-effect]').forEach(b=>b.onclick=()=>choose(b.dataset.effect!));get('mobile-effect').onchange=()=>choose((get('mobile-effect')as HTMLSelectElement).value);
 get('studio').onclick=()=>{view='studio';navigate()};get('board').onclick=()=>{view='board';navigate()};get('play').onclick=()=>{if(api?.playing)api.stop();else api?.play();sync()};get('reset').onclick=()=>{api?.reset();sync()};input('seek').oninput=()=>{api?.stop();api?.seek(+input('seek').value);sync()};get('speed').onchange=()=>{if(api)api.speed=+(get('speed')as HTMLSelectElement).value};get('loop').onchange=()=>{if(api)api.loop=input('loop').checked};get('reduced').onchange=()=>{if(api){api.reduced=input('reduced').checked;if(api.reduced)api.loop=false;api.seek(api.time)}};get('light').onchange=()=>frame.contentDocument?.body.classList.toggle('element-light',input('light').checked);
 for(const id of ['heavy','friendly','enhanced','player','side'])get(id).onchange=()=>void apply();
 const mq=matchMedia('(prefers-reduced-motion: reduce)');input('reduced').checked=mq.matches;mq.addEventListener('change',e=>{input('reduced').checked=e.matches;if(api){api.reduced=e.matches;api.stop();api.seek(api.time)}});
 window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==frame.contentWindow)return;if(e.data?.type==='element-ready'){api=(frame.contentWindow as any).elementStage;(window as any).elementLab={get stage(){return api},select:choose,setView:(v:string)=>{view=v;navigate()}};frame.contentDocument?.body.classList.toggle('element-light',input('light').checked);void apply()}else if(e.data?.type==='element-tick')sync()});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)api?.stop()});navigate();
}
