import './style.css';
type Row={id:string;name:string;owner:string;group:string;category:string;description:string;cards:{id:string;name:string}[];state:string;playable:boolean;variants:number};
const app=document.querySelector<HTMLDivElement>('#review')!;
app.innerHTML=`<header class="masthead"><div><small>LORE / ANIMATION REVIEW</small><h1>演出の一括プレビュー</h1></div><div class="summary"><strong>29シリーズ + 186効果 + 追加2項目</strong><span>旧A〜D案はすべて不採用</span></div><a href="/mimic-family.html?card=MIMIC_LORD&mode=compare" style="color:#e0c58d">ミミック全種：新5種 × 3案／通常・マスター確定 →</a><button id="refresh">一覧を更新</button></header><div class="workspace"><aside class="library"><label class="search-label" for="search">演出を探す</label><input id="search" type="search" placeholder="腐敗、気合、カードID…"><div class="filters"><select id="group" aria-label="種類"><option value="">すべて</option><option value="series">シリーズ</option><option value="effect">効果・状態</option><option value="existing">既定・既存演出</option></select><select id="owner" aria-label="担当"><option value="">全担当</option>${['A','B','C','D'].map(x=>`<option>${x}</option>`).join('')}</select></div><div id="list-count" aria-live="polite"></div><nav id="list" aria-label="全演出一覧"></nav></aside><main><div class="selection"><div class="eyebrow" id="meta"></div><h2 id="title">一覧を読み込んでいます</h2><p id="description"></p><div class="toolbar"><label>カード <select id="card" aria-label="比較するカード"></select></label><div class="variant-tabs" role="group" aria-label="比較表示"><button id="v1">①</button><button id="v2">②</button><button id="compare">① ② を並べる</button></div><button id="play-all" disabled>再生</button><button id="reset-all" disabled>リセット</button><button id="previous" aria-label="前の項目">← 前</button><button id="next" aria-label="次の項目">次 →</button></div><p class="hint" id="hint">左の一覧から演出を選んでください。</p></div><div id="stages"></div><div class="review-note"><label for="note">この項目のフィードバックメモ <span>このブラウザに自動保存</span></label><textarea id="note" rows="2" placeholder="気になった動きや、採用したい案など"></textarea><span id="note-status" aria-live="polite"></span></div></main></div>`;
const el=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
let rows:Row[]=[],selected:Row|undefined,mode='1',card='',frames:HTMLIFrameElement[]=[];
let mountVersion=0;
const query=new URLSearchParams(location.search);
mode=['1','2','compare'].includes(query.get('view')||'')?query.get('view')!:'1';
card=query.get('card')||'';
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
function filtered(){const q=el<HTMLInputElement>('search').value.trim().toLowerCase();return rows.filter(r=>(!el<HTMLSelectElement>('group').value||r.group===el<HTMLSelectElement>('group').value)&&(!el<HTMLSelectElement>('owner').value||r.owner===el<HTMLSelectElement>('owner').value)&&`${r.id} ${r.name} ${r.description} ${r.cards.map(c=>`${c.id} ${c.name}`).join(' ')}`.toLowerCase().includes(q));}
function list(){const visible=filtered();el('list-count').textContent=`${visible.length} / ${rows.length} 項目`;el('list').innerHTML=visible.length?visible.map(r=>`<button class="entry ${selected?.id===r.id?'active':''}" data-id="${r.id}" ${selected?.id===r.id?'aria-current="true"':''}><span class="entry-id">${r.id} <span>${r.owner}</span></span><strong>${escape(r.name)}</strong><small>${escape(r.state)}${r.variants===2?' · 2案':''}</small></button>`).join(''):'<p class="empty">該当する項目がありません。</p>';el('list').querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.onclick=()=>choose(b.dataset.id!));const index=visible.findIndex(r=>r.id===selected?.id);el<HTMLButtonElement>('previous').disabled=index<=0;el<HTMLButtonElement>('next').disabled=index<0||index===visible.length-1;}
function choose(id:string,keepCard=false){if(selected?.id===id&&!keepCard)return;selected=rows.find(r=>r.id===id)||rows[0];if(!keepCard)card='';if(card&&!selected.cards.some(c=>c.id===card))card='';const picker=el<HTMLSelectElement>('card');picker.innerHTML='<option value="">代表カード</option>'+selected.cards.map(c=>`<option value="${escape(c.id)}">${escape(c.name)}</option>`).join('');picker.value=card;picker.disabled=!selected.cards.length;el('meta').textContent=`${selected.id} · 担当 ${selected.owner} · ${selected.state}`;el('title').textContent=selected.name;el('description').textContent=selected.description;if(selected.variants===1)mode='1';for(const id of ['v2','compare'])el<HTMLButtonElement>(id).disabled=selected.variants===1;try{el<HTMLTextAreaElement>('note').value=localStorage.getItem(`lore-animation-review:${selected.id}`)||'';}catch{el<HTMLTextAreaElement>('note').value='';}el('note-status').textContent='';list();mount();}
function mount(){if(!selected)return;const revision=++mountVersion;el<HTMLButtonElement>('play-all').disabled=true;el<HTMLButtonElement>('reset-all').disabled=true;const variants=mode==='compare'?[1,2]:[+mode];el('stages').className=mode==='compare'?'comparison':'';el('stages').replaceChildren();frames=[];el('hint').textContent=selected.variants===1?'既定・既存演出の確認項目です。新しい2案としては数えていません。':mode==='compare'?'同じ項目の2案を並べています。上の「2案を再生」で同時に開始できます。':'カード・場面・陣営などの詳細は盤面上の操作で切り替えられます。';
 for(const variant of variants){const panel=document.createElement('section');panel.className='preview-panel';const label=document.createElement('div');label.className='panel-label';label.textContent=selected.variants===1?'既定・既存演出':variant===1?'① 案':'② 案';const state=document.createElement('span');state.textContent='読み込み中';label.append(state);const frame=document.createElement('iframe');frame.title=`${selected.name} ${variant===1?'①':'②'} 実盤面`;const url=new URL(`/series-vfx-${selected.owner.toLowerCase()}.html`,location.origin);url.searchParams.set('revision','3');url.searchParams.set('item',selected.id);url.searchParams.set('variant',String(selected.owner==='C'?variant-1:variant));if(card)url.searchParams.set('card',card);frame.src=url.href;frame.dataset.owner=selected.owner;frame.addEventListener('load',()=>{if(mountVersion!==revision)return;adapt(frame);state.textContent='盤面を準備中';});panel.append(label,frame);el('stages').append(panel);frames.push(frame);}
 for(const [id,value]of [['v1','1'],['v2','2'],['compare','compare']]){el(id).classList.toggle('selected',mode===value);el(id).setAttribute('aria-pressed',String(mode===value));}el('play-all').textContent=mode==='compare'?'2案を再生':'再生';const url=new URL(location.href);url.searchParams.set('item',selected.id);url.searchParams.set('view',mode);if(card)url.searchParams.set('card',card);else url.searchParams.delete('card');history.replaceState(null,'',url);}
function adapt(frame:HTMLIFrameElement){const doc=frame.contentDocument;if(!doc)return;const style=doc.createElement('style');style.textContent=`
/* Only the review shell is adapted; embedded board rendering is untouched. */
body{margin:0!important}a[href*="revision2"],a[href*="revision=2"],a[href*="r2=1"]{display:none!important}
${frame.dataset.owner==='A'?`#lab{display:block!important}#lab>aside{display:flex!important;flex-wrap:wrap;gap:8px;padding:10px 14px!important;border-right:0}#lab>aside>small,#lab>aside>h1,#lab>aside>p,#lab>aside>a,#lab>aside>label:first-of-type,#variants,#lab>section>header,#lab>section>details{display:none!important}#lab>aside label{margin:0!important;min-width:115px}#lab>aside select{max-width:260px}#lab .stage{height:510px!important;min-height:400px!important}#lab footer{padding:8px 14px}`:''}
${frame.dataset.owner==='B'?`#app>header,main>aside,.scope,#permalink{display:none!important}main{display:block!important;height:auto!important}.selection{padding:10px 14px!important}.selection>h2,.selection>#stages{display:none!important}.controls label:has(#variant){display:none!important}section>iframe{height:540px!important;min-height:540px!important;flex:none!important}`:''}
${frame.dataset.owner==='C'?`.r3-shell aside,.r3-shell header>div:first-child,#itemPicker,#one,#two{display:none!important}.r3-shell header{min-height:0!important;padding:10px!important}.r3-shell main{left:0!important}#detail{height:54px!important}.r3-shell iframe{height:calc(100% - 54px)!important}`:''}
${frame.dataset.owner==='D'?`.d3-studio{grid-template-columns:1fr!important;grid-template-rows:1fr!important}.d3-studio>aside,header>div:first-child,#variant{display:none!important}header{padding:10px!important}`:''}
`;doc.head.append(style);}
function sync(){let ready=frames.length>0;for(const frame of frames){let playable=false;try{const win=frame.contentWindow as any;const appReady=frame.dataset.owner==='A'?win?.aR3Lab?.ready:frame.dataset.owner==='B'?win?.seriesBR3?.board?.ready:frame.dataset.owner==='C'?!!win?.seriesCR3&&!win.seriesCR3.loading:true;playable=!!appReady&&!!frame.contentDocument?.querySelector<HTMLButtonElement>('#play:not(:disabled)');}catch{}ready&&=playable;const label=frame.previousElementSibling?.querySelector('span');if(label)label.textContent=playable?'再生できます':'準備中・個別状態は下の表示を確認';}el<HTMLButtonElement>('play-all').disabled=!ready;el<HTMLButtonElement>('reset-all').disabled=!frames.length||!frames.every(f=>!!f.contentDocument?.querySelector('#reset:not(:disabled)'));}
for(const [id,value]of [['v1','1'],['v2','2'],['compare','compare']])el(id).onclick=()=>{mode=value;mount();};
el('play-all').onclick=()=>frames.forEach(f=>f.contentDocument?.querySelector<HTMLButtonElement>('#play')?.click());el('reset-all').onclick=()=>frames.forEach(f=>f.contentDocument?.querySelector<HTMLButtonElement>('#reset')?.click());
for(const id of ['search','group','owner'])el(id).addEventListener(id==='search'?'input':'change',list);
for(const [id,step]of [['previous',-1],['next',1]]as const)el(id).onclick=()=>{const visible=filtered(),index=visible.findIndex(r=>r.id===selected?.id),next=visible[index+step];if(next)choose(next.id);};
el('card').onchange=()=>{card=el<HTMLSelectElement>('card').value;mount();};el('note').oninput=()=>{if(!selected)return;try{localStorage.setItem(`lore-animation-review:${selected.id}`,el<HTMLTextAreaElement>('note').value);el('note-status').textContent='保存しました';}catch{el('note-status').textContent='保存できません。メモをコピーして保管してください。';}};
async function refresh(){el<HTMLButtonElement>('refresh').disabled=true;try{const response=await fetch('/review-catalog.json',{cache:'no-store'});if(!response.ok)throw new Error('一覧を読み込めませんでした');const data=await response.json();rows=data.rows.map((r:Row)=>({...r,state:'不採用（旧案）'}));if(!selected)choose(query.get('item')||'S01',true);else{selected=rows.find(r=>r.id===selected!.id);list();if(selected)el('meta').textContent=`${selected.id} · 担当 ${selected.owner} · ${selected.state}`;}}catch(error){el('hint').textContent=`${error}。「一覧を更新」で再試行してください。`;}finally{el<HTMLButtonElement>('refresh').disabled=false;}}
el('refresh').onclick=()=>void refresh();const timer=setInterval(sync,500);window.addEventListener('pagehide',()=>clearInterval(timer),{once:true});void refresh();
