import {accent} from './accent';
import '../../styles/tokens.css';import '../../styles/base.css';import '../../styles/card.css';import '../../styles/game-overlays.css';import '../../styles/game.css';import '../../styles/screens.css';import '../../styles/reading-board.css';import '../../styles/presentation.css';
import {GameView,setMyAvatar,setOppAvatar} from '../../ui/boardView';import {startBoardLayout} from '../../ui/layout';import {waitForDuel} from '../../ui/duelReadiness';import {clearMonsterStates} from '../../ui/monster/runtime';import {createGame} from '../../shared/engine';import {DB} from '../../shared/cards';import {setLang} from '../../i18n';
import {contact,duration} from './catalog';import {loadAssets} from './scene';import {Glass} from './glass';import {smooth,clamp} from '../dew-grant-six/renderer';
setLang('ja');setMyAvatar('SEEKER_BLUE');setOppAvatar('SEEKER_RED');
const css=document.createElement('style');css.textContent='body{margin:0;overflow:hidden;background:#f2eee8}.topbar,.help-callout,.help-fab,.mute-fab{display:none!important}';document.head.append(css);
const root=document.getElementById('app')!,noop=()=>{};
const view=new GameView(root,0,{onPlay:noop,onBlockedPlay:noop,onAttack:noop,onBlockedAttack:noop,onReorder:noop,onChooseTarget:noop,onBuyMarket:noop,onBuySupply:noop,onRefresh:noop,onEndTurn:noop,onSurrender:noop});
const g=createGame({mode:'bot',seed:73,starting:0,p0:{id:'preview-me',name:'YOU'},p1:{id:'preview-opp',name:'OPPONENT'}}).state;
g.turn=3;g.phase='main';g.pending=null;for(const [i,p] of g.players.entries()){p.openingDrawReady=false;p.hp=30;p.shield=8;p.dew=5;p.brand=0;p.mana=8;p.maxMana=8;p.enchants=[];p.quests=[];p.traps=[];p.field=['M4','ELF','TDE2'].map((id,j)=>({...DB[id],uid:`sb-${i}-${j}`,exhausted:false,summonedTurn:0,dmg:0,tempAtk:0,atkMod:0,defMod:0}));p.hand=[{...DB.DEFENSIVE_STANCE,uid:`sb-hand-${i}`}];}
view.render(g);view.setHandOpen(false);clearMonsterStates(root);
const canvas=document.createElement('canvas');canvas.style.cssText='position:fixed;inset:0;width:100%;height:100%;pointer-events:none;z-index:180';document.body.append(canvas);
const background=document.createElement('canvas'),glass=new Glass();let assets:Awaited<ReturnType<typeof loadAssets>>,ready=false,disposed=false,active=false,index=0,ms=0,side=0,multi=false,reduced=false,dark=false,shape=0,old=false;
const numbers=[...root.querySelectorAll<HTMLElement>('.pt-dew b')],original=numbers.map(n=>n.textContent);
function restore(){numbers.forEach((n,i)=>n.textContent=original[i]);canvas.getContext('2d')!.clearRect(0,0,canvas.width,canvas.height);}
function draw(){restore();if(!ready||!active||disposed||document.hidden)return;const dpr=Math.min(2,devicePixelRatio||1);if(canvas.width!==Math.round(innerWidth*dpr)||canvas.height!==Math.round(innerHeight*dpr)){canvas.width=Math.round(innerWidth*dpr);canvas.height=Math.round(innerHeight*dpr);}background.width=innerWidth;background.height=innerHeight;const bg=background.getContext('2d')!,c=canvas.getContext('2d')!;c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,innerWidth,innerHeight);root.style.filter=dark?'brightness(.62)':'';
 bg.fillStyle=dark?'#283a3d':'#e8e5de';bg.fillRect(0,0,innerWidth,innerHeight);
 for(const cv of root.querySelectorAll<HTMLCanvasElement>('.seeker-motion')){const r=cv.getBoundingClientRect();if(cv.width&&cv.height)bg.drawImage(cv,r.x,r.y,r.width,r.height);}
 for(const i of [0,1]){const card=root.querySelector<HTMLElement>(`[data-uid="sb-${i}-1"]`);if(card){const r=card.getBoundingClientRect();bg.drawImage(assets.card,r.x,r.y,r.width,r.height);}const badge=document.getElementById(i?'portraitOpp':'portraitMe')!.querySelector<HTMLElement>('.pt-dew')!,r=badge.getBoundingClientRect();bg.drawImage(assets.dew,r.x,r.y,r.width,r.height);}
 for(const i of multi?[0,1]:[side]){const portrait=document.getElementById(i?'portraitOpp':'portraitMe')!,badge=portrait.querySelector<HTMLElement>('.pt-dew')!,r=badge.getBoundingClientRect(),source=root.querySelector<HTMLElement>(`[data-uid="sb-${i}-1"]`)!.getBoundingClientRect();badge.querySelector('b')!.textContent=ms>=contact?'8':'5';if(reduced)continue;const t=clamp(ms/duration),u=smooth(.12,.69,t),x=source.x+source.width*.5+(r.x+r.width*.5-source.x-source.width*.5)*u,y=source.y+source.height*.5+(r.y+r.height*.5-source.y-source.height*.5)*u-Math.sin(Math.PI*u)*Math.max(18,r.width*.8),extent=r.width*(1.18+Math.sin(Math.PI*u)*.28)*smooth(0,.10,t)*(1-smooth(.72,.83,t));if(extent>.3){const angle=Math.atan2(r.y+r.height*.5-source.y-source.height*.5-Math.cos(Math.PI*u)*Math.PI*Math.max(18,r.width*.8),r.x+r.width*.5-source.x-source.width*.5);if(!old)accent(c,index,x,y,extent,ms/720,false,angle);const im=glass.draw(background,x,y,extent,shape,ms/720,dark,Math.max(100,extent*dpr*2),old?-1:index);if(im)c.drawImage(im,x-extent/2,y-extent/2,extent,extent);if(!old)accent(c,index,x,y,extent,ms/720,true,angle);}}
}
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent)return;if(e.data?.kind==='dew-toon-dispose'){dispose();return;}if(e.data?.kind!=='dew-toon-control'||disposed)return;const d=e.data;index=Math.max(0,Math.min(5,d.index|0));shape=Math.max(0,Math.min(4,d.shape|0));old=!!d.old;ms=Math.max(0,Math.min(duration,Number(d.ms)||0));side=d.side===1?1:0;multi=!!d.multi;reduced=!!d.reduced;dark=!!d.dark;active=!!d.active;draw();});
window.addEventListener('resize',()=>requestAnimationFrame(draw));document.addEventListener('visibilitychange',draw);const stop=startBoardLayout();function dispose(){if(disposed)return;disposed=true;restore();glass.dispose();canvas.remove();stop();view.destroy();}window.addEventListener('pagehide',dispose,{once:true});
(window as any).dewToonBoard={get state(){return{ready,disposed,active,index,shape,old,ms,side,multi,dark,reduced,counts:numbers.map(n=>n.textContent),canvases:document.querySelectorAll('body>canvas').length}},dispose};
void(async()=>{assets=await loadAssets();await waitForDuel(root);ready=true;parent.postMessage({kind:'dew-toon-ready'},location.origin);draw();})().catch(e=>parent.postMessage({kind:'dew-toon-error',error:String(e)},location.origin));
