import '../../styles/tokens.css';import '../../styles/base.css';import '../../styles/card.css';import '../../styles/game-overlays.css';import '../../styles/game.css';import '../../styles/screens.css';import '../../styles/reading-board.css';import '../../styles/presentation.css';
import {arrivalFixture} from '../series-vfx-b/revision3/fixtures';
import {BaseController} from '../../game/controller';import {startBoardLayout} from '../../ui/layout';import {waitForDuel} from '../../ui/duelReadiness';import {setMyAvatar,setOppAvatar} from '../../ui/boardView';import {setLang} from '../../i18n';import {synergyFixture} from '../series-vfx-b/revision3/synergy-fixtures';import type {Action} from '../../shared/types';import {setFxSkip} from '../../ui/anim';import {closeOverlay} from '../../ui/modal';
setLang('ja');setMyAvatar('SEEKER_BLUE');setOppAvatar('SEEKER_RED');
function fixtureFor(cue:string,owner:0|1){
 if(cue.startsWith('summon:')){const f=arrivalFixture(cue.slice(7),owner);return {...f,participants:f.after.players[owner].field.map(m=>m.uid)};}
 return synergyFixture(cue,'TGE6',owner);
}
let instance:QA,stop=()=>{};let fixture=fixtureFor('A170',0);
class QA extends BaseController{
 constructor(){super(document.getElementById('app')!,0,{onHome:()=>{},onRematch:()=>{}});this.state=structuredClone(fixture.before);this.introShown=true;this.view.render(this.state);this.view.setHandOpen(true);}
 protected submit(_a:Action){this.run();}
 run(){this.applyResult({state:structuredClone(fixture.after),events:fixture.events});}
}
const bar=document.createElement('div');bar.style.cssText='position:fixed;z-index:99999;top:8px;left:8px;background:white;padding:8px;color:black;font:13px sans-serif';bar.innerHTML='<select id="cue"><option value="A170">FIX 段階1</option><option value="A171">FIX 段階2</option><option value="A172">FIX 段階3</option><option value="A173">FIX 始原勝利</option><option value="summon:TSO2">孤独02</option><option value="summon:TPO3">捕食03</option><option value="summon:TAR3">貴族03</option><option value="summon:TDE2">魔族02</option><option value="summon:TGE3">始原02</option></select><select id="owner"><option value="0">自分</option><option value="1">相手</option></select><button id="resetqa">準備</button><button id="runqa">エンジン結果を再生</button><button id="skipqa">スキップ</button><span id="qa-status">準備中</span>';document.body.append(bar);
const status=bar.querySelector('#qa-status')!;
async function reset(){instance?.destroy();stop();closeOverlay();fixture=fixtureFor((bar.querySelector('#cue') as HTMLSelectElement).value,Number((bar.querySelector('#owner') as HTMLSelectElement).value) as 0|1);instance=new QA();stop=startBoardLayout();await waitForDuel(document.getElementById('app')!);status.textContent='準備完了';}
bar.querySelector<HTMLButtonElement>('#resetqa')!.onclick=()=>void reset();bar.querySelector<HTMLButtonElement>('#runqa')!.onclick=()=>instance.run();bar.querySelector<HTMLButtonElement>('#skipqa')!.onclick=()=>setFxSkip(true);
(window as any).tribeApprovedQA={get fixture(){return {events:fixture.events,over:fixture.after.over,winner:fixture.after.winner,participants:fixture.participants};}};
void reset();

const proof=document.createElement('output');proof.id='qa-proof';proof.style.cssText='position:fixed;bottom:0;left:0;z-index:9999;font:11px monospace;color:white;background:#111;padding:5px';document.body.append(proof);
let max=0,frames=0,magicSeen=false;
function inspect(){const rigs=[...document.querySelectorAll<HTMLElement>('[data-tribe-synergy]')];max=Math.max(max,rigs.length);if(rigs.length)frames++;magicSeen ||= !!document.querySelector('[data-tribe-victory]');proof.textContent=JSON.stringify({max,frames,magicSeen,live:rigs.length,hidden:document.querySelectorAll('.zone-mon .card[style*="visibility: hidden"]').length});requestAnimationFrame(inspect);}inspect();

const cancelButton=document.createElement('button');cancelButton.textContent='取消を検証';cancelButton.id='cancelqa';bar.append(cancelButton);
cancelButton.onclick=async()=>{await reset();instance.run();const start=performance.now();const check=()=>{if(document.querySelector('[data-tribe-synergy]')){setFxSkip(true);status.textContent='取消完了';return;}if(performance.now()-start>12000){status.textContent='取消対象が現れません';return;}requestAnimationFrame(check);};requestAnimationFrame(check);};
const batchButton=document.createElement('button');batchButton.textContent='18条件を検証';batchButton.id='batchqa';bar.append(batchButton);
const batchReport=document.createElement('pre');batchReport.id='qa-batch-report';batchReport.style.cssText='display:none';document.body.append(batchReport);
batchButton.onclick=async()=>{batchButton.disabled=true;const results:unknown[]=[];try{for(const owner of [0,1])for(const cue of ['summon:TSO2','summon:TPO3','summon:TAR3','summon:TDE2','summon:TGE3','A170','A171','A172','A173']){(bar.querySelector('#cue') as HTMLSelectElement).value=cue;(bar.querySelector('#owner') as HTMLSelectElement).value=String(owner);await reset();status.textContent=`検証 ${owner} ${cue}`;let maximum=0,seen=false,modalDuringFx=false,first=0,last=0;instance.run();const start=performance.now();await new Promise<void>((resolve,reject)=>{const poll=()=>{const n=document.querySelectorAll(cue.startsWith('summon:')?'[data-tribe-summon]':'[data-tribe-synergy]').length,modal=!!document.querySelector('.outcome-result');if(n){if(!seen)first=performance.now();seen=true;last=performance.now();maximum=Math.max(maximum,n);modalDuringFx ||= modal;}if(seen&&!n&&(cue!=='A173'||modal)){resolve();return;}if(performance.now()-start>20000){reject(Error(`Timed out: ${owner} ${cue}`));return;}requestAnimationFrame(poll);};poll();});const hidden=document.querySelectorAll('.zone-mon .card[style*="visibility: hidden"]').length;results.push({owner,cue,maximum,durationMs:Math.round(last-first),modalDuringFx,hidden,passed:maximum===(cue.startsWith('summon:')?1:cue==='A173'?6:cue==='A172'?4:cue==='A171'?3:2)&&hidden===0&&!modalDuringFx});}status.textContent='18条件完了';batchReport.textContent=JSON.stringify(results);}catch(e){status.textContent=String(e);batchReport.textContent=JSON.stringify({results,error:String(e)});}finally{batchButton.disabled=false;}};
