import {build} from 'esbuild';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
const dir=await fs.mkdtemp(path.join(os.tmpdir(),'dew-grant-'));
try{
 await build({stdin:{contents:"export * from './client/src/shared/engine';export {DB} from './client/src/shared/cards';",resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',outfile:dir+'/engine.mjs',plugins:[{name:'dew-boundary',setup(b){b.onLoad({filter:/shared\/engine\.ts$/},async({path})=>({contents:await fs.readFile(path,'utf8')+'\nexport {gainDew,makeCtx,tickEnchants,havenPurchase,treeKeeperTrigger,gainShield};',loader:'ts'}));}}]});
 const E=await import(dir+'/engine.mjs'),checks=[];
 const fresh=()=>{const g=E.createGame({mode:'online',seed:73,starting:0,p0:{id:'a',name:'A'},p1:{id:'b',name:'B'}}).state;g.turn=4;g.cur=0;g.phase='main';g.pending=null;for(const p of g.players)Object.assign(p,{field:[],hand:[],deck:[],discard:[],enchants:[],traps:[],quests:[],shield:0,brand:0,dew:0,hp:100,mana:20,maxMana:20,openingDrawReady:false});return g;};
 const grants=e=>e.filter(x=>x.type==='statusGrant'&&x.resource==='dew');
 for(const player of [0,1]){const g=fresh(),ev=[],p=g.players[player],ctx=E.makeCtx(g,ev);E.gainDew(ctx,p,3,'public');E.gainDew(ctx,p,2,'public');E.gainDew(ctx,p,0);E.gainDew(ctx,p,-1);assert.deepEqual(grants(ev).map(e=>[e.player,e.before,e.after,e.sourceUid]),[[player,0,3,'public'],[player,3,5,'public']]);checks.push('exact-positive-gains-'+player);}
 for(const player of [0,1])for(const before of [0,5]){const g=fresh();g.cur=player;g.players[player].dew=before;g.players[player].hand=[{...E.DB.NOURISHING_RAIN,uid:'rain'}];const r=E.reduce(g,{type:'play',idx:0});assert.equal(grants(r.events).length,1);assert.deepEqual(grants(r.events).map(e=>[e.player,e.before,e.after]),[[player,before,before+1]]);assert.equal(g.players[player].dew,before);assert.equal(r.state.players[player].discard.at(-1).id,'NOURISHING_RAIN');checks.push('spell-'+player+'-'+before);}
 {const g=fresh(),ev=[],p=g.players[0];p.enchants=['WORLD_CARE','WORLD_HEART'].map(id=>({card:{...E.DB[id],uid:id},cnt:0}));E.tickEnchants(g,E.makeCtx(g,ev),p);assert.deepEqual(grants(ev).map(e=>[e.sourceUid,e.before,e.after]),[['WORLD_CARE',0,1],['WORLD_HEART',1,3]]);checks.push('persistent-spells-distinct-origin');}
 {const g=fresh(),ev=[],p=g.players[0];p.enchants=[{card:{...E.DB.ELF_HAVEN,uid:'haven'}}];E.havenPurchase(g,E.makeCtx(g,ev),p,{...E.DB.ELF,uid:'purchased'});assert.equal(grants(ev)[0].sourceUid,'haven');assert(ev.some(e=>e.type==='enchantActivate'&&e.uid==='haven'));checks.push('purchase-trigger-haven');}
 {const g=fresh(),ev=[],p=g.players[0];p.field=['a','b'].map(uid=>({...E.DB.VITAL3,uid}));E.treeKeeperTrigger(g,E.makeCtx(g,ev),p,{...E.DB.WORLD_CARE,uid:'played'});assert.deepEqual(grants(ev).map(e=>[e.sourceUid,e.before,e.after]),[['a',0,1],['b',1,2]]);checks.push('multiple-keepers-causal-origins');}
 {const g=fresh(),ev=[],p=g.players[1];p.field=[{...E.DB.PRIEST,uid:'priest'}];E.gainShield(g,E.makeCtx(g,ev),p,6);assert.deepEqual(grants(ev).map(e=>[e.player,e.sourceUid,e.after]),[[1,'priest',2]]);checks.push('shield-priest-reaction');}
 {let g=fresh();g.players[0].dew=10;g.players[0].hand=[{...E.DB.HIGH_ELF,uid:'high-elf'}];g.players[1].hand=[{...E.DB.M1,uid:'opponent'}];let r=E.reduce(g,{type:'play',idx:0});assert.equal(r.state.pending.data.sourceUid,'high-elf');r=E.reduce(r.state,{type:'pick',uid:'done'});assert.deepEqual(grants(r.events).map(e=>[e.sourceUid,e.before,e.after]),[['high-elf',10,20]]);checks.push('resumed-high-elf-origin');}
 {const g=fresh();g.players[1].dew=8;g.players[0].hand=[{...E.DB.DESERTIFICATION,uid:'desert'}];const r=E.reduce(g,{type:'play',idx:0});assert.equal(r.state.players[1].dew,0);assert.equal(grants(r.events).length,0);checks.push('removal-never-plays-gain');}
 console.log(JSON.stringify({passed:true,checks},null,2));
}finally{await fs.rm(dir,{recursive:true,force:true});}
