import assert from 'node:assert/strict';import {build} from 'esbuild';import {JSDOM} from 'jsdom';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';
const dom=new JSDOM('<main id="root"><div id="anchor" data-board-plane="0"></div><div id="source" data-card-id="GAMBLER"></div><div id="reveal"></div></main>',{pretendToBeVisual:true});for(const k of ['window','document','HTMLElement','Event','HTMLCanvasElement'])globalThis[k]=dom.window[k];let reduced=false,now=0,next=0;const frames=new Map();globalThis.matchMedia=()=>({matches:reduced});globalThis.performance={now:()=>now};globalThis.innerWidth=1280;globalThis.innerHeight=900;globalThis.devicePixelRatio=1;globalThis.DOMMatrix=class{translate(){return this}scale(){return this}};globalThis.requestAnimationFrame=f=>{frames.set(++next,f);return next};globalThis.cancelAnimationFrame=i=>frames.delete(i);HTMLCanvasElement.prototype.getContext=()=>({drawImage(){},clearRect(){}});globalThis.verify={draws:[],variants:[],created:0,disposed:0,hold:false,fail:false};const dir=await mkdtemp(path.join(tmpdir(),'gambler-test-'));const settle=()=>new Promise(r=>setImmediate(r)),advance=async ms=>{now+=ms;const a=[...frames.values()];frames.clear();a.forEach(f=>f(now));await settle()};
try{
 await build({entryPoints:['client/src/ui/gamblerSummon/runtime.ts'],bundle:true,platform:'node',format:'esm',outfile:dir+'/runtime.mjs',plugins:[{name:'controlled-renderer',setup(b){b.onResolve({filter:/cardSurface$/},()=>({path:'surface',namespace:'test'}));b.onResolve({filter:/boardProjection$/},()=>({path:'projection',namespace:'test'}));b.onResolve({filter:/^\.\/renderer$/},()=>({path:'renderer',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},a=>({contents:a.path==='surface'?`export const CARD_PADDING=.12;export async function captureCardSurface(){if(verify.hold)await new Promise(r=>verify.release=r);if(verify.fail)throw Error('failed capture');return {face:document.createElement('canvas')}}`:a.path==='projection'?`export const layoutRect=()=>({left:0,top:0,width:180,height:280}),projectedPlacement=()=>({toString(){return 'matrix(1,0,0,1,0,0)'}});`:`export class Renderer{constructor(){verify.created++}draw(c,f,v,t){verify.draws.push(t);verify.variants.push(v)}refreshFace(){}releaseFace(){}dispose(){verify.disposed++}}`}));}}]});
 const {playGamblerSummon:play,cancelGamblerSummons,cancelGamblerSummon}=await import(dir+'/runtime.mjs'),source=document.querySelector('#source'),anchor=document.querySelector('#anchor'),reveal=document.querySelector('#reveal');let impacts=0;
 verify.hold=true;source.style.visibility='visible';const pending=play(source,{anchor,reveal});assert.equal(source.style.visibility,'hidden');assert.deepEqual(verify.draws,[0]);cancelGamblerSummon(source);verify.release();assert.equal(await pending,false);await settle();verify.hold=false;assert.equal(source.style.visibility,'visible');
 for(const id of ['GAMBLER','LEGEND_GAMBLER']){source.dataset.cardId=id;const task=play(source,{anchor,onImpact:()=>impacts++});await settle();const before=impacts;await advance(2345);assert.equal(impacts,before);await advance(2);assert.equal(impacts,before+1);await advance(2000);assert.equal(await task,true);assert.equal(impacts,before+1);assert.equal(verify.variants.at(-1),id==='GAMBLER'?0:1);assert.equal(source.style.visibility,'visible')}
 for(const reason of ['root','abort','resize','pagehide','hidden','detach']){const signal=new AbortController(),task=play(source,{anchor,signal:signal.signal});await settle();if(reason==='root')cancelGamblerSummons(document.querySelector('#root'));if(reason==='abort')signal.abort();if(reason==='resize'||reason==='pagehide')window.dispatchEvent(new Event(reason));if(reason==='hidden'){Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'))}if(reason==='detach'){anchor.remove();await advance(20)}assert.equal(await task,false);assert.equal(source.style.visibility,'visible');Object.defineProperty(document,'hidden',{configurable:true,value:false});document.querySelector('#root').append(anchor)}
 const nodes=[source,...Array.from({length:2},()=>{const n=source.cloneNode();document.querySelector('#root').append(n);return n})];const simultaneous=nodes.map(n=>play(n,{anchor}));assert.equal(document.querySelectorAll('.gambler-summon').length,3);await settle();cancelGamblerSummons();assert.deepEqual(await Promise.all(simultaneous),[false,false,false]);
 reduced=true;assert.equal(await play(source,{onImpact:()=>impacts++}),true);reduced=false;verify.fail=true;const warn=console.warn;console.warn=()=>{};assert.equal(await play(source),false);console.warn=warn;assert.equal(source.style.visibility,'visible');assert.equal(verify.created,verify.disposed);assert.equal(document.querySelectorAll('.gambler-summon').length,0);assert.equal(frames.size,0);console.log('PASS wheel before pending capture, selected two IDs, contact once, cancellation, three concurrent, reduced motion, failure and disposal');
}finally{await rm(dir,{recursive:true,force:true});dom.window.close()}
