import assert from 'node:assert/strict';import {build} from 'esbuild';import {JSDOM} from 'jsdom';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';
const dom=new JSDOM('<div id="root"><div id="anchor" data-board-plane="0"></div></div><div id="source" data-card-id="FIRE_MASTER"></div>',{pretendToBeVisual:true});for(const k of ['window','document','HTMLElement','Event','HTMLCanvasElement'])globalThis[k]=dom.window[k];let reduced=false,now=0,next=0;const frames=new Map();globalThis.matchMedia=()=>({matches:reduced});globalThis.performance={now:()=>now};globalThis.innerWidth=1280;globalThis.innerHeight=900;globalThis.DOMMatrix=class{translate(){return this;}scale(){return this;}};globalThis.requestAnimationFrame=f=>{frames.set(++next,f);return next;};globalThis.cancelAnimationFrame=i=>frames.delete(i);HTMLCanvasElement.prototype.getContext=()=>({clearRect(){}});
globalThis.verification={draws:[],created:0,disposed:0,released:0,hold:false,fail:false};const dir=await mkdtemp(path.join(tmpdir(),'mage-test-'));const settle=()=>new Promise(r=>setImmediate(r));const advance=async ms=>{now+=ms;const current=[...frames.values()];frames.clear();current.forEach(f=>f(now));await settle();};
try{await build({entryPoints:['client/src/ui/mageSummon/runtime.ts'],bundle:true,platform:'node',format:'esm',outfile:path.join(dir,'runtime.mjs'),plugins:[{name:'controlled-material',setup(b){b.onResolve({filter:/cardSurface$/},()=>({path:'capture',namespace:'test'}));b.onResolve({filter:/boardProjection$/},()=>({path:'projection',namespace:'test'}));b.onResolve({filter:/^\.\/renderer$/},()=>({path:'renderer',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},a=>({contents:a.path==='capture'?`export async function captureCardSurface(){if(verification.hold)await new Promise(r=>verification.release=r);if(verification.fail)throw Error('Capture failed');return {face:document.createElement('canvas')};}`:a.path==='projection'?`export const boardMatrix=()=>new DOMMatrix(),layoutRect=()=>({left:0,top:0,width:180,height:270});`:`export class Renderer{constructor(selected){if(!selected)throw Error('Only selected meshes in runtime');verification.created++;}drawBoard(c,f,v,ms,m,w,h,r,kind){verification.draws.push({v,ms,kind,mounted:!!document.querySelector('.mage-summon')});}releaseFace(){verification.released++;}dispose(){verification.disposed++;}}`}));}}]});
const {playMageSummon:play,cancelMageSummon:cancel,cancelMageSummons:cancelAll}=await import(path.join(dir,'runtime.mjs'));const source=document.getElementById('source'),anchor=document.getElementById('anchor');let hits=0;
for(const [kind,id]of ['FIRE_MASTER','BLACK_ELSA','BLACK_ALICE'].entries()){source.dataset.cardId=id;source.style.visibility='visible';const p=play(source,{anchor,onImpact:()=>hits++});assert.equal(source.style.visibility,'hidden','Hidden before async work');await settle();const first=verification.draws.at(-1);assert.deepEqual(first,{v:0,ms:0,kind,mounted:false},'Frame zero painted before attachment');assert.equal(document.querySelector('.mage-summon').dataset.visualTime,'360');const before=hits;await advance(2259);assert.equal(hits,before);await advance(1);assert.equal(hits,before+1);await advance(1540);assert.equal(await p,true);assert.equal(source.style.visibility,'visible');assert.equal(source.style.opacity,'');assert.equal(document.querySelector('.mage-summon'),null);}
verification.hold=true;let p=play(source,{anchor});assert.equal(source.style.visibility,'hidden');await settle();assert.equal(document.querySelector('.mage-summon'),null);cancel(source);verification.release();assert.equal(await p,false);await settle();assert.equal(source.style.visibility,'visible');verification.hold=false;
for(const reason of ['abort','root','resize','hidden','detach','pagehide']){const ctrl=new AbortController();p=play(source,{anchor,signal:ctrl.signal});await settle();if(reason==='abort')ctrl.abort();if(reason==='root')cancelAll(document.getElementById('root'));if(reason==='resize'||reason==='pagehide')window.dispatchEvent(new Event(reason));if(reason==='hidden'){Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));}if(reason==='detach'){anchor.remove();await advance(16);}assert.equal(await p,false,reason);assert.equal(source.style.visibility,'visible');Object.defineProperty(document,'hidden',{configurable:true,value:false});document.getElementById('root').append(anchor);}
const other=source.cloneNode();document.body.append(other);const beforeCreated=verification.created,beforeDisposed=verification.disposed;const ps=[play(source,{anchor}),play(other,{anchor})];await settle();assert.equal(verification.created,beforeCreated+1,'Concurrent effects share one GPU renderer');cancel(source);await ps[0];assert.equal(verification.disposed,beforeDisposed);cancel(other);await ps[1];assert.equal(verification.disposed,beforeDisposed+1);other.remove();
const first=play(source);await settle();const second=play(source);await settle();assert.equal(await first,false);assert.equal(source.style.visibility,'hidden');cancelAll();assert.equal(await second,false);assert.equal(source.style.visibility,'visible');
verification.fail=true;const warn=console.warn;console.warn=()=>{};const before=hits;try{assert.equal(await play(source,{onImpact:()=>hits++}),false);}finally{console.warn=warn;}assert.equal(hits,before+1);assert.equal(source.style.visibility,'visible');verification.fail=false;
reduced=true;const count=verification.draws.length;assert.equal(await play(source,{onImpact:()=>hits++}),true);assert.equal(verification.draws.length,count);reduced=false;const ctrl=new AbortController();ctrl.abort();assert.equal(await play(source,{signal:ctrl.signal}),false);source.dataset.cardId='M4';assert.equal(await play(source),false);assert.equal(frames.size,0);assert.equal(verification.created,verification.disposed);assert.equal(document.querySelector('.mage-summon'),null);console.log('PASS selected 01 x3, hidden synchronous, paint-before-mount, contact once, delayed capture, cancellation, shared renderer lifecycle, fallback and reduced motion');
}finally{await rm(dir,{recursive:true,force:true});dom.window.close();}
