import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {build} from 'esbuild';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {pathToFileURL} from 'node:url';
const dir=await mkdtemp(tmpdir()+'/lore-menu-records-');
try{
await build({entryPoints:['client/src/shared/cards.ts','server/src/social.ts'],bundle:true,platform:'node',format:'esm',outdir:dir,outbase:'.'});
const {sanitizeDecks}=await import(pathToFileURL(dir+'/client/src/shared/cards.js'));
const first=sanitizeDecks(null);first.list.forEach((d,i)=>d.name=`  星の書庫 ${i+1}\n `);const saved=sanitizeDecks(JSON.parse(JSON.stringify(first)));assert.deepEqual(saved.list.map(d=>d.name),Array.from({length:5},(_,i)=>`星の書庫 ${i+1}`));assert.deepEqual(sanitizeDecks(null).list.map(d=>d.name),[undefined,undefined,undefined,undefined,undefined]);assert.equal(sanitizeDecks({list:[{name:42},{name:' '.repeat(30)},{name:'星'.repeat(40)}]}).list[2].name.length,24);assert.equal(sanitizeDecks({list:[{name:42}]}).list[0].name,undefined);
const db=new DatabaseSync(':memory:');db.exec(`CREATE TABLE users(id TEXT,display TEXT,avatar TEXT,badge TEXT,stats_public INT,wins INT,losses INT,created_at INT,credits INT,sleeve TEXT,sleeves TEXT);CREATE TABLE matches(id TEXT,player_a TEXT,player_b TEXT,winner TEXT,mode TEXT,turns INT,created_at INT,ended_at INT);INSERT INTO users VALUES('me','Seeker',NULL,NULL,1,1000,1000,1,0,NULL,NULL);INSERT INTO users VALUES('other','Opponent',NULL,NULL,1,0,0,1,0,NULL,NULL);`);
let n=0;const add=(mode,winner,ended=1,a='me',b='other')=>db.prepare('INSERT INTO matches VALUES(?,?,?,?,?,8,?,?)').run(String(n++),a,b,winner,mode,n,ended);
add('ranked','me');add('ranked','other');add('ranked',null);add('online','me');add('online','me');add('online','other');add('tutorial','other');add('ranked','me',null);add('ranked','other',1,'stranger','other');for(let i=0;i<60;i++)add('bot',i%2?'me':'bot',1,'me','bot');
const env={ALLOWED_ORIGIN:'http://localhost',DB:{prepare(sql){let args=[];return{bind(...values){args=values;return this;},async first(){if(sql.includes('ratings'))throw Error('no rating in fixture');if(sql.includes('rewards'))return null;const statement=db.prepare(sql);return statement.get(...args)||null;},async all(){const statement=db.prepare(sql);const bindings=sql.includes('?1')?[Object.fromEntries(args.map((v,i)=>[String(i+1),v]))]:args;return {results:statement.all(...bindings)};}}}}};
const {handleSocial}=await import(pathToFileURL(dir+'/server/src/social.js'));
// Public stats traverse the real route and execute the actual SQL, after the privacy gate.
const get=async()=>{const r=await handleSocial(env,new Request('https://test/api/social/profile?id=me'),'/social/profile',{id:'viewer'});assert.equal(r.status,200);return(await r.json()).profile;};
let p=await get();assert.deepEqual(p.byMode,{ranked:{w:1,l:1},online:{w:2,l:1},bot:{w:30,l:30}});assert.equal(p.recent.filter(m=>m.mode==='ranked').length,3);assert.equal(p.recent.filter(m=>m.mode==='bot').length,40);assert.equal(p.recent.filter(m=>m.mode==='online').length,3);assert(!p.recent.some(m=>m.mode==='tutorial'));assert(!('credits'in p));
db.exec('UPDATE users SET stats_public=0 WHERE id=\'me\'');p=await get();assert.equal(p.private,true);assert(!('byMode'in p));assert(!('recent'in p));db.close();console.log('PASS deck names round-trip/sanitization; real SQLite profile mode totals, 40 records per mode, draw/unfinished/unrelated/tutorial exclusions and privacy');
}finally{await rm(dir,{recursive:true,force:true});}
