import assert from 'node:assert/strict';import {build} from 'esbuild';import {JSDOM} from 'jsdom';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';
const dom=new JSDOM('<div id="root"><div id="anchor" data-board-plane="0"></div></div><div id="source"></div>',{pretendToBeVisual:true});for(const k of ['window','document','HTMLElement','Event','HTMLCanvasElement'])globalThis[k]=dom.window[k];
let reduced=false,now=0,next=0;const frames=new Map();globalThis.matchMedia=()=>({matches:reduced});globalThis.performance={now:()=>now};globalThis.DOMMatrix=class{translate(){return this}scale(){return this}};globalThis.requestAnimationFrame=f=>{frames.set(++next,f);return next};globalThis.cancelAnimationFrame=i=>frames.delete(i);HTMLCanvasElement.prototype.getContext=()=>({drawImage(){},clearRect(){}});
globalThis.innerWidth=1280;globalThis.innerHeight=900;
globalThis.checks={draws:[],created:0,disposed:0,hold:false,fail:false,releaseFace:0};const dir=await mkdtemp(path.join(tmpdir(),'mercenary-summon-'));const settle=async()=>{for(let i=0;i<4;i++)await new Promise(r=>setImmediate(r))};const advance=async ms=>{now+=ms;const callbacks=[...frames.values()];frames.clear();callbacks.forEach(f=>f(now));await settle()};
try{await build({entryPoints:['client/src/ui/mercenarySummon/runtime.ts'],bundle:true,platform:'node',format:'esm',outfile:path.join(dir,'runtime.mjs'),plugins:[{name:'mock-renderer',setup(b){b.onResolve({filter:/cardSurface$/},()=>({path:'capture',namespace:'test'}));b.onResolve({filter:/boardProjection$/},()=>({path:'projection',namespace:'test'}));b.onResolve({filter:/^\.\/renderer$/},()=>({path:'renderer',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},a=>({contents:a.path==='capture'?`export async function captureCardSurface(){if(checks.hold)await new Promise(r=>checks.release=r);if(checks.fail)throw Error('capture failed');return{face:document.createElement('canvas')}}`:a.path==='projection'?`const m={scale(){return this},translate(){return this},toString(){return 'matrix(1,0,0,1,0,0)'}};export const boardMatrix=()=>m,projectedPlacement=()=>m,layoutRect=()=>({left:0,top:0,width:180,height:270});`:`export class Renderer{constructor(){checks.created++;this.ready=checks.loading?new Promise(r=>checks.loaded=r):Promise.resolve();}drawBoard(c,f,v,t){if(checks.drawFail)throw Error('draw failed');checks.draws.push({h:this.tier,v,t})}releaseFace(){checks.releaseFace++}dispose(){checks.disposed++}}`}));}}]});
const {playMercenarySummon:play,cancelMercenarySummon:cancel,cancelMercenarySummons:all}=await import(path.join(dir,'runtime.mjs'));const source=document.getElementById('source'),anchor=document.getElementById('anchor');let impacts=0;
for(const [h,id]of ['MERCENARY','MERC_LEADER','MERC_MASTER'].entries()){source.dataset.cardId=id;source.style.visibility='visible';const p=play(source,{anchor,onImpact:()=>impacts++});assert.equal(source.style.visibility,'hidden','hide before any await');await settle();assert.equal(checks.draws.at(-1).t,0,'first drawn frame is zero');assert.equal(document.querySelector('.mercenary-summon').dataset.variant,'2');assert.equal(source.style.visibility,'hidden');const before=impacts;await advance(1669);assert.equal(impacts,before);await advance(1);assert.equal(impacts,before+1);await advance(2000);assert.equal(await p,true);assert.equal(source.style.visibility,'visible');assert.equal(impacts,before+1);assert(checks.draws.some(d=>d.h===h&&d.v===1));}
for(const why of ['single','root','abort','resize','hidden','disconnect','pagehide']){const ac=new AbortController(),p=play(source,{anchor,signal:ac.signal});await settle();if(why==='single')cancel(source);if(why==='root')all(document.getElementById('root'));if(why==='abort')ac.abort();if(why==='resize'||why==='pagehide')window.dispatchEvent(new Event(why));if(why==='hidden'){Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'))}if(why==='disconnect'){anchor.remove();await advance(40)}assert.equal(await p,false,why);assert.equal(source.style.visibility,'visible');Object.defineProperty(document,'hidden',{configurable:true,value:false});document.getElementById('root').append(anchor);}
checks.hold=true;const pending=play(source);await settle();cancel(source);checks.release();await settle();assert.equal(await pending,false);checks.hold=false;
const first=play(source);await settle();const second=play(source);await settle();assert.equal(await first,false);cancel(source);assert.equal(await second,false);assert.equal(source.style.visibility,'visible');
const other=source.cloneNode();other.id='other';document.body.append(other);const created=checks.created;const multi=[play(source,{anchor}),play(other,{anchor})];await settle();assert.equal(checks.created,created+1,'GPU renderer is shared');all();assert.deepEqual(await Promise.all(multi),[false,false]);other.remove();
reduced=true;assert.equal(await play(source,{onImpact:()=>impacts++}),true);reduced=false;const ac=new AbortController();ac.abort();assert.equal(await play(source,{signal:ac.signal}),false);source.dataset.cardId='ELF';assert.equal(await play(source),false);source.dataset.cardId='MERCENARY';
const warn=console.warn;console.warn=()=>{};for(const field of ['fail','drawFail']){checks[field]=true;const before=impacts,p=play(source,{onImpact:()=>impacts++});await settle();assert.equal(await p,false);assert.equal(impacts,before+1);assert.equal(source.style.visibility,'visible');checks[field]=false;}console.warn=warn;
assert.equal(frames.size,0);assert.equal(document.querySelectorAll('.mercenary-summon').length,0);assert.equal(checks.created,checks.disposed);console.log('PASS mercenary 02: all three routes, contact once, shared GPU, cancellation, pending capture, replacement, reduced, fallback, cleanup');
}finally{await rm(dir,{recursive:true,force:true});dom.window.close()}
