import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {JSDOM} from 'jsdom';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
const dom=new JSDOM('',{url:'http://localhost',pretendToBeVisual:true});
for(const key of ['window','document','localStorage'])Object.defineProperty(globalThis,key,{value:dom.window[key],configurable:true});
let hidden=false,reduced=false,id=0;
Object.defineProperty(document,'hidden',{get:()=>hidden});
globalThis.matchMedia=()=>({get matches(){return reduced;}});
dom.window.devicePixelRatio=2;
const frames=new Map(),timers=new Map();
globalThis.requestAnimationFrame=cb=>{frames.set(++id,cb);return id;};
globalThis.cancelAnimationFrame=n=>frames.delete(n);
const nativeSet=globalThis.setTimeout,nativeClear=globalThis.clearTimeout;
globalThis.setTimeout=(cb,ms,...args)=>{if(ms!==2420)return nativeSet(cb,ms,...args);timers.set(++id,cb);return id;};
globalThis.clearTimeout=n=>{if(!timers.delete(n))nativeClear(n);};
let dimensions={width:1168,height:720},transforms=[],text=[];
dom.window.HTMLCanvasElement.prototype.getBoundingClientRect=()=>dimensions;
const gradient={addColorStop(){}};
const context=new Proxy({globalAlpha:1,measureText:s=>({width:s.length*6}),createLinearGradient:()=>gradient,createRadialGradient:()=>gradient,setTransform:(...a)=>transforms.push(a),fillText:s=>text.push(s)},{get:(obj,key)=>key in obj?obj[key]:()=>{}});
dom.window.HTMLCanvasElement.prototype.getContext=()=>context;
const temp=await mkdtemp(path.join(tmpdir(),'lore-turn-'));
try{
 await build({stdin:{contents:"export * from './client/src/ui/turnBanner';export {setLang} from './client/src/i18n';export {turnBanner,setFxSkip} from './client/src/ui/anim';",resolveDir:process.cwd()},bundle:true,format:'esm',platform:'node',outfile:path.join(temp,'entry.mjs'),plugins:[{name:'dom-monster',setup(b){b.onResolve({filter:/monster\/runtime$/},()=>({path:'monster',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:'export const syncMonsterStates=()=>{},clearMonsterStates=()=>{},setMonsterSkip=()=>{},monsterRect=()=>null,playMonster=async()=>false;',loader:'js'}));}}]});
 const {mountTurnBanner,cancelTurnBanner,setLang,turnBanner,setFxSkip}=await import(path.join(temp,'entry.mjs'));
 frames.clear();timers.clear();
 const count=()=>document.querySelectorAll('.fx-turn-sigil').length;
 const tick=delta=>{const callbacks=[...frames.values()];frames.clear();callbacks.forEach(f=>f(performance.now()+delta));};
 const clean=()=>{assert.equal(count(),0);assert.equal(frames.size,0);assert.equal(timers.size,0);};
 setLang('ja');mountTurnBanner(true,6);const first=document.querySelector('canvas');
 assert.match(document.querySelector('[role=status]').getAttribute('aria-label'),/あなたのターンです TURN 6/);
 tick(420);assert(text.includes('あなたのターンです'));assert.equal(first.width,2336);
 dimensions={width:350,height:600};tick(800);assert.equal(first.width,700);
 mountTurnBanner(false,17);assert.equal(count(),1);assert.equal(first.width,0);
 assert.match(document.querySelector('[role=status]').getAttribute('aria-label'),/相手のターンです TURN 17/);
 tick(1900);tick(2330);clean();
 reduced=true;mountTurnBanner(true);tick(1000);assert.equal(count(),1);cancelTurnBanner();cancelTurnBanner();clean();
 mountTurnBanner(true);document.querySelector('.fx-turn-sigil').remove();tick(10);clean();
 mountTurnBanner(true);hidden=true;document.dispatchEvent(new dom.window.Event('visibilitychange'));clean();mountTurnBanner(false);clean();hidden=false;
 mountTurnBanner(true);window.dispatchEvent(new dom.window.Event('pagehide'));clean();
 mountTurnBanner(false);for(const f of [...timers.values()])f();clean();
 setFxSkip(false);turnBanner(true,8);assert.equal(count(),1);setFxSkip(true);clean();turnBanner(false,9);clean();setFxSkip(false);
 console.log('PASS turn banner: both sides, labels, replacement, resize, reduced motion, expiry, external removal, hidden/pagehide and resource cleanup');
}finally{globalThis.setTimeout=nativeSet;globalThis.clearTimeout=nativeClear;dom.window.close();await rm(temp,{recursive:true,force:true});}
