import {THEMES,asset} from './themes';
/** A controlled resolution experiment. Art, layout, thickness and materials
 * remain identical; only the two scene renderers' raster budget changes. */
export function mountAudit(){
 const q=new URLSearchParams(location.search);let theme=THEMES.find(t=>t.id===q.get('set'))??THEMES[5],quality='current',side='self';
 document.body.innerHTML=`<main><p class="eyebrow">LORE · COSMETIC QUALITY AUDIT</p><h1>画質と、装備の存在感を分けて確認</h1><p>画像・素材・厚み・カメラは同じ。下の比較で変わるのは盤面の描画解像度だけです。</p><div class="tools"><label>セット <select id="theme">${THEMES.map(t=>`<option value="${t.id}" ${t===theme?'selected':''}>${t.name}</option>`).join('')}</select></label><label>装着者 <select id="side"><option value="self">自分</option><option value="opponent">相手</option></select></label><label>盤面サイズ <select id="size"><option value="595x540">現在のパネル相当 595×540</option><option value="1280x720">1280×720</option><option value="1920x1080">1920×1080</option></select></label></div><div class="tools"><button data-quality="current" aria-pressed="true">以前の描画上限</button><button data-quality="native" aria-pressed="false">画面密度に合わせる（上限2倍）</button><button id="pause" aria-pressed="false">素材の動きを停止</button></div><p id="metrics" role="status">盤面を準備中…</p><p class="note">比較は厚み1倍・8枚に固定。高密度側は検証用で、通常対戦は画面密度に合わせ、静止盤面を最大600万画素に制限します。大きい盤面は横にスクロールできます。</p><div class="viewport"><iframe id="audit-board" title="描画解像度の比較"></iframe></div><h2>原画が実寸でどれだけ読めるか</h2><p>左から48px・96px・240px。これは原画の縮小表示で、盤面の描画結果ではありません。</p><div id="art-row"></div><h2>今回の品質判定</h2><p><strong>素材・外装・ドローへの接続を改修済み。</strong>このページでは改修後の素材を固定し、解像度だけを比較できます。</p><p>各セットの見た目と操作中の表現はスタジオで比較できます。見た目の承認と動作確認は別に扱います。</p><a href="/cosmetic-studio.html?set=tidal&side=self&thickness=1">演出を再生できるスタジオへ</a></main>`;
 const style=document.createElement('style');style.textContent=`*{box-sizing:border-box}body{margin:0;background:#101923;color:#e4e9ea;font:14px/1.7 system-ui}main{max-width:1500px;padding:28px;margin:auto}h1{font-size:25px;font-weight:500}h2{font-size:19px;font-weight:500;margin-top:30px}.eyebrow{font-size:10px;letter-spacing:.18em;color:#9db5bf}.tools{display:flex;gap:12px;flex-wrap:wrap;margin:14px 0}select,button{font:inherit;font-size:12px;color:inherit;background:#1d2a36;border:1px solid #71818e;padding:9px}button{cursor:pointer}button[aria-pressed=true]{border-color:#e5cfa4;background:#3b4146}.note,#metrics{font-size:12px;color:#aebfcb}.viewport{overflow:auto;border:1px solid #566572;background:#16212b}iframe{display:block;border:0;width:595px;height:540px}#art-row{display:flex;align-items:flex-end;gap:24px;flex-wrap:wrap}#art-row img{display:block;height:auto}a{color:#b5d8eb}button:focus-visible,select:focus-visible{outline:2px solid #fff;outline-offset:3px}`;document.head.append(style);
 const frame=document.querySelector<HTMLIFrameElement>('#audit-board')!,metric=document.querySelector<HTMLElement>('#metrics')!;let ready=false,paused=false;
 const state=()=>frame.contentWindow?.postMessage({type:'atelier-state',state:{set:theme.id,side,motion:!paused,count:8,dense:false}},location.origin);
 const load=()=>{const pause=document.querySelector<HTMLButtonElement>('#pause')!;pause.disabled=!theme.motion;pause.textContent=theme.motion?(paused?'素材の動きを再開':'素材の動きを停止'):'静止セット';ready=false;metric.textContent='盤面を準備中…';frame.src=`/cosmetic-studio.html?board=1&polish=1&set=${theme.id}&side=${side}&thickness=1&auditQuality=${quality}`;document.querySelector('#art-row')!.innerHTML=[48,96,240].map(w=>`<figure style="margin:0"><img alt="${theme.name} ${w}px" src="${asset(theme,'back.webp')}" width="${w}"><figcaption>${w}px</figcaption></figure>`).join('');};
 document.querySelector<HTMLSelectElement>('#theme')!.onchange=e=>{theme=THEMES.find(t=>t.id===(e.target as HTMLSelectElement).value)!;load();};
 document.querySelector<HTMLSelectElement>('#side')!.onchange=e=>{side=(e.target as HTMLSelectElement).value;load();};
 document.querySelector<HTMLSelectElement>('#size')!.onchange=e=>{const [w,h]=(e.target as HTMLSelectElement).value.split('x');frame.style.width=w+'px';frame.style.height=h+'px';};
 document.querySelectorAll<HTMLButtonElement>('[data-quality]').forEach(b=>b.onclick=()=>{quality=b.dataset.quality!;document.querySelectorAll<HTMLElement>('[data-quality]').forEach(e=>e.setAttribute('aria-pressed',String(e.dataset.quality===quality)));load();});
 document.querySelector<HTMLButtonElement>('#pause')!.onclick=e=>{paused=!paused;const b=e.currentTarget as HTMLButtonElement;b.setAttribute('aria-pressed',String(paused));b.textContent=paused?'素材の動きを再開':'素材の動きを停止';if(ready)state();};
 const onMessage=(e:MessageEvent)=>{if(e.source===frame.contentWindow&&e.origin===location.origin&&e.data?.type==='atelier-ready'){ready=true;state();}};addEventListener('message',onMessage);
 const poll=setInterval(()=>{if(!ready)return;const doc=frame.contentDocument,c=doc?.querySelector<HTMLCanvasElement>('.duel-objects-3d'),deck=doc?.querySelector<HTMLElement>('#pile-myDeck');if(!c)return;const cr=c.getBoundingClientRect(),dr=deck?.getBoundingClientRect();metric.textContent=`描画 ${c.width}×${c.height} / 表示 ${Math.round(cr.width)}×${Math.round(cr.height)} / DPR ${devicePixelRatio} / 描画倍率 ${(c.width/cr.width).toFixed(2)} / 自分デッキ置き場 ${dr?.width.toFixed(1)}×${dr?.height.toFixed(1)}px`;},500);
 addEventListener('pagehide',()=>{clearInterval(poll);removeEventListener('message',onMessage);},{once:true});load();
}
