import * as T from 'three';import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';import {RoomEnvironment} from 'three/examples/jsm/environments/RoomEnvironment.js';import {loadLibraryAssets} from '../../ui/libraryAssets';import {makePile} from '../../ui/pileModels';import {createAtelierMaterials} from './materials';import {THEMES} from './themes';import type {StudioState} from './board';
export async function mountInspection(){
 document.body.innerHTML='<div id="inspection"></div><div class="labels"><span>DECK HOLDER</span><span>SHELF</span></div><p class="hint">ドラッグで回転 · スクロールで拡大 · カードを外した仕上げ</p>';
 const style=document.createElement('style');style.textContent='html,body{margin:0;overflow:hidden;background:#131e27;color:#d7dee0;font:10px sans-serif}canvas{display:block}.labels{position:fixed;bottom:50px;left:0;right:0;display:flex;justify-content:space-around;letter-spacing:.22em;pointer-events:none}.hint{position:fixed;bottom:13px;left:0;right:0;text-align:center;font-size:10px;color:#a4b7c4;pointer-events:none}';document.head.append(style);
 const root=document.getElementById('inspection')!,renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.toneMapping=T.AgXToneMapping;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;root.append(renderer.domElement);
 const scene=new T.Scene();scene.background=new T.Color('#18232d');const camera=new T.PerspectiveCamera(34,innerWidth/innerHeight,.01,100);camera.position.set(0,4,4.8);
 const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,0,0);controls.enablePan=false;controls.minDistance=3;controls.maxDistance=12;controls.maxPolarAngle=Math.PI*.44;controls.update();
 const pmrem=new T.PMREMGenerator(renderer),room=new RoomEnvironment(),environment=pmrem.fromScene(room,.04);room.dispose();pmrem.dispose();scene.environment=environment.texture;scene.environmentIntensity=.65;
 const key=new T.DirectionalLight(0xfff0db,2.6);key.position.set(-3,6,4);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-4;key.shadow.camera.right=4;key.shadow.camera.top=4;key.shadow.camera.bottom=-4;key.shadow.normalBias=.008;scene.add(key);const fill=new T.DirectionalLight(0xbcd5ff,.9);fill.position.set(4,3,-3);scene.add(fill);
 const floor=new T.Mesh(new T.PlaneGeometry(200,200),new T.MeshStandardMaterial({color:'#18232d',roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=-.005;floor.receiveShadow=true;scene.add(floor);
 const materials=createAtelierMaterials();let disposed=false,dirty=true,rebuildNeeded=true,frame=0,last=0;let objects:T.Object3D[]=[],cleanups:Array<()=>void>=[];
 const disposeObject=(o:T.Object3D)=>{o.traverse(n=>{if(n instanceof T.Mesh){n.geometry.dispose();(Array.isArray(n.material)?n.material:[n.material]).forEach(m=>m.dispose());}});scene.remove(o);};
 const assets=loadLibraryAssets(()=>{dirty=true;rebuildNeeded=true;});const empty=new T.Texture();
 const q=new URLSearchParams(location.search);let state:StudioState={set:q.get('set')??'nocturne',side:q.get('side')==='both'?'both':q.get('side')==='opponent'?'opponent':'self',motion:true,count:0,dense:false};let epoch=0;
 async function apply(next:StudioState){const n=++epoch;await materials.select(THEMES.find(t=>t.id===next.set)??null,next.side);if(disposed||n!==epoch)return;state={...next,time:undefined};materials.setMotion(next.motion);if(next.time!==undefined)materials.seek(next.time);dirty=true;rebuildNeeded=true;}
 function rebuild(){cleanups.forEach(f=>f());cleanups=[];objects.forEach(disposeObject);objects=[];
  for(const [i,kind]of(['deck','shelf']as const).entries()){const model=assets.clone(kind);if(!model)continue;const el=document.createElement('div');el.id=`pile-${state.side==='opponent'?'opp':'my'}${kind==='deck'?'Deck':'Disc'}`;el.className='pile pile--'+kind;materials.applyFurniture(model,el);const pile=makePile(0,kind==='shelf',empty,undefined,model);pile.group.position.x=i?1.15:-1.15;scene.add(pile.group);pile.group.updateMatrixWorld(true);objects.push(pile.group);cleanups.push(materials.decoratePile(pile,el));}
 }
 controls.addEventListener('change',()=>{dirty=true;});const resize=()=>{renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();dirty=true;};window.addEventListener('resize',resize);
 const message=(e:MessageEvent)=>{if(e.origin!==location.origin||e.source!==parent||e.data?.type!=='atelier-state')return;const s=e.data.state;if(s&&['default',...THEMES.map(t=>t.id)].includes(s.set)&&['self','opponent','both'].includes(s.side))void apply({...s,count:0});};window.addEventListener('message',message);
 await apply(state);parent.postMessage({type:'atelier-ready'},location.origin);
 function tick(now:number){if(disposed)return;frame=requestAnimationFrame(tick);if(document.hidden||now-last<24)return;last=now;const animated=materials.tick(now);if(rebuildNeeded){rebuild();rebuildNeeded=false;dirty=true;}if(animated||dirty){dirty=false;renderer.autoClear=true;renderer.render(scene,camera);renderer.autoClear=false;materials.render(renderer,camera);}if(assets.settled)root.dataset.ready='true';}
 frame=requestAnimationFrame(tick);Object.assign(window,{atelier:{apply,info:()=>materials.info(),state:()=>state}});
 window.addEventListener('pagehide',()=>{disposed=true;epoch++;cancelAnimationFrame(frame);window.removeEventListener('resize',resize);window.removeEventListener('message',message);controls.dispose();cleanups.forEach(f=>f());objects.forEach(disposeObject);disposeObject(floor);materials.dispose();assets.dispose();empty.dispose();environment.dispose();key.shadow.dispose();renderer.dispose();renderer.forceContextLoss();},{once:true});
}
