import './studio.css';
import {rows,sources,status,available,recipes,definitions,url,outcomes,directions,fixed,cardStatus} from './catalog';
import {cardName,setLang} from '../../../i18n';
setLang('ja');
const q=new URLSearchParams(location.search);let item=q.get('item')||'S07',card=q.get('card')||'MIMIC';
document.body.innerHTML=`<div class="d3-studio"><aside><small>R3 全担当制作 / 品質未承認</small><h1>Dの演出一覧</h1><p>5シリーズ・27効果＋既定リフト2接続。R1は不採用。</p><nav id="items"></nav><a href="?r2=1">R2 腐敗の比較履歴</a></aside><section class="d3-work"><header><div><h2 id="title"></h2><p id="note"></p></div><div class="d3-controls"><select id="card" aria-label="対象カード"></select><select id="variant" aria-label="演出案"><option value="1">①</option><option value="2">②</option></select><select id="side" aria-label="自分・相手"><option value="0">自分</option><option value="1">相手</option></select><select id="outcome" aria-label="結果"><option value="hit">成功・報酬</option><option value="miss">ハズレ・敵召喚</option><option value="heal">回復</option></select><button id="play">再生</button><button id="pause">停止</button><button id="reset">リセット</button><button id="retry">読み直す</button><select id="speed" aria-label="速度"><option value="1">1倍</option><option value="0.5">0.5倍</option><option value="0.25">0.25倍</option></select><label><input type="checkbox" id="loop">ループ</label><label><input type="checkbox" id="reduced">動きを減らす</label><select id="background" aria-label="盤面背景"><option value="light">白い盤面</option><option value="dark">暗い盤面</option></select></div></header><div id="stage"></div><footer><input type="range" id="seek" min="0" max="4200" value="0" aria-label="材質の時刻"><span id="time">0.00 s</span><p id="phase">準備中</p><small>実GameView / 現行reduceで計算した固定条件の試作。オンライン対戦ではありません。</small></footer></section></div>`;
const el=(id:string)=>document.getElementById(id)!;let frame:HTMLIFrameElement|null=null;let loadingTimer=0;
function setReady(ready:boolean,message:string){for(const id of ['play','pause','reset','seek'])(el(id)as HTMLButtonElement).disabled=!ready;el('phase').textContent=message;el('stage').classList.toggle('d3-loading',!ready&&!!frame);let hint=el('stage').querySelector<HTMLDivElement>('.d3-load-hint');if(!ready&&frame){if(!hint){hint=document.createElement('div');hint.className='d3-load-hint';hint.setAttribute('role','status');el('stage').append(hint);}hint.textContent=message;}else hint?.remove();if(ready)window.clearTimeout(loadingTimer);}
function beginLoading(){window.clearTimeout(loadingTimer);setReady(false,'盤面とカード画像を読み込み中…');loadingTimer=window.setTimeout(()=>setReady(false,'読み込みに時間がかかっています。「読み直す」で再試行できます。'),45000);}
el('items').innerHTML=rows.map(r=>`<a href="${url(r.id,sources(r.id)[0]||'',1)}" data-id="${r.id}"><strong>${r.id} ${r.name}</strong><span>${status(r.id)}</span></a>`).join('');
function send(command:string,extra:Record<string,unknown>={}){frame?.contentWindow?.postMessage({kind:'d3',command,...extra},location.origin);}
function configure(){const results=outcomes(item,card);el('outcome').innerHTML=results.map(([v,label])=>`<option value="${v}">${label}</option>`).join('');const recipe=recipes[card];el('title').textContent=`${item} ${rows.find(r=>r.id===item)?.name||''}`;el('note').textContent=recipe?.note||'未制作。完成した別項目の演出へ置き換えて再生することはありません。';const s=el('variant') as HTMLSelectElement;const chosen=s.value;s.innerHTML=directions(item,card).map((label,i)=>`<option value="${i+1}">${fixed(item)?'':i===0?'①':'②'} ${label}</option>`).join('');s.value=fixed(item)?'1':chosen||'1';const enabled=available(item,card);el('stage').innerHTML=enabled?'<iframe title="実盤面" id="board" src="?revision=3&board=1"></iframe>':'<div class="d3-empty">この項目は未制作です。左の一覧に全担当範囲を残しています。</div>';frame=el('stage').querySelector('iframe');if(enabled)beginLoading();else{window.clearTimeout(loadingTimer);setReady(false,'この項目は未制作です。');}history.replaceState(null,'',url(item,card,+s.value));el('items').querySelectorAll('a').forEach(a=>a.classList.toggle('active',a.dataset.id===item));}
function setup(){if(!frame)return;beginLoading();send('setup',{item,card,variant:+(el('variant')as HTMLSelectElement).value,side:+(el('side')as HTMLSelectElement).value,outcome:(el('outcome')as HTMLSelectElement).value,reduced:(el('reduced')as HTMLInputElement).checked,background:(el('background')as HTMLSelectElement).value});}
function cardOptions(){el('card').innerHTML=sources(item).map(id=>`<option value="${id}">${definitions[id]?cardName({...definitions[id],uid:id}):id} — ${available(item,id)?cardStatus(item,id):'未制作'}</option>`).join('');if(!sources(item).includes(card))card=sources(item)[0]||'';(el('card')as HTMLSelectElement).value=card;}
el('items').querySelectorAll<HTMLAnchorElement>('a').forEach(a=>a.onclick=e=>{e.preventDefault();item=a.dataset.id!;card=sources(item)[0]||'';cardOptions();configure();});
(el('variant')as HTMLSelectElement).value=q.get('variant')||'1';
el('card').onchange=()=>{card=(el('card')as HTMLSelectElement).value;configure();};
for(const id of ['variant','side','outcome','reduced','background'])el(id).onchange=()=>{setup();history.replaceState(null,'',url(item,card,+(el('variant')as HTMLSelectElement).value));};
for(const id of ['play','pause','reset'])el(id).onclick=()=>send(id);
el('retry').onclick=()=>configure();
el('seek').oninput=()=>send('seek',{time:+(el('seek')as HTMLInputElement).value});
for(const id of ['speed','loop'])el(id).onchange=()=>send('options',{speed:+(el('speed')as HTMLSelectElement).value,loop:(el('loop')as HTMLInputElement).checked});
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==frame?.contentWindow||e.data?.kind!=='d3-status')return;if(e.data.boot)setup();if(e.data.busy!=null){for(const element of document.querySelectorAll<HTMLButtonElement|HTMLSelectElement|HTMLInputElement>('.d3-controls button,.d3-controls select,.d3-controls input,#seek'))element.disabled=e.data.busy&&!['pause','reset'].includes(element.id);el('items').style.pointerEvents=e.data.busy?'none':'';}if(e.data.ready){setReady(true,e.data.phase||'準備完了');send('options',{speed:+(el('speed')as HTMLSelectElement).value,loop:(el('loop')as HTMLInputElement).checked});}if(e.data.error){window.clearTimeout(loadingTimer);setReady(false,`読み込めませんでした。「読み直す」で再試行してください。 ${e.data.error}`);}if(e.data.duration)(el('seek')as HTMLInputElement).max=String(e.data.duration);if(e.data.time!=null){(el('seek')as HTMLInputElement).value=String(e.data.time);el('time').textContent=(e.data.time/1000).toFixed(2)+' s';}if(e.data.phase)el('phase').textContent=e.data.phase;});
cardOptions();configure();
