// Flavor-name pass for cards whose original names read like effect labels or
// generated templates. IDs and effects remain unchanged.
export const FLAVOR_CARD_NAMES = {
    // Core spells
    S1: { ko: "삼격의 불씨", ja: "三撃の火種", en: "Spark of the Third Strike" },
    S10: { ko: "청람 서고", ja: "青藍の書庫", en: "Cobalt Archive" },
    S3: { ko: "칼날의 속삭임", ja: "刃の囁き", en: "Whisper to the Blade" },
    S4: { ko: "쌍월의 계시", ja: "双月の啓示", en: "Twin-Moon Revelation" },
    S6: { ko: "운명색인", ja: "運命索引", en: "Index of Fate" },
    S7: { ko: "전장의 맥동", ja: "戦場の脈動", en: "Pulse of the Battlefield" },
    S11: { ko: "잿빛 혜성", ja: "灰色彗星", en: "Ashen Comet" },
    S12: { ko: "강철맥 각인", ja: "鋼脈刻印", en: "Steelvein Inscription" },
    S13: { ko: "별무덤 낙하", ja: "星墓の落下", en: "Fall of the Star-Tomb" },
    SX2: { ko: "봉인의 실밥", ja: "封印の綻び", en: "Loose Thread of the Seal" },
    SX4: { ko: "두 번째 열쇠", ja: "第二の鍵", en: "The Second Key" },
    SX6: { ko: "매복망 대붕락", ja: "伏兵網大崩落", en: "Grand Collapse of the Ambush Web" },
    HANDRESET: { ko: "망각의 새 패", ja: "忘却の新札", en: "New Hand of Oblivion" },
    GAMBLE: { ko: "육면의 변덕", ja: "六面の気まぐれ", en: "Six-Faced Whim" },
    FLAME: { ko: "불씨의 채무", ja: "火種の負債", en: "Ember Debt" },
    NEGOTIATE: { ko: "검은 봉인의 거래", ja: "黒封印の取引", en: "Bargain of the Black Seal" },
    DISARM1: { ko: "첫 나사 뽑기", ja: "最初の螺子抜き", en: "The First Loose Screw" },
    DISARM2: { ko: "청동 해부도", ja: "青銅解剖図", en: "Brass Dissection" },
    // Core traps
    T1: { ko: "반월 방진", ja: "半月防陣", en: "Half-Moon Ward" },
    T8: { ko: "철가시 매복진", ja: "鉄棘伏兵陣", en: "Ironthorn Ambush" },
    T2: { ko: "무언결계", ja: "無言結界", en: "Wordless Field" },
    T3: { ko: "왕묘의 낙혈", ja: "王墓の落穴", en: "Royal Tomb Sinkhole" },
    T6: { ko: "되받는 뇌광", ja: "返しの雷光", en: "Rebounding Thunder" },
    T9: { ko: "심해의 역조", ja: "深海の逆潮", en: "Abyssal Undertow" },
    T4: { ko: "거울가시 심판", ja: "鏡棘の審判", en: "Judgment of Mirror Thorns" },
    T11: { ko: "찰나의 약탈", ja: "刹那の略奪", en: "Plundered Moment" },
    T12: { ko: "칠중 청동성벽", ja: "七重青銅城壁", en: "Sevenfold Bronze Rampart" },
    T13: { ko: "성흔의 낙뢰", ja: "聖痕の落雷", en: "Stigmata Thunderfall" },
    // Generated spell/trap series: replace template names with one-off titles.
    GS5_0: { ko: "빙점의 역화", ja: "氷点の逆火", en: "Flashfire at Freezing Point" },
    GS5_1: { ko: "폭풍눈의 동결", ja: "嵐眼の凍結", en: "Eye of the Frozen Storm" },
    GS5_2: { ko: "황금맥의 생명등", ja: "黄金脈の生命灯", en: "Lifewick of the Golden Vein" },
    GS5_3: { ko: "저주문서 독해", ja: "呪文書の解読", en: "Reading the Cursed Codex" },
    GS5_4: { ko: "성검의 한 획", ja: "聖剣の一閃", en: "Stroke of the Hallowed Blade" },
    GT5_0: { ko: "그림자 대역진", ja: "影の身代わり陣", en: "Shadow Decoy Array" },
    GT5_1: { ko: "용암문 폐쇄", ja: "溶岩門封鎖", en: "Sealing the Magma Gate" },
    GT5_2: { ko: "창공경의 역광", ja: "蒼天鏡の返光", en: "Skyglass Reversal" },
    GT5_3: { ko: "혈맥 역류진", ja: "血脈逆流陣", en: "Bloodvein Reversal" },
    GT5_4: { ko: "비취아귀", ja: "翡翠の顎", en: "Jade Maw" },
    GS6_0: { ko: "균열심장 폭발", ja: "亀裂心臓の爆発", en: "Riftheart Detonation" },
    GS6_1: { ko: "고대빙고의 개방", ja: "古代氷庫の開放", en: "Opening the Elder Ice Vault" },
    GS6_2: { ko: "심연샘의 맥동", ja: "深淵泉の脈動", en: "Pulse of the Abyssal Well" },
    GS6_3: { ko: "철서고의 계시", ja: "鉄書庫の啓示", en: "Revelation of the Iron Archive" },
    GS6_4: { ko: "화맥 점화", ja: "火脈点火", en: "Ignition of the Firevein" },
    GS6_5: { ko: "백상 행군령", ja: "白霜進軍令", en: "Whitefrost Marching Order" },
    GT6_0: { ko: "폭풍피뢰진", ja: "嵐避雷陣", en: "Storm-Lure Array" },
    GT6_1: { ko: "황금성문", ja: "黄金城門", en: "Gates of Aurum" },
    GT6_2: { ko: "저주거울의 흉조", ja: "呪鏡の凶兆", en: "Omen of the Hexed Mirror" },
    GT6_3: { ko: "성역의 단죄선", ja: "聖域の断罪線", en: "Sanctum's Execution Line" },
    GT6_4: { ko: "무영의 아귀", ja: "無影の顎", en: "Maw Without Shadow" },
    GT6_5: { ko: "용암재판", ja: "溶岩裁判", en: "Trial by Magma" },
    GS7_0: { ko: "태양창 파열", ja: "太陽槍破裂", en: "Sunlance Rupture" },
    GS7_1: { ko: "태초빙핵의 개안", ja: "太初氷核の開眼", en: "Awakening of the First Ice" },
    GS7_2: { ko: "무한생명륜", ja: "無限生命輪", en: "Wheel of Endless Life" },
    GS7_3: { ko: "공허서고 개문", ja: "虚空書庫開門", en: "Opening the Void Archive" },
    GS7_4: { ko: "붕괴선 각인", ja: "崩壊線刻印", en: "Engraving the Faultline" },
    GS7_5: { ko: "선조군단의 기상", ja: "祖霊軍団の蜂起", en: "Rising of the Ancestor Host" },
    GS8_0: { ko: "은월포", ja: "銀月砲", en: "Silvermoon Cannon" },
    GS8_1: { ko: "종말빙옥", ja: "終末氷獄", en: "Rime Prison of the End" },
    GS8_2: { ko: "여명성배의 범람", ja: "黎明聖杯の氾濫", en: "Overflow of the Dawn Grail" },
    GS8_3: { ko: "칠흑재판록", ja: "漆黒裁判録", en: "Black Ledger of Judgment" },
    GS8_4: { ko: "광휘검진", ja: "光輝剣陣", en: "Radiant Blade Array" },
    GS8_5: { ko: "태초군문 개방", ja: "太初軍門開放", en: "Opening the First War-Gate" },
    GT8_0: { ko: "무한성벽의 맹세", ja: "無限城壁の誓い", en: "Oath of the Endless Rampart" },
    GT8_1: { ko: "공허막의 침식", ja: "虚空幕の侵蝕", en: "Erosion of the Void Curtain" },
    GT8_2: { ko: "파경의 붕락", ja: "破鏡の崩落", en: "Collapse of the Shattered Mirror" },
    GT8_3: { ko: "고대왕의 되갚음", ja: "古王の報復", en: "Reprisal of the Elder King" },
    GT8_5: { ko: "강철낙인 처형", ja: "鋼鉄烙印の処刑", en: "Execution by Iron Brand" },
    GS9_0: { ko: "성창낙일", ja: "聖槍落日", en: "Hallowed Spearfall" },
    GS9_1: { ko: "그림자빙하 매장", ja: "影氷河の埋葬", en: "Burial Beneath the Shadow Glacier" },
    GS9_2: { ko: "용암성배의 세례", ja: "溶岩聖杯の洗礼", en: "Baptism of the Magma Grail" },
    GS9_3: { ko: "천공기록 강림", ja: "天空記録の降臨", en: "Descent of the Sky Archive" },
    GT9_2: { ko: "흑요경의 복수", ja: "黒曜鏡の復讐", en: "Vengeance of the Obsidian Mirror" },
    GT9_3: { ko: "은형의 처단", ja: "銀影の処断", en: "Silver Shade Execution" },
    GS10_0: { ko: "무한성의 포효", ja: "無限星の咆哮", en: "Roar of the Infinite Star" },
    GS10_1: { ko: "공허빙점 침식", ja: "虚空氷点の侵蝕", en: "Voidfrost Encroachment" },
    GS10_2: { ko: "붕괴성배의 기적", ja: "崩壊聖杯の奇跡", en: "Miracle of the Broken Grail" },
    GS10_3: { ko: "고대왕립서고", ja: "古代王立書庫", en: "The Elder Royal Archive" },
    GT10_0: { ko: "심연의 반월진", ja: "深淵の半月陣", en: "Abyssal Half-Moon Array" },
    GT10_1: { ko: "철왕관의 성문", ja: "鉄王冠の城門", en: "Gate of the Iron Crown" },
    GT10_2: { ko: "업화경의 복제", ja: "業火鏡の複製", en: "Reflection of the Hellfire Mirror" },
    GT10_3: { ko: "동결처형대", ja: "凍結処刑台", en: "Frozen Execution Scaffold" },
    GS11_0: { ko: "성좌소각", ja: "星座焼却", en: "Constellation Pyre" },
    GS11_1: { ko: "무영빙하 낙하", ja: "無影氷河落下", en: "Fall of the Lightless Glacier" },
    GT11_0: { ko: "화산왕의 견갑", ja: "火山王の肩甲", en: "Mantle of the Volcano King" },
    GT11_1: { ko: "천궁의 폐문", ja: "天宮の閉門", en: "Sealing the Celestial Gate" },
    GT12_0: { ko: "여명성채 최후진", ja: "黎明城塞の最終陣", en: "Last Array of the Dawn Citadel" },
    GT12_1: { ko: "최후심판의 문", ja: "最後審判の門", en: "Gate of Final Judgment" },
};
export function applyFlavorCardNames(pools) {
    for (const pool of pools) {
        for (const [id, names] of Object.entries(FLAVOR_CARD_NAMES)) {
            const card = pool[id];
            if (!card)
                continue;
            card.name = names.ko;
            card.nameJa = names.ja;
            card.nameEn = names.en;
        }
    }
}
