import '../../styles/tokens.css';import '../../styles/base.css';import '../../styles/card.css';import '../../styles/game-overlays.css';import '../../styles/game.css';import '../../styles/screens.css';import '../../styles/reading-board.css';import '../../styles/presentation.css';
import {GameView,setMyAvatar,setOppAvatar} from '../../ui/boardView';import {startBoardLayout} from '../../ui/layout';import {waitForDuel} from '../../ui/duelReadiness';import {projectedPlacement} from '../../ui/boardProjection';import {clearMonsterStates} from '../../ui/monster/runtime';import {createGame} from '../../shared/engine';import {DB} from '../../shared/cards';import {setLang} from '../../i18n';import {surface} from './surface';import {Renderer} from './renderer';import {DURATION} from './catalog';
setLang('ja');setMyAvatar('SEEKER_BLUE');setOppAvatar('SEEKER_RED');document.body.style.cssText='margin:0;overflow:hidden;background:#f2eee8';const css=document.createElement('style');css.textContent='.topbar,.help-callout,.help-fab,.mute-fab{display:none!important}';document.head.append(css);
const root=document.getElementById('app')!,noop=()=>{};const view=new GameView(root,0,{onPlay:noop,onBlockedPlay:noop,onAttack:noop,onBlockedAttack:noop,onReorder:noop,onChooseTarget:noop,onBuyMarket:noop,onBuySupply:noop,onRefresh:noop,onEndTurn:noop,onSurrender:noop});const renderer=new Renderer(),faces=new Map<string,HTMLCanvasElement>();
let ready=false,disposed=false,side=0,variant=0,ms=0,reduced=false,multi=false,card='ELF',dark=false;let originals:HTMLElement[]=[];const rigs:Array<{el:HTMLElement;canvas:HTMLCanvasElement}>=[];
for(let i=0;i<3;i++){const el=document.createElement('div');el.style.cssText='position:fixed;left:0;top:0;width:180px;height:270px;transform-origin:0 0;pointer-events:none;z-index:180;visibility:hidden';const canvas=document.createElement('canvas');canvas.width=canvas.height=900;canvas.style.cssText='position:absolute;left:-252px;top:-207px;width:684px;height:684px';el.append(canvas);document.body.append(el);rigs.push({el,canvas});}
const mon=(id:string,uid:string)=>({...DB[id],uid,exhausted:false,summonedTurn:0,dmg:0,tempAtk:0,atkMod:0,defMod:0});
function setup(){restore();const g=createGame({mode:'bot',seed:71,starting:0,p0:{id:'preview-self',name:'YOU'},p1:{id:'preview-opp',name:'OPPONENT'}}).state;g.turn=3;g.phase='main';g.pending=null;for(const [i,p]of g.players.entries()){p.openingDrawReady=false;p.mana=12;p.maxMana=12;p.hp=30;p.enchants=[];p.quests=[];p.traps=[];p.field=['M4',card,'TDE2'].map((id,j)=>mon(id,`six-${i}-${j}`));p.hand=[{...DB.M4,uid:`six-hand-${i}`}];}view.render(g);view.setHandOpen(false);clearMonsterStates(root);originals=Array.from(root.querySelectorAll<HTMLElement>('.zone-mon .card'));}
function restore(){originals.forEach(n=>n.style.visibility='');rigs.forEach(r=>r.el.style.visibility='hidden');}
function draw(){restore();if(!ready||disposed||ms>=DURATION||document.hidden)return;root.style.filter=dark?'brightness(.7)':'';const chosen=originals.filter(n=>n.dataset.uid?.startsWith(`six-${side}-`)&&(multi||n.dataset.uid.endsWith('-1')));for(const [i,n]of chosen.entries()){const index=Number(n.dataset.uid!.slice(-1)),id=['M4',card,'TDE2'][index],rig=rigs[i];const f=faces.get(id);if(!f)continue;n.style.visibility='hidden';rig.el.style.visibility='visible';rig.el.style.transform=projectedPlacement(n,180,270).toString();const c=rig.canvas.getContext('2d')!;c.setTransform(900/684,0,0,900/684,0,0);c.clearRect(0,0,684,684);renderer.draw(c,f,variant,ms,342,342,180,reduced);}}
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent)return;if(e.data?.kind==='summon-six-suspend'){restore();return;}if(e.data?.kind!=='summon-six-control')return;const d=e.data;const next=['ELF','TDE2','M4'].includes(d.card)?d.card:card;if(next!==card){card=next;setup();}side=d.side===1?1:0;variant=Math.max(0,Math.min(5,Number(d.variant)||0));ms=Math.max(0,Math.min(DURATION,Number(d.ms)||0));multi=!!d.multi;reduced=!!d.reduced;dark=!!d.dark;draw();});
window.addEventListener('resize',()=>requestAnimationFrame(draw));document.addEventListener('visibilitychange',()=>{if(document.hidden)restore();});
setup();const stop=startBoardLayout();window.addEventListener('pagehide',()=>{restore();disposed=true;rigs.forEach(r=>r.el.remove());renderer.dispose();stop();view.destroy();},{once:true});
(window as any).summonBoard={get state(){return{ready,side,variant,ms,multi,hidden:originals.filter(n=>n.style.visibility==='hidden').length,rigs:rigs.filter(r=>r.el.style.visibility==='visible').length};},restore};
void(async()=>{await waitForDuel(root);for(const id of ['ELF','M4','TDE2'])faces.set(id,await surface(id));ready=true;parent.postMessage({kind:'summon-six-ready'},location.origin);})().catch(e=>parent.postMessage({kind:'summon-six-error',error:String(e)},location.origin));
