import {surface} from './surface';import {Renderer} from './renderer';import {designs,DURATION} from './catalog';import './style.css';
const root=document.getElementById('app')!;let mode='grid',variant=0,ms=0,speed=1,playing=false,loop=true,dark=false,reduced=matchMedia('(prefers-reduced-motion:reduce)').matches,ready=false,side=0,multi=false,raf=0,last=0,painted=0,disposed=false;let face:HTMLCanvasElement;const renderer=new Renderer();
document.body.style.background='#131617';document.title='LORE · 召喚6案';root.innerHTML=`<main><header><div><div class="eyebrow">LORE / MOTION STUDIES — 03 OCT 2026</div><h1>召喚、その一拍。</h1><p>柔らかな陰影、物質の厚み、接地の重さ。6つの着地方向を比較。</p></div><span class="badge">LOCAL PREVIEW · 未採用</span></header><nav class="toolbar" aria-label="表示"><button data-mode="grid" class="active">6案を比較</button><button data-mode="detail">1案を拡大</button><button data-mode="board">実盤面</button><button data-mode="before">現行との比較</button><span class="spacer"></span><select id="card" aria-label="カード"><option value="ELF">エルフ</option><option value="TDE2">魔族</option><option value="M4">モンスター</option></select><button id="theme">白い盤面</button><label><input id="reduced" type="checkbox">動きを低減</label></nav><div class="status" id="status">カードと描画素材を準備中…</div><section class="stage"><div class="grid" id="grid">${designs.map((d,i)=>`<article><div class="label"><small>0${i+1} / ${d.en}</small><strong>${d.name}</strong></div><canvas data-v="${i}" aria-label="${d.name}"></canvas><div class="foot"><p>${d.note}</p><button data-zoom="${i}">拡大 ↗</button></div></article>`).join('')}</div><div class="detail" id="detail" hidden><canvas id="large" aria-label="選択した召喚演出"></canvas><aside>${designs.map((d,i)=>`<button data-select="${i}">0${i+1}　${d.name}</button>`).join('')}<p id="intent"></p></aside></div><div id="board" hidden><div class="board-options">${designs.map((d,i)=>`<button data-select="${i}">${i+1} ${d.name}</button>`).join('')}<button id="side">自分側</button><button id="multi">1枚</button></div><div class="board-wrap"><iframe title="LORE 実盤面で召喚を確認" src="about:blank"></iframe></div></div><div class="grid compare" id="before" hidden>${['現行：2D＋元の3D','元の3Dだけ','新案'].map((s,i)=>`<article><div class="label"><small>${['CURRENT / DOUBLE','ORIGINAL / SINGLE','NEW / SINGLE'][i]}</small><strong id="compare-title-${i}">${s}</strong></div><canvas data-before="${i}"></canvas><div class="foot"><p>${['同じ接地から2系統の砂埃が発生。','既存のテクスチャ・運動式を使用した比較再生。','6案から選択中の演出。単一の接地時計。'][i]}</p></div></article>`).join('')}</div></section><div class="timeline"><button id="play">再生</button><button id="reset" aria-label="最初へ">↺</button><select id="speed" aria-label="再生速度"><option value="1">1×</option><option value="0.5">0.5×</option><option value="0.25">0.25×</option></select><input id="seek" aria-label="時刻" type="range" min="0" max="2500" value="0"><output id="time">0.00 / 2.50</output><span class="phase" id="phase">予兆</span><label style="font-size:11px"><input id="loop" type="checkbox" checked>反復</label></div><div class="notes"><strong>重複の確認：</strong>現行の着地は、カード側の2D砂埃と、盤面側の元の3D砂煙を同時に発火しています。「現行との比較」で見比べられます。<br>この6案は、粒を増やすよりも煙の主形状・表面の反射・接地影・消え方を調整したローカル試作です。表示上の選択は採用・公開を行いません。</div><footer>通常速度 / 低速 / シーク / 両陣営 / 同時召喚 / 低減モーション　·　既存のゲーム処理・デプロイには未反映</footer></main>`;
const $=<T extends HTMLElement=HTMLElement>(s:string)=>root.querySelector<T>(s)!;const frame=$<HTMLIFrameElement>('iframe');
function send(suspend=false){frame.contentWindow?.postMessage(suspend?{kind:'summon-six-suspend'}:{kind:'summon-six-control',variant,ms,side,multi,reduced,dark,card:$<HTMLSelectElement>('#card').value},location.origin);}
function canvasDraw(canvas:HTMLCanvasElement,v:number){const r=canvas.getBoundingClientRect();if(!r.width||!r.height)return;const d=Math.min(devicePixelRatio,1.5),w=Math.round(r.width*d),h=Math.round(r.height*d);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}const c=canvas.getContext('2d')!;c.setTransform(d,0,0,d,0,0);c.clearRect(0,0,r.width,r.height);const cw=Math.min(r.width*.33,r.height*.39);renderer.draw(c,face,v,ms,r.width*.5,r.height*.60,cw,reduced);}
function draw(){if(!ready||disposed)return;if(mode==='grid')root.querySelectorAll<HTMLCanvasElement>('[data-v]').forEach(c=>canvasDraw(c,Number(c.dataset.v)));else if(mode==='detail')canvasDraw($<HTMLCanvasElement>('#large'),variant);else if(mode==='before')root.querySelectorAll<HTMLCanvasElement>('[data-before]').forEach(c=>canvasDraw(c,[7,6,variant][Number(c.dataset.before)]));else send();$<HTMLInputElement>('#seek').value=String(ms);$('#time').textContent=`${(ms/1000).toFixed(2)} / 2.50`;$('#phase').textContent=ms<designs[variant].hit-100?'溜め・下降':ms<designs[variant].hit+120?'接地':ms<1600?'展開・崩れ':'沈降・余韻';}
function setMode(next:string){mode=next;for(const id of ['grid','detail','board','before'])$('#'+id).hidden=id!==mode;root.querySelectorAll<HTMLElement>('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));if(mode==='board'){if(frame.getAttribute('src')==='about:blank')frame.src='/summon-six.html?board';}else{send(true);frame.src='about:blank';}draw();}
function select(v:number){variant=v;root.querySelectorAll<HTMLElement>('[data-select]').forEach(b=>b.classList.toggle('active',Number(b.dataset.select)===v));$('#intent').textContent=designs[v].note;$('#compare-title-2').textContent=`新案：${v+1} ${designs[v].name}`;draw();}
function pause(){playing=false;cancelAnimationFrame(raf);raf=0;$('#play').textContent='再生';}
function tick(now:number){if(!playing||disposed)return;ms+=Math.max(0,Math.min(100,now-last))*speed;last=now;if(ms>DURATION){if(loop)ms=0;else{ms=DURATION;pause();}}if(now-painted>33){draw();painted=now;}if(playing)raf=requestAnimationFrame(tick);}
function play(){if(!ready||disposed)return;if(ms>=DURATION)ms=0;pause();playing=true;last=performance.now();$('#play').textContent='一時停止';raf=requestAnimationFrame(tick);}
root.querySelectorAll<HTMLElement>('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode!));root.querySelectorAll<HTMLElement>('[data-zoom]').forEach(b=>b.onclick=()=>{select(Number(b.dataset.zoom));setMode('detail');});root.querySelectorAll<HTMLElement>('[data-select]').forEach(b=>b.onclick=()=>select(Number(b.dataset.select)));
$('#play').onclick=()=>playing?pause():play();$('#reset').onclick=()=>{ms=0;draw();};$<HTMLInputElement>('#seek').oninput=()=>{pause();ms=Number($<HTMLInputElement>('#seek').value);draw();};$<HTMLSelectElement>('#speed').onchange=()=>speed=Number($<HTMLSelectElement>('#speed').value);$<HTMLInputElement>('#loop').onchange=()=>loop=$<HTMLInputElement>('#loop').checked;
$('#theme').onclick=()=>{dark=!dark;root.classList.toggle('dark',dark);$('#theme').textContent=dark?'暗い盤面':'白い盤面';draw();};$('#side').onclick=()=>{side=1-side;$('#side').textContent=side?'相手側':'自分側';draw();};$('#multi').onclick=()=>{multi=!multi;$('#multi').textContent=multi?'3枚同時':'1枚';draw();};
function reduce(value:boolean){reduced=value;$<HTMLInputElement>('#reduced').checked=value;if(value){pause();ms=DURATION;loop=false;$<HTMLInputElement>('#loop').checked=false;}draw();}$<HTMLInputElement>('#reduced').onchange=()=>reduce($<HTMLInputElement>('#reduced').checked);matchMedia('(prefers-reduced-motion:reduce)').addEventListener('change',e=>reduce(e.matches));
$<HTMLSelectElement>('#card').onchange=async()=>{pause();face=await surface($<HTMLSelectElement>('#card').value);draw();};
window.addEventListener('resize',draw);window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==frame.contentWindow)return;if(e.data?.kind==='summon-six-ready'){if(mode==='board')send();}if(e.data?.kind==='summon-six-error')$('#status').textContent='盤面の準備に失敗: '+e.data.error;});
document.addEventListener('visibilitychange',()=>{if(document.hidden){pause();send(true);}});window.addEventListener('pagehide',()=>{pause();disposed=true;renderer.dispose();send(true);},{once:true});
(window as any).summonLab={get ready(){return ready;},get state(){return{mode,variant,ms,playing,reduced,side,multi};},seek(t:number,v=variant){pause();ms=t;select(v);draw();},setMode,setSide(s:number){side=s;draw();},setMulti(v:boolean){multi=v;draw();},reduce,play,pause};
void(async()=>{face=await surface();ready=true;select(0);$('#status').textContent='6案は同時再生。拡大では質感、実盤面ではカード実寸と隣接情報を確認できます。';if(reduced)reduce(true);else if(!new URLSearchParams(location.search).has('qa'))play();if(new URLSearchParams(location.search).has('qa'))void import('./qa').then(m=>m.run(renderer,face,$('#status')));})().catch(e=>{$('#status').textContent='準備に失敗: '+e.message;});
