// ============================================================
// LORE — English battle-log translator.
// Engine logs are authored in KO/JA; for EN we translate the Korean
// HTML at render time with ordered phrase rules. Card-name tags
// (<b class="log-card">) are protected and re-localized separately.
// ============================================================

const R: [RegExp, string][] = [
  // ---- full/long phrases first (order matters) ----
  [/초기 덱 · (\d+)장 드로우 · 마나 (\d+)\./g, "Starting deck · drew $1 · mana $2."],
  [/(\d+)턴 경과 — 무승부!/g, "$1 turns elapsed — it's a draw!"],
  [/고정 마켓/g, "market:"],
  [/제시 마켓/g, "offer:"],
  [/구매 \((\d+)\)/g, "bought ($1)"],
  [/\[묘지로\]/g, "[→ graveyard]"],
  [/이 카드 폐기\(덱에서 제거\)|이 카드 폐기/g, "culled (removed from deck)"],
  [/고코스트 폐기 → /g, "discarded a high-cost card → "],
  [/함정을 세트 \(정체는 비공개\)/g, "set a trap (face-down)"],
  [/제시를 무료 갱신/g, "refreshed the offer for free"],
  [/제시 갱신 \((\d+) 마나\)/g, "refreshed the offer ($1 mana)"],
  [/보물상자 사용 봉인 중/g, "Treasure Chests are sealed"],
  [/보물상자 → 묘지, (\d+)장 드로우/g, "chest → graveyard, drew $1"],
  [/패에 보물상자가 없음/g, "no Treasure Chest in hand"],
  [/보물상자 →/g, "Treasure Chest →"],
  [/꽝! 상대 필드에 마스터 미믹\((\d+)\/(\d+)\) 소환 \((\d+)%\)/g, "Dud! Master Mimic ($1/$2) summoned to the enemy field ($3%)"],
  [/꽝! 상대 필드에 미믹\((\d+)\/(\d+)\) 소환/g, "Dud! Mimic ($1/$2) summoned to the enemy field"],
  [/소환 반동: 자신에게 (\d+) 데미지/g, "summon recoil: $1 damage to self"],
  [/소환 효과: (\d+)장 드로우/g, "on summon: drew $1"],
  [/소환 강화:/g, "summon boost:"],
  [/생명의 순환: 최대 마나/g, "Cycle of Life: max mana"],
  [/발아! 최대 마나/g, "Sprouted! max mana"],
  [/축복! 최대 마나 \+(\d+) 추가/g, "Blessing! max mana +$1 extra"],
  [/길드의 정보망 획득 — 턴 시작시 드로우 \+1 \(영구, (\d+)%\)/g, "gained Guild Network — +1 draw at turn start (permanent, $1%)"],
  [/마법·함정 존이 가득 차 정보망을 놓쳤다/g, "spell/trap zone full — the Network was lost"],
  [/경보! 상대 필드에 초급·중급 암살자 소환 \((\d+)%\)/g, "Alarm! Novice & Adept Assassins summoned to the enemy field ($1%)"],
  [/대참사! 상대 필드에 초급·중급·상급 암살자 소환 \((\d+)%\)/g, "Disaster! Novice, Adept & Elite Assassins summoned to the enemy field ($1%)"],
  [/지옥: 자신 (\d+) \/ 상대 (\d+)/g, "Inferno: self $1 / enemy $2"],
  [/\s*의 직접 공격/g, " direct attack"],
  [/직접 공격/g, "direct attack"],
  [/\[관통\]/g, "[pierce]"],
  [/\[출혈\]/g, "[bleed]"],
  [/\[포식 시너지\]/g, "[Devour synergy]"],
  [/(\d+) 관통/g, "$1 pierce"],
  // ---- v11 패시브 키워드 (generic 무효화/파괴 룰보다 먼저) ----
  [/도발! /g, "Taunt! "],
  [/ 이\(가\) 대신 공격을 받는다/g, " is attacked instead"],
  [/회피 실패 🎲 (\d+)/g, "Evade failed 🎲 $1"],
  [/회피!/g, "Evade!"],
  [/ 이\(가\) 공격을 무효화/g, " negates the attack"],
  [/기합!/g, "Guts!"],
  [/파괴 무효 \(남은 기합 (\d+)\)/g, "destruction negated ($1 Guts left)"],
  [/부패 카운터 (\d+)\/3/g, "Decay counter $1/3"],
  [/부패 붕괴!/g, "Decay collapse!"],
  [/부패 카운터 (\d+)개를 부여할 적 몬스터 선택/g, "pick an enemy monster to receive $1 Decay counter"],
  [/ 이\(가\) '부패'를 얻는다/g, " gains 'Decay'"],
  [/ 이\(가\) '위엄'을 얻는다/g, " gains 'Majesty'"],
  [/'부패'를 부여할 자신 몬스터 선택 \((\d+)체( 남음)?\)/g, "pick your monster to grant 'Decay' ($1 left)"],
  [/'위엄'을 부여할 자신 몬스터 선택/g, "pick your monster to grant 'Majesty'"],
  [/위엄: 소환된 턴에는 공격할 수 없다|: 소환된 턴에는 공격할 수 없다/g, "Majesty: cannot attack on its summoning turn"],
  [/골램 군단 결집 — 페널티 없음/g, "Golem legion assembled — no penalty"],
  [/골램 부재/g, "no Golem backup"],
  [/선택이 완성되었다 — 게임에서 승리한다!/g, "the Choice is complete — win the game!"],
  [/게임에서 제외된 컬이 (\d+)장 — 20장 이상이어야 발동 가능/g, "$1 Culls exiled — need 20 or more to cast"],
  [/선택받은 마법사 — 발동할 마법사 선택 \(제외된 컬 1장 → 묘지, 상대에게 6 데미지 · 취소 가능\)/g, "Chosen Mage — pick a mage to activate (1 exiled Cull → graveyard, 6 damage to the opponent · may cancel)"],
  [/ — 제외된 컬 1장을 묘지로 되돌리고 상대에게 6 데미지/g, " — returns 1 exiled Cull to the graveyard and deals 6 damage to the opponent"],
  [/시련의 영역 — 묘지에서 게임에서 제외할 카드 선택 \(2장까지\)/g, "Domain of Trials — pick cards in your graveyard to exile (up to 2)"],
  [/고대 문명 — 패에 넣을 알 선택/g, "Ancient Civilization — pick an egg to add to your hand"],
  [/고대 문명이 깨어난다!/g, "the Ancient Civilization awakens!"],
  [/ 을\(를\) 패에 넣는다/g, " added to hand"],
  [/ 은\(는\) 파괴된다/g, " is destroyed"],
  [/계약이 다했다 — 파괴된다/g, "the pact has run its course — destroyed"],
  [/대가: 자신에게 6 데미지/g, "price: take 6 damage"],
  [/자신에게 7 데미지, 최대 마나 -1/g, "take 7 damage, max mana -1"],
  [/자신 필드에 이미 '선견지명'이 있습니다/g, "you already have 'Foresight' on your field"],
  [/통하지 않음/g, "no effect"],
  [/공격이 (\d+)로 절반/g, "attack halved to $1"],
  [/공격 무효화/g, "attack negated"],
  [/공격 무효/g, "attack negated"],
  [/무효화/g, "negated"],
  [/\(소생 실패\)/g, "(revive failed)"],
  [/탈취\(소생\)/g, "stolen (revived)"],
  [/파괴 \+ 게임에서 제외/g, "destroyed + exiled from the game"],
  [/게임에서 제외할 카드 선택 \(3장\)/g, "pick cards to exile (3)"],
  [/게임에서 제외할 카드 선택 \(원하는 만큼\)/g, "pick cards to exile (any number)"],
  [/게임에서 제외할 카드 선택/g, "pick a card to exile from the game"],
  // ---- 알(egg) / 용 / 신수 ----
  [/소환 \(부화 (\d+)턴 \/ 내구도 (\d+)\)/g, "summoned (hatch $1 turns / durability $2)"],
  [/공격! 내구도 -(\d+) \(남은 내구도 (\d+)\)/g, "attack! durability -$1 ($2 left)"],
  // ---- 알 대응 테크 / 피의 마법 / 흡혈귀 ----
  [/부화를 (\d+)턴 앞당길 알 선택/g, "pick an egg to speed up by $1 turns"],
  [/부화 카운터 -(\d+) \(남은 (\d+)턴\)/g, "hatch counter -$1 ($2 turns left)"],
  [/자신 필드에 알이 없습니다/g, "you have no egg on your field"],
  [/알이 아닙니다/g, "not an egg"],
  [/알 (\d+)개 내구도 \+(\d+)/g, "$1 egg(s) durability +$2"],
  [/양측 최대 체력 \+(\d+)/g, "both players max HP +$1"],
  [/필드의 모든 몬스터 공격 \+(\d+)\(지속\)/g, "all monsters on the field ATK +$1 (lasting)"],
  [/피의 축제: /g, "Blood Festival: "],
  [/흡혈 술식: 피의 마법 데미지 무효/g, "Vampiric Ritual: Blood Magic damage negated"],
  [/흡혈의 극의: /g, "Vampiric Secret Art: "],
  [/ 파괴되지 않음/g, " is not destroyed"],
  [/ 은\(는\) 함정으로 파괴되지 않는다/g, " cannot be destroyed by traps"],
  [/ 이\(가\) 피에 이끌린다…/g, " is drawn by the blood…"],
  [/ 흡혈: 최대 체력 \+(\d+)/g, " drains: max HP +$1"],
  [/발동! 견습 흡혈귀 소환/g, "triggers! summons an Apprentice Vampire"],
  [/파괴할 자신의 '흡혈귀' 선택/g, "pick your 'Vampire' to destroy"],
  [/자신 필드에 '흡혈귀' 계열 몬스터가 없습니다/g, "you have no 'Vampire' monster on your field"],
  [/파괴할 흡혈귀가 없어 불발/g, "no Vampire to destroy — fizzles"],
  [/파괴 실패 — 대가 미지불로 효과 불발/g, "destruction failed — cost unpaid, effect fizzles"],
  [/몬스터 존이 가득 차 소환 실패/g, "monster zone full — summon failed"],
  [/파괴 — 부화 실패/g, "destroyed — hatching failed"],
  [/부화!/g, "hatched!"],
  [/등장/g, "appears"],
  [/알은 공격할 수 없습니다/g, "the egg cannot attack"],
  [/흑룡의 위압: 상대 몬스터 전체 방어 -(\d+)\(지속\)/g, "Black Dragon's dread: all enemy monsters DEF -$1 (lasting)"],
  [/상대의 제외된 카드가 없음/g, "the opponent has no exiled cards"],
  [/청룡의 축복: /g, "Blue Dragon's blessing: "],
  [/신수 강림: /g, "the Divine Beast descends: "],
  [/매 턴 드로우 \+1\(영구\)/g, "+1 draw each turn (permanent)"],
  [/적룡의 화염: 마법 데미지 \+(\d+)/g, "Red Dragon's flame: spell damage +$1"],
  [/ 은\(는\) 효과의 대상이 되지 않는다/g, " cannot be targeted by effects"],
  [/ 을\(를\) 상대 묘지로 되돌림/g, " returned to the opponent's graveyard"],
  [/세트 함정 파괴 \(정체: /g, "set trap destroyed (revealed: "],
  // 신수: "영구마법 <카드명> 파괴" — 카드명 태그는 N 로 보호된 상태에서 매칭
  // (generic "영구마법" 룰을 앞에 두면 아래쪽 기존 영구마법 룰들이 깨지므로 태그-특정 패턴만)
  [/영구마법 (\d+) 파괴/g, "destroyed enchantment $1"],
  [/상대 묘지로 되돌릴 카드 선택 \(상대의 제외존, 최대 (\d+)장\)/g, "pick cards to return to the opponent's graveyard (their exile zone, up to $1)"],
  [/파괴할 상대 카드 선택 \(몬스터·세트 함정·영구마법, (\d+)장\)/g, "pick opponent cards to destroy (monsters/set traps/enchantments, $1)"],
  // ---- 종족 시너지 개편 / 시초 리워크 ----
  [/포식 시너지 — 파괴할 적 몬스터 선택 \((\d+)체 남음\)/g, "Devour synergy — pick an enemy monster to destroy ($1 left)"],
  [/포식 시너지 — 파괴할 적 몬스터 선택 \((\d+)체\)/g, "Devour synergy — pick an enemy monster to destroy ($1)"],
  [/공격력을 2로 만들 적 몬스터 선택/g, "pick an enemy monster to set to 2 ATK"],
  [/ 의 공격력이 2가 된다/g, "'s ATK becomes 2"],
  [/거인의 교역 — 마나를 지불하고 구매할 코스트 5\+ 시초 카드 선택/g, "Giant's Trade — pick a cost-5+ Origin card to buy with mana"],
  [/거인의 교역 → /g, "Giant's Trade → "],
  [/ 구매 \(마나 (\d+)\)/g, " bought (mana $1)"],
  [/마나가 부족해 구매하지 못함/g, "not enough mana to buy"],
  [/1장 드로우 — 몬스터다!/g, "drew 1 — it's a monster!"],
  [/1장 드로우 — 몬스터가 아니다/g, "drew 1 — not a monster"],
  [/매 턴 드로우 \+(\d+)\(영구\)/g, "+$1 draw each turn (permanent)"],
  [/상대 세트 함정 전부 파괴 — 그중 /g, "destroyed all enemy set traps — of those, "],
  [/ 은\(는\) 게임에서 제외/g, " is exiled from the game"],
  [/상대 최대 체력 -(\d+) \((\d+)\)/g, "enemy max HP -$1 ($2)"],
  [/상대 필드의 모든 카드 파괴 \+ 게임에서 제외/g, "every card on the enemy field destroyed + exiled"],
  // ---- 스타팅 카드 15종 ----
  [/유령의 원한: 상대의 성장에 (.+?) 이\(가\) (\d+) 데미지/g, "Ghost's grudge: $1 takes $2 damage from the opponent's growth"],
  [/상대 최대 마나 \+1 \((\d+)\) · 상대는 다음 턴 함정 설치 불가/g, "opponent max mana +1 ($1) · they cannot set traps next turn"],
  [/협상: 이번 턴에는 함정을 설치할 수 없습니다/g, "Negotiation: you cannot set traps this turn"],
  [/혈귀술: (\d+) 데미지 → 회복으로 반전/g, "Blood Fiend Art: $1 damage inverted to healing"],
  [/약화술식 해제: 모든 몬스터 공격 \+2 복구/g, "Enfeebling Ritual lifted: all monsters ATK +2 restored"],
  [/양 필드의 모든 몬스터 공격 -2/g, "all monsters on both fields ATK -2"],
  [/카운트 (\d+)\/3/g, "count $1/3"],
  [/발동! 상대에게 14 데미지/g, "triggers! 14 damage to the opponent"],
  [/미믹 파티 개최 — (.+?) 필드에 1마리, (.+?) 필드에 2마리/g, "Mimic Party! 1 Mimic on $1's field, 2 on $2's"],
  [/대가: 최대 마나 -1 \((\d+)\), 자신에게 8 데미지/g, "price: max mana -1 ($1), take 8 damage"],
  [/운명의 수레바퀴 — (.+?) 의 결과를 다시 굴릴 수 있다/g, "Wheel of Fate — you may reroll $1's result"],
  [/결과를 되감고 다시 굴린다…/g, "rewinding the result and rerolling…"],
  [/ 은\(는\) 게임에서 제외된다/g, " is exiled from the game"],
  [/상대 최대 마나가 6을 초과해 사용 불가/g, "unusable — opponent max mana above 6"],
  [/상대 최대 마나가 4가 아니라 사용 불가/g, "unusable — opponent max mana is not 4"],
  [/발현! 최대 마나 \+2 \((\d+)\) — 이 카드는 게임에서 제외/g, "manifests! max mana +2 ($1) — this card is exiled"],
  [/계약 불이행! 최대 마나 -2 \((\d+)\), 자신에게 12 데미지/g, "pact broken! max mana -2 ($1), take 12 damage"],
  [/다종족 계약: 시너지 2배!/g, "Multi-Tribe Pact: synergy doubled!"],
  [/필드의 모든 몬스터 공\/방 반전! \(2턴\)/g, "all monsters' ATK/DEF swapped! (2 turns)"],
  [/반전 지속 연장 \(2턴\)/g, "swap extended (2 turns)"],
  [/트릭룸/g, "Trick Room"],
  [/종료 — 공\/방 원위치 \(반전 중 오른 스탯은 계승\)/g, "ends — ATK/DEF restored (gains made while swapped are kept)"],
  [/상대 (\d+) \/ 자신 (\d+) 데미지/g, "opponent $1 / self $2 damage"],
  [/공격 \+(\d+) 할 자신 몬스터 선택 \((\d+)체( 남음)?\)/g, "pick your monster for ATK +$1 ($2 left)"],
  [/이미 선택한 몬스터입니다|알이 아닙니다/g, "invalid target"],
  [/게임에서 제외/g, "exiled from the game"],
  [/덱에서 1장 선택/g, "pick 1 card from your deck"],
  [/버린 패에서 1장 선택/g, "pick 1 card from your discard pile"],
  [/방어 -(\d+) 할 적 몬스터 선택/g, "pick an enemy monster for DEF -$1"],
  [/공격 -(\d+) 할 적 몬스터 선택/g, "pick an enemy monster for ATK -$1"],
  [/공격 \+(\d+) 할 자신 몬스터 선택/g, "pick your monster for ATK +$1"],
  [/강화할 자신 몬스터 선택/g, "pick your monster to empower"],
  [/공격할 적 몬스터 선택/g, "pick an enemy monster to attack"],
  [/저코스트 카드 (\d+)장 제외/g, "exiled $1 low-cost card(s)"],
  [/군단\((\d+)장\) 결집:/g, "horde assembled ($1 cards):"],
  [/덱\+묘지 (\d+)장 — 군단 미달\((\d+)장\)/g, "deck+graveyard $1 — below horde size ($2)"],
  [/정예\((\d+)장\) 편성:/g, "elite formation ($1 cards):"],
  [/덱\+묘지 (\d+)장 — 정예 초과\((\d+)장\)/g, "deck+graveyard $1 — above elite size ($2)"],
  [/함정 (\d+)장 →/g, "$1 trap(s) →"],
  [/보유 함정 없음/g, "no traps owned"],
  [/상대 세트 함정 (\d+)장 전부 파괴/g, "destroyed all $1 enemy set traps"],
  [/공격력 (\d+) 이하 몬스터 (\d+)체 파괴/g, "destroyed $2 monster(s) with ATK $1 or less"],
  [/방어력 (\d+) 이하 몬스터 (\d+)체 파괴/g, "destroyed $2 monster(s) with DEF $1 or less"],
  [/공격력 (\d+) 이하 몬스터/g, "monster with ATK $1 or less:"],
  [/방어력 (\d+) 이하 몬스터/g, "monster with DEF $1 or less:"],
  [/공격력 (\d+) 이하 적 몬스터가 없습니다/g, "no enemy monster with ATK $1 or less"],
  [/방어력 (\d+) 이하 적 몬스터가 없습니다/g, "no enemy monster with DEF $1 or less"],
  [/묘지가 비어 있습니다/g, "graveyard is empty"],
  [/유리 병기 금지령: 방어 (\d+) 이하는 공격 불가/g, "Glass Arms Ban: DEF $1 or less cannot attack"],
  [/몬스터 (\d+)체의 방어를 (\d+)으로/g, "set $1 monster(s) DEF to $2"],
  [/허수아비\((\d+)\/(\d+)\) (\d+)체 소환/g, "summoned $3 Scarecrows ($1/$2)"],
  [/병사\((\d+)\/(\d+)\) (\d+)체 소환/g, "summoned $3 Soldiers ($1/$2)"],
  [/상대 종족 몬스터 (\d+)장 →/g, "$1 enemy tribe monster(s) →"],
  [/미믹 (\d+)마리 →/g, "$1 Mimic(s) →"],
  [/필드에 미믹 없음/g, "no Mimics on the field"],
  [/제외된 컬 (\d+)장 →/g, "$1 exiled Cull(s) →"],
  [/제외된 컬 없음/g, "no exiled Culls"],
  [/미믹\((\d+)\/(\d+)\) (\d+)마리 소환/g, "summoned $3 Mimics ($1/$2)"],
  [/제외된 미믹 (\d+)장 →/g, "$1 exiled Mimic(s) →"],
  [/제외된 미믹 없음/g, "no exiled Mimics"],
  [/미믹 계열 (\d+)장 →/g, "$1 Mimic-family card(s) →"],
  [/미믹 계열 없음/g, "no Mimic-family cards"],
  [/마스터 미믹\((\d+)\/(\d+)\) 강림!/g, "Master Mimic ($1/$2) descends!"],
  [/미믹\((\d+)\/(\d+)\) (\d+)마리 소환 \+ 미믹 (\d+)장 게임에서 제외/g, "summoned $3 Mimics ($1/$2) + exiled $4 Mimics"],
  [/경제 위기!/g, "Economic Crisis!"],
  [/세계수의 가호:/g, "World Tree's blessing:"],
  [/조건 미달\((\d+)\)/g, "condition not met ($1)"],
  [/거벽/g, "giant wall"],
  [/파괴할 적 몬스터 선택 \((\d+)체 남음\)/g, "pick an enemy monster to destroy ($1 left)"],
  [/파괴할 적 몬스터 선택/g, "pick an enemy monster to destroy"],
  [/상대 몬스터 (\d+)체 전멸/g, "annihilated $1 enemy monster(s)"],
  [/방어력 (\d+) 이상 적 몬스터가 없습니다/g, "no enemy monster with DEF $1+"],
  [/파괴할 적 몬스터가 없습니다/g, "no enemy monster to destroy"],
  [/고정 마켓 (\d+)장 전부 갱신/g, "refreshed all $1 fixed-market cards"],
  [/제외된 카드 (\d+)장 × (\d+) =/g, "$1 exiled cards × $2 ="],
  [/묘지에 컬 (\d+)장 추가/g, "added $1 Culls to the graveyard"],
  [/패에 컬 (\d+)장 추가/g, "gained $1 Cull to hand"],
  [/상대에게 종족 몬스터가 없습니다/g, "the opponent has no tribe monsters"],
  [/덱과 묘지가 비어 있습니다/g, "deck and graveyard are empty"],
  [/리콜 → (\d+)장 회수/g, "Recall → took $1 card"],
  [/발동 \(지속 영구\)/g, "activated (permanent)"],
  [/발동 \(지속 (\d+)턴\)/g, "activated ($1 turns)"],
  [/효과 종료/g, "effect ended"],
  [/매 턴 효과/g, "turn effects"],
  [/대상 없음/g, "no target"],
  [/파괴할 함정 없음/g, "no trap to destroy"],
  [/파괴할 상대 영구마법이 없습니다/g, "no enemy enchantment to destroy"],
  [/상대 영구마법 (\d+)장 파괴/g, "destroyed $1 enemy enchantment(s)"],
  [/상대 세트 함정 (\d+)장 파괴/g, "destroyed $1 enemy set trap(s)"],
  [/상대의 세트 함정 (\d+)장 파괴|상대의 세트 함정을? (\d+)장 파괴/g, "destroyed $1 enemy set trap(s)"],
  [/상대 함정 (\d+)장 파괴/g, "destroyed $1 enemy trap(s)"],
  [/상대 몬스터 (\d+)체 \+ 마법\/함정 (\d+)장 파괴/g, "destroyed $1 enemy monster(s) + $2 spell/trap"],
  [/상대 카드 (\d+)장 무작위 파괴/g, "destroyed $1 random enemy card(s)"],
  [/상대 몬스터 (\d+)체 파괴/g, "destroyed $1 enemy monster(s)"],
  [/공격 (\d+) 이하 상대 몬스터 전멸/g, "wiped enemy monsters with ATK $1 or less"],
  [/덱에서 랜덤 몬스터 (\d+)체 무료 소환|덱에서 (\d+)체 무료 소환/g, "summoned $1 random monsters from deck for free"],
  [/덱\/묘지에서 몬스터 (\d+)체 소환/g, "summoned $1 monster(s) from deck/graveyard"],
  [/덱에서/g, "from deck"],
  [/무료 소환/g, "summoned for free"],
  [/무작위 소환/g, "randomly summoned"],
  [/자신을 복제 소환/g, "cloned itself"],
  [/복제 실패/g, "clone failed"],
  [/마나(\d+) 지불 → 무한의 기사\((\d+)\/(\d+)\) 소환/g, "paid $1 mana → summoned Infinite Knight ($2/$3)"],
  [/마나가 부족해 기사를 소환하지 못함/g, "not enough mana for the knight"],
  [/마나(\d+) → 방어 \+(\d+), 체력 \+(\d+)/g, "mana $1 → DEF +$2, HP +$3"],
  [/상대 체력 홀수 → (\d+) 데미지/g, "enemy HP odd → $1 damage"],
  [/상대 체력 짝수 → (\d+)장 드로우/g, "enemy HP even → drew $1"],
  [/(\d+)%: 상대 덱 맨 위 (\d+)장 제외/g, "$1%: exiled top $2 of the enemy deck"],
  [/(\d+)%: 자신 최대 마나 -(\d+)/g, "$1%: your max mana -$2"],
  [/(\d+)% 성공: 상대 최대 마나 -(\d+)/g, "$1% success: enemy max mana -$2"],
  [/(\d+)% 성공: 최대 체력 \+(\d+)/g, "$1% success: max HP +$2"],
  [/(\d+)% 성공 → /g, "$1% success → "],
  [/(\d+)% 성공: /g, "$1% success: "],
  [/(\d+)회째! 이후 피격 시마다 체력 \+(\d+)/g, "use #$1! now restores +$2 HP when hit"],
  [/상대는 이후 매 턴 (\d+) 데미지\(중첩 불가\)/g, "opponent now takes $1 damage each turn (no stacking)"],
  [/상대 몬스터 전체 공격 -(\d+)\(지속\)/g, "all enemy monsters ATK -$1 (lasting)"],
  [/아군 전체 공격 \+(\d+)\(이번 턴\) \+ 공격 \+(\d+)\(지속\)/g, "all allies ATK +$1 (this turn) + ATK +$2 (lasting)"],
  [/아군 전체 공격 \+(\d+)/g, "all allies ATK +$1"],
  [/\(이번 턴\)/g, "(this turn)"],
  [/\(영구\)/g, "(permanent)"],
  [/\(지속\)/g, "(lasting)"],
  [/체력 (\d+)\+ → 최대 체력 \+(\d+)/g, "HP $1+ → max HP +$2"],
  [/체력 완전 회복/g, "fully restored HP"],
  [/체력 (\d+) 회복/g, "restored $1 HP"],
  [/체력 \+(\d+) 회복/g, "restored +$1 HP"],
  [/최대 체력/g, "max HP"],
  [/최대 마나/g, "max mana"],
  [/\(체력 (\d+)\)/g, "(HP $1)"],
  [/체력/g, "HP"],
  [/(\d+)장 드로우/g, "drew $1"],
  [/드로우/g, "draw"],
  [/(\d+) 데미지/g, "$1 damage"],
  [/데미지/g, "damage"],
  [/자신에게/g, "to self:"],
  [/상대에게/g, "to the opponent:"],
  [/의 공격 -(\d+)/g, " ATK -$1"],
  [/의 방어 -(\d+)/g, " DEF -$1"],
  [/공격 \+(\d+)/g, "ATK +$1"],
  [/방어 \+(\d+)/g, "DEF +$1"],
  [/공격 -(\d+)/g, "ATK -$1"],
  [/방어 -(\d+)/g, "DEF -$1"],
  [/\(공(\d+)\/방(\d+)\)/g, "($1/$2)"],
  [/\(공(\d+)\)/g, "(ATK $1)"],
  [/\(방(\d+)\)/g, "(DEF $1)"],
  [/소환 조건 미충족/g, "summon requirement not met"],
  [/몬스터 존이 가득 찼습니다 \(최대 (\d+)\)/g, "monster zone is full (max $1)"],
  [/마법·함정 존이 가득 찼습니다 \(최대 (\d+)\)/g, "spell/trap zone is full (max $1)"],
  [/부패/g, "Decay"],
  [/위엄/g, "Majesty"],
  [/도발/g, "Taunt"],
  [/기합/g, "Guts"],
  [/회피/g, "Evade"],
  [/소환/g, "summoned"],
  [/파괴/g, "destroyed"],
  [/함정/g, "trap"],
  [/기권/g, "surrendered"],
  [/자신/g, "self"],
  [/상대/g, "opponent"],
  [/승리!?/g, "wins!"],
  // generic cast line ("P <card> 발동") — MUST stay after the specific 발동 rules above
  [/발동/g, "activated"],
];

const TRIBE_EN: Record<string, string> = { "고독": "Solitary", "고귀": "Noble", "포식": "Devour", "귀족": "Aristocrat", "시초": "Origin" };

/** Translate a Korean log/hint HTML string to English (card-name tags preserved). */
export function logToEn(html: string): string {
  // protect card-name tags & player-name spans
  const keep: string[] = [];
  let s = html.replace(/<b class="log-card"[^>]*>.*?<\/b>|<span class="t">.*?<\/span>/g, (m) => {
    keep.push(m); return `\u0001${keep.length - 1}\u0002`;
  });
  // tribe synergy banner (needs name mapping)
  s = s.replace(/\[(고독|고귀|포식|귀족|시초)\] 동족 (\d+)마리 시너지!/g, (_m, tr, n) => `[${TRIBE_EN[tr] ?? tr}] ${n}-piece tribe synergy!`);
  for (const [re, en] of R) {
    if (typeof en === "string") s = s.replace(re, en);
  }
  // restore protected tags
  s = s.replace(/\u0001(\d+)\u0002/g, (_m, i) => keep[Number(i)]);
  s = s.replace(/(<span class="t">)게임 시작\.(<\/span>)/g, "$1Game started.$2");
  return s;
}
