import '../../styles/tokens.css';import '../../styles/base.css';import '../../styles/card.css';import '../../styles/game-overlays.css';import '../../styles/game.css';import '../../styles/screens.css';import '../../styles/reading-board.css';import '../../styles/presentation.css';
import {GameView,setMyAvatar,setOppAvatar} from '../../ui/boardView';import {startBoardLayout} from '../../ui/layout';import {waitForDuel} from '../../ui/duelReadiness';import {boardMatrix,layoutRect} from '../../ui/boardProjection';import {clearMonsterStates} from '../../ui/monster/runtime';import {createGame} from '../../shared/engine';import {DB} from '../../shared/cards';import {setLang} from '../../i18n';import {surface} from './surface';import {Renderer,pose} from './renderer';import {DURATION,cards} from './catalog';
setLang('ja');setMyAvatar('SEEKER_BLUE');setOppAvatar('SEEKER_RED');document.body.style.cssText='margin:0;overflow:hidden;background:#f2eee8';const css=document.createElement('style');css.textContent='.topbar,.help-callout,.help-fab,.mute-fab{display:none!important}';document.head.append(css);
const root=document.getElementById('app')!,noop=()=>{};const view=new GameView(root,0,{onPlay:noop,onBlockedPlay:noop,onAttack:noop,onBlockedAttack:noop,onReorder:noop,onChooseTarget:noop,onBuyMarket:noop,onBuySupply:noop,onRefresh:noop,onEndTurn:noop,onSurrender:noop});const renderer=new Renderer(),faces=new Map<string,HTMLCanvasElement>();
let ready=false,disposed=false,side=0,variant=0,ms=0,reduced=false,multi=false,card='FIRE_MASTER',dark=false,rigs=0,scheduled=0;let originals:HTMLElement[]=[];
const overlay=document.createElement('canvas');overlay.style.cssText='position:fixed;inset:0;width:100%;height:100%;pointer-events:none;z-index:180';document.body.append(overlay);
const mon=(id:string,uid:string)=>({...DB[id],uid,exhausted:false,summonedTurn:0,dmg:0,tempAtk:0,atkMod:0,defMod:0});
function setup(){restore();const g=createGame({mode:'bot',seed:71,starting:0,p0:{id:'preview-self',name:'YOU'},p1:{id:'preview-opp',name:'OPPONENT'}}).state;g.turn=3;g.phase='main';g.pending=null;for(const [i,p]of g.players.entries()){p.openingDrawReady=false;p.mana=12;p.maxMana=12;p.hp=30;p.enchants=[];p.quests=[];p.traps=[];p.field=[card,card,card].map((id,j)=>mon(id,`mage-${i}-${j}`));p.hand=[{...DB.M4,uid:`mage-hand-${i}`}];}view.render(g);view.setHandOpen(false);clearMonsterStates(root);originals=Array.from(root.querySelectorAll<HTMLElement>('.zone-mon .card'));}
function restore(){originals.forEach(n=>{n.style.visibility='';n.style.opacity='';});overlay.getContext('2d')!.clearRect(0,0,overlay.width,overlay.height);rigs=0;}
function draw(){restore();root.style.filter=dark?'brightness(.7)':'';if(!ready||disposed||ms>=DURATION||document.hidden)return;const d=Math.min(devicePixelRatio,1.5);if(overlay.width!==Math.round(innerWidth*d)||overlay.height!==Math.round(innerHeight*d)){overlay.width=Math.round(innerWidth*d);overlay.height=Math.round(innerHeight*d);}const ctx=overlay.getContext('2d')!;ctx.setTransform(d,0,0,d,0,0);const chosen=originals.filter(n=>n.dataset.uid?.startsWith(`mage-${side}-`)&&(multi||n.dataset.uid.endsWith('-1')));for(const n of chosen){const f=faces.get(card);if(!f)continue;const blend=Math.max(0,Math.min(1,(ms-3500)/300));n.style.visibility=blend>0?'':'hidden';n.style.opacity=blend>0?String(blend):'';ctx.globalAlpha=1-blend;const r=layoutRect(n),z=Number(n.closest<HTMLElement>('[data-board-plane]')?.dataset.boardPlane)||0;const matrix=boardMatrix(r.left+r.width/2,r.top+r.height/2,z).scale(r.width/180,-r.height/270,r.width/180);renderer.drawBoard(ctx,f,variant,ms,matrix,innerWidth,innerHeight,reduced,cards.indexOf(card as typeof cards[number]));ctx.globalAlpha=1;rigs++;}}
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent)return;if(e.data?.kind==='mage-summon-six-suspend'){ms=DURATION;restore();return;}if(e.data?.kind!=='mage-summon-six-control')return;const d=e.data;const next=cards.includes(d.card)?d.card:card;if(next!==card){card=next;setup();}side=d.side===1?1:0;variant=Math.max(0,Math.min(5,Number(d.variant)||0));ms=Math.max(0,Math.min(DURATION,Number(d.ms)||0));multi=!!d.multi;reduced=!!d.reduced;dark=!!d.dark;if(!scheduled)scheduled=requestAnimationFrame(()=>{scheduled=0;draw();});});
window.addEventListener('resize',()=>requestAnimationFrame(draw));document.addEventListener('visibilitychange',()=>{if(document.hidden)restore();});setup();const stop=startBoardLayout();
function dispose(){if(disposed)return;restore();disposed=true;cancelAnimationFrame(scheduled);overlay.remove();renderer.dispose();stop();view.destroy();faces.clear();}window.addEventListener('pagehide',dispose,{once:true});
(window as any).mageBoard={dispose,get state(){return{ready,revision:2,card,side,variant,ms,multi,hidden:originals.filter(n=>n.style.visibility==='hidden').length,rigs,height:pose(ms,reduced).height,disposed};},restore};
void(async()=>{await waitForDuel(root);for(const id of cards)faces.set(id,await surface(id));if(disposed)return;ready=true;draw();parent.postMessage({kind:'mage-summon-six-ready'},location.origin);})().catch(e=>parent.postMessage({kind:'mage-summon-six-error',error:String(e)},location.origin));
