import {surface} from './surface';import {Renderer,pose,type View} from './renderer';import {designs,DURATION,cards,names} from './catalog';import './style.css';
const root=document.getElementById('app')!;let mode='grid',variant=0,ms=0,speed=1,playing=false,loop=true,dark=false,reduced=matchMedia('(prefers-reduced-motion:reduce)').matches,ready=false,side=0,multi=false,raf=0,last=0,disposed=false;let face:HTMLCanvasElement;let cardIndex=0;let cameraView:View='oblique';const faces=new Map<string,HTMLCanvasElement>();const renderer=new Renderer();
document.body.style.background='#131617';document.title='LORE · 召喚6案';root.innerHTML=`<main><header><div><div class="eyebrow">LORE / MOTION STUDIES — 09 OCT 2026 · MATERIAL STUDIES / REVISION 02</div><h1>炎を纏い、影を紡ぐ。</h1><p>ファイアーマスター・エルサ・アリス。実体のある素材、陰影、接地から組み直した6つの召喚。</p></div><span class="badge">01 SELECTED · 3枚に採用</span></header><nav class="toolbar" aria-label="表示"><button data-mode="grid" class="active">6案を比較</button><button data-mode="detail">1案を拡大</button><button data-mode="board">実盤面</button><span class="spacer"></span><select id="card" aria-label="カード">${cards.map((id,i)=>`<option value="${id}">${names[i]}</option>`).join('')}</select><select id="camera" aria-label="視点"><option value="oblique">斜めから</option><option value="top">真上から</option><option value="side">横から</option></select><button id="theme">白い盤面</button><label><input id="reduced" type="checkbox">動きを低減</label></nav><div class="status" id="status">カードと描画素材を準備中…</div><section class="stage"><div class="grid" id="grid">${designs.map((d,i)=>`<article><div class="label"><small>0${i+1} / ${d.en}</small><strong>${d.name}</strong></div><canvas data-v="${i}" aria-label="${d.name}"></canvas><div class="foot"><p>${d.note}</p><button data-zoom="${i}">拡大 ↗</button></div></article>`).join('')}</div><div class="detail" id="detail" hidden><canvas id="large" aria-label="選択した召喚演出"></canvas><aside>${designs.map((d,i)=>`<button data-select="${i}">0${i+1}　${d.name}</button>`).join('')}<p id="intent"></p></aside></div><div id="board" hidden><div class="board-options">${designs.map((d,i)=>`<button data-select="${i}">${i+1} ${d.name}</button>`).join('')}<button id="side">自分側</button><button id="multi">1枚</button></div><div class="board-wrap"><iframe title="LORE 実盤面で召喚を確認" src="about:blank"></iframe></div></div></section><div class="timeline"><button id="play">再生</button><button id="reset" aria-label="最初へ">↺</button><select id="speed" aria-label="再生速度"><option value="1">1×</option><option value="0.5">0.5×</option><option value="0.25">0.25×</option></select><input id="seek" aria-label="時刻" type="range" min="0" max="3800" value="0"><output id="time">0.00 / 3.80</output><span class="phase" id="phase">予兆</span><label style="font-size:11px"><input id="loop" type="checkbox" checked>反復</label></div><div class="notes">炎の内部密度、黒曜の反射、紙の曲がり、素材が落とす影を立体で描画。カードは盤面と平行に降下し、裏面で接地します。<br>カードを選ぶと6案すべてが切り替わります。番号の選択はプレビューのみです。</div><footer>3枚 × 6案 · ①を採用 · その他は比較用試作</footer></main>`;
const $=<T extends HTMLElement=HTMLElement>(s:string)=>root.querySelector<T>(s)!;const frame=$<HTMLIFrameElement>('iframe');
function send(suspend=false){frame.contentWindow?.postMessage(suspend?{kind:'mage-summon-six-suspend'}:{kind:'mage-summon-six-control',variant,ms,side,multi,reduced,dark,card:$<HTMLSelectElement>('#card').value},location.origin);}
function canvasDraw(canvas:HTMLCanvasElement,v:number){const r=canvas.getBoundingClientRect();if(!r.width||!r.height)return;const d=Math.min(devicePixelRatio,1.5),w=Math.round(r.width*d),h=Math.round(r.height*d);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}const c=canvas.getContext('2d')!;c.setTransform(d,0,0,d,0,0);c.clearRect(0,0,r.width,r.height);const cw=Math.min(r.width*.38,r.height*.49);renderer.draw(c,face,v,ms,r.width*.5,r.height*.56,cw,reduced,cardIndex,true,cameraView);}
function draw(){if(!ready||disposed)return;if(mode==='grid')root.querySelectorAll<HTMLCanvasElement>('[data-v]').forEach(c=>canvasDraw(c,Number(c.dataset.v)));else if(mode==='detail')canvasDraw($<HTMLCanvasElement>('#large'),variant);else send();$<HTMLInputElement>('#seek').value=String(ms);$('#time').textContent=`${(ms/1000).toFixed(2)} / 3.80`;$('#phase').textContent=pose(ms,reduced).phase;}
function setMode(next:string){mode=next;for(const id of ['grid','detail','board'])$('#'+id).hidden=id!==mode;root.querySelectorAll<HTMLElement>('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));if(mode==='board'){if(frame.getAttribute('src')==='about:blank')frame.src='/mage-summon-six.html?board';}else{send(true);frame.src='about:blank';}draw();}
function select(v:number){variant=v;root.querySelectorAll<HTMLElement>('[data-select]').forEach(b=>b.classList.toggle('active',Number(b.dataset.select)===v));$('#intent').textContent=designs[v].note;draw();}
async function setCard(id:string){cardIndex=Math.max(0,cards.indexOf(id as typeof cards[number]));$<HTMLSelectElement>('#card').value=cards[cardIndex];face=faces.get(cards[cardIndex])!;draw();}
function pause(){playing=false;cancelAnimationFrame(raf);raf=0;$('#play').textContent='再生';}
function tick(now:number){if(!playing||disposed)return;ms+=Math.max(0,now-last)*speed;last=now;if(ms>DURATION){if(loop)ms=0;else{ms=DURATION;pause();}}draw();if(playing)raf=requestAnimationFrame(tick);}
function play(){if(!ready||disposed)return;if(ms>=DURATION)ms=0;pause();playing=true;last=performance.now();$('#play').textContent='一時停止';raf=requestAnimationFrame(tick);}
root.querySelectorAll<HTMLElement>('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode!));root.querySelectorAll<HTMLElement>('[data-zoom]').forEach(b=>b.onclick=()=>{select(Number(b.dataset.zoom));setMode('detail');});root.querySelectorAll<HTMLElement>('[data-select]').forEach(b=>b.onclick=()=>select(Number(b.dataset.select)));
$<HTMLSelectElement>('#camera').onchange=()=>{cameraView=$<HTMLSelectElement>('#camera').value as View;draw();};
$('#play').onclick=()=>playing?pause():play();$('#reset').onclick=()=>{ms=0;draw();};$<HTMLInputElement>('#seek').oninput=()=>{pause();ms=Number($<HTMLInputElement>('#seek').value);draw();};$<HTMLSelectElement>('#speed').onchange=()=>speed=Number($<HTMLSelectElement>('#speed').value);$<HTMLInputElement>('#loop').onchange=()=>loop=$<HTMLInputElement>('#loop').checked;
$('#theme').onclick=()=>{dark=!dark;root.classList.toggle('dark',dark);$('#theme').textContent=dark?'暗い盤面':'白い盤面';draw();};$('#side').onclick=()=>{side=1-side;$('#side').textContent=side?'相手側':'自分側';draw();};$('#multi').onclick=()=>{multi=!multi;$('#multi').textContent=multi?'3枚同時':'1枚';draw();};
function reduce(value:boolean){reduced=value;$<HTMLInputElement>('#reduced').checked=value;if(value){pause();ms=DURATION;loop=false;$<HTMLInputElement>('#loop').checked=false;}draw();}$<HTMLInputElement>('#reduced').onchange=()=>reduce($<HTMLInputElement>('#reduced').checked);matchMedia('(prefers-reduced-motion:reduce)').addEventListener('change',e=>reduce(e.matches));
$<HTMLSelectElement>('#card').onchange=async()=>{pause();await setCard($<HTMLSelectElement>('#card').value);};
window.addEventListener('resize',draw);window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==frame.contentWindow)return;if(e.data?.kind==='mage-summon-six-ready'){if(mode==='board')send();}if(e.data?.kind==='mage-summon-six-error')$('#status').textContent='盤面の準備に失敗: '+e.data.error;});
document.addEventListener('visibilitychange',()=>{if(document.hidden){pause();send(true);}});window.addEventListener('pagehide',()=>{pause();disposed=true;renderer.dispose();send(true);},{once:true});
(window as any).mageLab={get ready(){return ready;},get state(){return{revision:2,mode,variant,ms,playing,reduced,side,multi,card:cards[cardIndex],cameraView,renderer:renderer.status};},seek(t:number,v=variant){pause();ms=t;select(v);},setCard,setMode,setView(v:View){cameraView=v;$<HTMLSelectElement>('#camera').value=v;draw();},setSide(s:number){side=s;$('#side').textContent=side?'相手側':'自分側';draw();},setMulti(v:boolean){multi=v;$('#multi').textContent=multi?'3枚同時':'1枚';draw();},reduce,play,pause};
void(async()=>{for(const id of cards)faces.set(id,await surface(id));face=faces.get(cards[0])!;ready=true;select(0);$('#status').textContent='6案は同時再生。拡大では質感、実盤面ではカード実寸と隣接情報を確認できます。';if(reduced)reduce(true);else if(!new URLSearchParams(location.search).has('qa'))play();})().catch(e=>{$('#status').textContent='準備に失敗: '+e.message;});
