import {studies,groupLabel,beforeCount,afterCount} from './catalog';
import type {Study} from './catalog';
import {Renderer,loadAssets} from './renderer';
import './style.css';
const app=document.getElementById('app')!;
app.innerHTML=`<main class="wrap"><p class="footnote"><a href="/dew-liquid-five.html">液体の雫を作り直した新しい5案を見る →</a></p><header><div><p class="eyebrow">LORE / MATERIAL & MOTION STUDIES</p><h1>一滴から、満ちていく。</h1><p>雫の初回・追加付与、各3案。翡翠の液体、濡れた反射、表面張力を比較。<br>初回は状態の成立、追加は既存の状態を保った強化を描きます。</p></div><div class="edition">06 MOTION STUDIES<br>02 GROUPS × 03 DIRECTIONS<br><span class="badge">比較試作 · 採用前</span></div></header><nav class="tabs" aria-label="演出グループ"></nav><div class="toolbar"><button id="play">一時停止</button><button id="restart">先頭から</button><label>速度<select id="speed"><option value="1">1×</option><option value=".5">0.5×</option><option value=".25">0.25×</option></select></label><label><input id="loop" type="checkbox" checked>ループ</label><span class="spacer"></span><button id="bg">暗い背景</button><button id="side">相手側</button><button id="view">実盤面</button><label><input id="reduced" type="checkbox">動きを低減</label><label><input id="multi" type="checkbox">両側同時</label></div><section class="hero"><div class="screen"><canvas id="hero" width="1280" height="740" aria-label="選択したアニメーション"></canvas><iframe title="LORE実盤面で演出比較" src="/dew-grant-board.html"></iframe></div><aside class="detail"></aside></section><div class="timeline"><span class="time" id="time">0.00 / 2.40s</span><input id="seek" aria-label="再生位置" type="range" min="0" max="1000" value="0"><span class="stats" id="ready">素材を準備中</span></div><div class="section-head"><h3>3案を同時比較</h3><span>同じ進行率で再生。選択すると上部に拡大します。</span></div><section class="grid"></section><p class="footnote">比較値：初回 0 → 3 ／ 追加 5 → 8。接触と液体の定着に合わせて、一度だけ加算します。<br>既存の雫アイコン・カード絵を用いた比較試作です。追加では元の雫と数値を保持します。</p><details><summary>参照・制作判断</summary><p>シールド／烙印の20案と、選定後の「線を綺麗でリアルに光らせる」という修正方針を参照。雫は青白の盾・朱色の烙印と区別し、深い翡翠、薄い真珠色の反射、金の器で描きます。<br>承認済み「銀紋の流墨」の、発生源の表面 → 同じ物質の移動 → 到着での変形という連続性を用います。実盤面はGameViewの模擬状態です。ゲームイベントへの接続とステージング公開は案選定後。</p></details></main>`;
const el=<T extends HTMLElement>(s:string)=>document.querySelector<T>(s)!;
const hero=el<HTMLCanvasElement>('#hero'),iframe=el<HTMLIFrameElement>('iframe'),seek=el<HTMLInputElement>('#seek');
const params=new URLSearchParams(location.search);let selected=studies.find(s=>s.id===params.get('id'))??studies[0],playing=!params.has('paused'),progress=0,speed=1,dark=false,side=0,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,board=false,multi=false,boardReady=false,disposed=false,last=performance.now(),raf=0,renderer:Renderer;
let group:Study[]=[],tiles:HTMLCanvasElement[]=[],frames=0,totalCost=0;el<HTMLInputElement>('#reduced').checked=reduced;if(reduced)playing=false;
function send(){if(!boardReady)return;iframe.contentWindow?.postMessage({kind:'dew-grant-control',id:selected.id,ms:Math.min(1,progress)*selected.duration,side,reduced,multi,dark,active:board&&!document.hidden},location.origin);}
function draw(){if(!renderer||disposed)return;const start=performance.now(),ms=Math.min(1,progress)*selected.duration;renderer.draw(hero,selected,ms,dark,side,reduced);group.forEach((s,i)=>renderer.draw(tiles[i],s,Math.min(1,progress)*s.duration,dark,side,reduced));seek.value=String(Math.min(1,progress)*1000);el('#time').textContent=`${(ms/1000).toFixed(2)} / ${(selected.duration/1000).toFixed(2)}s`;const contact=selected.contact/selected.duration;el('.phase').textContent=progress<.1?'予兆':progress<contact?'変形・定着':progress<.93?'付与成立・収束':'状態保持';el('.counter').textContent=`${progress>=contact?afterCount(selected):beforeCount(selected)}`;send();frames++;totalCost+=performance.now()-start;}
function select(s:Study){selected=s;progress=0;const old=group[0];if(!old||old.family!==s.family||old.mode!==s.mode){group=studies.filter(x=>x.family===s.family&&x.mode===s.mode);el('.grid').innerHTML=group.map(x=>`<button class="tile" data-id="${x.id}" aria-label="${x.id} ${x.name}を拡大"><canvas width="768" height="444"></canvas><div class="tile-body"><span class="id">${x.id} / ${x.material}</span><h3>${x.name}</h3><p>${x.description}</p></div></button>`).join('');tiles=Array.from(document.querySelectorAll<HTMLCanvasElement>('.tile canvas'));document.querySelectorAll<HTMLButtonElement>('.tile').forEach(b=>b.onclick=()=>select(studies.find(x=>x.id===b.dataset.id)!));}
 el('.detail').innerHTML=`<span class="id">${s.id} / ${groupLabel(s.family,s.mode)}</span><h2>${s.name}</h2><span class="material">${s.material}</span><p class="description">${s.description}</p><div class="phase">予兆</div><div class="counter">${beforeCount(s)}</div><span class="stats">${beforeCount(s)} → ${afterCount(s)} · ${(s.duration/1000).toFixed(2)}秒</span>`;
 document.querySelectorAll<HTMLButtonElement>('.tabs button').forEach((b,i)=>b.setAttribute('aria-pressed',String(studies[i*3].family===s.family&&studies[i*3].mode===s.mode)));document.querySelectorAll<HTMLButtonElement>('.tile').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.id===s.id)));history.replaceState(null,'',`?id=${s.id}${playing?'':'&paused=1'}`);draw();}
el('.tabs').innerHTML=[0,3].map(i=>`<button data-index="${i}">${groupLabel(studies[i].family,studies[i].mode)}<small>03</small></button>`).join('');document.querySelectorAll<HTMLButtonElement>('.tabs button').forEach(b=>b.onclick=()=>select(studies[Number(b.dataset.index)]));
el('#play').onclick=()=>{playing=!playing;last=performance.now();el('#play').textContent=playing?'一時停止':'再生'};
el('#restart').onclick=()=>{progress=0;draw()};el<HTMLSelectElement>('#speed').onchange=e=>speed=Number((e.target as HTMLSelectElement).value);
seek.oninput=()=>{progress=Number(seek.value)/1000;playing=false;el('#play').textContent='再生';draw()};
el('#bg').onclick=()=>{dark=!dark;el('#bg').textContent=dark?'白い背景':'暗い背景';draw()};el('#side').onclick=()=>{side=1-side;el('#side').textContent=side?'自分側':'相手側';draw()};
el('#view').onclick=()=>{board=!board;el('.screen').classList.toggle('board',board);el('#view').textContent=board?'拡大表示':'実盤面';draw()};
el<HTMLInputElement>('#reduced').onchange=e=>{reduced=(e.target as HTMLInputElement).checked;draw()};el<HTMLInputElement>('#multi').onchange=e=>{multi=(e.target as HTMLInputElement).checked;draw()};
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==iframe.contentWindow)return;if(e.data?.kind==='dew-grant-ready'){boardReady=true;send();}if(e.data?.kind==='dew-grant-error'){el('#ready').textContent='盤面: '+e.data.error;}});
function tick(now:number){if(disposed)return;const dt=Math.max(0,now-last);last=now;if(playing&&!document.hidden&&renderer){progress+=dt*speed/selected.duration;if(progress>1.25){if(el<HTMLInputElement>('#loop').checked)progress=0;else{progress=1;playing=false;el('#play').textContent='再生';}}draw();}raf=requestAnimationFrame(tick);}
document.addEventListener('visibilitychange',()=>{last=performance.now();send();});window.addEventListener('pagehide',()=>{disposed=true;cancelAnimationFrame(raf);renderer?.dispose();iframe.contentWindow?.postMessage({kind:'dew-grant-dispose'},location.origin)},{once:true});
(window as any).dewGrant={select:(id:string)=>select(studies.find(s=>s.id===id)!),seek:(p:number)=>{playing=false;progress=p;draw()},configure:(o:any)=>{if(o.dark!==undefined)dark=o.dark;if(o.side!==undefined)side=o.side;if(o.reduced!==undefined)reduced=o.reduced;if(o.multi!==undefined)multi=o.multi;if(o.board!==undefined){board=o.board;el('.screen').classList.toggle('board',board);}draw()},get state(){return {id:selected.id,progress,playing,boardReady,frames,meanDrawMs:totalCost/frames,studies:studies.length,count:progress>=selected.contact/selected.duration?afterCount(selected):beforeCount(selected)}}};
select(selected);void loadAssets().then(a=>{renderer=new Renderer(a);el('#ready').textContent=renderer.surface.gl?'6案 準備完了':'Canvas代替表示（表面の反射を省略）';el('#play').textContent=playing?'一時停止':'再生';draw();raf=requestAnimationFrame(tick)}).catch(e=>{el('#ready').className='error';el('#ready').textContent=String(e)});
