import {ghostDie,setFxSkip} from '../ui/anim';
import '../styles/tokens.css';import '../styles/base.css';import '../styles/card.css';import '../styles/game-overlays.css';import '../styles/game.css';import '../styles/screens.css';import '../styles/reading-board.css';import '../styles/presentation.css';
import {GameView,setMyAvatar,setOppAvatar} from '../ui/boardView';import {startBoardLayout} from '../ui/layout';import {waitForDuel} from '../ui/duelReadiness';import {clearMonsterStates} from '../ui/monster/runtime';import {createGame} from '../shared/engine';import {DB} from '../shared/cards';import {setLang} from '../i18n';
setLang('ja');setMyAvatar('SEEKER_BLUE');setOppAvatar('SEEKER_RED');document.body.style.cssText='margin:0;overflow:hidden;background:#eeeae4';const style=document.createElement('style');style.textContent='.topbar,.help-callout,.help-fab,.mute-fab{display:none!important}';document.head.append(style);
const root=document.getElementById('app')!,noop=()=>{};const view=new GameView(root,0,{onPlay:noop,onBlockedPlay:noop,onAttack:noop,onBlockedAttack:noop,onReorder:noop,onChooseTarget:noop,onBuyMarket:noop,onBuySupply:noop,onRefresh:noop,onEndTurn:noop,onSurrender:noop});
const g=createGame({mode:'bot',seed:71,starting:0,p0:{id:'mana-study-self',name:'YOU'},p1:{id:'mana-study-opp',name:'OPPONENT'}}).state;g.turn=3;g.pending=null;g.phase='main';for(const [i,p]of g.players.entries()){p.openingDrawReady=false;p.mana=8;p.maxMana=12;p.hp=30;p.enchants=[{card:{...DB.E3,uid:`mana-spell-${i}`},turns:4,bornTurn:1}];p.quests=[];p.traps=[];p.field=['M4','ELF','GM6_0'].map((id,j)=>({...DB[id],uid:`mana-mon-${i}-${j}`,exhausted:false,summonedTurn:0,dmg:0,tempAtk:0,atkMod:0,defMod:0}));p.hand=[{...DB.M4,uid:`mana-hand-${i}`}];p.discard=[{...DB.ELF,uid:`mana-shelf-${i}`}];}view.render(g);view.setHandOpen(false);clearMonsterStates(root);const stop=startBoardLayout();

const initial=JSON.stringify(g);const panel=document.createElement('div');panel.style.cssText='position:fixed;bottom:8px;left:8px;z-index:200;background:#101c30;color:white;padding:12px;display:flex;gap:8px';panel.innerHTML=`<select id="qa-side"><option value="0">自分</option><option value="1">相手</option></select><select id="qa-kind"><option value="mon">モンスター</option><option value="spell">残存魔法</option></select><label><input id="qa-empty" type="checkbox">空墓地</label><button id="qa-play">01を再生</button><button id="qa-multi">2枚同時</button><button id="qa-skip">スキップ</button><button id="qa-reset">戻す</button><span id="qa-status">準備中</span>`;document.body.append(panel);
const status=panel.querySelector('#qa-status')!;let busy=false;
function reset(){setFxSkip(true);Object.assign(g,JSON.parse(initial));if(panel.querySelector<HTMLInputElement>('#qa-empty')!.checked)g.players.forEach(p=>p.discard=[]);view.render(g);view.setHandOpen(false);clearMonsterStates(root);setFxSkip(false);status.textContent='準備完了';}
async function play(multi=false){if(busy)return;reset();busy=true;const side=Number((panel.querySelector('#qa-side') as HTMLSelectElement).value),spell=(panel.querySelector('#qa-kind') as HTMLSelectElement).value==='spell',ids=spell?[`mana-spell-${side}`]:[1,...(multi?[0]:[])].map(i=>`mana-mon-${side}-${i}`);status.textContent='再生中';try{await Promise.all(ids.map(async uid=>{const node=root.querySelector<HTMLElement>(`[data-uid="${uid}"]`)!;await ghostDie(node,side?'opp':'me');const p=g.players[side];if(spell){const old=p.enchants.find(e=>e.card.uid===uid);if(old)p.discard.push(old.card);p.enchants=p.enchants.filter(e=>e.card.uid!==uid);}else{const old=p.field.find(c=>c.uid===uid);if(old)p.discard.push(old);p.field=p.field.filter(c=>c.uid!==uid);}}));view.render(g);status.textContent='墓地へ復元・完了';}finally{busy=false;}}
panel.querySelector<HTMLButtonElement>('#qa-play')!.onclick=()=>void play();panel.querySelector<HTMLButtonElement>('#qa-multi')!.onclick=()=>void play(true);panel.querySelector<HTMLButtonElement>('#qa-skip')!.onclick=()=>setFxSkip(true);panel.querySelector<HTMLButtonElement>('#qa-reset')!.onclick=reset;
window.addEventListener('pagehide',()=>{setFxSkip(true);stop();view.destroy();});void waitForDuel(root).then(()=>{status.textContent='準備完了';});
const recordButton=document.createElement('button');recordButton.textContent='録画して再生';recordButton.id='qa-record';panel.append(recordButton);
recordButton.onclick=()=>{let recorder:MediaRecorder|undefined;const chunks:Blob[]=[];const observer=new MutationObserver(()=>{const canvas=document.querySelector<HTMLCanvasElement>('.mana-destruction');if(canvas&&!recorder){const stream=canvas.captureStream(30);recorder=new MediaRecorder(stream,{mimeType:'video/webm'});recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(chunks,{type:'video/webm'}));a.download='mana-adoption-runtime.webm';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000);};recorder.start();}else if(!canvas&&recorder?.state==='recording'){recorder.stop();observer.disconnect();}});observer.observe(document.body,{childList:true});void play().finally(()=>{observer.disconnect();if(recorder?.state==='recording')recorder.stop();});};

const metrics=document.createElement('span');metrics.id='qa-metrics';panel.append(metrics);window.addEventListener('lore:mana-destruction-finished',e=>{metrics.textContent=JSON.stringify((e as CustomEvent).detail);});
