import '../styles/loungeHorizon.css';
import './menuEvolutionScene.css';
import {loungeNavGlyph} from '../ui/loungeNavGlyphs';
import {mountLoungeNavMotion} from '../ui/loungeNavMotion';
import {studies,type StudyGroup} from './menuEvolutionData';
if(import.meta.env.DEV){
 const params=new URLSearchParams(location.search);
 const group:StudyGroup=params.get('group')==='header'?'header':params.get('group')==='secondary'?'secondary':'home';
 const number=(key:string,fallback=1)=>Math.min(5,Math.max(0,Number(params.get(key)??fallback)||0));
 const variant=number('v')||1,combined=params.has('combined');
 const header=combined?number('a'):group==='header'?variant:0;
 const home=combined?number('b'):group==='home'?variant:0;
 const secondary=combined?number('c'):group==='secondary'?variant:1;
 let page=params.get('page')==='shop'?'shop':group==='secondary'?'leaderboard':'home';
 let mode=0,theme=0,rank=0,deck=0,speed=1,reduce=false;let cleanup=()=>{};let motions:Animation[]=[];let motionRun=0;
 const labels=['ホーム','デッキ','カード','ランキング','フレンド','ショップ','遊び方'];
 const keys=['home','deck','cards','leaderboard','friends','shop','tutorial'];
 const themes=['astral','verdant','crimson','ivory'],themeNames=['星図','翠葉','緋印','白銀'];
 const modes=['ランク対戦','ノーマル対戦','BOT対戦'];
 const names=['Aster','Lunaria','Shion','Noctis','シーカー'];
 const nums=[1,2,3,4,26],ratings=[1820,1794,1730,1692,1184];
 const root=document.querySelector<HTMLElement>('#app')!;
 root.innerHTML=`<div class="lounge-shell horizon-nav evo-shell" data-header="${header}" data-home="${home}" data-secondary="${secondary}"><div class="scene-shade"></div><header class="evo-header"></header><main class="evo-content"></main><aside class="lounge-rail"><nav aria-label="メインメニュー">${keys.map((key,i)=>`<button data-nav="${key}">${loungeNavGlyph(i)}<span>${labels[i]}</span></button>`).join('')}</nav></aside><div class="evo-toast" role="status"></div></div>`;
 const shell=root.firstElementChild as HTMLElement,nav=shell.querySelector<HTMLElement>('nav')!,content=shell.querySelector<HTMLElement>('main')!;
 const logo='<img class="evo-logo" src="/art/brand/lore-logo-transparent.webp" alt="LORE">';
 const profile=`<button class="evo-profile" data-action="profile"><span class="profile-portrait"></span><span><b>シーカー</b><small>SEEKER · LV. 7</small></span></button>`;
 const balance='<button class="evo-balance" data-action="shards"><span>◇</span><b>840</b><small>SHARDS</small></button>';
 const utility='<button class="evo-utility" data-action="menu" aria-label="メニュー"><span></span><span></span></button>';
 function paintHeader(){const title=page==='home'?'ビブリオン':labels[keys.indexOf(page)]??'ビブリオン';shell.querySelector('header')!.innerHTML=`<a class="evo-brand" href="#" aria-label="ホーム">${logo}</a>${header===4?`<div class="chapter-title"><small>BIBLION / ${page==='home'?'HOME':page.toUpperCase()}</small><b>${title}</b></div>`:''}${profile}<div class="header-tools">${balance}${utility}</div>`;shell.querySelector<HTMLAnchorElement>('.evo-brand')!.onclick=e=>{e.preventDefault();navigate('home')};}
 const deckArt=()=>`<div class="deck-fan">${(deck?['ELF','HIGH_ELF','ELF_HAVEN']:['STARTER_CHEST','STARTER_MANA','STARTER_TRASH']).map((id,i)=>`<img style="--card:${i}" src="/art/cards/${id}.webp" alt="">`).join('')}</div>`;
 const deckLine=()=>`<button class="evo-deck" data-action="deck">${deckArt()}<span><small>使用デッキ</small><b>${deck?'翠葉の記録':'スターターデッキ'}</b><em>デッキを変更</em></span><i>↗</i></button>`;
 const modeTabs=()=>`<div class="mode-tabs" role="group" aria-label="対戦モード">${modes.map((m,i)=>`<button data-mode="${i}" aria-pressed="${mode===i}">${m.replace('対戦','')}</button>`).join('')}</div>`;
 const rankInfo=()=>'<div class="rank-note"><span>GOLD</span><b>1,184 <small>MMR</small></b><em>SEASON 2026.09</em></div>';
 const start=()=>`<button class="evo-start" data-action="start"><span>${mode===2?'練習を始める':'対戦する'}</span><i>→</i></button>`;
 function paintHome(){
  const intro=`<div class="duel-title"><small>BIBLION / DUEL</small><h1>${modes[mode]}</h1><p>${mode===0?'未知の記録に、触れる。':mode===1?'自分のペースで、対戦を。':'カードの使い方を、確かめる。'}</p></div>`;
  if(home===0){content.innerHTML=`<section class="home-study original-home">${rankInfo()}<button class="original-sigil" data-action="start"><strong>ランク対戦</strong><small>デュエルへ</small></button><div class="original-modes"><button data-mode="1">ノーマル対戦</button><button data-mode="2">BOT対戦</button></div>${deckLine()}</section>`;return}
  if(home===4){content.innerHTML=`<section class="home-study mode-stage"><small class="eyebrow">CHOOSE YOUR DUEL</small><h1>次のデュエルへ。</h1><div class="mode-choices">${modes.map((m,i)=>`<button data-mode="${i}" aria-pressed="${mode===i}"><i>0${i+1}</i><span><b>${m}</b><small>${['ランクをかけて、記録を広げる','MMRを気にせず、自由に対戦','BOTと、じっくり練習する'][i]}</small></span><em>${mode===i?'↗':'+'}</em></button>`).join('')}</div>${deckLine()}${start()}</section>`;return}
  if(home===2){content.innerHTML=`<section class="home-study sigil-study">${modeTabs()}<button class="quiet-sigil" data-action="start"><img src="/art/lounge/stage-v1/sigil.webp" alt=""><span><small>DUEL</small><strong>${modes[mode]}</strong><em>対戦する →</em></span></button>${rankInfo()}${deckLine()}</section>`;return}
  if(home===3){content.innerHTML=`<section class="home-study paper-invitation"><div class="ticket-top"><small>BIBLION</small><i>01 / DUEL</i></div>${intro}${rankInfo()}${modeTabs()}${deckLine()}${start()}</section>`;return}
  if(home===5){content.innerHTML=`<section class="home-study deck-first"><div class="duel-title"><small>YOUR NEXT CHAPTER</small><h1>このデッキで、挑む。</h1></div><button class="showcase-deck" data-action="deck">${deckArt()}<span>${deck?'翠葉の記録':'スターターデッキ'} <i>↗</i></span></button>${modeTabs()}${rankInfo()}${start()}</section>`;return}
  content.innerHTML=`<section class="home-study type-invitation">${intro}${rankInfo()}${modeTabs()}${deckLine()}${start()}</section>`;
 }
 function rankPage(){return `<div class="secondary-summary"><img src="/art/tiers/gold.webp" alt="ゴールド"><div><small>あなたの現在地</small><strong>#26</strong><span>GOLD · 1,184 MMR</span></div></div><div class="secondary-toolbar"><span>SEASON 2026.09</span><button data-action="rule">ランクのしくみ ↗</button></div><div class="ranking-list">${names.map((n,i)=>`<button class="ranking-row ${rank===i?'selected':''} ${i===4?'is-you':''}" data-rank="${i}"><i>${String(nums[i]).padStart(2,'0')}</i><span class="row-portrait" style="--portrait:${i}"></span><b>${n}${i===4?'<small>YOU</small>':''}</b><span>${i===4?'GOLD':'MASTER'}</span><strong>${ratings[i].toLocaleString()}</strong></button>`).join('')}</div><aside class="detail-panel"><small>SELECTED SEEKER</small><h2>${names[rank]}</h2><span class="detail-rank">#${nums[rank]}</span><p>${ratings[rank].toLocaleString()} MMR</p><span>${rank===4?'GOLD':'MASTER'}</span><button data-action="profile">プロフィールを見る ↗</button></aside>`}
 function shopPage(){return `<div class="secondary-summary"><img src="/cosmetics/v2/sleeve-${themes[theme]}.webp" alt="${themeNames[theme]}のスリーブ"><div><small>選択中のスリーブ</small><strong>${themeNames[theme]}</strong><span>カードの裏面を、自分の色に。</span></div></div><div class="secondary-toolbar"><span>スリーブ · 4種類</span><button data-action="rule">装備について ↗</button></div><div class="shop-collection">${themes.map((t,i)=>`<button class="cosmetic-choice ${i===theme?'selected':''}" data-theme="${i}"><span><img src="/cosmetics/v2/sleeve-${t}.webp" alt="${themeNames[i]}のスリーブ"></span><b>${themeNames[i]}</b><small>${i===theme?'選択中':'プレビュー'}</small></button>`).join('')}</div><aside class="detail-panel"><small>SELECTED SLEEVE</small><img class="detail-sleeve" src="/cosmetics/v2/sleeve-${themes[theme]}.webp" alt=""><h2>${themeNames[theme]}のスリーブ</h2><p>デッキの外観から装備できます。</p><button data-action="try">試着する ↗</button></aside>`}
 function otherPage(){return `<div class="secondary-summary"><div><small>BIBLION</small><strong>${labels[keys.indexOf(page)]}</strong><span>情報面の構成を確認するためのサンプル</span></div></div><div class="secondary-toolbar"><span>RECORDS</span><button data-action="rule">ヘルプ ↗</button></div><div class="ranking-list">${['最近の記録','お気に入り','すべての記録'].map((n,i)=>`<button class="ranking-row" data-rank="${i}"><i>0${i+1}</i><b>${n}</b><span>↗</span></button>`).join('')}</div>`}
 function paintSecondary(){const title=labels[keys.indexOf(page)]??'ランキング';content.innerHTML=`<section class="secondary-study"><header class="secondary-heading"><small>BIBLION / ${page.toUpperCase()}</small><h1>${title}</h1><p>${page==='shop'?'あなたのデッキに、しるしを。':'シーカーたちの、現在地。'}</p><div class="secondary-index"><button data-page="leaderboard" aria-pressed="${page==='leaderboard'}">ランキング</button><button data-page="shop" aria-pressed="${page==='shop'}">ショップ</button></div></header><div class="secondary-body">${page==='shop'?shopPage():page==='leaderboard'?rankPage():otherPage()}</div></section>`}
 function animate(){const run=++motionRun;motions.forEach(a=>a.cancel());motions=[];shell.dataset.motion='settled';if(reduce||matchMedia('(prefers-reduced-motion:reduce)').matches)return;shell.dataset.motion='running';const elements=content.querySelectorAll('.duel-title,.rank-note,.evo-deck,.evo-start,.secondary-heading,.secondary-summary,.ranking-list,.shop-collection');elements.forEach((e,i)=>motions.push(e.animate([{opacity:.35,transform:'translateY(8px)'},{opacity:1,transform:'translateY(0)'}],{duration:360/speed,delay:Math.min(i,3)*45/speed,easing:'cubic-bezier(.16,.8,.2,1)',fill:'backwards'})));Promise.all(motions.map(a=>a.finished.catch(()=>{}))).then(()=>{if(run===motionRun)shell.dataset.motion='settled'});}
 function update(){shell.dataset.page=page;paintHeader();page==='home'?paintHome():paintSecondary();bind();}
 function navigate(key:string){const previous=page;page=key;update();cleanup();nav.querySelector('.horizon-cursor')?.remove();nav.querySelectorAll<HTMLButtonElement>('button').forEach(b=>{if(b.dataset.nav===page)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});cleanup=mountLoungeNavMotion(nav,previous);animate();}
 let toastTimer=0;
 function toast(text:string){const target=shell.querySelector<HTMLElement>('.evo-toast')!;target.textContent=text;target.classList.add('visible');clearTimeout(toastTimer);toastTimer=window.setTimeout(()=>target.classList.remove('visible'),1800)}
 function bind(){shell.querySelectorAll<HTMLButtonElement>('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='deck'){deck=1-deck;update();animate()}else toast(a==='start'?`プレビュー：${modes[mode]}を開始する操作`:a==='try'?`プレビュー：${themeNames[theme]}を試着中`:'プレビュー：この操作の配置を確認できます')});content.querySelectorAll<HTMLButtonElement>('[data-mode]').forEach(b=>b.onclick=()=>{mode=Number(b.dataset.mode);update();animate()});content.querySelectorAll<HTMLButtonElement>('[data-theme]').forEach(b=>b.onclick=()=>{theme=Number(b.dataset.theme);update();animate()});content.querySelectorAll<HTMLButtonElement>('[data-rank]').forEach(b=>b.onclick=()=>{rank=Number(b.dataset.rank);update();animate()});content.querySelectorAll<HTMLButtonElement>('[data-page]').forEach(b=>b.onclick=()=>navigate(b.dataset.page!));}
 nav.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.onclick=()=>navigate(b.dataset.nav!));
 window.addEventListener('message',event=>{if(event.origin!==location.origin||event.source!==parent)return;if(event.data?.type==='evo-replay')animate();if(event.data?.type==='evo-settings'){speed=event.data.slow?.5:1;reduce=event.data.reduced===true;shell.classList.toggle('reduced',reduce);if(reduce)motions.forEach(a=>a.cancel())}});
 navigate(page);document.title=`${studies[group].label} / ${variant} ${studies[group].variants[variant-1][0]}`;
}
