import '../../styles/tokens.css';import '../../styles/base.css';import '../../styles/card.css';import '../../styles/game-overlays.css';import '../../styles/game.css';import '../../styles/screens.css';import '../../styles/reading-board.css';import '../../styles/presentation.css';
import {GameView,setMyAvatar,setOppAvatar} from '../../ui/boardView';import {startBoardLayout} from '../../ui/layout';import {waitForDuel} from '../../ui/duelReadiness';import {projectedPlacement} from '../../ui/boardProjection';import {clearMonsterStates} from '../../ui/monster/runtime';import {createGame} from '../../shared/engine';import {DB} from '../../shared/cards';import {setLang} from '../../i18n';
import {DURATION,demons,ease,type Demon} from './catalog';import {DemonRenderer} from './renderer';import {surface} from './surface';
setLang('ja');setMyAvatar('SEEKER_BLUE');setOppAvatar('SEEKER_RED');
document.body.style.cssText='margin:0;overflow:hidden;background:#f2eee8';const style=document.createElement('style');style.textContent='.topbar,.help-callout,.help-fab,.mute-fab{display:none!important}';document.head.append(style);
const root=document.getElementById('app')!,noop=()=>{};const view=new GameView(root,0,{onPlay:noop,onBlockedPlay:noop,onAttack:noop,onBlockedAttack:noop,onReorder:noop,onChooseTarget:noop,onBuyMarket:noop,onBuySupply:noop,onRefresh:noop,onEndTurn:noop,onSurrender:noop});
const renderer=new DemonRenderer(),faces=new Map<Demon,HTMLCanvasElement>();const rig=document.createElement('div');rig.style.cssText='position:fixed;left:0;top:0;width:180px;height:280px;transform-origin:0 0;pointer-events:none;z-index:180;';const canvas=document.createElement('canvas');canvas.width=720;canvas.height=960;canvas.style.cssText='position:absolute;left:-150px;top:-180px;width:480px;height:640px;';rig.append(canvas);document.body.append(rig);const ctx=canvas.getContext('2d')!;
let id:Demon='TDE1',side=0,variant=0,ms=0,reduced=false,ready=false,disposed=false,stopLayout=()=>{},original:HTMLElement|null=null;
const makeMon=(card:string,uid:string)=>({...DB[card],uid,exhausted:false,summonedTurn:0,dmg:0,tempAtk:0,atkMod:0,defMod:0});
function setupState(){if(original)original.style.visibility='';const g=createGame({mode:'bot',seed:71,starting:0,p0:{id:'demon-preview-self',name:'YOU'},p1:{id:'demon-preview-opp',name:'OPPONENT'}}).state;g.turn=3;g.pending=null;g.phase='main';for(const [i,p]of g.players.entries()){p.openingDrawReady=false;p.mana=12;p.maxMana=12;p.hp=30;p.enchants=[];p.quests=[];p.traps=[];p.field=[makeMon('M4',`demon-left-${i}`),makeMon(i===side?id:'ELF',`demon-target-${i}`),makeMon('GM6_0',`demon-right-${i}`)];p.hand=[{...DB.M4,uid:`demon-hand-${i}`}];}view.render(g);view.setHandOpen(false);clearMonsterStates(root);original=root.querySelector<HTMLElement>(`.card[data-uid="demon-target-${side}"]`);}
function mix(a:DOMMatrix,b:DOMMatrix,t:number){const x=a.toFloat64Array(),y=b.toFloat64Array();return new DOMMatrix(Array.from(x,(v,i)=>v+(y[i]-v)*t));}
function draw(){if(!ready||disposed||!original)return;const active=ms<DURATION;original.style.visibility=active?'hidden':'visible';rig.style.visibility=active?'visible':'hidden';if(!active)return;const end=projectedPlacement(original,180,280);
 const s=Math.min(innerWidth/1100,innerHeight/760,.7),start=new DOMMatrix().translate(innerWidth*.5-90*s,side?innerHeight*.15:innerHeight*.66).scale(s);
 const progress=reduced?1:ease(0,2900,ms);rig.style.transform=mix(start,end,progress).toString();ctx.setTransform(1.5,0,0,1.5,0,0);ctx.clearRect(0,0,480,640);renderer.draw(ctx,faces.get(id)!,id,variant,ms,240,320,180,reduced);
}
function suspend(){if(original)original.style.visibility='';rig.style.visibility='hidden';}
function dispose(){if(disposed)return;suspend();disposed=true;renderer.dispose();rig.remove();stopLayout();view.destroy();faces.clear();}
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent)return;if(e.data?.kind==='demon-suspend'){suspend();return;}if(e.data?.kind!=='demon-control')return;const d=e.data;const next=demons.includes(d.id)?d.id:id,nextSide=d.side===1?1:0;if(next!==id||nextSide!==side){id=next;side=nextSide;setupState();}variant=Math.max(0,Math.min(2,Number(d.variant)||0));ms=Math.max(0,Math.min(DURATION,Number(d.ms)||0));reduced=!!d.reduced;root.style.filter=d.dark?'brightness(.70)':'';draw();});
window.addEventListener('resize',()=>requestAnimationFrame(draw));document.addEventListener('visibilitychange',()=>{if(document.hidden)suspend();});window.addEventListener('pagehide',dispose,{once:true});
(window as any).demonBoard={get state(){return {ready,id,side,variant,ms,disposed,originalVisible:original?getComputedStyle(original).visibility!=='hidden':null,renderer:renderer.status};},dispose};
void(async()=>{setupState();stopLayout=startBoardLayout();await waitForDuel(root);for(const d of demons)faces.set(d,await surface(d,true));if(disposed)return;ready=true;draw();parent.postMessage({kind:'demon-board',ready,initial:true},location.origin);})().catch(e=>parent.postMessage({kind:'demon-board',error:String(e)},location.origin));
