import '../../styles/tokens.css';import '../../styles/card.css';
import {setLang} from '../../i18n';
import {DURATION,demons,studies,title,phase,type Demon} from './catalog';
import {DemonRenderer} from './renderer';import {surface} from './surface';
setLang('ja');
const q=new URLSearchParams(location.search);let id:Demon=demons.includes(q.get('card') as Demon)?q.get('card') as Demon:'TDE1';let ms=0,playing=false,raf=0,last=0,disposed=false,ready=false,mode='compare',variant=0,boardReady=false;
const media=matchMedia('(prefers-reduced-motion: reduce)');let reduced=media.matches;
const faces=new Map<Demon,HTMLCanvasElement>(),renderer=new DemonRenderer();
document.getElementById('app')!.innerHTML=`<main class="ds-page"><header class="ds-head"><div><div class="ds-kicker">LORE / DEMON SUMMON STUDIES</div><h1>黒い魔力、その顕現。</h1><p>魔族ごとに、三つの召喚。カードの内側から生まれる暗黒を見比べる。</p></div><div class="ds-count">12<small>4体 × 3案</small></div></header><nav class="ds-tabs" aria-label="魔族">${demons.map(d=>`<button data-card="${d}">${title(d)}</button>`).join('')}</nav><div class="ds-tools"><button id="compare" class="active">3案を比較</button><button id="board">実盤面で見る</button><label>案 <select id="variant"><option value="0">01</option><option value="1">02</option><option value="2">03</option></select></label><label>陣営 <select id="side"><option value="0">自分</option><option value="1">相手</option></select></label><span class="spacer"></span><button id="theme">白い背景</button></div><div class="ds-stage" id="stage"><canvas id="scene" aria-label="魔族召喚の3案同時再生"></canvas></div><section class="ds-captions" id="captions"></section><div class="ds-controls"><button id="play">再生</button><button id="reset">先頭へ</button><input id="seek" type="range" min="0" max="${DURATION}" step="1" value="0" aria-label="再生位置"><output id="clock">0.00 / 3.60 s</output><select id="speed" aria-label="再生速度"><option value="1">1倍</option><option value="0.5">0.5倍</option><option value="0.25">0.25倍</option></select><label><input type="checkbox" id="loop">連続再生</label><label><input type="checkbox" id="reduced" ${reduced?'checked':''}>動きを低減</label></div><div class="ds-status" id="status">カードを準備しています…</div><p class="ds-foot">ローカル比較試作。実盤面は公開カードを置いた固定状態です。通常対戦への適用・効果発動・効果音は含みません。</p><details class="ds-ref"><summary>品質基準「銀紋の流墨」を再生して比較</summary><video controls preload="none" src="/@fs/Users/hiromaru05s/Desktop/LORE_TCG/docs/vfx-prototypes/2026-09-27-rift-ink-rich/qa/inscription.mp4"></video></details></main>`;
const $=<T extends HTMLElement>(s:string)=>document.querySelector<T>(s)!;
const stage=$('#stage'),canvas=$<HTMLCanvasElement>('#scene'),ctx=canvas.getContext('2d')!,scrub=$<HTMLInputElement>('#seek');let frame:HTMLIFrameElement|null=null;
function options(){return {id,variant,ms,reduced,side:Number($<HTMLSelectElement>('#side').value),dark:stage.classList.contains('light')?false:true};}
function post(){if(frame&&boardReady)frame.contentWindow?.postMessage({kind:'demon-control',...options()},location.origin);}
function captions(){document.querySelectorAll<HTMLButtonElement>('[data-card]').forEach(b=>{b.classList.toggle('active',b.dataset.card===id);b.setAttribute('aria-pressed',String(b.dataset.card===id));});$('#captions').innerHTML=studies[id].map((p,i)=>`<article><small>0${i+1} / ${p.material}</small><h2>${p.name}</h2><p>${p.note}</p></article>`).join('');Array.from($<HTMLSelectElement>('#variant').options).forEach((o,i)=>o.text=`0${i+1} ${studies[id][i].name}`);}
function draw(){if(!ready||disposed)return;scrub.value=String(ms);$('#clock').textContent=`${(ms/1000).toFixed(2)} / 3.60 s`;$('#status').textContent=`${phase(ms)} · ${title(id)}${reduced?' · 低減モーション':renderer.status==='fallback'?' · WebGL非対応：簡易表示':''}${mode==='board'&&!boardReady?' · 盤面を準備中':''}`;
 if(mode==='board'){post();return;}const w=stage.clientWidth,h=stage.clientHeight,dpr=Math.min(devicePixelRatio,2);if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const bg=ctx.createRadialGradient(w*.5,h*.75,0,w*.5,h*.5,Math.max(w,h)*.7);bg.addColorStop(0,stage.classList.contains('light')?'#e8dfeb':'#322837');bg.addColorStop(1,stage.classList.contains('light')?'#faf8f2':'#18131f');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);const vertical=w<650,cw=vertical?w:w/3,ch=vertical?h/3:h;
 for(let i=0;i<3;i++){const x=vertical?0:i*cw,y=vertical?i*ch:0;ctx.save();ctx.beginPath();ctx.rect(x,y,cw,ch);ctx.clip();ctx.strokeStyle=stage.classList.contains('light')?'#d2c8d6':'#43344b';ctx.lineWidth=1;if(i){ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(vertical?w:x,vertical?y:h);ctx.stroke();}ctx.fillStyle=stage.classList.contains('light')?'#66536f':'#bca5ca';ctx.font='11px system-ui';ctx.fillText(`0${i+1} / ${studies[id][i].name}`,x+18,y+25);const size=Math.min(cw*.47,ch*.40,190);renderer.draw(ctx,faces.get(id)!,id,i,ms,x+cw/2,y+ch*.54,size,reduced);ctx.restore();}
 canvas.dataset.time=String(Math.round(ms));}
function pause(){playing=false;cancelAnimationFrame(raf);$('#play').textContent='再生';}
function play(){if(!ready||disposed||playing)return;if(ms>=DURATION)ms=0;playing=true;last=performance.now();$('#play').textContent='一時停止';raf=requestAnimationFrame(tick);}
function tick(now:number){if(!playing)return;ms=Math.min(DURATION,ms+Math.min(80,now-last)*Number($<HTMLSelectElement>('#speed').value));last=now;draw();if(ms>=DURATION){if($<HTMLInputElement>('#loop').checked)ms=0;else pause();}if(playing)raf=requestAnimationFrame(tick);}
function seek(t:number){pause();ms=Math.max(0,Math.min(DURATION,t));draw();}
function setCard(d:Demon){if(!demons.includes(d))return;id=d;captions();draw();}
function setMode(m:string){pause();mode=m==='board'?'board':'compare';stage.classList.toggle('board',mode==='board');$('#compare').classList.toggle('active',mode==='compare');$('#board').classList.toggle('active',mode==='board');if(mode==='board'){if(!frame){boardReady=false;frame=document.createElement('iframe');frame.title='実盤面で魔族の召喚を比較';frame.src='/demon-summon.html?board=1';canvas.hidden=true;canvas.style.display='none';stage.append(frame);}}else{frame?.remove();frame=null;boardReady=false;canvas.hidden=false;canvas.style.display='block';}draw();}
function dispose(){if(disposed)return;pause();disposed=true;resize.disconnect();frame?.remove();renderer.dispose();faces.clear();}
$('#play').onclick=()=>playing?pause():play();$('#reset').onclick=()=>seek(0);scrub.oninput=()=>seek(Number(scrub.value));$('#compare').onclick=()=>setMode('compare');$('#board').onclick=()=>setMode('board');$('#theme').onclick=()=>{stage.classList.toggle('light');$('#theme').textContent=stage.classList.contains('light')?'暗い背景':'白い背景';draw();};$<HTMLSelectElement>('#variant').onchange=()=>{variant=Number($<HTMLSelectElement>('#variant').value);draw();};$<HTMLSelectElement>('#side').onchange=draw;$<HTMLInputElement>('#reduced').onchange=()=>{reduced=$<HTMLInputElement>('#reduced').checked;draw();};document.querySelectorAll<HTMLButtonElement>('[data-card]').forEach(b=>b.onclick=()=>setCard(b.dataset.card as Demon));
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==frame?.contentWindow||e.data?.kind!=='demon-board')return;if(e.data.error){pause();$('#status').textContent=e.data.error;return;}boardReady=e.data.ready;if(e.data.initial)draw();});
document.addEventListener('visibilitychange',()=>{if(document.hidden){pause();frame?.contentWindow?.postMessage({kind:'demon-suspend'},location.origin);}});window.addEventListener('pagehide',dispose,{once:true});media.addEventListener('change',e=>{reduced=e.matches;$<HTMLInputElement>('#reduced').checked=reduced;draw();});const resize=new ResizeObserver(draw);resize.observe(stage);
(window as any).demonLab={play,pause,seek,setCard,setMode,setVariant(v:number){variant=v;$<HTMLSelectElement>('#variant').value=String(v);draw();},dispose,get state(){return {ready,ms,playing,id,variant,mode,boardReady,reduced,renderer:renderer.status,disposed};}};
void(async()=>{for(const d of demons)faces.set(d,await surface(d));if(disposed)return;ready=true;captions();draw();if(!reduced)play();})().catch(e=>{$('#status').textContent=String(e);});
