import manifest from './assets/manifest.json';
import './style.css';
const files=import.meta.glob('./assets/*.mp3',{eager:true,query:'?url',import:'default'}) as Record<string,string>;
const clips=manifest.map(c=>({...c,url:files['./assets/'+c.file]}));
const root=document.querySelector<HTMLElement>('#review')!;
root.innerHTML=`<header><p class="eyebrow">LORE · SOUND STUDY / 03 OCT 2026</p><h1>魔法を出す、一瞬の音。</h1><p class="lead">素材も、立ち上がりも異なる5案。<br>単音で選び、実盤面とBGMで確かめる。</p><div class="badges"><span>5 DIRECTIONS</span><span>音量を揃えて比較</span><span>比較プレビュー</span></div></header>
<section class="controls" aria-label="試聴設定"><label>音量 <input id="volume" type="range" min="0" max="100" value="70"><output id="volume-label">70%</output></label><label><input id="bgm" type="checkbox">対戦BGMを重ねる</label><label><input id="mono" type="checkbox">モノラル</label><button id="stop">■ 停止</button><button id="all">▶ 5案を順に聴く</button><p id="status" role="status" aria-live="polite">再生ボタンを押してください。音量は小さめから。</p></section>
<div class="workspace"><section class="catalog" aria-label="5つの候補">${clips.map(c=>`<article data-id="${c.id}"><div class="number">${c.number}</div><div class="copy"><p class="character">${c.character}</p><h2>${c.title}${c.number==='01'?' · 採用':''}</h2><p>${c.description}</p><small>${c.seconds.toFixed(2)}秒 · ${c.number==='04'?'火属性寄り':c.number==='03'?'明るい魔法寄り':'共通音の候補'}</small><div class="buttons"><button data-single="${c.id}" aria-label="${c.number} 単音を再生">▶ 単音</button><button data-scene="${c.id}" aria-label="${c.number} 実盤面で再生">▶ 実盤面</button><button data-repeat="${c.id}" aria-label="${c.number} 3回連続再生">↻ 3回</button></div></div></article>`).join('')}<div class="current"><div><b>比較用：前回の音</b><p>前回のv6。和音主体の音との違いを確認。</p></div><button id="old">▶ 前回の音</button></div></section>
<section class="board"><div class="board-heading"><div><p class="eyebrow">IN CONTEXT</p><h2>同じカード、同じ動きで。</h2></div><label>カード<select id="card"><option value="FLAME">火花 / 効果ダメージ</option><option value="FORESIGHT">先見の明 / 永続魔法</option></select></label></div><iframe id="scene" title="LORE 実盤面の魔法プレイ" src="/src/dev/spell-sound-five/scene.html" allow="autoplay"></iframe><p id="scene-status">盤面を読み込んでいます…</p><p class="note">ゲーム本体のカード表示・演出・効果音経路を使う固定シーン。発動音だけ候補に置き換え、着弾などは既存音を残します。</p></section></div>
<details><summary>今回の設計とリサーチ</summary><div class="research"><p>役割は「魔法カードのプレイが成立したこと」。攻撃の着弾、回復、マナ支払いの音とは分けます。5案すべてを汎用音として推すのではなく、04は火属性寄り、03は明るい魔法寄りという違いも比較対象です。</p><p><a href="https://hearthstone.blizzard.com/en-gb/news/23964694/inside-battle-net-meet-the-sound-team-behind-hearthstone-s-harmonic-design/" target="_blank" rel="noreferrer">Hearthstone 音響チーム</a>：カード操作の拍に合わせ、発動と命中を分ける。<a href="https://www.boomlibrary.com/blog/inside-the-sonic-lab-behind-magic-alchemy/" target="_blank" rel="noreferrer">BOOM Library 制作記録</a>：実物の質感を加工し、短く、残響を抑えてまとめる。<a href="https://www.asoundeffect.com/sounds-of-magic/" target="_blank" rel="noreferrer">Iain McGregor の論考</a>：物の音が変化する過程から魔法を考える。</p><p>今回の5案はCC0の布・風切り・ガラス・火の効果音などを再編集。前回の合成和音は使いません。文献調査に基づく制作案であり、参照ゲームの音のコピーや、音響専門家による聴感審査済みという意味ではありません。</p><p>候補は強い200ms区間のエネルギーを揃えています（知覚上の音量を完全一致させるものではありません）。既存v6は元の音量。再生/停止、クリップ、重複、同じ実盤面での比較を検証し、好みの判断と分けています。</p></div></details><footer>1〜5キー：単音試聴 / Esc：停止 · 採用：01 シルクの封印（2026-10-05）</footer>`;
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
let context:AudioContext|undefined,bus:GainNode,musicBus:GainNode,ticket=0;
const gainByVoice=new WeakMap<AudioBufferSourceNode,GainNode>();
const cache=new Map<string,Promise<AudioBuffer>>(),voices=new Set<AudioBufferSourceNode>();let bgmSource:AudioBufferSourceNode|undefined;
const frame=$<HTMLIFrameElement>('scene');
function audio(){if(!context){context=new AudioContext();bus=context.createGain();bus.gain.value=.49;const limiter=context.createDynamicsCompressor();limiter.threshold.value=-8;limiter.knee.value=6;limiter.ratio.value=8;limiter.attack.value=.002;limiter.release.value=.1;bus.connect(limiter).connect(context.destination);musicBus=context.createGain();musicBus.gain.value=.147;musicBus.connect(context.destination);}void context.resume();return context;}
function decode(url:string){const ctx=audio();let p=cache.get(url);if(!p){p=fetch(url).then(r=>{if(!r.ok)throw Error('音源を取得できません');return r.arrayBuffer();}).then(b=>ctx.decodeAudioData(b));cache.set(url,p);p.catch(()=>cache.delete(url));}return p;}
function post(action:string,extra:Record<string,unknown>={}){frame.contentWindow?.postMessage({kind:'spell-review',action,...extra},location.origin);}
function stop(){ticket++;for(const v of voices){try{gainByVoice.get(v)?.gain.setTargetAtTime(0,context!.currentTime,.004);v.stop(context!.currentTime+.025);}catch{}}voices.clear();bgmSource=undefined;post('stop');document.querySelectorAll('.playing').forEach(n=>n.classList.remove('playing'));$('status').textContent='停止しました。';}
function source(buffer:AudioBuffer,music=false){const ctx=audio(),s=ctx.createBufferSource();s.buffer=buffer;const envelope=ctx.createGain();s.connect(envelope);gainByVoice.set(s,envelope);if($<HTMLInputElement>('mono').checked&&!music){const n=ctx.createGain();n.channelCount=1;n.channelCountMode='explicit';envelope.connect(n).connect(bus);s.addEventListener('ended',()=>n.disconnect());}else envelope.connect(music?musicBus:bus);s.addEventListener('ended',()=>{voices.delete(s);s.disconnect();envelope.disconnect()});voices.add(s);return s;}
async function music(id:number){if(!$<HTMLInputElement>('bgm').checked)return;const b=await decode('/music/poised-opening.mp3');if(id!==ticket)return;bgmSource=source(b,true);bgmSource.loop=true;bgmSource.start(0,12);}
const pause=(ms:number)=>new Promise<void>(r=>setTimeout(r,ms));
async function play(ids:string[],repeat=1){stop();const id=ticket;try{const urls=ids.map(key=>key==='current'?'/sfx/lore-v6/play.mp3':clips.find(c=>c.id===key)!.url);$('status').textContent='音を準備中…';const buffers=await Promise.all(urls.map(decode));await music(id);if(id!==ticket)return;
 for(let n=0;n<repeat;n++)for(let i=0;i<ids.length;i++){if(id!==ticket)return;document.querySelectorAll('.playing').forEach(n=>n.classList.remove('playing'));document.querySelector(`[data-id="${ids[i]}"]`)?.classList.add('playing');$('status').textContent=ids[i]==='current'?'前回の音を再生中':`${clips.find(c=>c.id===ids[i])!.title} · ${repeat>1?`${n+1}/3`:'再生中'}`;const s=source(buffers[i]);s.start();await pause(Math.max(1050,buffers[i].duration*1000+350));}
 if(id===ticket){stop();$('status').textContent='再生終了。別の案と比較できます。';}}catch(e){if(id===ticket){stop();$('status').textContent=String(e);}}}
async function board(key:string){if(matchMedia('(max-width:1000px)').matches)frame.scrollIntoView({block:'center',behavior:'instant'});stop();const id=ticket;audio();await music(id);if(id!==ticket)return;document.querySelector(`[data-id="${key}"]`)?.classList.add('playing');$('status').textContent=`${clips.find(c=>c.id===key)!.title} · 実盤面で再生`;post('play',{id:key,card:$<HTMLSelectElement>('card').value,volume:Number($<HTMLInputElement>('volume').value)/100,mono:$<HTMLInputElement>('mono').checked});}
root.querySelectorAll<HTMLButtonElement>('[data-single]').forEach(b=>b.onclick=()=>void play([b.dataset.single!]));root.querySelectorAll<HTMLButtonElement>('[data-repeat]').forEach(b=>b.onclick=()=>void play([b.dataset.repeat!],3));root.querySelectorAll<HTMLButtonElement>('[data-scene]').forEach(b=>{b.disabled=true;b.onclick=()=>void board(b.dataset.scene!)});
$('stop').onclick=stop;$('all').onclick=()=>void play(clips.map(c=>c.id));$('old').onclick=()=>void play(['current']);
$<HTMLInputElement>('volume').oninput=()=>{const v=Number($<HTMLInputElement>('volume').value)/100;audio();bus.gain.setTargetAtTime(v*v,context!.currentTime,.015);musicBus.gain.setTargetAtTime(.3*v*v,context!.currentTime,.015);$('volume-label').textContent=Math.round(v*100)+'%';post('volume',{volume:v});};
$<HTMLInputElement>('bgm').onchange=()=>{if(!$<HTMLInputElement>('bgm').checked&&bgmSource){try{bgmSource.stop()}catch{}bgmSource=undefined;}};
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==frame.contentWindow||e.data?.kind!=='spell-scene')return;const d=e.data;$('scene-status').textContent=d.message;root.querySelectorAll<HTMLButtonElement>('[data-scene]').forEach(b=>b.disabled=!d.ready);if(d.finished||d.error){if(bgmSource){try{bgmSource.stop()}catch{}bgmSource=undefined;}$('status').textContent=d.error?'盤面を再生できませんでした。'+d.message:'実盤面の再生が終了しました。';document.querySelectorAll('.playing').forEach(n=>n.classList.remove('playing'));}});
document.addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement)return;if(e.key==='Escape')stop();const n=Number(e.key);if(n>=1&&n<=5)void play([clips[n-1].id]);});document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});window.addEventListener('pagehide',()=>{stop();void context?.close()});
