import {soundUrls} from '../../ui/sound';
import manifest from './assets/manifest.json';
import './style.css';
const files=import.meta.glob('./assets/*.mp3',{eager:true,query:'?url',import:'default'}) as Record<string,string>;
const clips=manifest.map(c=>({...c,url:files['./assets/'+c.file]}));
const root=document.querySelector<HTMLElement>('#review')!;
root.innerHTML=`<header><p class="eyebrow">LORE · SOUND STUDY / 05 OCT 2026</p><h1>召喚が、盤面に定着する音。</h1><p class="lead">素材も、接地感も異なる9案。<br>単音で選び、実盤面とBGMで確かめる。</p><div class="badges"><span>9 DIRECTIONS</span><span>音量を揃えて比較</span><span>比較プレビュー</span></div></header>
<section class="controls" aria-label="試聴設定"><label>音量 <input id="volume" type="range" min="0" max="100" value="70"><output id="volume-label">70%</output></label><label><input id="bgm" type="checkbox">対戦BGMを重ねる</label><label><input id="mono" type="checkbox">モノラル</label><button id="stop">■ 停止</button><button id="all">▶ 9案を順に聴く</button><p id="status" role="status" aria-live="polite">再生ボタンを押してください。音量は小さめから。</p></section>
<div class="workspace"><section class="catalog" aria-label="9つの候補">${clips.map(c=>`<article data-id="${c.id}"><div class="number">${c.number}</div><div class="copy"><p class="character">${c.character}</p><h2>${c.title}${c.id==='04-air'?' · 採用':''}</h2><p>${c.description}</p><small>${c.seconds.toFixed(2)}秒 · ${c.fit}</small><div class="buttons"><button data-single="${c.id}" aria-label="${c.number} 単音を再生">▶ 単音</button><button data-scene="${c.id}" aria-label="${c.number} 実盤面で再生">▶ 実盤面</button><button data-repeat="${c.id}" aria-label="${c.number} 3回連続再生">↻ 3回</button></div></div></article>`).join('')}<div class="current"><div><b>現在の召喚音：04</b><p>ゲームで使用中の召喚音。元の音量で比較。</p></div><div class="buttons"><button id="old">▶ 単音</button><button data-scene="current">▶ 実盤面</button></div></div></section>
<section class="board"><div class="board-heading"><div><p class="eyebrow">IN CONTEXT</p><h2>同じカード、同じ動きで。</h2></div><label>カード<select id="card"><option value="M2">ストーンパップ / 小型</option><option value="M12">タイタンゲート / 大型</option></select></label><label>陣営<select id="side"><option value="0">自分</option><option value="1">相手</option></select></label></div><iframe id="scene" title="LORE 実盤面の召喚" src="/src/dev/summon-sound-nine/scene.html" allow="autoplay"></iframe><p id="scene-status">盤面を読み込んでいます…</p><p class="note">ゲーム本体のカード表示・演出・効果音経路を使う固定シーン。カードが接地する瞬間の召喚音を置き換えます。魔法プレイで採用済みの01とは別の比較です。</p></section></div>
<details><summary>TCGの召喚音をどう考えたか</summary><div class="research"><p>共通の召喚音は「存在が盤面に定着した」ことを伝える短い接地音として設計。素材の輪郭・低い胴鳴り・短い余韻を組み合わせ、9つの方向を比較します。03・06〜09は個性の強い候補です。</p><p><a href="https://hearthstone.blizzard.com/en-gb/news/23964694/inside-battle-net-meet-the-sound-team-behind-hearthstone-s-harmonic-design/" target="_blank" rel="noreferrer">Hearthstoneの音響チーム</a>：カードを出す拍とカードの印象に合わせる。<a href="https://www.playgwent.com/en/news/37954/secrets-of-sound-design-with-paula-karbowniczek" target="_blank" rel="noreferrer">GWENTのサウンドデザイナー</a>：世界観と素材の一貫性、映像との同期を重視する。</p><p>LOREで採用中の石板召喚を使い、同じ接地タイミングで再生。候補はCC0素材の編集で制作しています。「石板風」「砂塵風」は加工後の質感を示す名前です。</p><p>強い200ms区間の音量を揃えています。知覚上の音量の完全一致ではないため、BGMとモノラルでも比較できます。機能確認と聴感の評価は分けています。</p></div></details><footer>1〜9キー：単音 / Esc：停止 · 04「空気のクッション」をゲーム本体の召喚音に採用。</footer>`;
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
let context:AudioContext|undefined,bus:GainNode,musicBus:GainNode,ticket=0;
const gainByVoice=new WeakMap<AudioBufferSourceNode,GainNode>();
const cache=new Map<string,Promise<AudioBuffer>>(),voices=new Set<AudioBufferSourceNode>();let bgmSource:AudioBufferSourceNode|undefined;
const frame=$<HTMLIFrameElement>('scene');
function audio(){if(!context){context=new AudioContext();bus=context.createGain();bus.gain.value=.49;const limiter=context.createDynamicsCompressor();limiter.threshold.value=-8;limiter.knee.value=6;limiter.ratio.value=8;limiter.attack.value=.002;limiter.release.value=.1;bus.connect(limiter).connect(context.destination);musicBus=context.createGain();musicBus.gain.value=.147;musicBus.connect(context.destination);}void context.resume();return context;}
function decode(url:string){const ctx=audio();let p=cache.get(url);if(!p){p=fetch(url).then(r=>{if(!r.ok)throw Error('音源を取得できません');return r.arrayBuffer();}).then(b=>ctx.decodeAudioData(b));cache.set(url,p);p.catch(()=>cache.delete(url));}return p;}
function post(action:string,extra:Record<string,unknown>={}){frame.contentWindow?.postMessage({kind:'summon-review',action,...extra},location.origin);}
function stop(){ticket++;for(const v of voices){try{gainByVoice.get(v)?.gain.setTargetAtTime(0,context!.currentTime,.004);v.stop(context!.currentTime+.025);}catch{}}voices.clear();bgmSource=undefined;post('stop');document.querySelectorAll('.playing').forEach(n=>n.classList.remove('playing'));$('status').textContent='停止しました。';}
function source(buffer:AudioBuffer,music=false){const ctx=audio(),s=ctx.createBufferSource();s.buffer=buffer;const envelope=ctx.createGain();s.connect(envelope);gainByVoice.set(s,envelope);if($<HTMLInputElement>('mono').checked&&!music){const n=ctx.createGain();n.channelCount=1;n.channelCountMode='explicit';envelope.connect(n).connect(bus);s.addEventListener('ended',()=>n.disconnect());}else envelope.connect(music?musicBus:bus);s.addEventListener('ended',()=>{voices.delete(s);s.disconnect();envelope.disconnect()});voices.add(s);return s;}
async function music(id:number){if(!$<HTMLInputElement>('bgm').checked)return;const b=await decode('/music/poised-opening.mp3');if(id!==ticket)return;bgmSource=source(b,true);bgmSource.loop=true;bgmSource.start(0,12);}
const pause=(ms:number)=>new Promise<void>(r=>setTimeout(r,ms));
async function play(ids:string[],repeat=1){stop();const id=ticket;try{const urls=ids.map(key=>key==='current'?soundUrls('summon')[0]:clips.find(c=>c.id===key)!.url);$('status').textContent='音を準備中…';const buffers=await Promise.all(urls.map(decode));await music(id);if(id!==ticket)return;
 for(let n=0;n<repeat;n++)for(let i=0;i<ids.length;i++){if(id!==ticket)return;document.querySelectorAll('.playing').forEach(n=>n.classList.remove('playing'));document.querySelector(`[data-id="${ids[i]}"]`)?.classList.add('playing');$('status').textContent=ids[i]==='current'?'現在の召喚音を再生中':`${clips.find(c=>c.id===ids[i])!.title} · ${repeat>1?`${n+1}/3`:'再生中'}`;const s=source(buffers[i]);s.start();await pause(Math.max(1050,buffers[i].duration*1000+350));}
 if(id===ticket){stop();$('status').textContent='再生終了。別の案と比較できます。';}}catch(e){if(id===ticket){stop();$('status').textContent=String(e);}}}
async function board(key:string){if(matchMedia('(max-width:1000px)').matches)frame.scrollIntoView({block:'center',behavior:'instant'});stop();const id=ticket;audio();await music(id);if(id!==ticket)return;document.querySelector(`[data-id="${key}"]`)?.classList.add('playing');$('status').textContent=`${key==='current'?'現在の召喚音':clips.find(c=>c.id===key)!.title} · 実盤面で再生`;post('play',{id:key,card:$<HTMLSelectElement>('card').value,side:Number($<HTMLSelectElement>('side').value),volume:Number($<HTMLInputElement>('volume').value)/100,mono:$<HTMLInputElement>('mono').checked});}
root.querySelectorAll<HTMLButtonElement>('[data-single]').forEach(b=>b.onclick=()=>void play([b.dataset.single!]));root.querySelectorAll<HTMLButtonElement>('[data-repeat]').forEach(b=>b.onclick=()=>void play([b.dataset.repeat!],3));root.querySelectorAll<HTMLButtonElement>('[data-scene]').forEach(b=>{b.disabled=true;b.onclick=()=>void board(b.dataset.scene!)});
$('stop').onclick=stop;$('all').onclick=()=>void play(clips.map(c=>c.id));$('old').onclick=()=>void play(['current']);
$<HTMLInputElement>('volume').oninput=()=>{const v=Number($<HTMLInputElement>('volume').value)/100;audio();bus.gain.setTargetAtTime(v*v,context!.currentTime,.015);musicBus.gain.setTargetAtTime(.3*v*v,context!.currentTime,.015);$('volume-label').textContent=Math.round(v*100)+'%';post('volume',{volume:v});};
$<HTMLInputElement>('bgm').onchange=()=>{if(!$<HTMLInputElement>('bgm').checked&&bgmSource){try{bgmSource.stop()}catch{}bgmSource=undefined;}};
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==frame.contentWindow||e.data?.kind!=='summon-scene')return;const d=e.data;$('scene-status').textContent=d.message;root.querySelectorAll<HTMLButtonElement>('[data-scene]').forEach(b=>b.disabled=!d.ready);if(d.finished||d.error){if(bgmSource){try{bgmSource.stop()}catch{}bgmSource=undefined;}$('status').textContent=d.error?'盤面を再生できませんでした。'+d.message:'実盤面の再生が終了しました。';document.querySelectorAll('.playing').forEach(n=>n.classList.remove('playing'));}});
document.addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement)return;if(e.key==='Escape')stop();const n=Number(e.key);if(n>=1&&n<=9)void play([clips[n-1].id]);});document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});window.addEventListener('pagehide',()=>{stop();void context?.close()});
