import {catalog} from './catalog';
import {DB,STARTERS} from '../../shared/cards';
const defs={...DB,...STARTERS};
const names:Record<string,string[]>={S07:['噛み合わせの金牙','飢えた宝光'],S15:['銀刻の流墨','次元の折層'],S23:['錆蝕の断層','菌糸の毒膜'],S24:['象牙の跳賽','光刻の賭盤'],S25:['金錠の開扉','封緘の解織']};
document.body.innerHTML=`<div id="studio"><aside><div class="eyebrow">LORE · D / MATERIAL STUDIES</div><h1>異質の記録</h1><p>5系統・34場面。カード表面から作用と到着まで、共通時計で比較。</p><div class="group"><label>系統 / 効果</label><select id="cue">${catalog.map(s=>`<option value="${s.id}">${s.id} ${s.name}</option>`).join('')}</select></div><div class="group"><label>対象カード</label><select id="card"></select></div><div class="group"><label>除外起点（A017）</label><select id="origin"><option value="hand">手札</option><option value="field">場</option><option value="deck">デッキ</option><option value="shelf">シェルフ</option></select></div><div class="group"><label>演出案</label><select id="variant"><option value="1">①</option><option value="2">②</option></select></div><div class="group"><label>陣営 / 結果</label><div class="row"><select id="side"><option value="0">自分</option><option value="1">相手</option></select><select id="outcome"><option value="hit">結果A / 通常</option><option value="miss">結果B / 外れ</option><option value="two">結果C / 蓄積2</option></select></div></div><div class="group"><label>伝説ギャンブラーの的中報酬</label><select id="rewardChoice"><option value="mana">最大マナ+4</option><option value="heal">体力+35</option><option value="destroy">敵カード2枚破壊</option></select></div><div class="group"><label>再生操作</label><div class="row"><button id="play">再生</button><button id="pause">停止</button><button id="reset">リセット</button></div><input id="seek" aria-label="シーク" type="range" min="0" max="6600" value="0"></div><div class="group"><div class="row"><select id="speed"><option value="1">1倍</option><option value="0.5">0.5倍</option><option value="0.25">0.25倍</option></select><select id="background"><option value="light">白い盤面</option><option value="dark">暗い盤面</option></select></div><label><input id="loop" type="checkbox" checked>ループ</label><label><input id="reduced" type="checkbox">動きを減らす</label><label><input id="simultaneous" type="checkbox">同時発動テスト</label></div><h2>発生 → 変化 → 到着</h2><p id="details"></p><small>実GameView・現行カード描画。状態は比較用固定デモ。ユーザー承認は未確認。</small><button id="record">同一時計の動画保存</button></aside><section class="stage"><header><strong id="title"></strong><span id="time">0.00 s</span></header><iframe id="board" src="?board=1"></iframe><div class="foot"><div id="readout">準備中</div><small id="intent"></small></div></section></div>`;
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const frame=$<HTMLIFrameElement>('board');
export function family(id:string){if(id.startsWith('S'))return id;return ['A039','A040','A041','A042'].includes(id)?'S23':['A011','A058','A117','A118','A119','A120','A121'].includes(id)?'S07':['A153','A154','A155','A156','A157'].includes(id)?'S24':['A152'].includes(id)?'S25':'S15';}
function select(){const row=catalog.find(r=>r.id===$<HTMLSelectElement>('cue').value)!;const cards=row.cardIds.length?row.cardIds:row.id==='A004'?['QUICK_POISON','QUICK_MIMIC','QUICK_SURVIVAL']:['STARTER_TRASH','ELF'];$('card').innerHTML=cards.map(id=>`<option value="${id}">${defs[id]?.nameJa||defs[id]?.name||id}</option>`).join('');const n=names[family(row.id)];$('variant').innerHTML=n.map((s,i)=>`<option value="${i+1}">${i+1===1?'①':'②'} ${s}</option>`).join('');$('details').textContent='stages'in row?row.stages!:row.animation!;update();}
function send(command:string,extra:Record<string,unknown>={}){frame.contentWindow?.postMessage({kind:'series-d',command,...extra},location.origin);}
function config(){return {rewardChoice:$<HTMLSelectElement>('rewardChoice').value,origin:$<HTMLSelectElement>('origin').value,cue:$<HTMLSelectElement>('cue').value,card:$<HTMLSelectElement>('card').value,variant:+$<HTMLSelectElement>('variant').value,side:+$<HTMLSelectElement>('side').value,outcome:$<HTMLSelectElement>('outcome').value,reduced:$<HTMLInputElement>('reduced').checked,simultaneous:$<HTMLInputElement>('simultaneous').checked,background:$<HTMLSelectElement>('background').value,speed:+$<HTMLSelectElement>('speed').value,loop:$<HTMLInputElement>('loop').checked};}
function contextControls(cue:string,card:string){$('origin').closest<HTMLElement>('.group')!.hidden=cue!=='A017';$('rewardChoice').closest<HTMLElement>('.group')!.hidden=card!=='LEGEND_GAMBLER';}
function update(){const v=config();contextControls(v.cue,v.card);const def=defs[v.card];$('title').textContent=`${v.cue} · ${names[family(v.cue)][v.variant-1]}`;$('intent').textContent=def?.textJa||def?.text||'';send('setup',v);}
$('cue').onchange=select;for(const id of ['card','variant','side','outcome','origin','rewardChoice','background','reduced','simultaneous'])$(id).onchange=update;
for(const id of ['speed','loop'])$(id).onchange=()=>send('options',config());for(const id of ['play','pause','reset','record'])$(id).onclick=()=>send(id);$('seek').oninput=()=>send('seek',{time:+$<HTMLInputElement>('seek').value});
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.data?.kind!=='series-d-status')return;if(e.data.config){const cfg=e.data.config;contextControls(cfg.cue,cfg.card);const row=catalog.find(r=>r.id===cfg.cue)!;$<HTMLSelectElement>('cue').value=cfg.cue;const cards=row.cardIds.length?row.cardIds:cfg.cue==='A004'?['QUICK_POISON','QUICK_MIMIC','QUICK_SURVIVAL']:['STARTER_TRASH','ELF'];$('card').innerHTML=cards.map(id=>`<option value="${id}">${defs[id]?.nameJa||defs[id]?.name||id}</option>`).join('');$<HTMLSelectElement>('card').value=cfg.card;$('variant').innerHTML=names[family(cfg.cue)].map((name,i)=>`<option value="${i+1}">${i+1===1?'①':'②'} ${name}</option>`).join('');for(const key of ['variant','side','outcome','background','speed'])$<HTMLSelectElement>(key).value=String(cfg[key]);for(const key of ['loop','reduced','simultaneous'])$<HTMLInputElement>(key).checked=cfg[key];$('title').textContent=`${cfg.cue} · ${names[family(cfg.cue)][cfg.variant-1]}`;$('intent').textContent=defs[cfg.card]?.textJa||defs[cfg.card]?.text||'';$('details').textContent='stages'in row?row.stages!:row.animation!;}if(e.data.ready)update();if(e.data.time!=null){$('time').textContent=(e.data.time/1000).toFixed(2)+' s';$<HTMLInputElement>('seek').value=String(e.data.time);$('readout').textContent=e.data.phase;}if(e.data.recording)$('record').textContent=e.data.recording;});
$<HTMLInputElement>('reduced').checked=matchMedia('(prefers-reduced-motion: reduce)').matches;select();
