import {surface} from './surface';import {Renderer} from './renderer';import {designs,DURATION} from './catalog';import './style.css';
document.title='LORE · ギャンブラー召喚6案';const root=document.getElementById('app')!;let renderer:Renderer;let faces:HTMLCanvasElement[]=[];let variant=0,ms=0,playing=false,speed=1,last=0,raf=0,paint=0,mode='detail',dark=false,reduced=matchMedia('(prefers-reduced-motion:reduce)').matches,side=0,multi=false,ready=false;
root.innerHTML=`<main><header><div><small>LORE / SUMMON STUDIES · 08 OCT 2026</small><h1>運を、手繰る。</h1><p>ギャンブラー / 伝説のギャンブラー — 六つの召喚</p></div><a class="tag" style="color:#e3c493;text-decoration:none" href="/gambler-wheel-five.html">⑤を作り直した5案へ ↗</a></header><nav class="modes"><button data-mode="detail" class="active">2枚を比較</button><button data-mode="grid">6案を一覧</button><button data-mode="board">手札から召喚</button><span></span><button id="theme">背景：白</button><label><input id="reduced" type="checkbox">動きを低減</label></nav><nav class="designs">${designs.map((d,i)=>`<button data-v="${i}"><small>0${i+1}</small><b>${d.name}</b><em>${d.en}</em></button>`).join('')}</nav><section id="detail"><div class="pair">${['ギャンブラー','伝説のギャンブラー'].map((n,i)=>`<article><div class="card-label"><span>${n}</span><small>${i?'LEGENDARY / GOLD' :'GAMBLER / SINGLE'}</small></div><canvas data-face="${i}" aria-label="${n}の召喚"></canvas></article>`).join('')}</div><div class="caption"><div><small id="material"></small><h2 id="name"></h2></div><p id="note"></p></div></section><section id="grid" hidden>${designs.map((d,i)=>`<article><button data-pick="${i}"><small>0${i+1} / ${d.en}</small><h2>${d.name}</h2></button><div class="pair">${[0,1].map(j=>`<div><canvas data-grid="${i},${j}"></canvas><small>${j?'伝説のギャンブラー':'ギャンブラー'}</small></div>`).join('')}</div></article>`).join('')}</section><section id="board" hidden><div class="board-tools"><select id="card" aria-label="召喚カード"><option value="GAMBLER">ギャンブラー</option><option value="LEGEND_GAMBLER">伝説のギャンブラー</option></select><button id="side">自分側</button><button id="multi">1枚</button><button id="summon">手札から召喚</button><button id="cancel">中断・カードを戻す</button></div><p class="hint">手札のカードをクリックして召喚。自分側／相手側・同時召喚を比較できます。</p><iframe title="LORE実盤面の召喚プレビュー"></iframe></section><footer><button id="play">再生</button><button id="reset">最初へ</button><select id="speed" aria-label="再生速度"><option value="1">1×</option><option value="0.5">0.5×</option><option value="0.25">0.25×</option></select><input id="seek" type="range" min="0" max="2800" value="0" aria-label="再生位置"><output id="time">0.00</output><label><input id="loop" type="checkbox" checked>反復</label></footer><p id="status" role="status">カード素材を準備しています…</p><p class="boundary">通常召喚の変更候補です。ダイスの出目判定やターン開始効果は含みません。ゲームへの採用前の比較用です。</p></main>`;
const $=<E extends HTMLElement=HTMLElement>(s:string)=>root.querySelector<E>(s)!;const frame=$<HTMLIFrameElement>('iframe');
function send(extra:Record<string,unknown>={}){frame.contentWindow?.postMessage({kind:'gambler-control',variant,speed,card:$<HTMLSelectElement>('#card').value,side,multi,reduced,dark,...extra},location.origin)}
function draw(){if(!ready)return;if(mode==='detail')root.querySelectorAll<HTMLCanvasElement>('[data-face]').forEach(c=>{const n=Number(c.dataset.face);renderer.draw(c,faces[n],variant,ms,!!n,reduced,false,dark)});if(mode==='grid')root.querySelectorAll<HTMLCanvasElement>('[data-grid]').forEach(c=>{const [v,n]=c.dataset.grid!.split(',').map(Number);renderer.draw(c,faces[n],v,ms,!!n,reduced,false,dark)});$('#time').textContent=(ms/1000).toFixed(2)+' s';$<HTMLInputElement>('#seek').value=String(ms)}
function pause(){playing=false;cancelAnimationFrame(raf);$('#play').textContent='再生'}
function tick(now:number){if(!playing)return;ms+=Math.max(0,Math.min(100,now-last))*speed;last=now;if(ms>DURATION+500){if($<HTMLInputElement>('#loop').checked)ms=0;else{ms=DURATION;pause()}}if(now-paint>40){draw();paint=now}if(playing)raf=requestAnimationFrame(tick)}
function play(){if(!ready)return;if(mode==='board'){send({action:'play'});return}pause();if(ms>=DURATION)ms=0;playing=true;last=performance.now();$('#play').textContent='一時停止';raf=requestAnimationFrame(tick)}
function select(v:number){variant=v;root.querySelectorAll<HTMLElement>('[data-v]').forEach(b=>b.classList.toggle('active',Number(b.dataset.v)===v));$('#name').textContent=`0${v+1} ${designs[v].name}`;$('#note').textContent=designs[v].note;$('#material').textContent=designs[v].material;ms=0;send();draw()}
function setMode(v:string){pause();mode=v;for(const n of ['detail','grid','board'])$('#'+n).hidden=n!==v;root.querySelectorAll<HTMLElement>('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===v));if(v==='board'){frame.src='/gambler-six.html?board'}else{send({action:'cancel'});frame.removeAttribute('src');draw();if(!reduced)play()}}
root.querySelectorAll<HTMLElement>('[data-v]').forEach(b=>b.onclick=()=>{select(Number(b.dataset.v));if(mode!=='board'&&!reduced)play()});root.querySelectorAll<HTMLElement>('[data-pick]').forEach(b=>b.onclick=()=>{select(Number(b.dataset.pick));setMode('detail')});root.querySelectorAll<HTMLElement>('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode!));
$('#play').onclick=()=>playing?pause():play();$('#reset').onclick=()=>{pause();ms=0;send({action:'cancel'});draw()};$<HTMLInputElement>('#seek').oninput=()=>{pause();ms=Number($<HTMLInputElement>('#seek').value);draw();if(mode==='board')send({action:'seek',ms})};$<HTMLSelectElement>('#speed').onchange=()=>{speed=Number($<HTMLSelectElement>('#speed').value);send({speed})};$('#theme').onclick=()=>{dark=!dark;$('#theme').textContent=dark?'背景：暗':'背景：白';draw();send()};
function reduce(v:boolean){reduced=v;$<HTMLInputElement>('#reduced').checked=v;if(v){pause();ms=DURATION}draw();send({action:'cancel'})}$<HTMLInputElement>('#reduced').onchange=()=>reduce($<HTMLInputElement>('#reduced').checked);matchMedia('(prefers-reduced-motion:reduce)').addEventListener('change',e=>reduce(e.matches));$('#side').onclick=()=>{side=1-side;$('#side').textContent=side?'相手側':'自分側';send({action:'cancel'})};$('#multi').onclick=()=>{multi=!multi;$('#multi').textContent=multi?'3枚同時':'1枚';send({action:'cancel'})};$<HTMLSelectElement>('#card').onchange=()=>send({action:'cancel'});$('#summon').onclick=()=>send({action:'play'});$('#cancel').onclick=()=>send({action:'cancel'});
window.addEventListener('message',e=>{if(e.origin===location.origin&&e.source===frame.contentWindow&&e.data?.kind==='gambler-ready')send()});document.addEventListener('visibilitychange',()=>{if(document.hidden){pause();send({action:'cancel'})}});window.addEventListener('pagehide',()=>{pause();renderer?.dispose()},{once:true});
(window as any).gamblerLab={get ready(){return ready},get state(){return {variant,ms,playing,mode,reduced}},seek(t:number,v=variant){pause();select(v);ms=t;draw()},setMode,reduce,play,pause};
void(async()=>{faces=await Promise.all(['GAMBLER','LEGEND_GAMBLER'].map(surface));renderer=new Renderer();ready=true;select(0);$('#status').textContent='2枚は同じ時計で再生。6案の造形と素材を比較してください。';reduce(reduced);if(!reduced&&!location.search.includes('qa'))play()})().catch(e=>{$('#status').textContent='描画を開始できませんでした：'+e.message;console.error(e)});
