import {cardEl} from '../../../ui/cardView';
import {moveOnBoard} from '../../../ui/boardMotion';
import {clearMonsterStates} from '../../../ui/monster/runtime';
import {GameView,setMyAvatar,setOppAvatar} from '../../../ui/boardView';
import {createGame,effAtk,curHp} from '../../../shared/engine';
import {startBoardLayout} from '../../../ui/layout';
import {waitForDuel} from '../../../ui/duelReadiness';
import {discardFromHand,exileCard,exileGeneratedCards,destroyAnim,setFxSkip,deathShatter} from '../../../ui/anim';
import {ownCards} from './scenario';
import {freezeMaterial} from './materialHandoff';
import {additional} from './effects';
import {attackPlan,attackPose,drawAttackVisual} from '../../../ui/attackVisual';
import {projectedPlacement} from '../../../ui/boardProjection';
import {defs,type Item,mode} from './catalog';
import {sat,smooth,pulse,hotSurface,weapon,projectile,impact,line,setMaterialImage,withMaterialImage,type Point} from './paint';
import type {CardInst,FieldMon} from '../../../shared/types';
export class Board {
 trigger='summon';sceneLabel='';
 initialStatus=new Map<HTMLElement,string>();
 baseline=new Map<string,{atk:number;def:number}>();
 materialHandoffs=new Set<()=>void>();
 view:GameView;g:any;stopLayout:()=>void;ready:Promise<void>;id:Item;cardId:string;variant=0;side=0;condition=true;targetKind='monster';choice='CHOSEN_KNIGHT';time=0;speed=1;playing=false;loading=true;elapsed=0;playStarted=0;clockFrame=0;reduced=false;loop=false;frame=0;start=0;epoch=0;canvas=document.createElement('canvas');ctx=this.canvas.getContext('2d')!;surfaces=new Map<HTMLElement,HTMLCanvasElement>();events:string[]=[];nativeDone=new Set<string>();nativeBusy=false;duration=4800;flights:HTMLElement[]=[];flightSources=new Set<HTMLElement>();onTick=(_t:number)=>{};
 constructor(root:HTMLElement,entry:Item,cardId:string){this.id=entry;this.cardId=cardId;setMyAvatar('SEEKER_BLUE');setOppAvatar('SEEKER_RED');this.g=createGame({mode:'bot',seed:734,starting:0,p0:{id:'c-r3-self',name:'シーカー'},p1:{id:'c-r3-opp',name:'相手'}}).state;const noop=()=>{};this.view=new GameView(root,0,{onPlay:noop,onBlockedPlay:noop,onAttack:noop,onBlockedAttack:noop,onReorder:noop,onChooseTarget:noop,onBuyMarket:noop,onBuySupply:noop,onRefresh:noop,onEndTurn:noop,onSurrender:noop});this.stopLayout=startBoardLayout();this.canvas.className='r3-canvas';document.body.append(this.canvas);this.fixture();this.ready=(async()=>{await waitForDuel(root);await Promise.all([...document.images].map(i=>i.decode().catch(()=>{})));this.loading=false;this.paint(0)})();}
 inst(id:string,uid:string):CardInst{return {...defs[id],uid}}
 mon(id:string,uid:string):FieldMon{return {...this.inst(id,uid),exhausted:false,summonedTurn:0,tempAtk:0,atkMod:0,defMod:0,dmg:0,guts:defs[id]?.passive?.includes('guts')?1:0}}
 fixture(){this.surfaces.clear();this.initialStatus.clear();this.baseline.clear();this.nativeDone.clear();this.events=[];const d=defs[this.cardId],isMon=d?.t==='mon';this.g.turn=4;this.g.pending=null;this.g.opening=undefined;this.g.over=null;
  for(const [n,p] of this.g.players.entries()){p.hp=40;p.mana=9;p.maxMana=12;p.openingDrawReady=false;p.enchants=[];p.traps=[];p.quests=[];p.removed=Array.from({length:8},(_,j)=>this.inst('STARTER_TRASH',`cull-${n}-${j}`));p.discard=[this.inst('STARTER_MANA',`shelf-${n}`)];p.hand=[this.inst(n===this.side&&!isMon?this.cardId:'STARTER_CHEST',`r3-hand-${n}`),this.inst('STARTER_TRASH',`r3-payment-${n}`)];const ids=n===this.side?ownCards(this.id,this.cardId,this.condition,this.choice,this.trigger):['ELF','INFKNIGHT','MANA_GIANT','SOLDIER2'];p.field=ids.map((id,j)=>this.mon(id,j?`r3-other-${n}-${j}`:`r3-subject-${n}`));if(this.cardId==='TREASON'&&this.condition&&n!==this.side)p.field[0]=this.mon('CASTLE',`r3-subject-${n}`);if(this.cardId==='CHOSEN_AREA'&&n===this.side)p.removed=Array.from({length:this.condition?25:24},(_,j)=>this.inst('STARTER_TRASH',`cull-${n}-${j}`));if(this.cardId==='COLOSSEUM'&&!this.condition&&n===this.side)p.removed=p.removed.slice(0,6);if(this.cardId==='QUICK_SORT'&&n===this.side&&this.condition)p.removed.push(this.inst('STARTER_TRASH','extra-cull-1'),this.inst('STARTER_TRASH','extra-cull-2'));if(['FIRE_ART','FIRE_MASTER'].includes(this.cardId)&&n===this.side){p.hand.push(this.inst('FIRE_BALL','r3-fire-companion'));if(this.trigger==='death')p.hand.push(this.inst('FIRE_ARROW','r3-fire-return-2'));}if(this.cardId==='Q_TOWN'&&n===this.side)p.hand.push(this.inst('DOMINION','r3-reward'),this.inst('WINE','r3-town-wine'));if(this.cardId==='AMA'&&n===this.side)p.hand.push(this.inst('STARTER_CHEST','r3-chest-payment'));}
  for(const p of this.g.players)for(const m of p.field)m.defMod=24;
  if(['S21','S22'].includes(this.id.family)||['A001','A007','A012','A128'].includes(this.id.id))for(const m of this.g.players[this.side].field)m.defMod=0;
  const action=mode(this.id,this.cardId),me=this.g.players[this.side],opp=this.g.players[1-this.side];
  if(action==='A030'){me.field[0]=this.mon('SOLDIER2',`r3-subject-${this.side}`);opp.field[0]=this.mon(this.cardId,`r3-subject-${1-this.side}`);opp.field[0].defMod=24;me.field[0].defMod=24;}
  if(action==='A031'){opp.field[0]=this.mon('INFKNIGHT',`r3-subject-${1-this.side}`);opp.field[0].defMod=24;}
  if(action==='A038')opp.field[0].atkMod+=curHp(me,me.field[0])-effAtk(opp,opp.field[0],this.g);
  if(action==='A028')opp.field[0].defMod=40;
  if(action==='A027')opp.field[0]=this.mon('SOLDIER2',`r3-subject-${1-this.side}`);
  if(action==='A076')me.hand.push(this.inst('FIRE_BALL','r3-amplifier-spell'));
  if(action==='A029')opp.field[0]=this.mon('SOLDIER2',`r3-subject-${1-this.side}`);
  if(action==='A033'&&!this.condition){opp.field[0]=this.mon('SOLDIER2',`r3-subject-${1-this.side}`);opp.field[0].defMod=12;}
  if(action==='A122'||this.cardId==='MIND_BURST'){me.field.forEach((m:any,j:number)=>{m.guts=j<3?j+1:0});if(this.cardId!=='MIND_BURST')me.hand.push(this.inst('MIND_BURST','r3-burst'));}

  for(const m of [...me.field,...opp.field])if(m.id==='CASTLE')m.gcount=2;
  for(const p of this.g.players)for(const m of p.field)this.baseline.set(m.uid,{atk:effAtk(p,m,this.g),def:curHp(p,m)});
  this.view.render(this.g);clearMonsterStates(this.view.root);this.view.setHandOpen(false);document.querySelector('.help-callout')?.remove();if(this.side===1){const revealed=new Set([!isMon?'r3-hand-1':'','r3-fire-companion','r3-fire-return-2','r3-burst','r3-amplifier-spell','r3-reward','r3-town-wine','r3-chest-payment',this.cardId==='FIRE_ZONE'?'r3-payment-1':'']);for(const card of this.g.players[1].hand){if(!revealed.has(card.uid))continue;const back=document.querySelector<HTMLElement>(`#oppHand [data-uid="${card.uid}"]`);if(!back)continue;const face=cardEl(card,{size:'hand'});face.style.cssText=back.style.cssText;face.style.position='absolute';face.style.setProperty('--cw',back.style.width);face.style.setProperty('--ch',back.style.height);back.replaceWith(face)}}

  for(const e of document.querySelectorAll<HTMLElement>('.card[data-uid]')){this.initialStatus.set(e,e.querySelector('.card-status')?.innerHTML??'');const cv=document.createElement('canvas');cv.width=200;cv.height=300;cv.className='r3-surface';e.append(cv);this.surfaces.set(e,cv)}
 }
 el(uid:string){return document.querySelector<HTMLElement>(`.card[data-uid="${uid}"]`)!}
 subject(n=this.side){return this.el(`r3-subject-${n}`)}
 source(){return defs[this.cardId]?.t==='mon'?this.subject():this.el(`r3-hand-${this.side}`)}
 targets(all=false){const uids=new Set(this.g.players[1-this.side].field.map((m:any)=>m.uid));return [...document.querySelectorAll<HTMLElement>(`.zone-mon .card[data-uid]`)].filter(e=>all||uids.has(e.dataset.uid))}
 point(e:HTMLElement):Point{const r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height*.54}}
 player(n:number){return document.getElementById(n?'portraitOpp':'portraitMe')!}
 local(e:HTMLElement,fn:(c:CanvasRenderingContext2D)=>void){const cv=this.surfaces.get(e);if(!cv)return;const c=cv.getContext('2d')!;c.save();c.scale(2,2);withMaterialImage(e.querySelector<HTMLImageElement>('img')??undefined,()=>fn(c));c.restore()}
 stat(e:HTMLElement,kind:'atk'|'def',n:number){const v=e.querySelector(`.ad-${kind} .seal-value`);if(v)v.textContent=String(Math.max(0,n))}
 base(e:HTMLElement,kind:'atk'|'def'){const uid=e.dataset.uid;const m=this.g.players.flatMap((p:any)=>p.field).find((x:any)=>x.uid===uid);const p=this.g.players.find((p:any)=>p.field.some((x:any)=>x.uid===uid));return m?(kind==='def'?curHp(p,m):effAtk(p,m,this.g)):(this.baseline.get(uid??'')?.[kind]??0)}
 damage(e:HTMLElement,n:number){this.stat(e,'def',Math.max(0,this.base(e,'def')-n))}
 pose(e:HTMLElement,x:number,y:number,r=0){if(this.reduced)return;e.style.translate=`${x}px ${y}px`;e.style.rotate=`${r}deg`;}
 phase(){if(this.nativeBusy)return '既定の移動・決着を再生中';if(this.sceneLabel)return this.sceneLabel;return this.time<500?'発生源・支払い':this.time<1250?'表面の予兆':this.time<2600?'変化・接触':this.time<this.duration-600?'効果の反映':'収束・結果'}
 paint(t:number){this.clearFlights();this.sceneLabel='';this.time=t;this.canvas.style.display=this.reduced?'none':'';const c=this.ctx,dpr=Math.min(devicePixelRatio,2);this.canvas.width=innerWidth*dpr;this.canvas.height=innerHeight*dpr;c.scale(dpr,dpr);
  for(const badge of document.querySelectorAll('.r3-brand'))badge.remove();
  for(const [e,cv] of this.surfaces){const status=e.querySelector('.card-status');if(status)status.innerHTML=this.initialStatus.get(e)??'';cv.getContext('2d')!.clearRect(0,0,200,300);e.style.translate='';e.style.rotate='';e.style.clipPath='';if(!this.nativeDone.has(e.dataset.uid??''))e.style.visibility='';if(e.closest('.zone-mon')){this.stat(e,'atk',this.base(e,'atk'));this.stat(e,'def',this.base(e,'def'))}}
  for(let n=0;n<2;n++){const tray=this.player(n).querySelector('.pt-mana');const max=tray?.querySelector('.pt-mana-max'),mana=tray?.querySelector('.mana-readout b');if(max)max.textContent='/12';if(mana)mana.textContent='9';const hp=document.getElementById(n?'hp-opp':'hp-me');if(hp)hp.textContent='40'}
  setMaterialImage(this.source().querySelector<HTMLImageElement>('img')??undefined);const m=mode(this.id,this.cardId);if(m.startsWith('fire-'))this.fire(m,t);else if(m.startsWith('chosen-'))this.chosen(m,t);else this.extra(m,t);
  this.elapsed=this.playing?(performance.now()-this.playStarted)*this.speed:t;this.onTick(t);
 }
 fire(m:string,t:number){const source=this.source(),targets=this.targets(),v=this.variant,c=this.ctx,a=this.point(source),w=Math.max(34,source.getBoundingClientRect().width),heat=pulse(t,250,1100,2200);this.local(source,k=>hotSurface(k,t,heat,v));
  if(m==='fire-meteor'&&t>400){const n=this.player(this.side).querySelector('.pt-mana-max');if(n)n.textContent='/11'}
  if(m==='fire-summon'){if(this.trigger==='death'){this.local(source,k=>hotSurface(k,t,pulse(t,200,1050,1600),v));for(const [j,uid] of ['r3-fire-companion','r3-fire-return-2'].entries()){const e=this.el(uid),start=1700+j*700;if(e){const arrived=this.nativeDone.has(uid);e.style.visibility=t<start||this.playing&&!arrived?'hidden':'';this.pose(e,0,this.playing&&arrived?0:(1-smooth((t-start)/650))*25,0);this.local(e,k=>hotSurface(k,t,pulse(t,start,start+350,start+900),v));}}this.sceneLabel=t<1350?'炎術師の破壊':'シェルフへ → デッキ／シェルフからファイアー魔法2枚を手札へ';return;}const e=source;this.pose(e,0,(1-smooth(t/1400))*e.offsetHeight*.95*(this.side?-1:1)-Math.sin(sat((t-1200)/700)*Math.PI)*4,(1-smooth(t/1400))*(v?-7:5));this.local(e,k=>hotSurface(k,t,pulse(t,300,1400,3000),v));const companion=this.el('r3-fire-companion');if(companion){this.local(companion,k=>hotSurface(k,t,pulse(t,1700,2200,3300),v));const cost=companion.querySelector('.card-cost .seal-value');if(cost)cost.textContent=String(t>=1700?Math.max(0,defs.FIRE_BALL.cost-2):defs.FIRE_BALL.cost);}return}
  if(m==='fire-discount'){for(const [j,e] of [source,this.el('r3-fire-companion')].filter(Boolean).entries()){this.local(e,k=>{hotSurface(k,t,pulse(t,j*200,1100+j*200,2500+j*200),v);});if(e.dataset.uid==='r3-fire-companion'){const cost=e.querySelector('.card-cost .seal-value');if(cost)cost.textContent=String(t>=1100?Math.max(0,defs.FIRE_BALL.cost-2):defs.FIRE_BALL.cost);}}this.sceneLabel='このターンのファイアー魔法コスト-2';return}
  const damageBy=new Map<HTMLElement,number>();const count=m==='fire-arrow'?3:m==='fire-meteor'?8:m==='fire-zone'?targets.length+1:1;
  const contact=m==='fire-zone'?2300:1700,spacing=m==='fire-meteor'?220:m==='fire-arrow'?370:80;
  for(let j=0;j<count;j++){const e=j===targets.length||m==='fire-arrow'&&j===2||m==='fire-ball'&&this.targetKind==='player'?this.player(1-this.side):targets[j%targets.length];const b=this.point(e),hit=contact+j*spacing,flight=(t-(hit-650))/650;
   if(m==='fire-zone'){this.local(e,k=>{hotSurface(k,t,pulse(t,1400+j*90,2300+j*80,3500),v);});if(t>=1700&&t<2800){const p=this.point(e);impact(c,{x:p.x,y:p.y+e.getBoundingClientRect().height*.2},w*.65,sat((t-hit+240)/800),v)}}
   else {const from=m==='fire-meteor'?{x:b.x+(v?-55:55),y:b.y-180}:a;projectile(c,from,b,flight,m==='fire-ball'?w*.83:m==='fire-arrow'?w*.43:w*.65,t+j*79,v,m==='fire-arrow');impact(c,b,w*.7,(t-hit)/700,v)}
   if(t>=hit){const dmg=m==='fire-ball'?6:m==='fire-arrow'?1:m==='fire-zone'?(this.condition?9:5):2;if(e.matches('.card')){damageBy.set(e,(damageBy.get(e)??0)+dmg);const r=pulse(t,hit,hit+80,hit+430);this.pose(e,(v?1:-1)*r*2,r*7*(this.side?-1:1),r*(v?1.4:-1.4));this.local(e,k=>hotSurface(k,t,pulse(t,hit,hit+170,hit+640)*.8,v));}else {const hp=document.getElementById(this.side?'hp-me':'hp-opp');damageBy.set(e,(damageBy.get(e)??0)+dmg);if(hp)hp.textContent=String(40-(damageBy.get(e)??0))}}
  }
  for(const [el,n] of damageBy)if(el.matches('.card'))this.damage(el,n);
  if(t>=450&&(m==='fire-ball'||m==='fire-arrow')){const hp=document.getElementById(this.side?'hp-opp':'hp-me');if(hp)hp.textContent=String(40-(m==='fire-ball'?2:1))}
 }
 chosen(m:string,t:number){const e=this.source(),w=e.offsetWidth,v=this.variant,c=this.ctx;if(m==='chosen-summon'||m==='chosen-select'){
  const enter=smooth((t-180)/1350),press=pulse(t,1400,1550,1960);this.pose(e,(1-enter)*w*(v?-.7:.5),(1-enter)*e.offsetHeight*(this.side?-1:1)+press*3,(1-enter)*(v?-8:5));this.local(e,k=>weapon(k,this.cardId,t-1000,pulse(t,400,1450,3200),v));
  if(t>1200&&t<2600){const p=this.point(e);c.save();c.globalAlpha=pulse(t,1200,1550,2600)*.65;line(c,[[p.x-w*.35,p.y+e.getBoundingClientRect().height*.43],[p.x+w*.33,p.y+e.getBoundingClientRect().height*.45]],'#51445c',3);c.restore()}
 }else this.extra(m,t)}
 extra(m:string,t:number){additional(this,m,t)}
 attack(from:HTMLElement,to:HTMLElement,age:number){if(age<0||age>=880||this.reduced)return;const r=from.getBoundingClientRect(),d=to.getBoundingClientRect(),plan=attackPlan(r,d),pose=attackPose(plan,age),w=from.offsetWidth,h=from.offsetHeight;const clone=from.cloneNode(true) as HTMLElement;clone.removeAttribute('data-uid');clone.classList.add('fx-card-flight');clone.style.cssText=`position:fixed;left:0;top:0;width:${w}px;height:${h}px;--cw:${w}px;--ch:${h}px;transform-origin:0 0;pointer-events:none;z-index:126;visibility:visible`;clone.style.transform=new DOMMatrix().translate(pose.x,pose.y).rotate(pose.turn).scale(pose.scale).translate(-plan.origin.x,-plan.origin.y).multiply(projectedPlacement(from,w,h)).toString();const old=from.querySelector<HTMLCanvasElement>('.r3-surface'),next=clone.querySelector<HTMLCanvasElement>('.r3-surface');if(old&&next)next.getContext('2d')!.drawImage(old,0,0);document.body.append(clone);this.flights.push(clone);this.flightSources.add(from);from.style.visibility='hidden';drawAttackVisual(this.ctx,r,d,age/1000);}
 clearFlights(){this.flights.forEach(n=>n.remove());this.flights=[];for(const source of this.flightSources)if(!this.nativeDone.has(source.dataset.uid??''))source.style.visibility='';this.flightSources.clear();}

 async nativeAt(t:number,seq:number){
  const key=this.cardId==='FIRE_MASTER'&&this.trigger==='death'?'military-death':this.cardId==='GOLEM2'&&(this.id.id==='A054'||this.trigger==='ally-death')?'golem-ally-death':this.cardId==='GM6_8'&&this.trigger==='death'?'military-death':mode(this.id,this.cardId),side=this.side?'opp':'me';
  if(['golem-ally-death','military-death','A013','A033','A127','A128','A012','A027','A029','quick-sort'].includes(key)&&(key!=='A033'||this.condition)&&t>=(key==='A012'?3500:key==='golem-ally-death'?1250:key==='A128'||key==='military-death'?1350:2450)&&!(['A127','quick-sort'].includes(key)&&!this.condition)&&!this.nativeDone.has('destroy')){this.nativeDone.add('destroy');const victims=key==='golem-ally-death'?[this.el(`r3-other-${this.side}-3`)]:key==='A127'?this.targets():key==='A012'?this.g.players[this.side].field.slice(0,3).map((m:any)=>this.el(m.uid)):key==='A128'||key==='military-death'?[this.subject()]:[this.subject(1-this.side)];for(const e of victims){const uid=e.dataset.uid!;if(!uid)continue;const owner=this.g.players.find((p:any)=>p.field.some((x:any)=>x.uid===uid));const card=owner.field.find((x:any)=>x.uid===uid);this.nativeBusy=true;
    const restore=await freezeMaterial(e,()=>seq===this.epoch);
    if(!restore)return;
    this.materialHandoffs.add(restore);
    try {await destroyAnim(uid,owner===this.g.players[0]?'me':'opp');}
    finally {restore();this.materialHandoffs.delete(restore);if(seq===this.epoch)this.nativeBusy=false;else if(e.isConnected&&!this.nativeDone.has(uid))e.style.visibility='';}
    if(seq!==this.epoch)return;owner.field=owner.field.filter((x:any)=>x.uid!==uid);owner.discard.push(card);this.nativeDone.add(uid);e.style.visibility='hidden';const pile=document.getElementById(owner===this.g.players[0]?'pile-myDisc':'pile-oppDisc');if(pile){pile.dataset.count=String(owner.discard.length);const n=pile.querySelector('.pile-count');if(n)n.textContent=String(owner.discard.length);}this.events.push(`${key}: native destroy to shelf ${uid}`)}}
  if(this.cardId==='FIRE_MASTER'&&this.trigger==='death'){for(const [j,uid] of ['r3-fire-companion','r3-fire-return-2'].entries()){if(t<1700+j*700||this.nativeDone.has(uid))continue;const card=this.g.players[this.side].hand.find((c:any)=>c.uid===uid),target=this.el(uid),origin=document.getElementById(j?(this.side?'pile-oppDisc':'pile-myDisc'):(this.side?'pile-oppDeck':'pile-myDeck'))!;if(card&&target){this.nativeBusy=true;await this.arrive(card,origin,seq,target);if(seq!==this.epoch)return;this.nativeBusy=false;this.nativeDone.add(uid);this.events.push('FIRE_MASTER: selected fire spell arrived in hand '+uid);}}}
  if(this.cardId==='Q_TOWN'&&this.condition&&t>=2500&&!this.nativeDone.has('town-wine')){this.nativeDone.add('town-wine');const el=this.el('r3-town-wine'),card=this.g.players[this.side].hand.find((c:any)=>c.uid==='r3-town-wine');if(el&&card){this.nativeBusy=true;const restore=await freezeMaterial(el,()=>seq===this.epoch);if(!restore)return;this.materialHandoffs.add(restore);try{await exileCard(card,side,el)}finally{restore();this.materialHandoffs.delete(restore)}if(seq!==this.epoch)return;this.nativeBusy=false;this.nativeDone.add(card.uid);this.events.push('Q_TOWN: wine event through fixed default Rift before reward');}}
  if(key==='A102'&&t>=1850&&!this.nativeDone.has('cull-two')){this.nativeDone.add('cull-two');const cards=[this.inst('STARTER_TRASH','r3-generated-1'),this.inst('STARTER_TRASH','r3-generated-2')];this.nativeBusy=true;await exileGeneratedCards(cards,side,this.source().getBoundingClientRect());this.nativeBusy=false;if(seq!==this.epoch)return;this.g.players[this.side].removed.push(...cards);this.updateRift(this.side);this.events.push('A102: two Culls through fixed default Rift')}
  if(key==='A103'&&t>=700&&!this.nativeDone.has('cull-return')){this.nativeDone.add('cull-return');const pl=this.g.players[this.side],card=pl.removed[0];if(card){this.nativeBusy=true;await this.arrive(card,document.getElementById(this.side?'rift-opp':'rift-me')!,seq);this.nativeBusy=false;if(seq!==this.epoch)return;pl.removed.shift();this.updateRift(this.side);pl.discard.push(card);this.updatePile(this.side);this.events.push('A103: one public Cull returns to shelf before shot')}}
  if(this.cardId==='AJIN'&&this.condition&&t>=1500&&!this.nativeDone.has('attune-grant')){this.nativeDone.add('attune-grant');const card=this.inst('STARTER_MANA','r3-attune-gain');this.nativeBusy=true;await this.arrive(card,this.source(),seq);this.nativeBusy=false;if(seq!==this.epoch)return;this.g.players[this.side].discard.push(card);this.updatePile(this.side);this.events.push('AJIN: success adds one Attune to shelf')}
  if(key==='sorter-summon'&&t>=1600&&!this.nativeDone.has('sorter-culls')){this.nativeDone.add('sorter-culls');const cards=Array.from({length:6},(_,i)=>this.inst('STARTER_TRASH',`sort-cull-${i}`));this.nativeBusy=true;await exileGeneratedCards(cards.slice(0,3),side,this.source().getBoundingClientRect());if(seq!==this.epoch)return;await exileGeneratedCards(cards.slice(3),side,this.source().getBoundingClientRect());this.nativeBusy=false;if(seq!==this.epoch)return;this.g.players[this.side].removed.push(...cards);this.updateRift(this.side);this.events.push('SORTER: 3 available Culls plus 3 additional Culls through default Rift')}
  if((key==='A174'||this.cardId==='CHOSEN_AREA')&&this.condition&&t>=3300&&!this.nativeDone.has('victory')){this.nativeDone.add('victory');this.nativeBusy=true;await deathShatter(this.side?'me':'opp',this.side===0,'選ばれし領域');this.nativeBusy=false;this.events.push('A174: existing outcome entry')}
 }
 updateRift(n:number){const count=document.querySelector(`#rift-${n?'opp':'me'} .rift-label b`);if(count)count.textContent=String(this.g.players[n].removed.length)}
 updatePile(n:number){const pile=document.getElementById(n?'pile-oppDisc':'pile-myDisc'),count=this.g.players[n].discard.length;if(pile){pile.dataset.count=String(count);const label=pile.querySelector('.pile-count');if(label)label.textContent=String(count)}}
 async arrive(card:CardInst,source:HTMLElement,seq:number,destination?:HTMLElement){if(this.reduced)return;const r=source.getBoundingClientRect(),node=cardEl(card,{size:'hand'}),target=destination??document.getElementById(this.side?'pile-oppDisc':'pile-myDisc')!;node.classList.add('fx-card-flight');node.style.cssText=`position:fixed;left:${r.left}px;top:${r.top}px;width:${Math.max(36,r.width)}px;--cw:${Math.max(36,r.width)}px;z-index:126;pointer-events:none`;document.body.append(node);const abort=new AbortController();const check=setInterval(()=>{if(seq!==this.epoch)abort.abort()},30);try{await Promise.all([...node.querySelectorAll('img')].map(i=>i.decode().catch(()=>{})));await moveOnBoard({kind:'arrival',target,card:node,signal:abort.signal})}finally{clearInterval(check);node.remove()}}
 async nativeCosts(seq:number){if(this.cardId==='AMA'){const card=this.g.players[this.side].hand.find((c:any)=>c.uid==='r3-chest-payment');if(card){await discardFromHand(card,this.side?'opp':'me');if(seq!==this.epoch)return;this.nativeDone.add(card.uid);this.el(card.uid).style.visibility='hidden';this.g.players[this.side].discard.push(card);this.updatePile(this.side);this.events.push('AMA: treasure payment arrived at shelf before mana change')}}if(this.cardId==='FIRE_ZONE'&&!this.nativeDone.has('zone-cost')){this.nativeDone.add('zone-cost');const uid=`r3-payment-${this.side}`,card=this.g.players[this.side].hand.find((x:any)=>x.uid===uid),el=this.el(uid);if(card&&el){await exileCard(card,this.side?'opp':'me',el);if(seq!==this.epoch)return;this.nativeDone.add(uid);el.style.visibility='hidden';this.events.push('FIRE_ZONE: native exileCard completed before fire')}}}
 async reducedNative(run:()=>Promise<void>){const reduced=this.reduced;if(reduced)setFxSkip(true);try{await run()}finally{if(reduced)setFxSkip(false)}}
 play(){if(this.loading)return;this.stop();this.fixture();this.time=0;this.paint(0);const seq=++this.epoch;this.playing=true;this.playStarted=performance.now();this.nativeBusy=true;const clock=()=>{if(seq!==this.epoch||!this.playing)return;this.elapsed=(performance.now()-this.playStarted)*this.speed;if(this.nativeBusy)this.onTick(this.time);this.clockFrame=requestAnimationFrame(clock)};this.clockFrame=requestAnimationFrame(clock);void this.reducedNative(()=>this.nativeCosts(seq)).then(()=>{if(seq!==this.epoch)return;this.nativeBusy=false;this.start=performance.now();const tick=async(now:number)=>{if(seq!==this.epoch||!this.playing)return;const t=Math.min(this.duration,(now-this.start)*this.speed);this.paint(t);const before=performance.now();await this.reducedNative(()=>this.nativeAt(t,seq));if(seq!==this.epoch)return;this.start+=performance.now()-before;if(t<this.duration)this.frame=requestAnimationFrame(tick);else {this.playing=false;if(this.loop)this.play()}};this.frame=requestAnimationFrame(tick)})}
 seek(t:number){this.stop();this.paint(t)}
 stop(){this.epoch++;this.playing=false;this.nativeBusy=false;cancelAnimationFrame(this.frame);cancelAnimationFrame(this.clockFrame);this.clearFlights();setFxSkip(true);setFxSkip(false);for(const restore of this.materialHandoffs)restore();this.materialHandoffs.clear()}
 reset(){this.stop();this.fixture();this.paint(0)}
 async load(i:Item,card:string,v:number,side:number){this.stop();const seq=this.epoch;this.loading=true;this.id=i;this.cardId=card;this.variant=v;this.side=side;this.fixture();await Promise.all([...document.images].map(i=>i.decode().catch(()=>{})));if(seq!==this.epoch)return;this.loading=false;this.paint(0)}
 snapshot(){return {id:this.id.id,card:this.cardId,variant:this.variant,time:this.time,playing:this.playing,nativeBusy:this.nativeBusy,loading:this.loading,elapsed:this.elapsed,events:this.events,sourceVisible:getComputedStyle(this.source()).visibility,targets:this.targets().map(e=>({uid:e.dataset.uid,hp:e.querySelector('.ad-def .seal-value')?.textContent})),canvases:document.querySelectorAll('.r3-canvas').length}}
 dispose(){this.stop();this.canvas.remove();this.surfaces.clear();this.stopLayout();this.view.destroy()}
}
