import {triggersFor} from './scenario';
import '../../../styles/tokens.css';import '../../../styles/base.css';import '../../../styles/card.css';import '../../../styles/game-overlays.css';import '../../../styles/game.css';import '../../../styles/screens.css';import '../../../styles/reading-board.css';import '../../../styles/presentation.css';
import './style.css';
import {setLang} from '../../../i18n';import {items,item,cardsFor,defs,url,available} from './catalog';
import {Board} from './board';
setLang('ja');const q=new URLSearchParams(location.search),selected=item(q.get('item')??'S04'),card=q.get('card')??cardsFor(selected)[0]??'SOLDIER2';
if(q.has('stage')){
 document.body.className='r3-stage';const b=new Board(document.getElementById('app')!,selected,card);(window as any).seriesCR3=b;
 b.onTick=t=>parent.postMessage({type:'r3-tick',time:t,elapsed:b.elapsed,phase:b.phase()},location.origin);
 void b.ready.then(()=>parent.postMessage({type:'r3-ready'},location.origin));
 window.addEventListener('pagehide',()=>b.dispose());window.addEventListener('resize',()=>{if(!b.loading)b.seek(b.time)});document.addEventListener('visibilitychange',()=>{if(document.hidden)b.stop()});
}else{
 document.body.className='r3-shell';let active=selected,variant=+(q.get('variant')??0),api:Board|undefined;
 const app=document.getElementById('app')!;app.innerHTML=`<header><div><small>LORE / C · REVISION 3</small><h1>全担当アニメーション比較</h1><a href="/series-vfx-c.html">気合 R2 固定版</a></div><div class="controls"><select id="itemPicker" aria-label="演出項目">${items.map(i=>`<option value="${i.id}" ${i.id===active.id?'selected':''}>${i.id} ${i.name} (${i.status})</option>`).join('')}</select><select id="card" aria-label="対象カード"></select><select id="trigger" aria-label="発動場面"></select><select id="side" aria-label="陣営"><option value="0">自分側</option><option value="1">相手側</option></select><label><input id="condition" type="checkbox" checked>条件成立</label><select id="target" aria-label="対象種別"><option value="monster">モンスター</option><option value="player">プレイヤー</option></select><select id="role" aria-label="召喚する職"><option value="CHOSEN_KNIGHT">剣士</option><option value="CHOSEN_MAGE">魔法使い</option><option value="CHOSEN_ARCHER">弓手</option><option value="CHOSEN_ROGUE">盗賊</option></select><button id="one">①</button><button id="two">②</button><button id="play">再生</button><button id="stop">停止</button><button id="reset">リセット</button><select id="speed" aria-label="速度"><option value="1">1倍</option><option value="0.5">0.5倍</option><option value="0.25">0.25倍</option></select><label><input id="loop" type="checkbox">ループ</label><label><input id="reduced" type="checkbox">動き低減</label><label><input id="dark" type="checkbox">暗背景</label><input id="seek" aria-label="時間" type="range" min="0" max="4800" value="0"><output id="clock">準備中</output></div></header><aside><p>6シリーズ · 48効果 · 既存接続6<br>全案ユーザー未承認</p>${items.map(i=>`<button class="item ${i.id===active.id?'active':''}" data-id="${i.id}"><b>${i.id} ${i.name}</b><span>${i.status}</span></button>`).join('')}</aside><main><div id="detail"></div><iframe title="C R3 実盤面" src="${url(active.id,variant,card)}&stage=1"></iframe><div id="unmade" hidden>この項目は未制作です。制作済みの項目を選ぶと実盤面で比較できます。</div></main>`;
 const get=(id:string)=>document.getElementById(id)!;const frame=document.querySelector('iframe')!;const header=document.querySelector('header')!;const layout=new ResizeObserver(()=>document.documentElement.style.setProperty('--r3-header',`${header.getBoundingClientRect().height}px`));layout.observe(header);window.addEventListener('pagehide',()=>layout.disconnect());
 const supported=(_id:string)=>true;
 function detail(){get('trigger').hidden=(get('trigger') as HTMLSelectElement).options.length<2;get('role').hidden=(get('card') as HTMLSelectElement).value!=='COLOSSEUM';get('target').hidden=!['FIRE_BALL','GUNNER','HEAVY_GUNNER'].includes((get('card') as HTMLSelectElement).value)&&active.id!=='A076';get('detail').innerHTML=`<strong>${active.id} ${active.name} — ${active.status}</strong><span>${active.directions[variant]}</span><small>実GameViewの確定局面。長い攻撃比較用の体力付与あり。採用・本体接続は未承認。</small>`;get('one').textContent='① '+active.directions[0];get('two').textContent='② '+active.directions[1];get('one').classList.toggle('selected',variant===0);get('two').classList.toggle('selected',variant===1)}
 function populate(prefer?:string){get('card').innerHTML=(cardsFor(active).length?cardsFor(active):['SOLDIER2']).map(id=>`<option value="${id}" ${!supported(id)?'disabled':''}>${defs[id]?.nameJa??id} (${id})${!supported(id)?' — 未制作':''}</option>`).join('');const s=get('card') as HTMLSelectElement;s.value=prefer&&supported(prefer)?prefer:[...s.options].find(o=>!o.disabled)?.value??'';populateTrigger();detail()}
 function populateTrigger(){get('trigger').innerHTML=triggersFor((get('card') as HTMLSelectElement).value).map(([value,label])=>`<option value="${value}">${label}</option>`).join('')}
 async function apply(){if(!api)return;const playable=available(active);get('unmade').hidden=playable;frame.hidden=!playable;for(const id of ['play','stop','reset']) (get(id) as HTMLButtonElement).disabled=!playable;if(playable){api.trigger=(get('trigger') as HTMLSelectElement).value;(get('play') as HTMLButtonElement).disabled=true;api.condition=(get('condition') as HTMLInputElement).checked;api.targetKind=(get('target') as HTMLSelectElement).value;api.choice=(get('role') as HTMLSelectElement).value;await api.load(active,(get('card') as HTMLSelectElement).value,variant,+(get('side') as HTMLSelectElement).value);(get('play') as HTMLButtonElement).disabled=api.loading;history.replaceState({},'',url(active.id,variant,api.cardId,api.trigger));}detail()}
 populate(card);if(q.get('trigger'))(get('trigger') as HTMLSelectElement).value=q.get('trigger')!;for(const b of document.querySelectorAll<HTMLButtonElement>('button'))b.disabled=true;
 get('itemPicker').onchange=()=>{active=item((get('itemPicker') as HTMLSelectElement).value);populate();void apply()};for(const b of document.querySelectorAll<HTMLButtonElement>('.item'))b.onclick=()=>{active=item(b.dataset.id!);(get('itemPicker') as HTMLSelectElement).value=active.id;populate();document.querySelectorAll('.item').forEach(e=>e.classList.toggle('active',(e as HTMLElement).dataset.id===active.id));void apply()};
 get('role').onchange=()=>void apply();get('condition').onchange=()=>void apply();get('target').onchange=()=>void apply();get('one').onclick=()=>{variant=0;void apply()};get('two').onclick=()=>{variant=1;void apply()};get('trigger').onchange=()=>void apply();get('card').onchange=()=>{populateTrigger();void apply()};get('side').onchange=()=>void apply();get('play').onclick=()=>api?.play();get('stop').onclick=()=>api?.stop();get('reset').onclick=()=>api?.reset();get('seek').oninput=()=>api?.seek(+(get('seek') as HTMLInputElement).value);get('speed').onchange=()=>{if(api){api.stop();api.speed=+(get('speed') as HTMLSelectElement).value}};get('loop').onchange=()=>{if(api)api.loop=(get('loop') as HTMLInputElement).checked};get('reduced').onchange=()=>{if(api){api.reduced=(get('reduced') as HTMLInputElement).checked;api.seek(api.time)}};get('dark').onchange=()=>frame.contentDocument?.body.classList.toggle('r3-dark',(get('dark') as HTMLInputElement).checked);
 window.addEventListener('message',async e=>{if(e.source!==frame.contentWindow)return;if(e.data?.type==='r3-ready'){api=(frame.contentWindow as any).seriesCR3;await api!.ready;(window as any).seriesCR3=api;document.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.disabled=false);void apply()}if(e.data?.type==='r3-tick'){(get('seek') as HTMLInputElement).value=e.data.time;get('clock').textContent=`${((e.data.elapsed??e.data.time)/1000).toFixed(2)}秒 · ${e.data.phase}`}});
}
