import './style.css';
const elf='/art/cards/ELF.webp';
const $=<T extends HTMLElement>(q:string)=>document.querySelector<T>(q)!;
$('#app').innerHTML=`<main><aside><small>LORE / B · REVISION 2</small><h1>森の射手の裁定</h1><p class="status">R2制作中・未承認<br>R1全案はユーザー不採用</p><img class="reference" src="${elf}" alt="現行ELFアート"><p>ELFの対象確定後の破壊効果。<br>ELFは残り、対象は既定墓地へ。</p><label>方向<select id="variant"><option value="1">① 弓の金細工からの一閃</option><option value="2">② 葉影の光面で捉える</option></select></label><label>陣営<select id="side"><option value="0">自分のELF</option><option value="1">相手のELF</option></select></label><div class="row"><button id="play">対象確定して再生</button><button id="reset">戻す</button></div><div class="row keys"><button data-key="0">予兆</button><button data-key="1">移動</button><button data-key="2">接触</button></div><input aria-label="演出時刻" type="range" id="seek" min="0" max="620" value="0"><label><input type="checkbox" id="reduced">動きを減らす</label><p id="phase">準備中</p><details><summary>この試作の接続</summary><p>ELF召喚・対象選択を現行reduceで解決。選択した上級アサシンのdestroyイベントへ到達してから既存destroyAnimを呼び、確定状態を表示。作画シークでは結果を動かしません。</p><p>固定局面。通常対戦への導入は未実施。リフトは変更なし。</p></details><a href="/series-vfx-b.html?revision=1">不採用R1の比較証拠</a></aside><section><iframe title="ELF R2 実盤面" src="/series-vfx-b.html?revision=2&board=1"></iframe><span class="corner">ELF · 2 DIRECTIONS / NOT APPROVED</span></section></main>`;
let api:any,ready=false;
for(const control of document.querySelectorAll<HTMLInputElement|HTMLSelectElement|HTMLButtonElement>('button,select,input'))control.disabled=true;
const frame=$<HTMLIFrameElement>('iframe');
async function choose(){if(!ready)return;await api.choose(Number($<HTMLSelectElement>('#variant').value),Number($<HTMLSelectElement>('#side').value));$<HTMLInputElement>('#seek').max=String(api.lengths[api.variant]);}
$('#variant').onchange=()=>void choose();$('#side').onchange=()=>void choose();$('#play').onclick=()=>{if(ready)void api.play();};$('#reset').onclick=()=>{if(ready)void api.reset();};$('#seek').oninput=()=>{if(ready)void api.seek(Number($<HTMLInputElement>('#seek').value));};$('#reduced').onchange=()=>{if(ready)api.reduced=$<HTMLInputElement>('#reduced').checked;};
for(const b of document.querySelectorAll<HTMLButtonElement>('[data-key]'))b.onclick=()=>{if(ready)void api.seek(api.keys[api.variant][Number(b.dataset.key)]);};
const boot=setInterval(()=>{const a=(frame.contentWindow as any)?.seriesBR2Board;if(a){$('#phase').textContent=a.phase;if(a.ready&&!ready){api=a;ready=true;$<HTMLInputElement>('#seek').max=String(api.lengths[api.variant]);for(const control of document.querySelectorAll<HTMLInputElement|HTMLSelectElement|HTMLButtonElement>('button,select,input'))control.disabled=false;$<HTMLInputElement>('#reduced').checked=api.reduced;}if(ready){$('#play').toggleAttribute('disabled',api.busy);$('#reset').toggleAttribute('disabled',false);$<HTMLInputElement>('#seek').value=String(api.time);}}},100);
(window as any).seriesBR2={get ready(){return ready;},get board(){return api;}};window.addEventListener('pagehide',()=>clearInterval(boot),{once:true});
