import {LiquidScene,loadAssets} from './scene';import type {View} from './scene';import {variants,duration,contact} from './catalog';import './style.css';
const app=document.getElementById('app')!;
app.innerHTML=`<main class="wrap"><header><div><p class="eyebrow">LORE / LIQUID OPTICS · STUDY 02</p><h1>水の厚みを、光で描く。</h1><p>動く雫そのものの質感を作り直した5案。透過、映り込み、液体の首や接触面まで。<br>まず拡大で材質を選び、付与フローと実盤面で大きさ・動きを比較できます。</p></div><div class="edition">05 LIQUID STUDIES<br><span class="badge">比較試作 · 採用前</span></div></header><nav class="tabs"><button data-view="material" aria-pressed="true">質感を拡大</button><button data-view="flow">付与フロー</button><button data-view="board">実盤面</button></nav><div class="toolbar"><button id="play">一時停止</button><button id="restart">先頭から</button><label>速度<select id="speed"><option value="1">1×</option><option value=".5">0.5×</option><option value=".25">0.25×</option></select></label><button id="bg">暗い背景</button><button id="side">相手側</button><label><input id="old" type="checkbox">旧表現と比較</label><label><input id="reduced" type="checkbox">動きを低減</label><label><input id="multi" type="checkbox">両側同時</label></div><section class="hero"><div class="screen"><canvas id="hero" width="1280" height="740"></canvas><iframe title="雫の材質・実盤面比較" src="/dew-liquid-board.html"></iframe></div><aside class="detail"></aside></section><div class="timeline"><span id="time">0.00 / 3.00s</span><input id="seek" aria-label="再生位置" type="range" min="0" max="3000" value="0"><span id="ready">素材を準備中</span></div><div class="section-head"><h3>5種類の液体</h3><span>同じ時刻で比較。各パネルを押すと拡大します。</span></div><section class="grid"></section><p class="footnote">変更対象は動く液体の雫です。金縁の雫アイコンは従来素材を使用。付与フローは追加付与の 5 → 8 に統一しています。<br>屈折は画面内の背景を利用する近似表現、動きは比較用に設計したものです。実盤面では近傍のカード・肖像から背景を再構成します。</p><details><summary>描画の変更点と参照</summary><p>旧案の楕円グラデーションと白線を、立体の液面・法線・厚みに基づく透過と反射へ置き換えました。角度に応じた反射、背景の屈折、透過距離に応じた吸収を分けています。流体シミュレーションの厳密解ではありません。<br><a href="https://threejs.org/docs/pages/MeshPhysicalMaterial.html" target="_blank" rel="noreferrer">Three.js公式資料：透過・屈折率・厚み・吸収・環境反射</a>を制作上の参照にしています。今回は専用の液体シェーダーで実装しています。<br><a href="/dew-grant-six.html">以前の6案へ戻る</a></p></details></main>`;
const el=<T extends HTMLElement>(s:string)=>document.querySelector<T>(s)!;
const hero=el<HTMLCanvasElement>('#hero'),iframe=el<HTMLIFrameElement>('iframe');
const params=new URLSearchParams(location.search);let selected=Math.max(0,variants.findIndex(v=>v.id===params.get('id'))),view:View|'board'='material',ms=0,speed=1,dark=false,side=0,old=false,multi=false,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,playing=!params.has('paused')&&!reduced,scene:LiquidScene|undefined,ready=false,disposed=false,raf=0,last=performance.now(),cost=0,frames=0,loops=0;
el('.grid').innerHTML=variants.map((v,i)=>`<button class="tile" data-index="${i}"><canvas width="560" height="324"></canvas><div class="tile-body"><span class="id">${v.id} / ${v.tag}</span><h3>${v.name}</h3><p>${v.text}</p></div></button>`).join('');
const tiles=[...document.querySelectorAll<HTMLCanvasElement>('.tile canvas')];el<HTMLInputElement>('#reduced').checked=reduced;
function select(i:number){selected=i;const v=variants[i];el('.detail').innerHTML=`<span class="id">${v.id} / LIQUID MATERIAL</span><h2>${v.name}</h2><span class="material">${v.tag}</span><p class="description">${v.text}</p><div class="phase">反射は液面に追従</div><p class="stats">アイコンは共通 · 動く雫を比較</p>`;document.querySelectorAll<HTMLButtonElement>('.tile').forEach((b,j)=>b.setAttribute('aria-pressed',String(i===j)));history.replaceState(null,'',`?id=${v.id}${playing?'':'&paused=1'}`);draw();}
function send(){if(ready)iframe.contentWindow?.postMessage({kind:'dew-liquid-control',index:selected,ms,dark,side,multi,reduced,active:view==='board'&&!document.hidden},location.origin);}
function draw(){if(!scene||disposed)return;const start=performance.now();if(view!=='board')scene.draw(hero,selected,ms,view,dark,old,reduced,side);variants.forEach((_,i)=>scene!.draw(tiles[i],i,ms,view==='board'?'flow':view,dark,false,reduced,side));el('#time').textContent=`${(ms/1000).toFixed(2)} / 3.00s`;el<HTMLInputElement>('#seek').value=String(ms);send();frames++;cost+=performance.now()-start;}
function setPlaying(v:boolean){playing=v;last=performance.now();el('#play').textContent=v?'一時停止':'再生';}
function configure(o:{view?:View|'board';dark?:boolean;old?:boolean;side?:number;reduced?:boolean;multi?:boolean}){if(o.view!==undefined)view=o.view;if(o.dark!==undefined)dark=o.dark;if(o.old!==undefined)old=o.old;if(o.side!==undefined)side=o.side;if(o.reduced!==undefined)reduced=o.reduced;if(o.multi!==undefined)multi=o.multi;el('.screen').classList.toggle('board',view==='board');document.querySelectorAll<HTMLButtonElement>('.tabs button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));draw();}
document.querySelectorAll<HTMLButtonElement>('.tile').forEach(b=>b.onclick=()=>select(Number(b.dataset.index)));document.querySelectorAll<HTMLButtonElement>('.tabs button').forEach(b=>b.onclick=()=>configure({view:b.dataset.view as View|'board'}));
el('#play').onclick=()=>setPlaying(!playing);el('#restart').onclick=()=>{ms=0;draw()};el<HTMLSelectElement>('#speed').onchange=e=>speed=Number((e.target as HTMLSelectElement).value);el<HTMLInputElement>('#seek').oninput=e=>{ms=Number((e.target as HTMLInputElement).value);setPlaying(false);draw()};el('#bg').onclick=()=>{configure({dark:!dark});el('#bg').textContent=dark?'白い背景':'暗い背景'};el('#side').onclick=()=>{configure({side:1-side});el('#side').textContent=side?'自分側':'相手側'};
for(const key of ['old','reduced','multi'] as const)el<HTMLInputElement>('#'+key).onchange=e=>{configure({[key]:(e.target as HTMLInputElement).checked});if(key==='reduced'&&reduced)setPlaying(false)};
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==iframe.contentWindow)return;if(e.data?.kind==='dew-liquid-ready'){ready=true;send()}if(e.data?.kind==='dew-liquid-error')el('#ready').textContent=String(e.data.error)});
function tick(now:number){const dt=Math.max(0,now-last);last=now;if(playing&&scene&&!document.hidden){ms+=dt*speed;if(ms>duration+550){ms=0;loops++}draw()}if(!disposed)raf=requestAnimationFrame(tick)}
document.addEventListener('visibilitychange',()=>{last=performance.now();send()});function dispose(){if(disposed)return;disposed=true;cancelAnimationFrame(raf);scene?.dispose();iframe.contentWindow?.postMessage({kind:'dew-liquid-dispose'},location.origin)}window.addEventListener('pagehide',dispose,{once:true});
(window as any).dewLiquid={select,seek:(t:number)=>{ms=t;setPlaying(false);draw()},configure,play:setPlaying,dispose,get state(){return{selected,ms,ready,playing,loops,view,frames,meanDrawMs:cost/Math.max(1,frames),count:ms>=contact?8:5,variants:variants.length,disposed,webgl:!!scene?.glass.gl}}};
select(selected);void loadAssets().then(assets=>{scene=new LiquidScene(assets);el('#ready').textContent=scene.glass.gl?'5案 準備完了':'WebGL非対応';setPlaying(playing);draw();raf=requestAnimationFrame(tick)}).catch(e=>el('#ready').textContent=String(e));
