import './preview.css';
import {scenes} from './catalog';
import {familyStyles} from './forms';
import {paint,DURATION} from './renderer';
const $=<T extends HTMLElement>(q:string)=>document.querySelector<T>(q)!;
document.querySelector('#app')!.innerHTML=`<main><aside><header><small>LORE / MATERIAL STUDIES · B</small><h1>生命と記録の表層</h1><a href="/series-vfx-b.html?revision=2">R2 制作中・未承認の2案へ</a><p>R1：ユーザー不採用・比較証拠</p></header><label>場面<select id="scene"></select></label><label>対象カード<select id="card"></select></label><div class="row"><label>案<select id="variant"><option value="1">①</option><option value="2">②</option></select></label><label>陣営<select id="side"><option value="0">自分</option><option value="1">相手</option></select></label></div><h2 id="title"></h2><p id="intent"></p><div class="row"><button id="play">再生</button><button id="pause">停止</button><button id="reset">リセット</button></div><input aria-label="シーク" id="seek" type="range" min="0" max="3600" value="0"><div class="row"><label>速度<select id="speed"><option>1</option><option>0.5</option><option>0.25</option></select></label><label><input id="loop" type="checkbox">ループ</label><label><input id="sim" type="checkbox">同時</label></div><div class="row"><label><input id="dark" type="checkbox">暗盤面</label><label><input id="reduced" type="checkbox">動きを減らす</label></div><p id="phase"></p><details><summary>表面拡大 / 同一時刻</summary><canvas id="detail" width="520" height="560"></canvas></details><details><summary>現行ルール・検証範囲</summary><p id="notes"></p><p>固定デモ状態。通常ゲームへの接続・採用なし。ユーザーによる見た目承認は未確認。</p></details></aside><section id="stage"><iframe title="実GameView" src="/series-vfx-b.html?board=1"></iframe><canvas id="fx"></canvas><div id="caption"><span id="sceneName"></span><small>①/②は同一カード・盤面・時計で比較</small></div></section></main>`;
const select=$<HTMLSelectElement>('#scene'),cards=$<HTMLSelectElement>('#card');
for(const s of scenes){const o=document.createElement('option');o.value=s.id;o.textContent=`${s.id} ${s.name}`;select.append(o);}select.value='S03';
const frame=$<HTMLIFrameElement>('iframe'),canvas=$<HTMLCanvasElement>('#fx'),ctx=canvas.getContext('2d')!,detail=$<HTMLCanvasElement>('#detail'),dc=detail.getContext('2d')!;
let api:any,texture:HTMLCanvasElement,time=0,playing=false,prev=0,raf=0,token=0,ready=false;
const current=()=>scenes.find(s=>s.id===select.value)!;
const variant=()=>Number($<HTMLSelectElement>('#variant').value);
const reduce=()=> $<HTMLInputElement>('#reduced').checked;
const media=matchMedia('(prefers-reduced-motion: reduce)');$<HTMLInputElement>('#reduced').checked=media.matches;
function dimensions(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio,2);if(canvas.width!==Math.round(r.width*d)||canvas.height!==Math.round(r.height*d)){canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);}ctx.setTransform(d,0,0,d,0,0);return r;}
function render(){const r=dimensions();ctx.clearRect(0,0,r.width,r.height);dc.clearRect(0,0,520,560);if(!ready)return;const s={...current(),cardIds:[cards.value]},v=variant(),a=api.sample();api.outcome(time/DURATION);api.hide(time>0&&time<DURATION);api.hideSecondary($<HTMLInputElement>('#sim').checked&&time>210&&time<DURATION);
 const target=s.id!=='A064'&&['heal','dew','shield'].includes(s.kind)||cards.value==='D_BLUE'?a.hero:a.target;const enemy=cards.value==='D_RED'?a.enemyHero:a.enemy;paint(ctx,texture,s,v,time,a.source,target,enemy,s.kind==='purchase'?a.shelf:a.hand,reduce(),api.arrival);
 if($<HTMLInputElement>('#sim').checked&&api.secondary)paint(ctx,api.secondary||texture,s,v,Math.max(0,(time-210)*DURATION/(DURATION-210)),{...a.source,x:a.target.x,y:a.target.y},a.source,a.enemy,a.hand,reduce());
 if(document.querySelector('details')?.open)paint(dc,texture,s,v,time,{x:260,y:270,w:185,h:289},{x:420,y:380,w:85,h:133},{x:80,y:110,w:85,h:133},{x:400,y:450,w:85,h:133},reduce(),api.arrival);
 $<HTMLInputElement>('#seek').value=String(Math.round(time));canvas.dataset.time=String(Math.round(time));
 $('#phase').textContent=`${(time/1000).toFixed(2)}s · ${api.phase}`;
}
function tick(now:number){if(playing){time=Math.min(DURATION,time+(now-prev)*Number($<HTMLSelectElement>('#speed').value));if(time>=DURATION){if($<HTMLInputElement>('#loop').checked){time=0;api.reset();}else playing=false;}render();}prev=now;raf=requestAnimationFrame(tick);}
async function setup(fill=true){const my=++token;ready=false;playing=false;time=0;if(fill){cards.innerHTML='';for(const id of current().cardIds){const o=document.createElement('option');o.value=id;o.textContent=`${api.name(id)} / ${id}`;cards.append(o);}}const s=current(),v=variant(),style=familyStyles[s.family]||familyStyles.elf;$('#title').textContent=s.id==='N001'?(v===1?'滴脈の還流':'水膜の結露'):s.id==='N002'?(v===1?'玻璃盾の吸収':'六層の護片'):v===1?style.name1:style.name2;$('#intent').textContent=v===1?'カード表面の刻みから主形状が成長し、力が対象へ伝わる。':'カードの薄層がほどけ、異なる輪郭と時間差で再構成する。';$('#notes').textContent=s.notes;$('#sceneName').textContent=`${s.id} ${s.name} · 案${v}`;
 try{const tex=await api.prepare(s,cards.value,Number($<HTMLSelectElement>('#side').value));if(my!==token)return;texture=tex;ready=true;for(const o of Array.from(cards.options)){const c=api.g.players.flatMap((p:any)=>[...p.field,...p.hand]).find((c:any)=>c.id===o.value);if(c)o.textContent=`${c.nameJa||c.id} / ${c.id}`;}render();}catch(e){$('#phase').textContent=String(e);throw e;}}
function seek(t:number){playing=false;time=Math.max(0,Math.min(DURATION,t));api.reset();render();}
$('#play').onclick=()=>{if(time>=DURATION){time=0;api.reset();}playing=true;prev=performance.now();};$('#pause').onclick=()=>{playing=false;};$('#reset').onclick=()=>seek(0);
select.onchange=()=>void setup();cards.onchange=()=>void setup(false);$('#side').onchange=()=>void setup(false);$('#variant').onchange=()=>{const saved=time;void setup(false).then(()=>seek(saved));};$('#seek').oninput=()=>seek(Number($<HTMLInputElement>('#seek').value));$('#dark').onchange=()=>{api.dark($<HTMLInputElement>('#dark').checked);render();};$('#reduced').onchange=()=>render();$('#sim').onchange=()=>render();document.querySelector('details')!.ontoggle=()=>render();
function stop(){playing=false;time=0;api?.hide(false);render();}
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});window.addEventListener('resize',()=>{api?.reset();render();});window.addEventListener('pagehide',()=>{cancelAnimationFrame(raf);api?.dispose();},{once:true});
const boot=setInterval(()=>{const a=(frame.contentWindow as any)?.seriesBBoard;if(a?.ready){clearInterval(boot);api=a;void setup().then(()=>{requestAnimationFrame(tick);});}},100);
(window as any).seriesB={get ready(){return ready;},get playing(){return playing;},get time(){return time;},scenes,seek,async choose(id:string,v=1,card?:string,side=0){select.value=id;$<HTMLSelectElement>('#variant').value=String(v);$<HTMLSelectElement>('#side').value=String(side);await setup();if(card&&cards.value!==card){cards.value=card;await setup(false);}},play(){ $('#play').click();},reset:()=>seek(0),dispose(){stop();cancelAnimationFrame(raf);api?.dispose();},state:()=>api.g};
