import '../../styles/tokens.css';import '../../styles/base.css';import '../../styles/card.css';import '../../styles/game-overlays.css';import '../../styles/game.css';import '../../styles/screens.css';import '../../styles/reading-board.css';import '../../styles/presentation.css';
import {GameView,setMyAvatar,setOppAvatar} from '../../ui/boardView';import {startBoardLayout} from '../../ui/layout';import {waitForDuel} from '../../ui/duelReadiness';import {boardMatrix,layoutRect} from '../../ui/boardProjection';import {clearMonsterStates} from '../../ui/monster/runtime';import {createGame} from '../../shared/engine';import {DB} from '../../shared/cards';import {setLang} from '../../i18n';import {surface} from './surface';import {Renderer} from './renderer';import {cards,duration,ease,type Id} from './catalog';
setLang('ja');setMyAvatar('SEEKER_BLUE');setOppAvatar('SEEKER_RED');document.body.style.cssText='margin:0;overflow:hidden;background:#f2eee8';const css=document.createElement('style');css.textContent='.topbar,.help-callout,.help-fab,.mute-fab{display:none!important}';document.head.append(css);
const root=document.getElementById('app')!,noop=()=>{},renderer=new Renderer(),faces=new Map<Id,HTMLCanvasElement>();let ready=false,disposed=false,id:Id='HEXER4',v=3,ms=0,side=0,multi=false,reduced=false,dark=false;
const request=()=>parent.postMessage({kind:'hexer-hand'},location.origin);
const view=new GameView(root,0,{onPlay:request,onBlockedPlay:request,onAttack:noop,onBlockedAttack:noop,onReorder:noop,onChooseTarget:noop,onBuyMarket:noop,onBuySupply:noop,onRefresh:noop,onEndTurn:noop,onSurrender:noop});
const overlay=document.createElement('canvas');overlay.className='hexer-overlay';overlay.style.cssText='position:fixed;inset:0;width:100%;height:100%;pointer-events:none;z-index:180';document.body.append(overlay);let originals:HTMLElement[]=[];let hand:HTMLElement|null=null;let boardFace:HTMLCanvasElement|null=null,captureVersion=0;
const mon=(c:string,uid:string)=>({...DB[c],uid,exhausted:false,summonedTurn:0,dmg:0,tempAtk:0,atkMod:0,defMod:0});
function restore(){originals.forEach(n=>n.style.visibility='');if(hand)hand.style.visibility='';overlay.getContext('2d')!.clearRect(0,0,overlay.width,overlay.height);}
function setup(){restore();const g=createGame({mode:'bot',seed:85,starting:0,p0:{id:'hexer-self',name:'YOU'},p1:{id:'hexer-opp',name:'OPPONENT'}}).state;g.turn=3;g.phase='main';g.pending=null;for(const [i,p]of g.players.entries()){p.openingDrawReady=false;p.mana=20;p.maxMana=20;p.hp=30;p.enchants=[];p.quests=[];p.traps=[];p.field=[0,1,2].map(j=>mon(multi?id:j===1?id:'M4',`hexer-${i}-${j}`));p.hand=[{...DB[id],uid:`hexer-hand-${i}`}];}view.render(g);view.setHandOpen(true);clearMonsterStates(root);originals=Array.from(root.querySelectorAll<HTMLElement>('.zone-mon .card'));hand=root.querySelector<HTMLElement>('[data-uid="hexer-hand-0"]');if(hand){hand.style.cursor='pointer';hand.title='クリックで召喚';hand.onclick=e=>{e.stopPropagation();request();};}boardFace=null;const version=++captureVersion;const anchor=originals.find(n=>n.dataset.uid===`hexer-0-1`);if(anchor)void surface(id,anchor).then(face=>{if(version===captureVersion){boardFace=face;draw();}});}
function targetMatrix(n:HTMLElement){const r=layoutRect(n),elevation=Number(n.closest<HTMLElement>('[data-board-plane]')?.dataset.boardPlane)||0;return boardMatrix(r.left+r.width/2,r.top+r.height/2,elevation).scale(r.width/180,-r.height/270,r.width/180);}
function draw(){restore();if(!ready||disposed||document.hidden)return;root.style.filter=dark?'brightness(.62)':'';const w=innerWidth,h=innerHeight;if(overlay.width!==w||overlay.height!==h){overlay.width=w;overlay.height=h;}const c=overlay.getContext('2d')!;const targets=originals.filter(n=>n.dataset.uid?.startsWith(`hexer-${side}-`)&&(multi||n.dataset.uid.endsWith('-1')));const total=duration(id);
 if(ms<=0&&!reduced){targets.forEach(n=>n.style.visibility='hidden');return;}
 if(hand)hand.style.visibility='hidden';if(ms>=total||reduced)return;
 for(const n of targets){n.style.visibility='hidden';let matrix=targetMatrix(n);let local=v===3?ms:(ms-550)/(total-550)*total;
 if(v!==3&&ms<550){const r=hand?.getBoundingClientRect();const from=new DOMMatrix().translate(r?r.left+r.width/2:w/2,side===1?h*.06:r?r.top+r.height/2:h*.9,0).scale((r?.width||75)/180,-(r?.height||112)/270,.6);const a=from.toFloat64Array(),b=matrix.toFloat64Array(),k=ease(0,550,ms);matrix=new DOMMatrix(Array.from(a,(val,i)=>val+(b[i]-val)*k));local=0;}
 renderer.drawBoard(c,v!==3&&ms<550?faces.get(id)!:(boardFace??faces.get(id)!),id,v,Math.max(0,local),matrix,w,h,reduced);
 }
}
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent)return;if(e.data?.kind==='hexer-suspend'){restore();return;}if(e.data?.kind!=='hexer-control')return;const d=e.data;let next=cards.includes(d.id)?d.id:id;let rebuild=next!==id||multi!==!!d.multi;id=next;v=Math.max(0,Math.min(5,Number(d.v)||0));ms=Math.max(0,Number(d.ms)||0);side=d.side===1?1:0;multi=!!d.multi;reduced=!!d.reduced;dark=!!d.dark;if(rebuild)setup();draw();});
window.addEventListener('resize',()=>requestAnimationFrame(draw));document.addEventListener('visibilitychange',()=>{if(document.hidden)restore();});setup();const stop=startBoardLayout();
window.addEventListener('pagehide',()=>{disposed=true;restore();renderer.dispose();overlay.remove();stop();view.destroy();},{once:true});
(window as any).hexerBoard={get state(){return{ready,id,v,ms,side,multi,hidden:originals.filter(n=>n.style.visibility==='hidden').length,handHidden:hand?.style.visibility==='hidden',renderer:renderer.status,targets:originals.filter(n=>n.dataset.uid?.startsWith(`hexer-${side}-`)).map(n=>({uid:n.dataset.uid,rect:n.getBoundingClientRect().toJSON()}))};},restore};
void(async()=>{await waitForDuel(root);for(const c of cards)faces.set(c,await surface(c));ready=true;draw();parent.postMessage({kind:'hexer-ready'},location.origin);})().catch(e=>parent.postMessage({kind:'hexer-error',error:String(e)},location.origin));
