import {cards,names,designs,duration,type Id} from './catalog';
import {Renderer} from './renderer';import {surface} from './surface';import './style.css';
const root=document.getElementById('app')!;let id:Id='HEXER4',v=0,ms=0,mode='grid',speed=1,playing=false,loop=true,dark=false,side=0,multi=false,reduced=matchMedia('(prefers-reduced-motion:reduce)').matches,angle='oblique',ready=false,raf=0,last=0,disposed=false,boardReady=false;const faces=new Map<Id,HTMLCanvasElement>(),renderer=new Renderer();
root.innerHTML=`<main><header><span class="eyebrow">LORE / BLOOD · SUMMON STUDIES / 08 OCT 2026</span><h1>呪いは、面からほどける。</h1><p>呪術師の召喚 · 6つの物質、6つの解き方。</p><span class="badge">比較試作 · 未採用</span></header><nav class="toolbar"><div class="tabs"><button data-mode="grid" class="active">六案比較</button><button data-mode="detail">一案を拡大</button><button data-mode="board">実盤面・手札から</button></div><select id="card" aria-label="対象カード">${cards.map((c,i)=>`<option value="${c}" ${i===4?'selected':''}>${names[i]}</option>`).join('')}</select><select id="angle" aria-label="視点"><option value="oblique">斜めから</option><option value="top">真上から</option><option value="side">接地を横から</option></select><button id="theme">暗い背景へ</button></nav><p id="status" role="status">カードと素材を準備しています…</p><section id="grid" class="grid">${designs.map((d,i)=>`<article><div class="label"><span>0${i+1}</span><div><small>${d.en}</small><h2>${d.name}</h2></div><button data-zoom="${i}" aria-label="${d.name}を拡大">↗</button></div><canvas data-v="${i}" aria-label="${d.name}の召喚アニメーション"></canvas><div class="description"><small>${d.material}</small><p>${d.note}</p></div></article>`).join('')}</section><section id="detail" hidden><div class="choices">${designs.map((d,i)=>`<button data-vchoice="${i}">0${i+1} ${d.name}</button>`).join('')}</div><canvas id="large"></canvas><p id="detail-note"></p></section><section id="board" hidden><div class="choices">${designs.map((d,i)=>`<button data-vchoice="${i}">0${i+1} ${d.name}</button>`).join('')}<button id="side">自分側</button><button id="multi">1枚召喚</button></div><p class="hint">手札のカードを押すと召喚します。空いた中央スロットへ移動してから、選択した演出が始まります。</p><iframe title="手札から召喚できるLORE実盤面" src="about:blank"></iframe></section><div class="transport"><button id="play" disabled>再生</button><button id="restart" disabled>最初から</button><select id="speed" aria-label="再生速度"><option value="1">1×</option><option value="0.5">0.5×</option><option value="0.25">0.25×</option></select><input id="seek" aria-label="再生位置" type="range" min="0" max="3700" value="0"><output id="clock">0.00 / 3.70</output><label><input id="loop" type="checkbox" checked>反復</label><label><input id="reduced" type="checkbox">動きを低減</label></div><footer><button id="evidence">検証・録画を保存</button><output id="qa-status"></output><p>5枚 × 6案。見習いは短い予兆と少ない構造、ケロイドは重い溜めと重層の素材。カードは盤面と平行なまま裏面で接地します。</p><p>召喚演出の比較用です。呪いの付与・ダイス成功・魔法無効の効果発動は別の演出です。</p></footer></main>`;
const $=<T extends HTMLElement=HTMLElement>(s:string)=>root.querySelector<T>(s)!,frame=$<HTMLIFrameElement>('iframe');const samples:number[]=[];
function send(suspend=false){if(!boardReady)return;frame.contentWindow?.postMessage(suspend?{kind:'hexer-suspend'}:{kind:'hexer-control',id,v,ms,side,multi,reduced,dark},location.origin);}
function canvas(c:HTMLCanvasElement,k:number){let r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio,1.5),w=Math.round(r.width*d),h=Math.round(r.height*d);if(!w||!h)return;if(c.width!==w||c.height!==h){c.width=w;c.height=h;}const x=c.getContext('2d')!;x.setTransform(1,0,0,1,0,0);x.clearRect(0,0,w,h);renderer.draw(x,faces.get(id)!,id,k,ms,w,h,reduced,angle);}
function draw(){if(!ready||disposed)return;let start=performance.now();if(mode==='grid')root.querySelectorAll<HTMLCanvasElement>('[data-v]').forEach(c=>canvas(c,Number(c.dataset.v)));else if(mode==='detail')canvas($<HTMLCanvasElement>('#large'),v);else send();samples.push(performance.now()-start);if(samples.length>300)samples.shift();$<HTMLInputElement>('#seek').max=String(duration(id));$<HTMLInputElement>('#seek').value=String(ms);$('#clock').textContent=`${(Math.min(ms,duration(id))/1000).toFixed(2)} / ${(duration(id)/1000).toFixed(2)}`;}
function pause(){playing=false;cancelAnimationFrame(raf);$('#play').textContent='再生';}
function tick(now:number){if(!playing)return;ms+=Math.max(0,now-last)*speed;last=now;if(ms>duration(id)+650){if(loop)ms=0;else{ms=duration(id);pause();}}draw();if(playing)raf=requestAnimationFrame(tick);}
function play(){if(!ready||reduced)return;if(ms>=duration(id))ms=0;pause();playing=true;last=performance.now();$('#play').textContent='一時停止';raf=requestAnimationFrame(tick);}
function setMode(next:string){pause();mode=next;for(const s of ['grid','detail','board'])$('#'+s).hidden=s!==next;root.querySelectorAll<HTMLElement>('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));if(mode==='board'){ms=0;if(frame.getAttribute('src')==='about:blank'){boardReady=false;frame.src='/hexer-six.html?board';}}else{send(true);frame.src='about:blank';boardReady=false;}draw();}
function select(k:number){v=Math.max(0,Math.min(5,k));root.querySelectorAll<HTMLElement>('[data-vchoice]').forEach(b=>b.classList.toggle('active',Number(b.dataset.vchoice)===v));$('#detail-note').textContent=designs[v].note;draw();}
root.querySelectorAll<HTMLElement>('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode!));root.querySelectorAll<HTMLElement>('[data-zoom]').forEach(b=>b.onclick=()=>{select(Number(b.dataset.zoom));setMode('detail');play();});root.querySelectorAll<HTMLElement>('[data-vchoice]').forEach(b=>b.onclick=()=>{select(Number(b.dataset.vchoice));ms=0;draw();});
$('#play').onclick=()=>playing?pause():play();$('#restart').onclick=()=>{ms=0;draw();play();};$<HTMLInputElement>('#seek').oninput=()=>{pause();ms=Number($<HTMLInputElement>('#seek').value);draw();};$<HTMLSelectElement>('#speed').onchange=()=>speed=Number($<HTMLSelectElement>('#speed').value);$<HTMLSelectElement>('#card').onchange=()=>{id=$<HTMLSelectElement>('#card').value as Id;ms=0;draw();};$<HTMLInputElement>('#loop').onchange=()=>loop=$<HTMLInputElement>('#loop').checked;$<HTMLSelectElement>('#angle').onchange=()=>{angle=$<HTMLSelectElement>('#angle').value;draw();};$('#theme').onclick=()=>{dark=!dark;document.body.classList.toggle('dark',dark);$('#theme').textContent=dark?'白い背景へ':'暗い背景へ';draw();};$('#side').onclick=()=>{side=1-side;$('#side').textContent=side?'相手側':'自分側';ms=0;draw();};$('#multi').onclick=()=>{multi=!multi;$('#multi').textContent=multi?'3枚同時':'1枚召喚';ms=0;draw();};
function reduce(value:boolean){reduced=value;$<HTMLInputElement>('#reduced').checked=value;pause();ms=value?duration(id):0;draw();}$<HTMLInputElement>('#reduced').onchange=()=>reduce($<HTMLInputElement>('#reduced').checked);matchMedia('(prefers-reduced-motion:reduce)').addEventListener('change',e=>reduce(e.matches));
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==frame.contentWindow)return;if(e.data?.kind==='hexer-ready'){boardReady=true;send();}if(e.data?.kind==='hexer-hand'){ms=0;play();}if(e.data?.kind==='hexer-error')$('#status').textContent='盤面の準備に失敗: '+e.data.error;});
window.addEventListener('resize',()=>{pause();draw();});document.addEventListener('visibilitychange',()=>{if(document.hidden){pause();send(true);}});window.addEventListener('pagehide',()=>{pause();disposed=true;renderer.dispose();send(true);},{once:true});
(window as any).hexerLab={get state(){return{ready,mode,id,v,ms,playing,reduced,side,multi,boardReady,renderer:renderer.status,drawP95:[...samples].sort((a,b)=>a-b)[Math.floor(samples.length*.95)]};},seek(t:number,k=v){pause();ms=t;select(k);},setMode,setCard(k:Id){id=k;$<HTMLSelectElement>('#card').value=k;ms=0;draw();},setSide(s:number){side=s;ms=0;draw();},setMulti(b:boolean){multi=b;draw();},reduce,play,pause};
void(async()=>{for(const c of cards)faces.set(c,await surface(c));ready=true;$('#play').removeAttribute('disabled');$('#restart').removeAttribute('disabled');select(0);$('#status').textContent='6案を同時に再生できます。各案の ↗ で拡大、実盤面では手札から召喚。';if(reduced)reduce(true);else{ms=duration(id)*.52;draw();play();}})().catch(e=>{$('#status').textContent='準備に失敗: '+e.message;console.error(e);});

$('#evidence').onclick=async()=>{if(!ready)return;pause();$('#evidence').setAttribute('disabled','');try{const q=await import('./qa');await q.run({renderer,faces,root,setMode,setCard(k:Id){id=k;$<HTMLSelectElement>('#card').value=k;},seek(t:number,k:number){ms=t;v=k;draw();},status:$('#qa-status')});}catch(e){$('#qa-status').textContent=String(e);}finally{$('#evidence').removeAttribute('disabled');}};
