import {cards,names,designs,duration,motion,type Id} from './catalog';import type {Renderer} from './renderer';
type Harness={renderer:Renderer;faces:Map<Id,HTMLCanvasElement>;root:HTMLElement;setMode:(m:string)=>void;setCard:(id:Id)=>void;seek:(t:number,v:number)=>void;status:HTMLElement};
async function save(name:string,data:Blob|string){const r=await fetch('/__hexer-evidence/'+name,{method:'POST',body:data});if(!r.ok)throw Error('Evidence save failed '+r.status);}
const blob=(c:HTMLCanvasElement)=>new Promise<Blob>(resolve=>c.toBlob(b=>resolve(b!),'image/png'));
export async function run(h:Harness){
 h.status.textContent='全30組み合わせ・連続再生を検証中…';h.setMode('grid');
 const c=document.createElement('canvas');c.width=440;c.height=520;const x=c.getContext('2d')!;const checks:unknown[]=[];let valid=0;
 const sheet=document.createElement('canvas');sheet.width=1320;sheet.height=1810;const s=sheet.getContext('2d')!;s.fillStyle='#eeeae5';s.fillRect(0,0,sheet.width,sheet.height);
 for(let row=0;row<cards.length;row++){const id=cards[row],face=h.faces.get(id)!;for(let v=0;v<6;v++){let populated=0;for(const f of [.12,.34,.58,.78,1]){x.clearRect(0,0,440,520);h.renderer.draw(x,face,id,v,duration(id)*f,440,520);const p=x.getImageData(0,0,440,520).data;let count=0;for(let i=3;i<p.length;i+=4)if(p[i]>32)count++;if(count>3000)populated++;}checks.push({id,v:v+1,visibleFrames:populated});if(populated===5)valid++;
 x.clearRect(0,0,440,520);h.renderer.draw(x,face,id,v,duration(id)*.58,440,520);s.drawImage(c,v*220,row*360+24,220,300);s.fillStyle='#302535';s.font='13px sans-serif';s.fillText(`${names[row]} / 0${v+1}`,v*220+10,row*360+17);s.font='12px sans-serif';s.fillText(designs[v].name,v*220+10,row*360+330);await new Promise(r=>setTimeout(r,0));}}
 await save('all-thirty.png',await blob(sheet));
 h.setCard('HEXER4');h.seek(2100,0);const overview=document.createElement('canvas');overview.width=1320;overview.height=1000;const o=overview.getContext('2d')!;
 const paintOverview=()=>{o.fillStyle='#eeeae5';o.fillRect(0,0,1320,1000);o.fillStyle='#302535';o.font='26px serif';o.fillText('LORE · 呪術師召喚 / 6案',24,42);h.root.querySelectorAll<HTMLCanvasElement>('[data-v]').forEach((el,i)=>{const col=i%3,row=Math.floor(i/3);o.fillStyle='#f8f6f1';o.fillRect(col*440+10,row*450+70,420,430);o.drawImage(el,col*440+12,row*450+104,416,310);o.fillStyle='#302535';o.font='18px serif';o.fillText(`0${i+1} ${designs[i].name}`,col*440+30,row*450+97);o.font='11px sans-serif';o.fillText(designs[i].material,col*440+30,row*450+448);});};paintOverview();await save('six-peak.png',await blob(overview));
 const stream=overview.captureStream(60),chunks:Blob[]=[],rec=new MediaRecorder(stream,{mimeType:'video/webm;codecs=vp9',videoBitsPerSecond:6500000});rec.ondataavailable=e=>chunks.push(e.data);const stopped=new Promise<void>(r=>rec.onstop=()=>r());const intervals:number[]=[];let previous=0;rec.start();const begin=performance.now();
 await new Promise<void>(resolve=>{function tick(now:number){if(previous)intervals.push(now-previous);previous=now;const ms=now-begin;h.seek(Math.min(ms,3700),0);paintOverview();if(ms<4200)requestAnimationFrame(tick);else resolve();}requestAnimationFrame(tick);});rec.stop();await stopped;stream.getTracks().forEach(t=>t.stop());await save('six-continuous.webm',new Blob(chunks,{type:'video/webm'}));
 const sorted=[...intervals].sort((a,b)=>a-b);const physics=cards.map(id=>({id,contact:motion(id,0).contact,contactHeight:motion(id,motion(id,0).contact).height,finalHeight:motion(id,duration(id)).height}));
 const report={date:'2026-10-08',cards:cards.length,variants:designs.length,combinations:valid,checks,physics,normalPlayback:{frames:intervals.length,frameIntervalMedian:sorted[Math.floor(sorted.length*.5)],frameIntervalP95:sorted[Math.floor(sorted.length*.95)],over50ms:intervals.filter(t=>t>50).length},renderer:h.renderer.status,userApproved:false,stage:'local prototype',runtimeIntegrated:false};await save('report.json',JSON.stringify(report,null,2));h.seek(2100,0);h.status.textContent=`30組×5時点: ${valid}/30 · 中央フレーム間隔 ${report.normalPlayback.frameIntervalMedian.toFixed(1)}ms · 録画保存済み`;
}
