import '../../../styles/tokens.css';import '../../../styles/base.css';import '../../../styles/card.css';import '../../../styles/game-overlays.css';import '../../../styles/game.css';import '../../../styles/screens.css';import '../../../styles/reading-board.css';import '../../../styles/presentation.css';
import {GameView,setMyAvatar,setOppAvatar} from '../../../ui/boardView';import {createGame} from '../../../shared/engine';import {DB,STARTERS} from '../../../shared/cards';import type {GameState,FieldMon,CardInst} from '../../../shared/types';import {startBoardLayout} from '../../../ui/layout';import {waitForDuel} from '../../../ui/duelReadiness';import {setLang} from '../../../i18n';import {destroyAnim} from '../../../ui/anim';import {paint,ready as materialReady,SIZE} from './material';
setLang('ja');setMyAvatar('SEEKER_BLUE');setOppAvatar('SEEKER_RED');document.body.style.cssText='margin:0;overflow:hidden';
const nop=()=>{};const view=new GameView(document.querySelector('#app')!,0,{onPlay:nop,onBlockedPlay:nop,onAttack:nop,onBlockedAttack:nop,onReorder:nop,onChooseTarget:nop,onBuyMarket:nop,onBuySupply:nop,onRefresh:nop,onEndTurn:nop,onSurrender:nop});
(view as unknown as {statRise:{dispose():void}}).statRise.dispose();
const defs={...DB,...STARTERS};const mon=(id:string,uid:string)=>({...defs[id],uid,exhausted:false,summonedTurn:0,tempAtk:0,atkMod:0,defMod:0,dmg:0}as FieldMon);const card=(id:string,uid:string)=>({...defs[id],uid}as CardInst);
let g:GameState,base:GameState,variant=1,side=0,time=0,speed=1,playing=false,ready=false,previous=0,raf=0,epoch=0,handoff=false,modelStage=-1,stopLayout=()=>{};
const overlay=Object.assign(document.createElement('canvas'),{width:SIZE,height:SIZE});overlay.className='d-r2-material';overlay.style.cssText='position:absolute;inset:0;width:100%;height:100%;pointer-events:none;z-index:3';
const target=()=>document.querySelector<HTMLElement>('.card[data-uid="r2-target"]');const report=(x:Record<string,unknown>)=>parent.postMessage({kind:'d-r2-status',...x},location.origin);
function render(){view.render(g);view.setHandOpen(false);document.querySelector('.help-callout')?.remove();}
function sync(){const s=time<300?0:time<850?1:time<2450?2:time<4150?3:4;if(s===modelStage)return;modelStage=s;g=structuredClone(base);if(s>=1){g.players[side].field[1].passivesG=['decay'];g.players[side].field[2].passivesG=['decay'];}if(s>=2)g.players[1-side].field[1].decayCnt=s-1;render();}
function draw(){sync();const art=target()?.querySelector<HTMLElement>('.card-art');if(art&&overlay.parentElement!==art)art.append(overlay);paint(overlay,variant,time);const grant=document.querySelector<HTMLElement>('.card[data-uid="r2-grant"] [data-psv="decay"]');if(grant)grant.style.filter=time<750&&time>300?`drop-shadow(0 0 3px #bde5cb) brightness(${1+Math.sin((time-300)/450*Math.PI)*.65})`:'';report({time,phase:time<850?'暗器製造の能力付与 → 味方2体の既存腐敗アイコン。対象への感染とは別。':time<2450?'第1の付与：敵カードに1個。生きたカード面に局所侵食が定着。':time<4150?'第2の付与：2個。同じ侵食起点から成長。カード・数値は存続。':time<4680?'第3の付与：3個。ここから固定シナリオの破壊成功が確定。':'破壊確定：局所素材を解放 → 既存 destroyAnim → シェルフ。'});}
async function setup(v=variant,s=side){if(handoff){report({phase:'既定破壊処理の終了待ちです。終わるまで切替できません。'});return;}const ticket=++epoch;ready=false;playing=false;variant=v;side=s;time=0;modelStage=-1;overlay.remove();g=createGame({mode:'bot',seed:71,starting:0,p0:{id:'r2-me',name:'YOU'},p1:{id:'r2-opp',name:'OPPONENT'}}).state;g.turn=3;g.pending=null;for(const [i,p]of g.players.entries()){p.openingDrawReady=false;p.mana=8;p.maxMana=12;p.hp=40;p.enchants=[];p.quests=[];p.removed=[];p.hand=[card('STARTER_TRASH',`h${i}1`),card('DECAY_CRAFT',`h${i}2`),card('STARTER_CHEST',`h${i}3`)];p.discard=[card('STARTER_TRASH',`d${i}`)];p.field=i===side?[mon('RUST_SHROOM','r2-source'),mon('ELF','r2-grant'),mon('M4','r2-neighbor')]:[mon('MIMIC2','r2-other'),mon('ELF','r2-target'),mon('M4','r2-neighbor2')];}base=structuredClone(g);render();stopLayout();stopLayout=startBoardLayout();await Promise.all([waitForDuel(document.querySelector('#app')!),materialReady,document.fonts.ready]);if(ticket!==epoch)return;ready=true;draw();report({phase:'準備完了。R2未承認の固定イベント試作。通し再生で既存シェルフ退場へ接続。'});}
async function finish(){playing=false;handoff=true;paint(overlay,variant,time);report({time,phase:'既存 destroyAnim へ引き継ぎ中（独自リフト演出なし）'});try{await destroyAnim('r2-target',side===0?'opp':'me');const p=g.players[1-side],at=p.field.findIndex(x=>x.uid==='r2-target');if(at>=0)p.discard.push(p.field.splice(at,1)[0]);p.hp-=3;g.players[side].maxMana+=1;render();report({time:5920,phase:'固定シナリオ結果：対象はシェルフ、持ち主−3、ラストマッシュルームの最大マナ＋1。'});}finally{overlay.remove();handoff=false;}}
function tick(now:number){if(playing&&ready&&!document.hidden&&!handoff){time+=Math.min(now-previous,70)*speed;if(time>=5260){time=5260;void finish();}else draw();}previous=now;raf=requestAnimationFrame(tick);}
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.data.kind!=='d-r2')return;const d=e.data;if(d.command==='setup')void setup(d.variant,d.side);if(d.command==='speed')speed=d.speed;if(!ready||handoff)return;if(d.command==='seek'){playing=false;time=d.time;draw();}if(d.command==='reset')void setup();if(d.command==='play'){void setup().then(()=>{if(ready){previous=performance.now();playing=true;}});}});
window.addEventListener('pagehide',()=>{++epoch;playing=false;ready=false;cancelAnimationFrame(raf);overlay.remove();stopLayout();view.destroy();});
(window as unknown as {dR2:unknown}).dR2={setup,seek:(n:number)=>{if(!handoff){playing=false;time=n;draw();}},play:()=>{previous=performance.now();playing=true;},get state(){return{ready,variant,side,time,handoff,playing,targetVisible:target()?.style.visibility,stage:modelStage}},get model(){return g.players.map(p=>({hp:p.hp,maxMana:p.maxMana,field:p.field.map(m=>({uid:m.uid,decay:m.decayCnt||0})),discard:p.discard.map(c=>c.uid)}))}};
raf=requestAnimationFrame(tick);report({ready:true});
