import {Renderer} from './renderer';import {surface} from './surface';import {heroes,designs,DURATION} from './catalog';import './style.css';
const root=document.getElementById('app')!;let hero=0,variant=0,mode='grid',ms=0,playing=false,loop=true,speed=1,reduced=matchMedia('(prefers-reduced-motion:reduce)').matches,dark=false,side=0,multi=false,ready=false,raf=0,last=0,painted=0,disposed=false;const renderer=new Renderer(),faces:HTMLCanvasElement[]=[];
root.innerHTML=`<main><header><a class="wordmark">LORE<span>MOTION ATELIER / 08</span></a><div class="intro"><div class="kicker">THE CHOSEN FOUR</div><h1>選ばれし者の、顕現。</h1><p>黒鋼、紫晶、紺帛、白亜、銀膜、双影。<br>四つの兵装を、六つの物質で呼び起こす。</p></div><div class="badge">SUMMON STUDIES<span>4 CLASSES × 6 DIRECTIONS</span></div></header><nav class="heroes" aria-label="職を選択">${heroes.map((h,i)=>`<button data-hero="${i}" class="${i===0?'active':''}"><img src="/art/cards-sm/${h.id}.webp" alt=""><span><small>0${i+1} / ${h.en}</small><strong>${h.name}</strong></span></button>`).join('')}</nav><section class="controls"><div class="modes"><button data-mode="grid" class="active">6案を比較</button><button data-mode="detail">個別に見る</button><button data-mode="board">実盤面</button></div><button id="theme">白い盤面</button><label><input id="reduced" type="checkbox">動きを低減</label><span id="status">カードと材質を準備中…</span></section><section id="grid" class="grid">${designs.map((d,i)=>`<article><div class="tile-top"><span>0${i+1}</span><div><small>${d.en}</small><h2>${d.name}</h2></div><button data-select="${i}" aria-label="${d.name}を拡大">↗</button></div><canvas data-v="${i}" aria-label="${d.name}"></canvas><div class="tile-bottom"><small>${d.material}</small><p>${d.note}</p></div></article>`).join('')}</section><section id="detail" class="detail" hidden><canvas id="large"></canvas><aside><small>SELECT A DIRECTION</small>${designs.map((d,i)=>`<button data-variant="${i}"><span>0${i+1}</span>${d.name}</button>`).join('')}<p id="intent"></p></aside></section><section id="board" hidden><div class="board-options"><select id="board-variant" aria-label="盤面で見る案">${designs.map((d,i)=>`<option value="${i}">0${i+1} ${d.name}</option>`).join('')}</select><button id="side">自分側</button><button id="multi">1枚</button><span>固定盤面での演出比較</span></div><iframe title="選ばれし4種の召喚・実盤面" src="about:blank"></iframe></section><div class="timeline"><button id="play">再生</button><button id="reset" aria-label="最初から">↺</button><select id="speed" aria-label="速度"><option value="1">1×</option><option value="0.5">0.5×</option><option value="0.25">0.25×</option></select><input id="seek" aria-label="再生位置" type="range" min="0" max="3400" value="0"><output id="time">0.00</output><span id="phase">予兆</span><label><input id="loop" type="checkbox" checked>反復</label></div><footer><p id="cue"></p><span>選定用プレビュー · ゲーム本体は未変更</span></footer></main>`;
const $=<E extends HTMLElement=HTMLElement>(s:string)=>root.querySelector<E>(s)!;const frame=$<HTMLIFrameElement>('iframe');
function send(suspend=false){frame.contentWindow?.postMessage(suspend?{kind:'chosen-heroes-suspend'}:{kind:'chosen-heroes-control',hero,variant,ms,side,multi,reduced,dark},location.origin)}
function drawCanvas(canvas:HTMLCanvasElement,v:number){const b=canvas.getBoundingClientRect();if(!b.width||!b.height)return;const d=Math.min(devicePixelRatio,1.5),w=Math.round(b.width*d),h=Math.round(b.height*d);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}const c=canvas.getContext('2d')!;c.setTransform(d,0,0,d,0,0);c.clearRect(0,0,b.width,b.height);renderer.draw(c,faces[hero],hero,v,ms,b.width/2,b.height/2,Math.min(b.width*.36,b.height*.46),reduced);}
function draw(){if(!ready||disposed)return;if(mode==='grid')root.querySelectorAll<HTMLCanvasElement>('[data-v]').forEach(c=>drawCanvas(c,Number(c.dataset.v)));else if(mode==='detail')drawCanvas($<HTMLCanvasElement>('#large'),variant);else send();$<HTMLInputElement>('#seek').value=String(ms);$('#time').textContent=(ms/1000).toFixed(2);$('#phase').textContent=ms<400?'予兆':ms<1300?'形成':ms<2100?'顕現・着地':ms<3000?'収束':'完了';}
function pause(){playing=false;cancelAnimationFrame(raf);raf=0;$('#play').textContent='再生'}
function tick(now:number){if(!playing||disposed)return;ms+=Math.min(100,now-last)*speed;last=now;if(ms>=DURATION){if(loop)ms=0;else{ms=DURATION;pause();}}if(now-painted>=33){draw();painted=now;}if(playing)raf=requestAnimationFrame(tick)}
function play(){if(!ready||disposed||reduced)return;if(ms>=DURATION)ms=0;pause();playing=true;last=performance.now();$('#play').textContent='一時停止';raf=requestAnimationFrame(tick)}
function setMode(m:string){mode=m;for(const n of ['grid','detail','board'])$('#'+n).hidden=n!==m;root.querySelectorAll<HTMLElement>('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));if(m==='board'){if(frame.getAttribute('src')==='about:blank')frame.src='/chosen-heroes-six.html?board';}else{send(true);frame.src='about:blank';}draw()}
function select(v:number){variant=v;$<HTMLSelectElement>('#board-variant').value=String(v);root.querySelectorAll<HTMLElement>('[data-variant]').forEach(b=>b.classList.toggle('active',Number(b.dataset.variant)===v));$('#intent').textContent=designs[v].note;draw()}
function setHero(h:number){hero=h;root.querySelectorAll<HTMLElement>('[data-hero]').forEach(b=>b.classList.toggle('active',Number(b.dataset.hero)===h));$('#cue').textContent=heroes[h].name+' / '+heroes[h].cue;ms=0;draw()}
function reduce(v:boolean){reduced=v;$<HTMLInputElement>('#reduced').checked=v;if(v){pause();ms=DURATION;}draw()}
root.querySelectorAll<HTMLElement>('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode!));root.querySelectorAll<HTMLElement>('[data-hero]').forEach(b=>b.onclick=()=>setHero(Number(b.dataset.hero)));root.querySelectorAll<HTMLElement>('[data-select]').forEach(b=>b.onclick=()=>{select(Number(b.dataset.select));setMode('detail')});root.querySelectorAll<HTMLElement>('[data-variant]').forEach(b=>b.onclick=()=>select(Number(b.dataset.variant)));
$('#play').onclick=()=>playing?pause():play();$('#reset').onclick=()=>{ms=0;draw()};$<HTMLInputElement>('#seek').oninput=()=>{pause();ms=Number($<HTMLInputElement>('#seek').value);draw()};$<HTMLSelectElement>('#speed').onchange=()=>speed=Number($<HTMLSelectElement>('#speed').value);$<HTMLInputElement>('#loop').onchange=()=>loop=$<HTMLInputElement>('#loop').checked;$<HTMLInputElement>('#reduced').onchange=()=>reduce($<HTMLInputElement>('#reduced').checked);$('#theme').onclick=()=>{dark=!dark;root.classList.toggle('dark',dark);$('#theme').textContent=dark?'暗い盤面':'白い盤面';draw()};$<HTMLSelectElement>('#board-variant').onchange=()=>select(Number($<HTMLSelectElement>('#board-variant').value));$('#side').onclick=()=>{side=1-side;$('#side').textContent=side?'相手側':'自分側';draw()};$('#multi').onclick=()=>{multi=!multi;$('#multi').textContent=multi?'3枚同時':'1枚';draw()};
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==frame.contentWindow)return;if(e.data?.kind==='chosen-heroes-ready')send();if(e.data?.kind==='chosen-heroes-error')$('#status').textContent=e.data.error});window.addEventListener('resize',draw);document.addEventListener('visibilitychange',()=>{if(document.hidden){pause();send(true)}});window.addEventListener('pagehide',()=>{pause();disposed=true;renderer.dispose();send(true)},{once:true});matchMedia('(prefers-reduced-motion:reduce)').addEventListener('change',e=>reduce(e.matches));
(window as any).chosenHeroes={get ready(){return ready},get state(){return{hero,variant,mode,ms,playing,reduced,side,multi}},seek(t:number,v=variant){pause();ms=t;select(v);draw()},setHero,setMode,setSide(s:number){side=s;draw()},setMulti(m:boolean){multi=m;draw()},reduce,play,pause,renderer,faces,setLoop(v:boolean){loop=v;$<HTMLInputElement>('#loop').checked=v}};
void(async()=>{await renderer.ready;for(const h of heroes)faces.push(await surface(h.id));ready=true;document.title="LORE / 選ばれし4種・召喚6案";setHero(0);select(0);$('#status').textContent='4職 × 6案 / 共通時計で比較';if(reduced)reduce(true);else if(!location.search.includes('paused'))play()})().catch(e=>$('#status').textContent='読み込み失敗: '+e.message);
