import '../../styles/tokens.css';import '../../styles/base.css';import '../../styles/card.css';import '../../styles/game-overlays.css';import '../../styles/game.css';import '../../styles/screens.css';import '../../styles/reading-board.css';import '../../styles/presentation.css';
import {GameView,setMyAvatar,setOppAvatar} from '../../ui/boardView';import {startBoardLayout} from '../../ui/layout';import {waitForDuel} from '../../ui/duelReadiness';import {clearMonsterStates} from '../../ui/monster/runtime';import {makeFixture} from '../series-vfx-d/revision3/fixture';import {revealSpell,finishQuickSpell,setFxSkip} from '../../ui/anim';import {setLang} from '../../i18n';
setLang('ja');setMyAvatar('SEEKER_BLUE');setOppAvatar('SEEKER_RED');
const app=document.getElementById('app')!,noop=()=>{};const view=new GameView(app,0,{onPlay:noop,onBlockedPlay:noop,onAttack:noop,onBlockedAttack:noop,onReorder:noop,onChooseTarget:noop,onBuyMarket:noop,onBuySupply:noop,onRefresh:noop,onEndTurn:noop,onSurrender:noop});
const toolbar=document.createElement('div');toolbar.style.cssText='position:fixed;left:12px;top:8px;z-index:1000;display:flex;gap:8px;background:#101b29;padding:10px;color:white';toolbar.innerHTML='<select aria-label="陣営"><option value="0">自分側</option><option value="1">相手側</option></select><select aria-label="魔法"><option value="S1">通常魔法</option><option value="QUICK_POISON">クイック魔法</option></select><button id="play">03を再生</button><button id="skip">中断</button><span id="status">準備中</span>';document.body.append(toolbar);
const status=toolbar.querySelector('#status')!,play=toolbar.querySelector<HTMLButtonElement>('#play')!;let fixture:ReturnType<typeof makeFixture>,busy=false;
function setup(){const side=Number(toolbar.querySelector<HTMLSelectElement>('[aria-label="陣営"]')!.value) as 0|1,card=toolbar.querySelector<HTMLSelectElement>('[aria-label="魔法"]')!.value;fixture=makeFixture({item:card==='S1'?'spell-frame':'A004',card,variant:1,side,outcome:'hit',reduced:false,background:'light'});view.render(structuredClone(fixture.before));view.setHandOpen(false);clearMonsterStates(app);return side;}
const side=setup();void side;const stop=startBoardLayout();void waitForDuel(app).then(()=>status.textContent='READY');
play.onclick=async()=>{if(busy)return;busy=true;play.disabled=true;setFxSkip(false);const side=setup();status.textContent='RUNNING';try{const held=await revealSpell(fixture.source,side===0?'me':'opp',fixture.source.quick?'vanish':'discard',undefined,!!fixture.source.quick);if(held)await finishQuickSpell(held,side===0?'me':'opp');view.render(structuredClone(fixture.after));clearMonsterStates(app);status.textContent='COMPLETE';}finally{busy=false;play.disabled=false;}};
toolbar.querySelector<HTMLButtonElement>('#skip')!.onclick=()=>{setFxSkip(true);status.textContent='SKIPPED';};toolbar.querySelectorAll('select').forEach(s=>s.onchange=()=>{if(!busy)setup();});window.addEventListener('pagehide',()=>{setFxSkip(true);stop();view.destroy();},{once:true});
