import './style.css';
import {entries,status,playable,directions} from './catalog';
import {eggStages,stateStages} from './stages';
const params=new URLSearchParams(location.search),initial=params.get('item')||'S02';
let selected=entries.find(e=>e.id===initial)||entries[0],variant=params.get('variant')==='2'?2:1;
const app=document.querySelector<HTMLElement>('#app')!;
app.innerHTML=`<header><div><small>B / 全担当範囲</small><h1>カードと動きの制作台帳</h1></div><nav><a href="?revision=2">R2固定比較</a><span>9シリーズ · 42効果 · 雫 / シールド</span></nav></header><main><aside><input id="search" aria-label="項目を検索" placeholder="ID・カード名・効果で検索"><div id="catalog"></div></aside><section><div class="selection"><small id="state"></small><h2 id="title"></h2><p id="stages"></p><div class="controls"><label>カード<select id="card"></select></label><label>案<select id="variant"><option value="1">①</option><option value="2">②</option></select></label><label>陣営<select id="side"><option value="0">自分</option><option value="1">相手</option></select></label><button id="play" disabled>再生</button><button id="reset" disabled>戻す</button><a id="permalink">この案を開く</a></div><div class="seek"><button data-time=".25" disabled>予兆</button><button data-time=".55" disabled>主動作</button><button data-time=".85" disabled>着地</button><input id="seek" aria-label="演出時刻" type="range" min="0" max="1000" value="0" disabled><label><input id="reduced" type="checkbox">動きを減らす</label></div><p id="phase">制作中の項目は準備完了まで再生できません。</p></div><iframe title="B R3 実盤面" src="?revision=3&board=1"></iframe><p class="scope">実盤面上のローカル試作。2案再生可と品質承認は別です。R1不採用・R2比較履歴を維持。</p></section></main>`;
const el=<T extends HTMLElement>(s:string)=>document.querySelector<T>(s)!;
const stageControl=document.createElement('label');stageControl.id='stage-control';stageControl.innerHTML='段階<select id="stage"></select>';el('.controls').insertBefore(stageControl,el('#play'));
function renderList(){const q=el<HTMLInputElement>('#search').value.toLowerCase();el('#catalog').innerHTML=entries.filter(e=>[e.id,e.name,...e.cardIds||[]].join(' ').toLowerCase().includes(q)).map(e=>`<button data-id="${e.id}" class="item ${e.id===selected.id?'current':''}" ${status(e.id)==='未制作'?'data-pending="true"':''}><span>${e.id} · ${e.name}</span><small>${status(e.id)}</small></button>`).join('');for(const b of document.querySelectorAll<HTMLButtonElement>('[data-id]'))b.onclick=()=>{selected=entries.find(e=>e.id===b.dataset.id)!;void choose();};}
function controls(enabled:boolean){for(const c of document.querySelectorAll<HTMLButtonElement|HTMLInputElement>('#play,#reset,#seek,[data-time]'))c.disabled=!enabled;}
let api:any,request=0,prepared=false,loading=false,loadError='';
async function choose(){const token=++request;controls(false);el('#state').textContent=status(selected.id);el('#title').textContent=`${selected.id} · ${selected.name}`;el('#stages').textContent=selected.animation||selected.stages||selected.name;
 const stages=eggStages[selected.id]||stateStages[selected.id]||[];stageControl.hidden=!stages.length;el('#stage').innerHTML=stages.map(([value,label])=>`<option value="${value}">${label}</option>`).join('');if(stages.some(([s])=>s===params.get('stage')))el<HTMLSelectElement>('#stage').value=params.get('stage')!;
 const options=selected.cardIds?.length?selected.cardIds:selected.id==='A146'?['M7']:selected.id==='N001'?['NOURISHING_RAIN']:selected.id==='N002'?['DEFENSIVE_STANCE']:['ELF'];el('#card').innerHTML=options.map(id=>`<option>${id}</option>`).join('');if(params.get('card')&&options.includes(params.get('card')!))el<HTMLSelectElement>('#card').value=params.get('card')!;
 el<HTMLSelectElement>('#variant').value=String(variant);renderList();await load(token);}
async function load(token=++request){controls(false);prepared=false;loading=true;loadError='';variant=Number(el<HTMLSelectElement>('#variant').value);const card=el<HTMLSelectElement>('#card').value;
 el<HTMLAnchorElement>('#permalink').href=`?revision=3&item=${selected.id}&variant=${variant}&card=${card}&stage=${el<HTMLSelectElement>('#stage').value}`;
 el('#phase').textContent=playable.has(selected.id)?'実盤面を準備中':`${status(selected.id)} · この項目の完成を待たず、他の制作も進めています。`;
 if(!api||!playable.has(selected.id)){loading=false;return;}
 try{await api.prepare(selected.id,card,variant,Number(el<HTMLSelectElement>('#side').value),el<HTMLSelectElement>('#stage').value||undefined);if(token!==request)return;prepared=true;controls(true);el('#stages').textContent=api.evidence?.effect?.notes?.length?api.evidence.effect.notes.join(' '):(selected.animation||selected.stages||selected.name);el('#phase').textContent=api.phase;el('#state').textContent=`${status(selected.id)} · ${directions[selected.id]?.[variant-1]||'効果比較'} · 品質未承認`;}
 catch(e){if(token===request){loadError=String(e);el('#state').textContent='要改稿';el('#phase').textContent=loadError;}}
 finally{if(token===request)loading=false;}
}
el<HTMLInputElement>('#search').oninput=renderList;for(const s of ['#card','#variant','#side'])el(s).onchange=()=>void load();el('#play').onclick=()=>void api?.play();el('#reset').onclick=()=>void api?.reset();el<HTMLInputElement>('#seek').oninput=()=>void api?.seek(Number(el<HTMLInputElement>('#seek').value)/1000);el<HTMLInputElement>('#reduced').onchange=()=>{if(api)api.reduced=el<HTMLInputElement>('#reduced').checked;};
el('#stage').onchange=()=>void load();for(const b of document.querySelectorAll<HTMLButtonElement>('[data-time]'))b.onclick=()=>void api?.seek(Number(b.dataset.time));
void choose();const timer=setInterval(()=>{const a=(el<HTMLIFrameElement>('iframe').contentWindow as any)?.seriesBR3Board;if(a?.ready&&!api){api=a;void load();}if(api&&playable.has(selected.id)){if(!loading)el('#phase').textContent=loadError||`${api.phase} · ${(api.elapsedMs/1000).toFixed(1)}秒`;el<HTMLButtonElement>('#play').disabled=!prepared||loading||api.busy;for(const c of document.querySelectorAll<HTMLButtonElement|HTMLInputElement>('#seek,[data-time]'))c.disabled=!prepared||loading||api.busy;el<HTMLInputElement>('#seek').value=String(Math.round(api.progress*1000));}},150);
(window as any).seriesBR3={get board(){return api;},get selected(){return selected.id;},get ready(){return !!api?.ready;}};window.addEventListener('pagehide',()=>clearInterval(timer),{once:true});
